### ISSUE TITLE
Response code is 429

### ISSUE THREAD

**Issue by jayeshgniyes** [postaddictme/instagram-php-scraper#1000]
Getting this error in all pages. Api was working fine just stop working without any changes 
Uncaught InstagramScraper\Exception\InstagramException: Response code is 429. Body: <!DOCTYPE html> <html lang="en" class="no-js not-logged-in "> <head> <meta charset="utf-8"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <title> Page Not Found &bull; Instagram </title> <meta name="robots" content="noimageindex, noarchive"> <meta name="apple-mobile-web-app-status-bar-style" content="default"> <meta name="mobile-web-app-capable" content="yes"> <meta name="theme-color" content="#ffffff"> <meta id="viewport" name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover"> <link rel="manifest" href="/data/manifest.json"> <script type="text/javascript"> (function() { var docElement = document.documentElement; var classRE = new RegExp('(^|\\s)no-js(\\s|$)'); var className = docElement.cl

**Comment by 89z** [comment]
Please provide example input

**Comment by jayeshgniyes** [comment]
I used a searchAccountsByUsername.php it was working fine but it's stop working from yesterday.

**Comment by 89z** [comment]
Please provide example input

**Comment by Koha2014** [comment]
Same problem. As far as I understand, Instagram is blocking requests. Everything goes fine from the local machine. I tried through the withCredentials () function, but there are messages about a suspicious login attempt on the instagram side. I confirm, but the following request also raises suspicions on Instagram. Perhaps it's time to give up this venture

**Comment by restyler** [comment]
> Same problem. As far as I understand, Instagram is blocking requests. Everything goes fine from the local machine. I tried through the withCredentials () function, but there are messages about a suspicious login attempt on the instagram side. I confirm, but the following request also raises suspicions on Instagram. Perhaps it's time to give up this venture

Try profixied fork of this scraper to mitigate the 429 issue: https://github.com/restyler/instagram-php-scraper ( do not use withCredentials() with this one, it does not make sense )

**Comment by fageapp** [comment]
Same problem.

**Comment by Koha2014** [comment]
> Same problem.

Try this variant:
1. Authorise in instagram via browser
2. Get Session ID from Cookies


$instagram  = \InstagramScraper\Instagram::withCredentials(new \GuzzleHttp\Client(), '', '', null);
$instagram->loginWithSessionId(YourInstagramSessionid);

**Comment by fageapp** [comment]
> > Same problem.
> 
> Try this variant:
> 
> 1. Authorise in instagram via browser
> 2. Get Session ID from Cookies
> 
> $instagram = \InstagramScraper\Instagram::withCredentials(new \GuzzleHttp\Client(), '', '', null); $instagram->loginWithSessionId(YourInstagramSessionid);
> 
> Important. Upgrade this extension to last version

an error occurs

Fatal error: Uncaught InstagramScraper\Exception\InstagramAuthException: Login with session went wrong. Please report issue. in /home/rudis/www/test3/src/InstagramScraper/Instagram.php:2038

**Comment by skmachine** [comment]
Instagram is very picky on your ip address.. Try https://github.com/skmachine/instagram-php-scraper it uses proxy rotation and works pretty reliable now.

**Comment by svonjoi** [comment]
> Instagram is very picky on your ip address.. Try https://github.com/skmachine/instagram-php-scraper it uses proxy rotation and works pretty reliable now.

I am trying to follow 200 accounts at once. I'm getting this error after looping follow method and after it reached 40 follows it giving me this error. So your solution  with proxies will solve that? Or my scenario instagram will block anyway like spam?

Thanks you

**Comment by svonjoi** [comment]
or if anybody knows, how many seconds i should wait between each follow/unfollow method execution to avoid this "ban"?

**Comment by beshoo** [comment]
You can not do that, Instagram will ban follow a action 24 hours...
Then ban the account.

Regard

**Comment by svonjoi** [comment]
So in other words, if im getting this message, my acc will be banned while this 24 hours passing? or this is a warning, and if i still attempting that, ill get ban?

**Comment by svonjoi** [comment]
> Then ban the account.

= permanent account ban, if I understand you correctly

I didnt find nothing about permanent account ban, can you share source please?

PD. I dont understand how this work (liking, following , etc) with this library if i havent create token, client id, etc....?
