### ISSUE TITLE
Strange behavior from Instagram (Hide photo from the public with a non-private account) 

### ISSUE THREAD

**Issue by beshoo** [postaddictme/instagram-php-scraper#1009]
Strange behavior from Instagram 
When you open this photo without a login session, you will get not found a 404
https://www.instagram.com/p/CXI3vziIP0T/

But if you open the photo with a logged-in session, you can see it without any problem. and the account is not a private account.!

Any explanation?

**Comment by 89z** [comment]
That link in browser says:

~~~
Sorry, this page isn't available.
~~~

**Comment by beshoo** [comment]
It seems the profile is restricted

**Comment by beshoo** [comment]
https://www.instagram.com/hana_realestate_istanbul/ 
this is the profile.
if you open it without a session you will have 
![image](https://user-images.githubusercontent.com/4635115/146474434-b0e2aefc-618d-4bc6-b73c-5ddfa703ba53.png)

**Comment by beshoo** [comment]
But why Instagram is hiding the media from the public (non logged users).. and is there any workaround to pass fake age via headers!

**Comment by 89z** [comment]
YouTube does the same thing:

https://www.youtube.com/watch?v=Cr381pDsSsA

**Comment by nfech01** [comment]
See #1035
