### ISSUE TITLE
InstagramScraper\Exception\InstagramAuthException #401

### ISSUE THREAD

**Issue by xyz70941** [postaddictme/instagram-php-scraper#1014]
I executed the login normally locally, and executed the program on AWS, and reported me the error message "User credentials are wrong".  
VENDORPATH/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php at line 2012
What can I do?

**Comment by smartali89** [comment]
Me too, but different error, i don't have 2 factor on that account


Fatal error: Uncaught InstagramScraper\Exception\InstagramAuthException: Something went wrong when try two step verification. Please report issue. in C:\xampp\htdocs\ig\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php:1794 Stack trace: #0 C:\xampp\htdocs\ig\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php(1650): InstagramScraper\Instagram->verifyTwoStep(Object(InstagramScraper\Http\Response), Array, Object(InstagramScraper\TwoStepVerification\ConsoleVerification)) #1 C:\xampp\htdocs\ig\scrapper.php(10): InstagramScraper\Instagram->login(false, Object(InstagramScraper\TwoStepVerification\ConsoleVerification)) #2 {main} thrown in C:\xampp\htdocs\ig\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php on line 1794

**Comment by xyz70941** [comment]
The login is successful, and the reason is that I cannot log in with my mobile phone number and password, but
I can log in with my username and password
Hope it helps you
