### ISSUE TITLE
Exception : " Media with this code does not exist "

### ISSUE THREAD

**Issue by alisbrr** [postaddictme/instagram-php-scraper#1021]
Today I get this error  (getMediaByUrl and similar functions like getMediaById ):

 ["message":protected]=>
  string(35) "Media with this code does not exist"
  ["string":"Exception":private]=>
  string(0) ""
  ["code":protected]=>
  int(500)

My code worked for Months ! until Today
i test getAccountMediasByUsername function and it worked so i think its not about server ip or ....

**Comment by fmchan** [comment]
same

**Comment by webspec2012** [comment]
+1

**Comment by 89z** [comment]
> https://www.instagram.com/p/CY6E2PlsGz9/

what is that object?

**Comment by M4S3S7** [comment]
instagram public media ?

**Comment by 89z** [comment]
what is the item in the picture?

**Comment by alisbrr** [comment]
> instagram public media ?

yes

**Comment by fonclub** [comment]
instagram made changes to its api. now the page structure is not suitable for the library and it gives an error

`if (!isset($mediaArray['graphql']['shortcode_media'])) {
            throw new InstagramException('Media with this code does not exist');
        }`

**Comment by cosminp-am** [comment]
Same here

**Comment by dragosionita** [comment]
Same :(

**Comment by alisbrr** [comment]
Any Fixed Version or Solution yet?

**Comment by julioleao2018** [comment]
Has anyone managed to resolve it?

**Comment by Kokil** [comment]
+1

**Comment by ice-matcha** [comment]
I found that the returned data structure changed
![lQLPDhsVCDVH0_XNAcvNB32wZrlAuyRLDMsB8yHTa4BcAA_1917_459](https://user-images.githubusercontent.com/24317750/150671299-a6808f00-ca0b-4107-91e0-e7e5255ecf54.png)

**Comment by M4S3S7** [comment]
if you wrote the code can you share ?

> I found that the returned data structure changed ![lQLPDhsVCDVH0_XNAcvNB32wZrlAuyRLDMsB8yHTa4BcAA_1917_459](https://user-images.githubusercontent.com/24317750/150671299-a6808f00-ca0b-4107-91e0-e7e5255ecf54.png)

**Comment by hossinasaadi** [comment]
Check Out this PR https://github.com/postaddictme/instagram-php-scraper/pull/1023

**Comment by ice-matcha** [comment]
checkout this:&nbsp;&nbsp;fix Media with this code does not exist Error by hossinasaadi · Pull Request #1023 · postaddictme/instagram-php-scraper (github.com)




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月23日(星期天) 晚上8:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [postaddictme/instagram-php-scraper] Exception : &quot; Media with this code does not exist &quot; (Issue #1021)





 
if you wrote the code can you share ?
  
I found that the returned data structure changed 
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fonclub** [comment]
[Fixed PR](https://github.com/postaddictme/instagram-php-scraper/pull/1024)

**Comment by Kokil** [comment]
there is still  issue in carousel

**Comment by fonclub** [comment]
> there is still issue in carousel

what's the problem?  describe in more detail

**Comment by Kokil** [comment]
> > there is still issue in carousel
> 
> what's the problem? describe in more detail

it return empty  image URL 
`                $url = $media->getImageHighResolutionUrl();
`

**Comment by Kokil** [comment]
did you check

**Comment by hckoks** [comment]
Any update in this issue ? im still getting same issue ...
