### ISSUE TITLE
InstagramScraper\Exception\InstagramException Media with this code does not exist

### ISSUE THREAD

**Issue by Kokil** [postaddictme/instagram-php-scraper#1022]
Here is my code : 

`$instagram = new \InstagramScraper\Instagram(new \GuzzleHttp\Client());
        $instagram = \InstagramScraper\Instagram::withCredentials(new \GuzzleHttp\Client(), 'username;, 'password', new Psr16Adapter('Files'));
        $instagram->setUserAgent('User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0');
        $instagram->login();
        $instagram->saveSession();

        $media = $instagram->getMediaByUrl('https://www.instagram.com/p/BHaRdodBouH');

        dd($media);`

i got following output

InstagramScraper\Exception\InstagramException Media with this code does not exist

**Comment by 89z** [comment]
I have an alternate scraper that works:

~~~go
package main

import (
   "fmt"
   "github.com/89z/mech/instagram"
)

func main() {
   login, err := instagram.NewLogin("srpen6", "1q1q1q1q")
   if err != nil {
      panic(err)
   }
   media, err := login.Media("BHaRdodBouH")
   if err != nil {
      panic(err)
   }
   fmt.Printf("%+v\n", media)
}
~~~

Result:

~~~
Likes: 13961
Display_URL: https://scontent-dfw5-2.cdninstagram.com/v/t51.2885-15/e35/13561512_1231835960184186_1767799031_n.jpg?_nc_ht=scontent-dfw5-2.cdninstagram.com&_nc_cat=106&_nc_ohc=NiJ-iCv-s1oAX_t3jN1&edm=AABBvjUBAAAA&ccb=7-4&ig_cache_key=MTI4NjQxNzQ0NjY1OTg1MzE5MQ%3D%3D.2-ccb7-4&oh=00_AT9P2JP8-zFcX8Hf0zVWWHqmHq_8BLfqaRmKa6E_nrb29w&oe=61F27565&_nc_sid=83d603
Comments:
- OIBOANOITI
- First Instagram dog
- Hihi
- 可爱
- 😂
~~~

https://github.com/89z/mech

**Comment by alisbrr** [comment]
Check [this](https://github.com/postaddictme/instagram-php-scraper/issues/1021#issuecomment-1017730395)

still waiting someone to fix it and make pull request

**Comment by hossinasaadi** [comment]
check out this PR https://github.com/postaddictme/instagram-php-scraper/pull/1023
