### ISSUE TITLE
Likes count missing on Media returned by getMediaByUrl() method

### ISSUE THREAD

**Issue by alina-ami** [postaddictme/instagram-php-scraper#1027]
I updated the package this morning to integrate the new changes and fixes and I find out that the getLikesCount() method on a Media object returns the value 0 all the time.

I think this happens because the key `likes` renamed in `like_count` in the JSON returned from Instagram.

I think the fix is to update the lines:
Media.php:599
```
case 'likes':
       $this->likesCount = $arr[$prop]['count'];
       break;
```
to
```
case 'like_count':
       $this->likesCount = $value;
       break;
```

**Comment by fonclub** [comment]
Thank you. Check this [PR](https://github.com/postaddictme/instagram-php-scraper/pull/1028)

**Comment by alina-ami** [comment]
> Thank you. Check this [PR](https://github.com/postaddictme/instagram-php-scraper/pull/1028)

Looks great 👍. Waiting for it to be merged.

**Comment by alina-ami** [comment]
@fonclub  I have also find out that the field containing the time when the post was uploaded on instagram changed from `taken_at_timestamp` to `taken_at`, and now the getCreatedTime() method from Media returns 0 because the createdTime field is never completed. Do you think you can fix that too? Thank you so much! 😊
