### ISSUE TITLE
How to get an image for a carousel of images using the getImageStandardResolutionUrl function

### ISSUE THREAD

**Issue by quilerks** [postaddictme/instagram-php-scraper#1031]
Good afternoon
I get the image with the getMediaByUrl function
And if there is 1 image in the post, for example, then the getImageStandardResolutionUrl function gets the image
But if there is a carousel of images in the post, then I can't get an image, for example, with the getImageStandardResolutionUrl function
If you output `var_dump($media->getCarouselMedia()); `
Then there will be such a result:
![image](https://user-images.githubusercontent.com/56394723/151518403-74066f2f-11b2-4d58-a998-b1b9b44c3ea5.png)
Can you tell me how to get an image for a post with a carousel of images now ?

**Comment by denisdenisi4** [comment]
How about this?
```php
$carousel = $media->getCarouselMedia();
if (is_array($carousel)) {
    foreach ($carousel as &$media) {
        var_dump($media->getCarouselMedia());
    }
}
```

**Comment by quilerks** [comment]
Thanks.
