### ISSUE TITLE
getMediaCommentsByCode don't work

### ISSUE THREAD

**Issue by antosha33** [postaddictme/instagram-php-scraper#107]
oh, i'm sorry for my developing skills, but i need your help.
pagination and getting comments don't work. 

error: Non-static method InstagramScraper\Instagram::getMediaCommentsByCode() should not be called statically in C:\wamp\www\insta2\index.php on line 50
line 50: $comments = Instagram::getMediaCommentsByCode('BG3Iz-No1IZ', 8000);
What is problem?

**Comment by NetForBit** [comment]
$instagram = Instagram::withCredentials('login','pass');
$instagram->login();
$instagram->getMediaCommentsByCode('BG3Iz-No1IZ', 8000); ?

**Comment by antosha33** [comment]
It works!
Thank you so much!!!
