### ISSUE TITLE
Pagination on get by location

### ISSUE THREAD

**Issue by alvinwiguna** [postaddictme/instagram-php-scraper#108]
Is this possible on the current version? I do not see an function for it.
Any possibility of this being added in the future?

**Comment by alvinwiguna** [comment]
any idea why this is coming up?

[Symfony\Component\Debug\Exception\FatalErrorException]
 Call to undefined method InstagramScraper\Instagram::withCredentials()

I cant seem to login with the API

**Comment by e-beach** [comment]
If anyone is wondering the above error means you have failed to require the API properly.
