### ISSUE TITLE
Undefined property: stdClass::$authenticated

### ISSUE THREAD

**Issue by ffaady** [postaddictme/instagram-php-scraper#1094]
Working fine on my local laravel project but when uploading on linux server this is happening
any idea?

**Comment by ag2m** [comment]
I have same problem when uploading on server!

**Comment by ffaady** [comment]
I solved the issue by putting credentials below is the code example

`from facebook_scraper import get_posts
import locale
locale.setlocale(locale.LC_ALL, 'en_US.utf8')
for post in get_posts(post_urls=["FACEBOOK_URL"], credentials={'email' : 'EMAIL' , 'pass' : 'PASSWORD'}) :
    print(post['text'][:50])    
`

**Comment by ag2m** [comment]
can you send a complete code please 🙌

**Comment by ffaady** [comment]
`from facebook_scraper import get_posts`
`import locale`
`locale.setlocale(locale.LC_ALL, 'en_US.utf8')`
`for` post in get_posts(post_urls=["FACEBOOKURL"], credentials={'email' : 'EMAIL' , 'pass' : 'PASSWORD'}) :
`    print(post['text'][:50])    `

**Comment by ag2m** [comment]
can you help me about this problem please 🙌🙌
@hendrasan
@ffaady

**Comment by ffaady** [comment]
see the solution is bit simple but has processes 
`require __DIR__ . '/../../../vendor/autoload.php';`

`$instagram = new \InstagramScraper\Instagram(new \GuzzleHttp\Client());`

`$instagram = \InstagramScraper\Instagram::withCredentials(new \GuzzleHttp\Client(), `
`'EMAIL', 'PASSWORD', new Psr16Adapter('Files'));`
`$instagram->login();`

`$media = $instagram->getMediaByCode('INSTACODE');`
