### ISSUE TITLE
Does this Library Work with 2FA Auth?

### ISSUE THREAD

**Issue by alexgarciab** [postaddictme/instagram-php-scraper#1096]
I noticed that in order to not get blocked using IG Accounts, 2FA is needed (apart from good proxies).

No matter what you do, even if the connection IP is the same, IG will block you after some time of usage.

Does this Library support 2FA Auth for IG Accounts? (Storing 2FA Seed Code & Auto-Generating 2FA 6-digit codes on demand)

**Comment by thatcoolguy** [comment]
Yeah, I managed to get this to work but after a while, you can't bypass the login without verifying e-mail code. Does anyone have a working solution for this?

**Comment by alexgarciab** [comment]
> Yeah, I managed to get this to work but after a while, you can't bypass the login without verifying e-mail code. Does anyone have a working solution for this?

Can you submit a pull request with the 2FA implementation?

**Comment by thatcoolguy** [comment]
I am in the same boat as you, unfortunately...

**Comment by thatcoolguy** [comment]
Fatal error: Uncaught Error: Undefined constant "InstagramScraper\TwoStepVerification\STDIN" in /home/765806.cloudwaysapps.com/ndxjpbzvrb/public_html/vendor/raiym/instagram-php-scraper/src/InstagramScraper/TwoStepVerification/ConsoleVerification.php:54 Stack trace: #0 /home/765806.cloudwaysapps.com/ndxjpbzvrb/public_html/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php(2375): InstagramScraper\TwoStepVerification\ConsoleVerification->getSecurityCode() #1 /home/765806.cloudwaysapps.com/ndxjpbzvrb/public_html/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php(2224): InstagramScraper\Instagram->verifyTwoStep() #2 /home/765806.cloudwaysapps.com/ndxjpbzvrb/public_html/get-pictures-test.php(13): InstagramScraper\Instagram->login() #3 {main} thrown in /home/765806.cloudwaysapps.com/ndxjpbzvrb/public_html/vendor/raiym/instagram-php-scraper/src/InstagramScraper/TwoStepVerification/ConsoleVerification.php on line 54
