### ISSUE TITLE
Search media by #hashtag not working

### ISSUE THREAD

**Issue by pdolinaj** [postaddictme/instagram-php-scraper#110]
I am trying to do a media search on a #hashtag but it throws 404 exception.

`$medias = Instagram::getMediasByTag('#hashtag', 10);`

Is this a bug or is there a different way to do this?

Many thanks.

**Comment by rommkaa** [comment]
try this (tag without "#"): 

`$medias = Instagram::getMediasByTag('hashtag', 10);`

**Comment by raiym** [comment]
See examples: 
https://github.com/postaddictme/instagram-php-scraper/blob/master/examples/getMediasByTag.php
