### ISSUE TITLE
Response code is 403: Forbidden

### ISSUE THREAD

**Issue by naveedumar786** [postaddictme/instagram-php-scraper#1100]
InstagramScraper\Exception\InstagramAuthException
Response code is 403: Forbidden.

Unable to find the solution...

**Comment by NabiKAZ** [comment]
```
PHP Fatal error:  Uncaught InstagramScraper\Exception\InstagramAuthException: Response code is 403: Forbidden.Something went wrong. Please report issue. in C:\Nabi\instagram-php-scraper\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php:2229
Stack trace:
#0 C:\Nabi\instagram-php-scraper\save_medias.php(70): InstagramScraper\Instagram->login(true, Object(InstagramScraper\TwoStepVerification\ConsoleVerification))
#1 {main}
  thrown in C:\Nabi\instagram-php-scraper\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php on line 2229

```

**Comment by hbranco** [comment]
`nstagramScraper\Exception\InstagramAuthException: Response code is 403: Forbidden.Something went wrong. Please report issue. in file C:\.......\back\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php on line 2229`

username and password is correctly.

**Comment by hbranco** [comment]
`nstagramScraper\Exception\InstagramAuthException: Response code is 403: Forbidden.Something went wrong. Please report issue. in file C:\.......\back\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php on line 2229`

username and password is correctly.

**Comment by fverdicchio** [comment]
PHP Fatal error:  Uncaught InstagramScraper\Exception\InstagramAuthException: Response code is 403: Forbidden.Something went wrong. Please report issue. in /home/fverdicchio/projects/wineexp-scraper/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:2229
Stack trace:
#0 /home/fverdicchio/projects/wineexp-scraper/index.php(18): InstagramScraper\Instagram->login()
#1 {main}
  thrown in /home/fverdicchio/projects/wineexp-scraper/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 2229

i'm having same problem

**Comment by reza305z** [comment]
Same issue here.
Xampp and VPN on localhost

**Comment by NabiKAZ** [comment]
I noticed that the following error appears on the web version as well:
```
CSRF token missing or incorrect
```

And there is a 403 error in the console:
```
Request URL: https://www.instagram.com/api/v1/web/accounts/login/ajax/
Request Method: POST
Status Code: 403
{"message":"CSRF token missing or incorrect","status":"fail"}
```

After a little research I came up with this solution:

> Open your chrome browser developer tools then go to the login page of instagram, in the network tab find request that goes like this https://www.instagram.com/ click on the request and in the response tab press `ctrl+f` and search for `csrf_token`, copy the value of csrf go the application tab, in storage section click on cookies and insert a cookie with `csrftoken` name and paste the value and make it secure. now fill the login form and press enter. hope it helps
ref: https://stackoverflow.com/a/74372169/1407491

This method works for entering the web version.
I think this trick can solve the problem of this package.

**Comment by NabiKAZ** [comment]
![image](https://user-images.githubusercontent.com/246721/201870020-f31b2c44-3668-496a-861c-9c80d1de420f.png)


![image](https://user-images.githubusercontent.com/246721/201870079-310ea616-5629-44e5-9fba-32357ff3789b.png)

https://github.com/postaddictme/instagram-php-scraper/blob/adfb322888f70a527e99ddc97b8e52fb1a914545/src/InstagramScraper/Instagram.php#L2213

**Comment by alexwebck** [comment]
It seems that the issue is still reproduced:
`Fatal error: Uncaught InstagramScraper\Exception\InstagramAuthException: Response code is 403: Forbidden.Something went wrong. Please report issue. in /sandbox/instagram/src/InstagramScraper/Instagram.php:2244`

Works only with the sessionId, but not with the login and password.

**Comment by ricardocosta43** [comment]
Create this function in instagram.php
```
function fetchCsrfToken()
    {
        $client = new Client();
        $response = $client->get('https://www.instagram.com/accounts/login/', [
            'headers' => [
                'User-Agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
            ]
        ]);

        $cookies = $response->getHeader('Set-Cookie');
        foreach ($cookies as $cookie) {
            if (preg_match('/csrftoken=([^;]+)/', $cookie, $matches)) {
                return $matches[1];
            }
        }

        return null;
    }
```

  Then find this code snippet in the image below and change it as shown in the image
    
![Captura de Tela 2024-10-10 às 13 46 11](https://github.com/user-attachments/assets/d8183f5e-bf72-49c8-b2f2-0e1f0f4ecfc8)

**Comment by alexwebck** [comment]
> Create this function in instagram.php
> 
> ```
> function fetchCsrfToken()
>     {
>         $client = new Client();
>         $response = $client->get('https://www.instagram.com/accounts/login/', [
>             'headers' => [
>                 'User-Agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
>             ]
>         ]);
> 
>         $cookies = $response->getHeader('Set-Cookie');
>         foreach ($cookies as $cookie) {
>             if (preg_match('/csrftoken=([^;]+)/', $cookie, $matches)) {
>                 return $matches[1];
>             }
>         }
> 
>         return null;
>     }
> ```
> 
> Then find this code snippet in the image below and change it as shown in the image
> 
> ![Captura de Tela 2024-10-10 às 13 46 11](https://private-user-images.githubusercontent.com/12566796/375540152-d8183f5e-bf72-49c8-b2f2-0e1f0f4ecfc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzI1NDUsIm5iZiI6MTcyODYzMjI0NSwicGF0aCI6Ii8xMjU2Njc5Ni8zNzU1NDAxNTItZDgxODNmNWUtYmY3Mi00OWM4LWIyZjItMGUxZjBmNGVjZmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA3MzcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2ZmU4YTBjYjA5NjJhYzFhOGMxZDllNjJkMWZhOTE5NTg2MzZmOThhZjYyZGVmZTBjZDU4ZDQ4OTQ3NDRiYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.m0JwKKlBXbLChytst6PtIuH4kTqWexTpeOI20GmNNhM)

@ricardocosta43 it seems that doesn't work:
Fatal error: Uncaught Error: Class "InstagramScraper\Client" not found in /src/InstagramScraper/Instagram.php:2919
>$client = new Client();

**Comment by ricardocosta43** [comment]
> > Create this function in instagram.php
> > ```
> > function fetchCsrfToken()
> >     {
> >         $client = new Client();
> >         $response = $client->get('https://www.instagram.com/accounts/login/', [
> >             'headers' => [
> >                 'User-Agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
> >             ]
> >         ]);
> > 
> >         $cookies = $response->getHeader('Set-Cookie');
> >         foreach ($cookies as $cookie) {
> >             if (preg_match('/csrftoken=([^;]+)/', $cookie, $matches)) {
> >                 return $matches[1];
> >             }
> >         }
> > 
> >         return null;
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then find this code snippet in the image below and change it as shown in the image
> > ![Captura de Tela 2024-10-10 às 13 46 11](https://private-user-images.githubusercontent.com/12566796/375540152-d8183f5e-bf72-49c8-b2f2-0e1f0f4ecfc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzI1NDUsIm5iZiI6MTcyODYzMjI0NSwicGF0aCI6Ii8xMjU2Njc5Ni8zNzU1NDAxNTItZDgxODNmNWUtYmY3Mi00OWM4LWIyZjItMGUxZjBmNGVjZmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA3MzcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2ZmU4YTBjYjA5NjJhYzFhOGMxZDllNjJkMWZhOTE5NTg2MzZmOThhZjYyZGVmZTBjZDU4ZDQ4OTQ3NDRiYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.m0JwKKlBXbLChytst6PtIuH4kTqWexTpeOI20GmNNhM)
> 
> @ricardocosta43 it seems that doesn't work: Fatal error: Uncaught Error: Class "InstagramScraper\Client" not found in /src/InstagramScraper/Instagram.php:2919
> 
> > $client = new Client();

Sorry!
Need import
`use GuzzleHttp\Client;`
need add package if not have
