### ISSUE TITLE
Неправильная работа getMediaCommentsByCode

### ISSUE THREAD

**Issue by mypostofice24** [postaddictme/instagram-php-scraper#111]
Делаю выборку комментариев из поста, если их немного, скажем до 100, функция как правило работает правильно (количество и порядок комментариев правильный). 
Если комментариев например от 500 начинаются проблемы, функция загружает большее количество комментариев и не в том порядке, в котором они выводятся в инсте. Плюс ко всему, несмотря на то, что комментариев функция выбирает больше, некоторые комментарии, которые точно есть в инстаграме она не загружает.

**Comment by raiym** [comment]
А есть ли повторяющиеся комментарии? Если выбирает больше? 

Был где-то тут issue, что количество комментариев, которые инстаграм показывает у себя не совпадает с тем, что есть на самом деле. Когда и много. 

Но вот, что не показывает те что есть, такого не было. Если есть возможность покажите пожалуйста пример, чтобы мы могли разобраться

**Comment by mypostofice24** [comment]
По поводу повторяющихся пока не могу сказать, сейчас постараюсь как нибудь вычислить, а по поводу примера вот:
https://www.instagram.com/p/BE9jKI8BF1t/?taken-by=margotrobbie - пост, инста показывает что комментариев 670, копирую все, вставляю в эксель - https://docs.google.com/spreadsheets/d/1jWvhddcR8Bi5ad9HrCyqdtkb3EEIm-_6Y3B6_nObZ2U/edit?usp=sharing
получаю 633 комментария (это что касается несовпадения ПОКАЗЫВАЕТ - ЕСТЬ НА САМОМ ДЕЛЕ).
Делаю выгрузку через getMediaCommentsByCode - https://docs.google.com/spreadsheets/d/1bwpyYgKUX4ikN-5YhaPCUHXveqFkEPD4iC_1CTNzDn8/edit?usp=sharing
Получаю 828 комментариев.
Теперь, что касается того, что getMediaCommentsByCode выгружает не все комментарии, например: один из первых комментариев в самой инсте от zas2000 текст комментария: 1st, этого комментария нет при выгрузке.

**Comment by mypostofice24** [comment]
По поводу повторяющихся комментариев в выгрузке они действительно есть, можно проветь сделав сортировку по алфавиту в экселе столбца с текстом комментария.

**Comment by raiym** [comment]
still issue
