### ISSUE TITLE
Ошибка getMediaCommentsByCode, если code неправильный

### ISSUE THREAD

**Issue by mypostofice24** [postaddictme/instagram-php-scraper#112]
Если функции getMediaCommentsByCode передать неверный code она выдает следующее:
Notice: Undefined index: comments in /Users/andrey/Desktop/Projects/incubator/insta/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 271

Warning: Invalid argument supplied for foreach() in /Users/andrey/Desktop/Projects/incubator/insta/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 272

Notice: Undefined index: comments in /Users/andrey/Desktop/Projects/incubator/insta/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 275

Notice: Undefined index: comments in /Users/andrey/Desktop/Projects/incubator/insta/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 276

Предлагаю добавить проверку в данной функции в строке: 271
if(empty($jsonResponse['comments'])) {
    throw new InstagramException('Something went wrong. Please report issue.');
}

**Comment by raiym** [comment]
Спасибо проверим. 
Если считаете, что можете улучшить код, то открывайте pull request. будем рады

**Comment by raiym** [comment]
still issue
