### ISSUE TITLE
Issue with server side login credentials

### ISSUE THREAD

**Issue by sfatfarma** [postaddictme/instagram-php-scraper#114]
Hello, I have a 'hard nut' issue right here. I entered my credentials in the php scraper and I received a text message with the security code. I should enter that security code on my server but I have no idea how or if this is possible... Since then, I receive a message: ' Instagram login failed: Something went wrong. Please report issue.'... Can anyone help me with this one? Or I have no chance to make this work :( ?

**Comment by raiym** [comment]
Oh, that is true. For now there is no way to enter sms code =(

**Comment by sfatfarma** [comment]
I finally solved this issue by disabled 2 factor authentication for my account. If anyone facing this issue, this is the solution. :) Thanks!

**Comment by raiym** [comment]
Thank you. 
it would be nice to support two-factor auth

**Comment by sfatfarma** [comment]
Anyway, really nice work you did with this project. Congrats and thank you!

**Comment by raiym** [comment]
https://github.com/postaddictme/instagram-php-scraper/pull/241
