### ISSUE TITLE
getMediaById() - possible bug

### ISSUE THREAD

**Issue by pdolinaj** [postaddictme/instagram-php-scraper#119]
I try to use function getMediaById() with existing media. However, the API responds that the media doesn't exist which is wrong.

Media ID: 1522408364867600568_25293493
Media URL: https://www.instagram.com/p/BUgrld_BEC4/

As I can see the API calls method getMediaByUrl() which correctly returns data for this video but there's this line which doesn't seem to be correct:

```
if (!isset($mediaArray['media'])) {
     throw new InstagramException('Media with this code does not exist');
}
```
There's no "media" key in the array but there's lots of details about this video under "graphql" -> "shortcode_media".

Therefore it's incorrect to say that this media doesn't exist because it does.

**Comment by raiym** [comment]
It is a bug.
If you have time please resolve it and make PR
If you don't I will fix it when get a chance

**Comment by e-beach** [comment]
Is this still an issue? The code works for me without error, and I can't find the referenced conditional in getMediaByUrl.

**Comment by raiym** [comment]
Not sure
need to check and write test case

**Comment by pdolinaj** [comment]
Any update on this one? It would be really good to have it fixed. Thanks

**Comment by pdolinaj** [comment]
This works with the latest version so can be closed.
