### ISSUE TITLE
404 error when trying to retrieve comments

### ISSUE THREAD

**Issue by th4deu** [postaddictme/instagram-php-scraper#120]
Hello there,

I've tried to retrieve comments and I get a 404 error.
I tried all the tests ppl have done here before and it's still not working. 

Here are the parameters sent (i replaced the session and csrftoken data):
url: https://www.instagram.com/query/
Array
(
    [cookie] => target=""; csrftoken=#mytoken#; rur=ATN; ds_user_id=#myuserid#; sessionid=#session#; mid=WT9hkAAEAAGKufsJuvVjifCevOwz; 
    [referer] => https://www.instagram.com/
    [x-csrftoken] => #mytoken#
)

parameters: ig_shortcode(BUF8XiRjFzP){comments.last(10){count,nodes{id,created_at,text,user{id,profile_pic_url,username,follows{count},followed_by{count},biography,full_name,media{count},is_private,external_url,is_verified}},page_info}}<

The code i'm using is like it was specified here:
$instagram = Instagram::withCredentials('user', 'pass');
$instagram->login();
$comments = $instagram->getMediaCommentsByCode('code', 10);

**Comment by ryux00** [comment]
It seems the query url is now https://www.instagram.com/graphql/query/ , since by inspecting the network connections from Instagram, I can't seem to find the /query url.But it is not working even after replacing the query url in the Endpoints.php file.

**Comment by th4deu** [comment]
Yes, I saw that. After a time, I created a function to retrieve the comments in two steps.
They changed the comments/json structure too, so, if is there a way to contribute to this project with this new structure let me know.
Maybe it's something temporary.

**Comment by raiym** [comment]
@th4deu do you know what is query_id?

**Comment by th4deu** [comment]
Ah, it's a number they generate. I tried some random numbers with the same length but it didn't work, so I tried to use a number they're using and it's working 'til now.
i changed the code 2 days ago and it didn't expire yet, and I think it won't...

**Comment by raiym** [comment]
@th4deu thank you
I will fix it
