### ISSUE TITLE
getAccountById(193886659) does not work anymore

### ISSUE THREAD

**Issue by NetForBit** [postaddictme/instagram-php-scraper#122]
Доброго вечера, столкнулся с проблемой, при запросе аккаунта по ID выбивает 404

$instagram->getAccountById(193886659);
**Sorry, this page isn't available.**
The link you followed may be broken, or the page may have been removed. Go back to Instagram.

$instagram->getMediaById(1042815830884781756);
Касаемо getMediaById то вообще, ничего не возвращает.

ID вывели из оборота?

**Comment by raiym** [comment]
#119 дубликат. 
Инстаграм изменил формат запроса, буду искать новый

**Comment by andeniel** [comment]
Такая же проблема появилась.

**Comment by raiym** [comment]
инстаграм изменил некоторые вещи, 
нужно найти новый запрос

**Comment by BrandonDude** [comment]
Same using v0.5.9.
