### ISSUE TITLE
login method not working due to checkpoint_required

### ISSUE THREAD

**Issue by loyhall** [postaddictme/instagram-php-scraper#123]
When I call the login method in the scraper it is failing.  I output the response from instagram and it's asking for a check_point challenge (I did a print_r after line 529 in src/InstagramScraper/Instagram.php ).. which gives me something like this:
         "checkpoint_url": "/challenge/3931234339/rjny343TI/"

So even after authenticating my account by going to that URL in a browser and then entering the verification code that they email to me, subsequent calls to the login function are still failing with the same check_point challenge.   

Any ideas, hints, tricks to get beyond this?

**Comment by jasoncartercs** [comment]
Any update on this?

**Comment by e-beach** [comment]
I believe this means you have two-factor authentication enabled on your account, and it won't work in that case. Do you normally have to go through this 2-step process when logging into Instagram?
