### ISSUE TITLE
Fatal error: Uncaught exception 'InstagramScraper\Exception\InstagramAuthException

### ISSUE THREAD

**Issue by zqjilove** [postaddictme/instagram-php-scraper#124]
require_once 'vendor/autoload.php';
use InstagramScraper\Instagram;
$instagram = Instagram::withCredentials('xxxx@xxx.xxxx', 'xxxxxx');
$instagram->login();
$medias = $instagram->getTopMediasByTagName('hello');
print_r($medias);

Fatal error: Uncaught exception 'InstagramScraper\Exception\InstagramAuthException' with message 'Something went wrong. Please report issue.' in /www/wwwroot/www.test.com/src/InstagramScraper/Instagram.php:534 Stack trace: #0 /www/wwwroot/www.test.com/test.php(11): InstagramScraper\Instagram->login() #1 {main} thrown in /www/wwwroot/www.test.com/src/InstagramScraper/Instagram.php on line 534

**Comment by StereoFlo** [comment]
i think it's a bad answer from instagram, try again from another server

**Comment by e-beach** [comment]
It works for me. This issue should probably be closed.
