### ISSUE TITLE
Steps to run the files

### ISSUE THREAD

**Issue by vipuljohri97** [postaddictme/instagram-php-scraper#125]
I am new to php. Can anyone tell me how to run the files and get the extracted output?

**Comment by StereoFlo** [comment]
1) install **git** to you system
2) install **php** to you system
3) make new directory for you project
4) open console and change you working directory to **you-project-directory**
5) paste in console this command **git clone git@github.com:postaddictme/instagram-php-scraper.git**
6) go to **you-project-directory/instagram-php-scraper** in you console
7) download composer.phar and put it to **you-project-directory/instagram-php-scraper**
8) check for **php**: in you console run **php -v**
9) if it's OK, run follow command in console **php composer.phar install**
10) wait for finish
11) edit index.php and try to run **php index.php**

**Comment by maxhuro** [comment]
Hello i have follwed all steps to extract but i'm confused, should i see any index.php or css files after extracting?

**Comment by StereoFlo** [comment]
@maxhuro no you dont. you'll can make it, and then, paste code examples from README.md
