### ISSUE TITLE
query_id is hard-coded

### ISSUE THREAD

**Issue by technuma** [postaddictme/instagram-php-scraper#127]
According to the code below, query_id is hard-coded.
Is there not a problem?

https://github.com/postaddictme/instagram-php-scraper/blob/dc03fd63256d0b4f6c909526aed7f6827da4d145/src/InstagramScraper/InstagramQueryId.php#L11

**Comment by e-beach** [comment]
No, the query_id specifies the type of the request, not the user for the request.
