### ISSUE TITLE
GetAccountById throws error 405

### ISSUE THREAD

**Issue by guytarded** [postaddictme/instagram-php-scraper#129]
I noticed my script stopped working. After a little bit debugging I noticed the errror is thrown by GetAccountById. I checked all values needed are filled and everything is okay.

Anyone had this problem too?

Errormessage: Error 405. Something went wrong. Report issue.

**Comment by inkrement** [comment]
I have the same problem.

**Comment by raiym** [comment]
Are you sure that you use 0.6.0 version?

**Comment by inkrement** [comment]
you are right... I used v0.5.8. Now it works

**Comment by raiym** [comment]
@inkrement cool!
