### ISSUE TITLE
running php index.php causes fatal error

### ISSUE THREAD

**Issue by e-beach** [postaddictme/instagram-php-scraper#130]
The index.php file calls getMediaByCode as a static method:

```
$media = Instagram::getMediaByCode('BQ6W8k6goDE');
var_dump($media);
```
The correct code with a non-static method existed a few commits ago, but it got changed in 4682e97eba524f9ce8d749bf1ad54f5563ab0a28.

This is important to fix, because, in my case, I am trying to figure out whether my current installation works, and the error doesn't help.

**Comment by raiym** [comment]
@e-beach thank you for issue 

Please don't rely on index.php, see tests folder for examples.
