### ISSUE TITLE
Vendor file not found

### ISSUE THREAD

**Issue by rohitme89** [postaddictme/instagram-php-scraper#131]
Hello 

vendor/autoload.php file not found. Where i find this file
![image](https://user-images.githubusercontent.com/11423476/27791487-d5392b88-6012-11e7-91bc-e365853d6989.png)

**Comment by e-beach** [comment]
Did you run `composer install` in the directory? That's what creates the file, for me.

**Comment by rohitme89** [comment]
where i find this composer install

**Comment by e-beach** [comment]
Please google it: https://getcomposer.org/doc/00-intro.md
