### ISSUE TITLE
can't get user followsCount/followedByCount

### ISSUE THREAD

**Issue by hjl888990** [postaddictme/instagram-php-scraper#132]
have login，getAccountById can't get followsCount/followedByCount，return null。the curl response only have count。

**Comment by inkrement** [comment]
same here, seems like Instagram changed their api/information policy

**Comment by kirillantv** [comment]
You can take count with getAccount . The problem is in getAccountById.

**Comment by inkrement** [comment]
@kirillantv sure, but I just have to id and not the name. So I would have to call getAccountById to load the username and then call getAccount?!

**Comment by kirillantv** [comment]
@inkrement seems like that. But this is dirty. I've writen an issue with a reason [https://github.com/postaddictme/instagram-php-scraper/issues/136](url) . Lets wait an answer.
