### ISSUE TITLE
Using $this when not in object context

### ISSUE THREAD

**Issue by playak** [postaddictme/instagram-php-scraper#135]
Getting fatal errors after the update to 6.0 (was on 3.2 before, which stopped working for other reasons):

PHP Fatal error:  Using $this when not in object context in .../httpdocs/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 348

**Comment by playak** [comment]
I changed a lot of 
$this->method to self::method
and
$this->property to $property

in that file. It's a hack that seems to work, but I assume there must be a better solution?

**Comment by e-beach** [comment]
The proper way to fix this is to change  static references in your code such as `Instagram::getAccountById` to methods of the $instagram object from Instagram:withCredentials.

Please see Readme.

**Comment by raiym** [comment]
@playak refer to examples https://github.com/postaddictme/instagram-php-scraper/tree/master/examples
