### ISSUE TITLE
Missing Cast

### ISSUE THREAD

**Issue by inkrement** [postaddictme/instagram-php-scraper#139]
I want to report a bug in the newest master version. Seems like a cast went wrong:

> PHP Catchable fatal error:  Object of class stdClass could not be converted to string in /.../vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 312

**Comment by e-beach** [comment]
This looks like getAccountById. Can you please give the id that caused the bug?

**Comment by e-beach** [comment]
As in, this error is a problem, but it also indicates that the getAccountById function is not working for you, so the id of the account will be helpful even when this particular bug is solved.
