### ISSUE TITLE
can't access protected property

### ISSUE THREAD

**Issue by chrismccoy** [postaddictme/instagram-php-scraper#151]
You have made the values protected, so they cannot be accessed.

     PHP Fatal error:  Cannot access protected property InstagramScraper\Model\Media::$caption

**Comment by chrismccoy** [comment]
using the 

     composer require raiym/instagram-php-scraper

method fixes this

**Comment by thagxt** [comment]
If executing the above gives you this error:

```
Problem 1
    - The requested package raiym/instagram-php-scraper No version set (parsed as 1.0.0) is satisfiable by raiym/instagram-php-scraper[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.
```
try this instead:
```
composer require "raiym/instagram-php-scraper:*"
```
