### ISSUE TITLE
Catch exception of getAccount($username)

### ISSUE THREAD

**Issue by thagxt** [postaddictme/instagram-php-scraper#155]
How can I Catch exception of getAccount($username) ? 

`<b>Fatal error</b>: Uncaught exception 'InstagramScraper\Exception\InstagramNotFoundException' with message 'Account with given username does not exist.' in /src/InstagramScraper/Instagram.php:61`

**Comment by stpnov** [comment]
```
catch (InstagramScraper\Exception\InstagramNotFoundException $e) {
   //to-do
}
```
