### ISSUE TITLE
getPaginateMedias() -- Fatal error: Using $this when not in object context

### ISSUE THREAD

**Issue by thagxt** [postaddictme/instagram-php-scraper#157]
When trying to _Paginate medias_ (with code provided in README) I get this error:

`Fatal error: Using $this when not in object context in /src/InstagramScraper/Instagram.php on line 238`

p.s.
"_Paginate medias_" example in _[README.md](https://github.com/postaddictme/instagram-php-scraper/blob/master/README.md#paginate-medias)_ on `$medias = $result['medias']` is missing the final semicolon.

**Comment by DanielSokil** [comment]
Add Semicolon end of line
$medias = $result['medias'];

**Comment by raiym** [comment]
README.md has been updated.
Refer to newly created examples:
https://github.com/postaddictme/instagram-php-scraper/tree/master/examples
