### ISSUE TITLE
Есть ли функция получения подписчиков по id аккаунта?

### ISSUE THREAD

**Issue by artyomeg** [postaddictme/instagram-php-scraper#159]
Искал функцию получения подписчиков в этой библиотеке, нашел в Endpoints константу FOLLOWERS_URL, и не нашел где она используется.
Если ли на данный момент функция получения подписчиков по id аккаунта?

**Comment by raiym** [comment]
Вот пример:
https://github.com/postaddictme/instagram-php-scraper/blob/master/examples/getAccountFollowers.php
