### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by pedropamn** [postaddictme/instagram-php-scraper#161]
I have a error 500 while call Instagram::getAccount() and Instagram::getMedias. This occurred in at least 3 different servers (Heroku, AppEngine and Compute Engine), but work fine in Amazon AWS.

What is wrong? Instagram PHP Scrapper require any aditional server configuration?

Thanks

**Comment by pedropamn** [comment]
Oh, i found the problem. The error was caused by the absence of Curl in PHP. I solve just installing (sudo apt-get install php5-curl)

**Comment by hrules6872** [comment]
You should close this issue then ;)
