### ISSUE TITLE
problem with getPaginateMedias -  should not be called statically

### ISSUE THREAD

**Issue by pinotarantino** [postaddictme/instagram-php-scraper#163]
Hello, 
on a wamp server (windows 2008), I get the following error message when I try to use Instagram::getPaginateMedias as described in Read Me instructions:
"Strict standards: Non-static method InstagramScraper\Instagram::getPaginateMedias() should not be called statically in ..."
Thanks in advance...
P;)

**Comment by DanielSokil** [comment]
I have same issue.

**Comment by raiym** [comment]
Use `$instagram = new Instagram();`
and then
`$instagram->getPaginateMedias();`
