### ISSUE TITLE
getMediasByTag error : should not be called statically

### ISSUE THREAD

**Issue by pinotarantino** [postaddictme/instagram-php-scraper#164]
Hello, 
in wamp stack (windows server 2008), when I call "getMediasByTag" as described in Read Me  I get the same error I get with pagination of media (other issue already opened): "Non-static method InstagramScraper\Instagram::getMediasByTag() should not be called statically in ..."

Thanks in advance!
P;)

**Comment by search2074** [comment]
Hi, 
`$model = new Instagram();
$q = 'Оно';
$posts = $model->getMediasByTag($q, 30);

foreach ($posts as $i => $post) {
    echo ($i) . '. ' . $post->caption . PHP_EOL;
}`

**Comment by pinotarantino** [comment]
I works! Thanks a lot search2074!

P;)
