### ISSUE TITLE
Invalid argument supplied for foreach() in... - getPaginateMedias

### ISSUE THREAD

**Issue by pinotarantino** [postaddictme/instagram-php-scraper#165]
Hello, 
it seems that pagination doesn't work, only the first page is returned even if another one to paginate  is present.
A message error apper: "Invalid argument supplied for foreach() in..."

Thanks a lot!
P;)

**Comment by search2074** [comment]
getPaginateMedias return hasNextPage property. Put this property to getPaginateMediasByTag('tag', $media['hasNextPage']);

**Comment by pinotarantino** [comment]
Ok thanks!
