### ISSUE TITLE
Error: Using $this when not in object context in InstagramScraper\Instagram::getMediasByTag() (line 414 of InstagramScraper/Instagram.php).

### ISSUE THREAD

**Issue by ucola** [postaddictme/instagram-php-scraper#167]
Hi all

if I try to use getMediasByTag then I became this error
`Error: Using $this when not in object context in InstagramScraper\Instagram::getMediasByTag() (line 414 of .../vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php).`

if I change the $this to a new object it works, but I don't think that this is a good solution...
and if i became the result back, the ownerId is filled out, but not the owner name. Any ideas?

thank for help

**Comment by search2074** [comment]
[see](https://github.com/postaddictme/instagram-php-scraper/issues/164#issuecomment-331153655)

**Comment by ucola** [comment]
ok thank you

we call the methods like this, its this wrong?
`try {
      $medias = Instagram::getMediasByTag($tag, $amount);
      return array('success' => $medias);
    }
    catch (\Exception $ex) {
      return array('error' => $ex);
    }`

**Comment by search2074** [comment]
Method has been set not static in version 0.5.0 [link](https://github.com/postaddictme/instagram-php-scraper/blob/v0.5.0/src/InstagramScraper/Instagram.php#L304).

try this:
```php
try { 
    $instagram = new Instagram();
    $medias = $instagram->getMediasByTag($tag, $amount); 

    return array('success' => $medias); 
} catch (\Exception $ex) { 
    return array('error' => $ex); 
}

**Comment by ucola** [comment]
work as described
