### ISSUE TITLE
getIdFromCode/getCodeFromId

### ISSUE THREAD

**Issue by OffTravel** [postaddictme/instagram-php-scraper#169]
Hi, I'm trying to obtain a media id from an url using getIdFromCode.

I'm testing using this url: https://www.instagram.com/p/BZy7j-QlGi1/
The media id is: 1617617172955424949

But `getIdFromCode('BZy7j-QlGi1')` return 1617617172955424768
And 
`getIdFromCode(1617617172955424949)` return 'BZy7j-RmBc_'
`getIdFromCode('1617617172955424949')` return 'BZy7j-RmHk_'

Am I doing something wrong?

**Comment by raiym** [comment]
@OffTravel true.
I think I know what is wrong 
will try to fix this
