### ISSUE TITLE
GetMedias не работает 

### ISSUE THREAD

**Issue by zebratratata** [postaddictme/instagram-php-scraper#171]
$instagram->getMedias возвращает объекты без коментов и без ссылок на страницы пользователей
Пробовал на теге "goldhalat_отзыв"

**Comment by raiym** [comment]
@zebratratata 
если речь идет про `getMediasByTag`, то я только, что добавил тест https://github.com/postaddictme/instagram-php-scraper/commit/cfe05bfd6fd7fdcd353ee55bdd6e703626a65f43
проверил, работает
также проверил с вашим хештегом, тоже работает

Закрываю issue, если возникнут проблемы пере-откройте и опишите шаги, которые ведут к проблеме
