### ISSUE TITLE
still getMediaCommentsByCode() 405 error

### ISSUE THREAD

**Issue by pinotarantino** [postaddictme/instagram-php-scraper#176]
Hello, 
I red that the bug about getMediaCommentsByCode()  has been fixed on nov. 16, but I still get the 405 error, even if I have the last scraper version installed (0.5.0).
I this coul help, I set "Unirest\Request::verifyPeer(false);" in my script...and I must set this also to avoid error:
"$model = new Instagram();
$comments = $model->getMediaCommentsByCode('BG3Iz-No1IZ', 100);"
My environment is a wamp.

Thank you in advance...

P;)

**Comment by pinotarantino** [comment]
Sorry Raym, I didn't upgrade my scraper version, now I have 0.6.1 version and all works...consider closed my issue...

Thanks and sorry again!
P,)

**Comment by raiym** [comment]
@pinotarantino no problem
