### ISSUE TITLE
get account details using getMediasByTag

### ISSUE THREAD

**Issue by lsaunders80** [postaddictme/instagram-php-scraper#178]
It looks like the getMediasByTag also creates the Account item, so I thought I would be able to do something like the code below, but all the account information is empty strings. Any ideas?

```
$model = new Instagram();
$q = 'fish';

$posts = $model->getMediasByTag($q, 20);
foreach ($posts as $i => $post) {
  echo ($post->getOwner()->getUsername() );
}
```

**Comment by raiym** [comment]
@lsaunders80 in this type of response only accountId available. 

```php
$accountId = $post->getOwner()->getId();
$instagram->getAccountById($accountId);
```

**Comment by levend18** [comment]
@raiym  thanks works for me ?
