### ISSUE TITLE
PHP minimum version & PhpFastCache version

### ISSUE THREAD

**Issue by Geolim4** [postaddictme/instagram-php-scraper#180]
Hello,

Your project requires at least php 5.4 while PhpFastCache v5 requires php 5.5 at least.
Just to let you know that it can leads to some incompatibilities or even worse, some errors.

Cheers,
Georges

**Comment by Birdmaaant** [comment]
Hi @Geolim4 
You need to install
composer require phpFastCache / phpFastCache ~ 5.0.17

after installing it, you also need to install
composer require phpfastcache / phpfastcache-bundle 1.0.4

that worked for me.

**Comment by Geolim4** [comment]
@Birdmaaant 

I'm the owner of PhpfastCache...
You wrong on almost everything:

First, if PhpFastCache V5 specifies php 5.5 for some good reasons and php 5.4 is NOT compatible with PFC V5.
This is why I pointed it out on my first message.

Secondly, you don't install phpFastCache / phpFastCache and phpfastcache / phpfastcache-bundle in the same time. phpfastcache / phpfastcache-bundle alredy make use of phpFastCache / phpFastCache as a dependency, this practice could also leads to serious incompatibility problems...

Cheers,
Georges

**Comment by pdolinaj** [comment]
I believe you should change the phpfastcache/phpfastcache 5.0.* to version 6.0.* since the phpfastcache-bundle now required version of phpfastcache 6.0.*

I've tested it and it seemed to work fine with version 6.

Thanks.

**Comment by Geolim4** [comment]
First, this is not the right repository to discuss about PhpFastCache bundle, secondly the v2+ of the bundle already makes use of pfc v6:
https://github.com/PHPSocialNetwork/phpfastcache-bundle/blob/V2/composer.json

So I don't understand your concerns :)

Secondly, I Initially made this issue to highlight the potential php version issue due to pfc dependency, consequently I'd appreciate if we can focus on the subject of this issue, thanks :)
