### ISSUE TITLE
Fatal error: Cannot access protected property InstagramScraper\Model\Account::$biography

### ISSUE THREAD

**Issue by amauryleproux** [postaddictme/instagram-php-scraper#182]
Hi I'm trying to access to the object $account->biography but I can't cause of the "Protected" .
When I make a print_r of $account I get something like [biography:protected] with a good value in it but i can't access directly to the value.

Any ideas?

Thanks :)

**Comment by AlexMiroshnikov** [comment]
That's quite obvious - https://github.com/postaddictme/instagram-php-scraper/blob/master/src/InstagramScraper/Model/Account.php#L125 - just use `getBiography()` method, like
```
$account->getBiography();
```

**Comment by amauryleproux** [comment]
Nope it wasn't "quite obvious" for me else if I will not have asked the question --' But anyway thank you very much for the obvious answer.

<3
