### ISSUE TITLE
PHP Strict Standards:  Non-static method InstagramScraper\Instagram::getLocationById() should not be called statically

### ISSUE THREAD

**Issue by amauryleproux** [postaddictme/instagram-php-scraper#185]
Guys does anyone has an idea why I get this error when I try to get Media by location id please?

Thanks

**Comment by AlexMiroshnikov** [comment]
You get this error because `getLocationById()` is not a static method, so it must be applied to an instance of `Instagram` class. Instead of `Instagram::getLocationById()` use the following:
```
$ig = Instagram::withCredentials(...);
$ig->getLocationById(...);
```
Btw, this is also quite obvious ;-) .

**Comment by amauryleproux** [comment]
I really start to love you haha thanks again but this time I found it before you replied :p but it's not working anyway :/

I got this : 
PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct():
It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.' in /Applications/MAMP/htdocs/instagram-php-scraper/vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/Files/Item.php:39

**Comment by AlexMiroshnikov** [comment]
@amauryleproux Is it the complete error message? Don't you have a longer error stacktrace?

**Comment by amauryleproux** [comment]
There is the whole message:

PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.' in /Applications/MAMP/htdocs/instagram-php-scraper/vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/Files/Item.php:39
Stack trace:
#0 /Applications/MAMP/htdocs/instagram-php-scraper/vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/Files/Item.php(39): DateTime->__construct()
#1 [internal function]: phpFastCache\Drivers\Files\Item->__construct(Object(phpFastCache\Drivers\Files\Driver), 'amauryleproux')
#2 /Applications/MAMP/htdocs/instagram-php-scraper/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/StandardPsr6StructureTrait.php(56): Reflection in /Applications/MAMP/htdocs/instagram-php-scraper/vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/Files/Item.php on line 39

Fatal error: Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.' in /Applications/MAMP/htdocs/instagram-php-scraper/vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/Files/Item.php:39
Stack trace:
#0 /Applications/MAMP/htdocs/instagram-php-scraper/vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/Files/Item.php(39): DateTime->__construct()
#1 [internal function]: phpFastCache\Drivers\Files\Item->__construct(Object(phpFastCache\Drivers\Files\Driver), 'amauryleproux')

**Comment by AlexMiroshnikov** [comment]
Try to either to add a default timezone to you php ini file or set it in your script via [`date_default_timezone_set()`](http://php.net/manual/en/function.date-default-timezone-set.php) command.

**Comment by amauryleproux** [comment]
You rock! Thanks again :)

**Comment by AlexMiroshnikov** [comment]
@amauryleproux You're welcome :)

**Comment by raiym** [comment]
Thank you @AlexMiroshnikov 
@amauryleproux I have updated examples: https://github.com/postaddictme/instagram-php-scraper/tree/master/examples
