### ISSUE TITLE
Fatal error - abstractModel not found

### ISSUE THREAD

**Issue by USOVANDREW** [postaddictme/instagram-php-scraper#187]
i have this problem:

Fatal error: Class 'InstagramScraper\Model\AbstractModel' not found in /InstagramScraper/Model/Account.php on line 9

what happend?

**Comment by USOVANDREW** [comment]
You need add

require_once __DIR__ . '/InstagramScraper/Traits/ArrayLikeTrait.php';
require_once __DIR__ . '/InstagramScraper/Traits/InitializerTrait.php';
require_once __DIR__ . '/InstagramScraper/Model/AbstractModel.php';

into instagram-scraper.php to fix it.

**Comment by patleeman** [comment]
@raiym I got this: 

**Fatal error: Class 'InstagramScraper\Model\AbstractModel' not found in /var/www/html/public/wp-content/plugins/crown-tracking/includes/lib/instagram/lib/vendor/instagram-php-scraper/src/InstagramScraper/Model/Account.php on line 9**

Looks like Account extends `AbstractModel` except abstract model is required after Account.php. Abstract Model also depends on the two traits, and needed them to be required prior to Abstract Model. I had to change InstagramScraper.php to this for it to work for me.
```
<?php

require_once __DIR__ . '/InstagramScraper/Instagram.php';
require_once __DIR__ . '/InstagramScraper/Endpoints.php';
require_once __DIR__ . '/InstagramScraper/InstagramQueryId.php';
require_once __DIR__ . '/InstagramScraper/Traits/ArrayLikeTrait.php';
require_once __DIR__ . '/InstagramScraper/Traits/InitializerTrait.php';
require_once __DIR__ . '/InstagramScraper/Model/AbstractModel.php';
require_once __DIR__ . '/InstagramScraper/Model/Account.php';
require_once __DIR__ . '/InstagramScraper/Model/CarouselMedia.php';
require_once __DIR__ . '/InstagramScraper/Model/Comment.php';
require_once __DIR__ . '/InstagramScraper/Model/Location.php';
require_once __DIR__ . '/InstagramScraper/Model/Media.php';
require_once __DIR__ . '/InstagramScraper/Model/Tag.php';
require_once __DIR__ . '/InstagramScraper/Exception/InstagramException.php';
require_once __DIR__ . '/InstagramScraper/Exception/InstagramAuthException.php';
require_once __DIR__ . '/InstagramScraper/Exception/InstagramNotFoundException.php';
```
