### ISSUE TITLE
Issue with php INT limit on ownerId 

### ISSUE THREAD

**Issue by jakerator** [postaddictme/instagram-php-scraper#189]
You're usin integer value for ownerId in Medias. But real intagram users are already far behind that limit of 2147483647  . So it returns incorrect Owners .   
Easy fix is simple removing (int) convertions in Model/Account class for 'id' field.

**Comment by raiym** [comment]
it has been resolved.

thank you

**Comment by raiym** [comment]
No all ids accepted as strings (when json decode is happening)
