### ISSUE TITLE
Return empty json because the fields is protected

### ISSUE THREAD

**Issue by filippodicostanzo** [postaddictme/instagram-php-scraper#192]
When I try to get all fields in json files with getmediabytag function but my json is empty.

if I try to get var_dump i see all fields in the array but all fields are protected

How I can return the json files with all fields?

Thanks

**Comment by filippodicostanzo** [comment]
I resolved with the creation of manual json after called get methods for all fields that i interested
```
        $instagram_array = [];

        $byTagTown = $insta->getMediasByTag($find, 10);

        for ($i=0; $i<count($byTagTown); $i++) {
            $instagram_array[$i]['imageHighResolutionUrl'] = $byTagTown[$i]->getImageHighResolutionUrl();
            $instagram_array[$i]['caption'] = $byTagTown[$i]->getCaption();
        }

        $json = $instagram_array;
```

**Comment by pedropamn** [comment]
Good solution... But would be better if have other way more "native" to do this...

**Comment by pedropamn** [comment]
Good alternative 👍
