### ISSUE TITLE
Endpoint ACCOUNT_MEDIAS is down?

### ISSUE THREAD

**Issue by pedropamn** [postaddictme/instagram-php-scraper#195]
Hello

When i use the function `Instagram::getMedias()`, the script shows html characters from Instagram error page and the messages:

```
\src\InstagramScraper\Instagram.php</b> on line <b>91
Fatal error</b>:  Uncaught InstagramScraper\Exception\InstagramException: Response code is 404.
```

At line 91, shows error from line 89, `Endpoints::getAccountMediasJsonLink`. In Endpoints.php, this endpoint is the ACCOUNT_MEDIAS constant

`const ACCOUNT_MEDIAS = 'https://www.instagram.com/{username}/media?max_id={max_id}';
`
But if you access this endpoints, the 404 error is shown by Instagram. 

The API is down, right? Is there other way to get medias? Below, the print of error (in portuguese)

Thanks

![image](https://user-images.githubusercontent.com/19939247/32516862-e25a3248-c3eb-11e7-94af-5a7e9fef73f6.png)

**Comment by raiym** [comment]
https://github.com/postaddictme/instagram-php-scraper/blob/master/examples/getAccountMediasByUsername.php please see example

**Comment by pedropamn** [comment]
Same error ( Response code is 404.)

**Comment by raiym** [comment]
I will take a look when I get home later today

**Comment by bebensiganteng** [comment]
@raiym thank you very much!

**Comment by fattony80** [comment]
@raiym looking forward to an update.

**Comment by sfatfarma** [comment]
Hello,

@raiym Same issue here. I get the same 404 error. Thank you very much for looking into this. Really appreciate your work. :)

Regards,
Szabi.

**Comment by zaivst** [comment]
The same problem. Yesterday all was ok, and today getMedias() get 404 error on any public account.

**Comment by zaivst** [comment]
https://www.instagram.com/anyuser/?__a=1 is works

**Comment by waffle9012** [comment]
@zaivst how do I use that endpoint to get all media for a given username?

**Comment by fattony80** [comment]
@raiym you're a champ, thanks.

**Comment by danrice01** [comment]
@raiym Amazing, thanks for sorting this so quickly!
