### ISSUE TITLE
Media Type

### ISSUE THREAD

**Issue by faiq-naseem** [postaddictme/instagram-php-scraper#197]
Media Type is returning "Image" for all medias even though if its a video. 

See image
https://i.imgur.com/ll70ma9.png

**Comment by raiym** [comment]
@faiq-naseem thank you

which method you use?

**Comment by faiq-naseem** [comment]
@raiym $instagram->getMedias('username', 5);

**Comment by raiym** [comment]
OK, thanks

**Comment by raiym** [comment]
@faiq-naseem what about now?

**Comment by faiq-naseem** [comment]
@raiym fixed now. If its a video then **video_url** link is missing. videoLowResolutionUrl is not even supported.
