### ISSUE TITLE
Get media likes

### ISSUE THREAD

**Issue by raiym** [postaddictme/instagram-php-scraper#20]

**Comment by raiym** [comment]
@350d have found that this link returns 10 last likes: 
https://www.instagram.com/query/?q=ig_shortcode(BHaRdodBouH){likes{nodes{id,user{id,profile_pic_url,username,follows{count},followed_by{count},biography,full_name,media{count},is_private,external_url,is_verified}},page_info}}

Question is: How to get more or implement pagination.

**Comment by raiym** [comment]
@350d seems that method above doesn't work anymore

**Comment by raiym** [comment]
No solution for now

**Comment by raiym** [comment]
Since we use authorization for some queries it is now possible to get media likes

**Comment by knissophiliac** [comment]
@raiym how is that possible now by using authorization?

**Comment by raiym** [comment]
@knissophiliac don't know yet. 
I have forgotten to add "I hope" at the end of the message.

**Comment by knissophiliac** [comment]
can't we use "/media/{media-id}/likers/" thing?

**Comment by raiym** [comment]
@knissophiliac it doesn't work even with cookies

**Comment by adgray** [comment]
You can access likes with the endpoint:

https://www.instagram.com/graphql/query/?query_id=17864450716183058&variables={"shortcode":"{{shortcode}}","first":{{count}},"after":"{{likeId}}"}

The "after" value is blank for the first call. The end-cursor value returned by that call is used as the "after" value for the next call (much like when retrieving comments).

**Comment by eversionsystems** [comment]
@adgray can you provide an example for a photo to get the user likes list?  Do you replace the "{{shortcode}}" value with the shortcode of the photo ?  I'm new to using the graphql and trying to decipher this.  Cheers!

**Comment by romanoidV** [comment]
Hello! Thank you for your work!
Can you please add the example to the folder: GetLikes for Media?
