### ISSUE TITLE
example paginateAccountMediaByUsername.php always return []

### ISSUE THREAD

**Issue by xx19941215** [postaddictme/instagram-php-scraper#202]
```php
<?php
require __DIR__ . '/../vendor/autoload.php';
// getPaginateMedias() work with and without authorization
$instagram = \InstagramScraper\Instagram::withCredentials('username', 'password', '/path/to/cache/folder');
$instagram->login();
$result = $instagram->getPaginateMedias('kevin');
$medias = $result['medias'];
if ($result['hasNextPage'] === true) {
    $result = $instagram->getPaginateMedias('kevin', $result['maxId']);
    $medias = array_merge($medias, $result['medias']);
}
echo json_encode($medias);
```
This example return [], I replace kevin with other username,  but the example still return empty array;
It seems like function getPaginateMedias do not work

**Comment by sebastiennoirie** [comment]
Hello,
it's seems that the endpoint `https://www.instagram.com/{username}/media/?max_id={max_id}` does not work anymore :(

**Comment by xx19941215** [comment]
@sebastiennoirie Thanks ~ Can I use any other API in this package to get all the media of a particular account?

**Comment by sebastiennoirie** [comment]
@xx19941215 I'm not sure because this library use a none official API.
Instagram has remove this url and now, I don't know to retrieve public contents :/

**Comment by raiym** [comment]
Do you use last version of API?

**Comment by UXandre** [comment]
@raiym the latest versions of Instagram api (legacy though) does not allow us to access public content even under the Sandbox mode. They seem to encourage developers to jump into Graph API, which is mainly for business uses.  I'm still hoping for you to come up with amazing solutions so we can work around the issue.

**Comment by raiym** [comment]
@UXandre it is already has been resolved.
Make sure that you use last version

**Comment by UXandre** [comment]
@raiym thanks a lot! I will give a go today! Really appreciate this library @raiym. It really helps a lot!

**Comment by pedropamn** [comment]
I have the last version of PHP Scrapper and just returns "[]"

```
require __DIR__ . '/vendor/autoload.php';
$instagram = new \InstagramScraper\Instagram();

$result = $instagram->getPaginateMedias('kevin');
print_r($result);
$medias = $result['medias'];
if ($result['hasNextPage'] === true) {
    $result = $instagram->getPaginateMedias('kevin', $result['maxId']);
    $medias = array_merge($medias, $result['medias']);
}
echo json_encode($medias);
```

The `print_r($result)` returns:

`Array ( [medias] => Array ( ) [maxId] => [hasNextPage] => 1 ) []`

:(

**Comment by andrewaolwatson** [comment]
I don't get it, it requires autoload.php but the files itself autoload.php is not in the download package
