### ISSUE TITLE
Get Media by userid

### ISSUE THREAD

**Issue by faiq-naseem** [postaddictme/instagram-php-scraper#203]
Instead of fetching media via username, Is it possible via userid?
$instagram->getMedias('username', 10);

**Comment by s3ri0usman** [comment]
Right now, it's not possible. But you can try to create your custom query through graphQL, something like this:

```
$response = Request::get(Endpoints::getGraphQlUrl('YOUR_QUERY_ID', ['id' => 'USER_ID']));
if ($response->code !== 200) {
    throw new InstagramException('Response code is ' . $response->code . '. Body: ' . static::getErrorBody($response->body) . ' Something went wrong. Please report issue.');
}
$jsonData = json_decode($response->raw_body, true);
```

**Comment by raiym** [comment]
Yes, you could for example 
`$account = $instagram->getAccountById('3');`
and then
`$instagram->getMediasByUsername($account->getUsername())`
