### ISSUE TITLE
Old get media endpoint won't work anymore. Here is a new one

### ISSUE THREAD

**Issue by romalytvynenko** [postaddictme/instagram-php-scraper#205]
Hello! Seems like old get media endpoint dont work anymore. Here is a new one:

https://www.instagram.com/graphql/query/?query_id=17888483320059182&variables={"id":"__USER_ID__","first":__POSTS_COUNT__,"after":"__MAX_POST_ID__"}

For me there is still question is query id is static number, or Instagram changes it regular.

**Comment by raiym** [comment]
@romalytvynenko update to the last version
