### ISSUE TITLE
GetMedias isn't working properly

### ISSUE THREAD

**Issue by ssthormess** [postaddictme/instagram-php-scraper#206]
Hello Everybody,

When I execute the following within my app:

`
			try {
			    $medias = $instagram->getMedias($target, 10);
			} catch (\Exception $ex) {
				error($ex);
			}
			print_r($medias);
`

I get the following response:

```
 InstagramScraper\Exception\InstagramException: Response code is 404. Body:  

[instagram 404-page]

 Something went wrong. Please report issue. in /srv/users/websites/apps/XXXXXXXXXX/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:72
Stack trace:
#0 /srv/users/websites/apps/XXXXXXXXXX/public/pages/confirm.php(68): InstagramScraper\Instagram::getMedias('XXXXXXXXXX', 10)
#1 /srv/users/websites/apps/XXXXXXXXXX/public/index.php(25): include('/srv/users/webs...')
#2 {main}
```

Any suggestions? I believe I'm properly using the library but there is something wrong or new on Instagram's end.

**Comment by bateller** [comment]
You are correct. Its on Instagram's side. They changed the endpoint.

See #205
