### ISSUE TITLE
getOwnerId() bug

### ISSUE THREAD

**Issue by aik27** [postaddictme/instagram-php-scraper#208]
getOwnerId() return incorrect ids. Just follow my logic.

Look at this code:

```
$Instagram = new \InstagramScraper\Instagram();
$media = $Instagram->getMediasByTag('shinomontage');
foreach ($media as $key=>$item) {
	echo '<a href="'.$item->getLink().'">';
	echo $item->getOwnerId();
	echo '</a><br />';
}
```

For now, It will return 11 similar **Owner ID** and 1 different. 

Result:

<a href="https://www.instagram.com/p/BbCD9ZIAxwL">2147483647</a><br /><a href="https://www.instagram.com/p/BagTxpCBOQN">2147483647</a><br /><a href="https://www.instagram.com/p/BacAHDHAJ9h">2147483647</a><br /><a href="https://www.instagram.com/p/BaajjNsgokY">2147483647</a><br /><a href="https://www.instagram.com/p/BZqREVSgdDp">2147483647</a><br /><a href="https://www.instagram.com/p/BZqQ4OkAqPg">2147483647</a><br /><a href="https://www.instagram.com/p/BYm3jtUAa1V">1540731511</a><br /><a href="https://www.instagram.com/p/BW-dY7AjL0A">2147483647</a><br /><a href="https://www.instagram.com/p/BW1yEnKDMlw">2147483647</a><br /><a href="https://www.instagram.com/p/BWyAf72HFND">2147483647</a><br /><a href="https://www.instagram.com/p/BWuCiqZBkwG">2147483647</a><br /><a href="https://www.instagram.com/p/BWVS9I1n9nq">2147483647</a><br />

I thought, ok, 1 man posted 11 images in sequence. But if you follow links, you will see - **most of this images posted by different accounts**. 

Tested at **v0.8.5**

**Comment by aik27** [comment]
I found the reason. Some accounts have ID outside integer range (−2 147 483 648  to 2 147 483 647). For example: 6 271 847 937. So type conversion to INT always return 2 147 483 647 (maximum range value). Affected this functions: 

account->getId()
account->initPropertiesCustom()

And maybe others.

**Comment by raiym** [comment]
https://github.com/postaddictme/instagram-php-scraper/commit/09d6cb586de189f507bf466f1ca98307f4d6af49
