### ISSUE TITLE
PHP Notice:  Undefined offset: 0 InstagramScraper/Model/Media.php on line 462

### ISSUE THREAD

**Issue by pdolinaj** [postaddictme/instagram-php-scraper#210]
Small thing but looks like the index needs to be checked to avoid this notice:

PHP Notice:  Undefined offset: 0 in .../instagram-php-scraper/src/InstagramScraper/Model/Media.php on line 462

Thanks

**Comment by raiym** [comment]
@pdolinaj closed by @jasonadkison commit https://github.com/postaddictme/instagram-php-scraper/commit/2b13036f933aa4bcea2d6aa6c575fd62e76de261
