### ISSUE TITLE
Wrong type conversion

### ISSUE THREAD

**Issue by aik27** [postaddictme/instagram-php-scraper#212]
Some accounts have ID outside integer range (−2 147 483 648  to 2 147 483 647). For example: 6 271 847 937. So type conversion to INT always return 2 147 483 647 (maximum range value). Affected this functions: 

account->getId()
account->initPropertiesCustom()

And maybe others. My user case: 

https://github.com/postaddictme/instagram-php-scraper/issues/208

**Comment by raiym** [comment]
@aik27 it has been resolved: https://github.com/postaddictme/instagram-php-scraper/commit/09d6cb586de189f507bf466f1ca98307f4d6af49
Will be available in upcoming update
