### ISSUE TITLE
getType() in getMediasByTag return empty

### ISSUE THREAD

**Issue by pedropamn** [postaddictme/instagram-php-scraper#225]
```
$medias = $instagram->getMediasByTag('cars', 5);
$medias[$i]->getType();
```

getType() returns empty in getMediasByTag.....

**Comment by pedropamn** [comment]
Temporarily, i solve this way:

```
//$i is a array index inside a for loop
$link = $medias[$i]->getLink();
$json_media_by_url = $instagram->getMediaByUrl($link);
$type = $json_media_by_url->getType();
```

This solve temporarily, but my script is accessing each media to get a type, when previously i had directly via `getMediasByTag`

Is there a better way? This is a bug?

Thanks

**Comment by Sieboldianus** [comment]
Same problem here. For now, I solved it with this (not perfect, but I only need distinction image/video):
```php
                    if (!empty($media->getVideoViews())) {
                        $media_type = "video";
                    } else {
                        $media_type = "image";
                    }     
```

**Comment by pedropamn** [comment]
@Sieboldianus is the last version?

**Comment by Sieboldianus** [comment]
Yes, I fetched all updates on November 30 (there's a minor chance that I did something wrong merging my own code).

**Comment by MKiselev** [comment]
Same problem. :worried:
