### ISSUE TITLE
Need solution - top_posts and getMediasByTag result

### ISSUE THREAD

**Issue by aik27** [postaddictme/instagram-php-scraper#227]
For now, this code return 4 images for 'bybakery_ru' hashtag:

```
$Instagram = new \InstagramScraper\Instagram();
$media = $Instagram->getMediasByTag('bybakery_ru');
foreach ($media as $key=>$item) {
	echo '<a href="'.$item->getLink().'">';
	echo $item->getId();
	echo '</a><br />';
}
```

But there are at least 7 images with this hashtag. Proof:

https://www.instagram.com/explore/tags/bybakery_ru/

So why InstagramScraper doesn't return all images?

I investigate this issue:

getMediasByTag function use this code to get images:

`$nodes = $arr['tag']['media']['nodes'];`

But $arr['tag'] also contained 'top_posts' key. This key has "nodes" too with all 7 images.

I don't understand logic, why ['media']['nodes'] contained 4 images, why ['top_posts']['nodes'] contained 7 and how getMediasByTag must be modificated to return all images in all situations.

Do you have any solution?

**Comment by Sieboldianus** [comment]
Just add
´´´
        $first = false;
        if ($maxId == '') {
            $first = true;
        }
        //...
	$nodes = $arr['tag']['media']['nodes'];
        if ($first == true) {
            $nodesTop = $arr['tag'['top_posts']['nodes'];
            $nodes = array_merge($nodes,$nodesTop);
        }
´´´
.. if you need top posts. But be aware that some top_posts may be duplicates of media-posts.

**Comment by aik27** [comment]
@Sieboldianus, thanks for code.
