### ISSUE TITLE
Some location bugs?

### ISSUE THREAD

**Issue by zaivst** [postaddictme/instagram-php-scraper#232]
1. Trying to get media by getMediaByCode method. But in dump you can see that locationName is not empty, and locationId is empty. Is it ok?

![err](https://user-images.githubusercontent.com/33477018/33650394-69d77e88-da94-11e7-9d3a-a049d39b6144.png)

2. Tying to get media list by getMedias method. But in dump both locationName and locationId are empty. Is it ok?

**Comment by Sieboldianus** [comment]
I can confirm both issues. For 2, my observation was that location information is not available anymore in user-media-list json (e.g. `https://www.instagram.com/{username}/?__a=1&max_id={max_id}`).

**Comment by tomassrnka** [comment]
For some unknown reason, location does not work when using getMedias method. Location is provided only for single post calls (getMediaById/Code etc). 

So my fix is only for 1. mentioned here.
