### ISSUE TITLE
Use "profile_pic_url_hd" instead of "profile_pic_url" or both

### ISSUE THREAD

**Issue by dolfy82** [postaddictme/instagram-php-scraper#234]
Hi,

Could it be possible to use "profile_pic_url_hd" instead of "profile_pic_url" for $profilePicUrl or add new property to Account ?

Thank you

**Comment by parviznoori50-spec** [comment]
https://www.instagram.com/yade.192?igsh=cDFnbHBnd2ExOXoy

**Comment by parviznoori50-spec** [comment]
https://www.instagram.com/yade.192?igsh=cDFnbHBnd2ExOXoy
