### ISSUE TITLE
Auth error

### ISSUE THREAD

**Issue by Wayfindertm** [postaddictme/instagram-php-scraper#237]
An uncaught Exception was encountered
Type: InstagramScraper\Exception\InstagramAuthException

Message: Something went wrong. Please report issue.

Filename: /home/w37436/public_html/xxxxxxxx/application/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php

Line Number: 989

var_dump($response->body):

object(stdClass)#51 (4) { ["message"]=> string(19) "checkpoint_required" ["checkpoint_url"]=> string(33) "/challenge/6119381144/LwISYjl8kZ/" ["lock"]=> bool(false) ["status"]=> string(4) "fail" }

**Comment by filippodicostanzo** [comment]
Same issue when i try to authenticate.

I try with many account but the module return the same error

**Comment by zebratratata** [comment]
I have this problem too.

**Comment by rusan** [comment]
https://github.com/postaddictme/instagram-php-scraper/pull/241 - for cli fixed here.

**Comment by zebratratata** [comment]
this is not helped. oO

**Comment by zebratratata** [comment]
` if (!preg_match('/name="security_code"/', $response->raw_body, $matches)) {
            throw new InstagramAuthException('Something went wrong when try two step verification. Please report issue.');
        }`

Down at this code

**Comment by filippodicostanzo** [comment]
How can I resolve this error?

An uncaught Exception was encountered
Type: InstagramScraper\Exception\InstagramAuthException

Message: Something went wrong. Please report issue.

Filename: /vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php

Line Number: 989

**Comment by rusan** [comment]
@zebratratata, @filippodicostanzo - I need the content of the page to parse it. I think it can be language dependable :(.

**Comment by filippodicostanzo** [comment]
I've downloaded full code from composer,
I changed the credentials and launch one of the example pages.

And return this error

**Comment by Wayfindertm** [comment]
I don't think what this issue can be resolved.

http://joxi.ru/D2PyebaipEy4nA
http://joxi.ru/GrqBYOQSQ0DO5m

**Comment by rusan** [comment]
@Wayfindertm, it is possible. But of course, you need to get access to email and enter the code from email. For my account, it works (only for cli).

**Comment by rusan** [comment]
@filippodicostanzo, do you have any internet messenger? We can debug online :).

**Comment by filippodicostanzo** [comment]
@rusan Yes i have facebook, skype and whatsapp.
what do you prefer?

**Comment by rusan** [comment]
@filippodicostanzo - find me on facebook https://facebook.com/rusan

**Comment by rusan** [comment]
#241 works only for cli mode right now. Maybe later it will support web mode.

**Comment by zebratratata** [comment]
[insta.log](https://github.com/postaddictme/instagram-php-scraper/files/1555754/insta.log)
this is response html code

**Comment by rusan** [comment]
@zebratratata, I'll check.

**Comment by rusan** [comment]
@zebratratata, can you check my branch - I update it.

**Comment by Wayfindertm** [comment]
It's page from my first screenshot.

@rusan боюсь что инстаграм окончательно прикрыл возможность парсинга без использования апи.

**Comment by zebratratata** [comment]
@rusan not working. i tried both login methods

**Comment by eversionsystems** [comment]
I'm getting the same error when I try to login.  With the same account I navigate to Instagram.com and I am being challenged with the "We Detected An Unusual Login Attempt".  I am stuck in a loop of clicking the "This Was Me" button and trying to create a session with the php scraper.  Is this something that using the new proxy feature will resolve?

**Comment by rusan** [comment]
@Wayfindertm, у меня работает - ты проверял на мастере этого репа? Просто фикс был в ветке в моём форке, теперь он вмержен - можно попробовать снова. Я пока готов суппортить. Если что-то не работат - можешь нашписать мне напрямую - ФБ я дал выше.

**Comment by rusan** [comment]
@zebratratata - right now my pull request merged - can you check it on master?

**Comment by rusan** [comment]
@eversionsystems - right now my pull request merged - can you check it on master?

**Comment by zebratratata** [comment]
@rusan it is worked in my localhost test site. but when i uploaded to main site, it is not worked.
O_O

**Comment by rusan** [comment]
@zebratratata, please contact me and we will debug this bug.

**Comment by filippodicostanzo** [comment]
@zebratratata yesterday with the help of @rusan I managed to make it work the instagram-scraper but only with cli because the session refers to CLI

**Comment by eversionsystems** [comment]
@rusan, I've got it to generate a token via the CLI now and it seems to be working.  Do you know how to include the config "CURLOPT_CAINFO" for the Unirest program?  I couldn't send any curl requests because it was complaining no SSL certificate was present so I hardcoded in the config in the file "\unirest-php\src\Unirest\Request.php" line 416.  Localhost is a Wampserver setup.

```
        $curl_base_options = [
            CURLOPT_URL => self::encodeUrl($url),
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_HTTPHEADER => self::getFormattedHeaders($headers),
            CURLOPT_HEADER => true,
            CURLOPT_SSL_VERIFYPEER => self::$verifyPeer,
            //CURLOPT_SSL_VERIFYHOST accepts only 0 (false) or 2 (true). Future versions of libcurl will treat values 1 and 2 as equals
            CURLOPT_SSL_VERIFYHOST => self::$verifyHost === false ? 0 : 2,
            // If an empty string, '', is set, a header containing all supported encoding types is sent
            CURLOPT_ENCODING => '',
	    CURLOPT_CAINFO		=> 'C:/wamp/ca-bundle.crt'
        ];
```

**Comment by eversionsystems** [comment]
@rusan I sporadically get this error when running my login script via CLI.

```
Fatal error: Uncaught exception 'Unirest\Exception' with message 'Could not resolve host: www.instagram.comhttps' in C:\wamp\www\gc\wp-content\plugins\group-comment\includes\instagram-php-scraper\vendor\mashape\unirest-php\src\Unirest\Request.php:477
Stack trace:
#0 C:\wamp\www\gc\wp-content\plugins\group-comment\includes\instagram-php-scraper\vendor\mashape\unirest-php\src\Unirest\Request.php(236): Unirest\Request::send('GET', 'https://www.ins...', NULL, Array, NULL, NULL)
#1 C:\wamp\www\gc\wp-content\plugins\group-comment\includes\instagram-php-scraper\src\InstagramScraper\Instagram.php(1055): Unirest\Request::get('https://www.ins...', Array)
#2 C:\wamp\www\gc\wp-content\plugins\group-comment\includes\instagram-php-scraper\src\InstagramScraper\Instagram.php(1014): InstagramScraper\Instagram->verifyTwoStep(Object(Unirest\Response), Array)
#3 C:\wamp\www\gc\wp-content\plugins\group-comment\includes\instagram-php-scraper\test.php(16): InstagramScraper\Instagram->login(true, true)
#4 {main}
  thrown in C:\wamp\www\gc\wp-content\plugins\group-comment\includes\instagram-php-scraper\vendor\mashape\unirest-php\src\Unirest\Request.php on line 477
```

**Comment by Wayfindertm** [comment]
@rusan На хостинге нет ssh. Я так понял тут надо через консоль войти, чтобы создалась сессия и потом должно норм работать?

**Comment by Wayfindertm** [comment]
@rusan я бы добавил еще проверку запущен из под cli или нет при считывании stdin

**Comment by rusan** [comment]
@Wayfindertm, так точно. Но можно сессию локально сделать, а потом её скопировать на хостинг - главное в правильную папку положить. Нет, я не хочу делать проверку перед считыванием. Я наверное добавлю эксепшен что если второй параметр для логина передаешь true не в cli - тогда сразу его кидать и говорить что так нельзя.

**Comment by Wayfindertm** [comment]
@rusan Ну или так :)

**Comment by rusan** [comment]
@eversionsystems, contact me directly. Something strange in your error...

**Comment by eversionsystems** [comment]
@rusan , how do I contact you?  I am seeing this error now when running the script via CLI.

```
Fatal error: Uncaught exception 'InstagramScraper\Exception\InstagramAuthException' with message 'Something went wrong when try two step verification and enter security code. Please report issue.' in C:\wamp\www\gc\wp-content\plugins\group-comment\includes\instagram-php-scraper\src\InstagramScraper\Instagram.php:1116
Stack trace:
#0 C:\wamp\www\gc\wp-content\plugins\group-comment\includes\instagram-php-scraper\src\InstagramScraper\Instagram.php(1015): InstagramScraper\Instagram->verifyTwoStep(Object(Unirest\Response), Array)
#1 C:\wamp\www\gc\wp-content\plugins\group-comment\includes\instagram-php-scraper\test.php(16): InstagramScraper\Instagram->login(true, true)
#2 {main}
  thrown in C:\wamp\www\gc\wp-content\plugins\group-comment\includes\instagram-php-scraper\src\InstagramScraper\Instagram.php on line 1116
```

**Comment by Wayfindertm** [comment]
@rusan `Но можно сессию локально сделать, а потом её скопировать на хостинг - главное в правильную папку положить`

А сессия к IP не привязана у них?

**Comment by rusan** [comment]
@eversionsystems, link in my profile or in this topic (https://facebook.com/rusan) or give me your prefered type of communication.

**Comment by rusan** [comment]
@Wayfindertm, насколько я понимаю нет. Так как если авторизироваться в вебе в одном месте и потом придти домой - ты все равно авторизован.

**Comment by filippodicostanzo** [comment]
Any news for fixing this issue on official repository?

**Comment by rusan** [comment]
@filippodicostanzo, my pull request was merged to master the official repository. You can use it.

**Comment by filippodicostanzo** [comment]
@rusan yes rusan thanks again for your support.

But do you have any news for work it in a webserver without shell?

**Comment by eversionsystems** [comment]
I'm still having issues with the 2-step verification process.  It's returning 404 response code but the $post_data and $url fields contain data.  I didn't check the $headers variable.

```
Fatal error: Uncaught InstagramScraper\Exception\InstagramAuthException: Something went wrong when try two step verification and enter security code. Please report issue. in /home/groupcom/public_html/gc/wp-content/plugins/group-comment/includes/instagram-php-scraper/src/InstagramScraper/Instagram.php:1117
Stack trace:
#0 /home/groupcom/public_html/gc/wp-content/plugins/group-comment/includes/instagram-php-scraper/src/InstagramScraper/Instagram.php(1015): InstagramScraper\Instagram->verifyTwoStep(Object(Unirest\Response), Array)
#1 /home/groupcom/public_html/gc/wp-content/plugins/group-comment/includes/instagram-php-scraper/create-cookie.php(16): InstagramScraper\Instagram->login(true, true)
#2 {main}
  thrown in /home/groupcom/public_html/gc/wp-content/plugins/group-comment/includes/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 1117
```

**Comment by rusan** [comment]
@eversionsystems, can you chat with me? I can debug it for you.
