### ISSUE TITLE
[Question] Support actions

### ISSUE THREAD

**Issue by WilliamBlais** [postaddictme/instagram-php-scraper#244]
Hi,

Thank you for your library!

I was wondering if you even plan to support actions, for example: like, comment, follow...

Thanks,
William

**Comment by zaivst** [comment]
This is from "private API", so i think it is not neccesary to make it in this library bacause using "private API" is for your own risk and there is information that instagram can block such accounts

**Comment by raiym** [comment]
@WilliamBlais @zaivst yes there is a plan to implement this features since web versions supports it. 

It is already exist in Java library, so need to implement in php. 

Don't know when though.

**Comment by WilliamBlais** [comment]
@zaivst You can do all those actions using the public web API. For example, like endpoint is https://www.instagram.com/web/likes/{mediaID}/like/

@raiym Awesome! I'll do some research to see how to implement it.

**Comment by zaivst** [comment]
Seems that I mixed up it with private api that allows to add new media. Sorry

**Comment by WilliamBlais** [comment]
@zaivst No worries! :)

**Comment by raiym** [comment]
supported
