### ISSUE TITLE
getMediasByTag Not Working

### ISSUE THREAD

**Issue by absfarah** [postaddictme/instagram-php-scraper#250]
I believe Instagram has changed the response JSON?

It looks like this: https://gist.github.com/absfarah/39a15138693a479780f05ec705bf6a2f

So that function and perhaps others won't work.

**Comment by zaivst** [comment]
I confirm this issue

**Comment by zaivst** [comment]
Instagram get correct response but with changed JSON structure if use request without max_id parameter
For example:
`https://www.instagram.com/explore/tags/agungvolcano/?__a=1`

**Comment by theianjohnson** [comment]
See https://github.com/postaddictme/instagram-php-scraper/pull/251/files for a fix for getMediasByTag() function, which I use for https://tagify.io

**Comment by zaivst** [comment]
Thanks! It works!
