### ISSUE TITLE
i cant run the code from my server

### ISSUE THREAD

**Issue by kesienajoel** [postaddictme/instagram-php-scraper#252]
the script runs perfectly on my local machine, but when i move it to my server, i keep getting either "500 internal server error" or "Message: Failed to connect to 2a03:2880:f222:e5:face:b00c:0:4420: Network is unreachable" while executing any of the examples.

**Comment by aik27** [comment]
`"Message: Failed to connect to 2a03:2880:f222:e5:face:b00c:0:4420: Network is unreachable"`

cURL sending requests through IPv6. Seems like interface is active but was not configured.
Simplest solution - disable IPv6 on server, If you can.

`"500 internal server error"`

Look at PHP / Web-servers logs
