### ISSUE TITLE
checkpoint required

### ISSUE THREAD

**Issue by abunour22** [postaddictme/instagram-php-scraper#258]
When using Instagram::setProxy()
it's return An uncaught Exception was encountered
Type: InstagramScraper\Exception\InstagramAuthException

Message: Something went wrong. Please report issue.

Filename: /home/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php

checkpoint_required

**Comment by Sieboldianus** [comment]
Not a direct reply, but you can also use proxy function for curl:
Put this at the beginning of your code
`Unirest\Request::proxy('212.32.3.1', 3128, CURLPROXY_HTTP);`

**Comment by muthu-kc** [comment]
It's because of IP from the new location.

You can send GET request to challenge URL and after get verification code, send POST request with code. Then you will get session for the user.

**Comment by iamtelo** [comment]
please send the code for that

**Comment by muthu-kc** [comment]
You can refer the code in this thread to avoid checkpoint issue.
