### ISSUE TITLE
Error get media

### ISSUE THREAD

**Issue by iranappo** [postaddictme/instagram-php-scraper#259]
Hello
I have used getMedias in last week and it was working
But now i cannot use it and it get error

**Comment by zaivst** [comment]
It's ok for me...

**Comment by iranappo** [comment]
I will try it Thanks

**Comment by danielz0** [comment]
Hi guys,
I am experiencing the same error. Whenever trying to get media I got empty set. 

I have investigated this a bit and looks like $this in InitializerTrait.php has been constantly overwriting with empty values. Currently, I am not sure if this is php7 issue or the scraper issue, but I would highly appreciate if you could try to scrape Instagram pages in a loop, but also looping through images found. 

You will see that public static function create(array $params = null) in InitializerTrait.php is somehow called twice from Media::create($mediaArray); first time with correct array of params, but the second time with wrong set of values. Unfortunately the second call overwrites values from the first call.

Here is my use case scenario:
Loop thought instagram URLs (example: https://www.instagram.com/ikeasaudiarabia/).
Get last 20 medias on this URL.
Loop through medias and get images.

Hope this will help you to reproduce the issue.
Best,

**Comment by iranappo** [comment]
@danielz0 Do you can send relate class for me?

**Comment by iranappo** [comment]
@danielz0 Do you can send relate class for me?

**Comment by danielz0** [comment]
Do you mean the class from namespace InstagramScraper;  named Instagram? Or my class?

**Comment by iranappo** [comment]
Class that you edit it and it is working
Do you change Instagram class or make class for yourself?

**Comment by danielz0** [comment]
`
foreach ($pages as $page){
	    	try{
	    		$instagram = new Instagram();
	    		$response = $instagram->getMedias($page->url, 1);
	    		$this->processResponse($response, $page);
	    		$this->updateFromSuccess($page);
	    	
	    	}catch (InstagramException $e){
	    		Log::debug('Instagram page ' . $page->url . ' failed');
	    		$this->updateFromError($page);
	    	}
    	}
`
And this line:
`public function processResponse($response, InstagramScrapeSeed $page)
    {
        foreach ($response as $media){
			if(!($media instanceof InstagramScraper\Model\Media)){
				Log::debug(__CLASS__.'::'.__FUNCTION__.' Instagram page '.$page.' has wrong media\'s type: '.gettype($media).' : '.json_encode($media));
				continue;
			}`

always returns error because I got empty set of media.

Sorry, @iranappo I can not make it working. Always got wrong results. I have tried on both 0.8.8 and 0.8.11 version.

**Comment by iranappo** [comment]
OK,What is your offer?
I need class that working always without any problem?

**Comment by danielz0** [comment]
@iranappo I am not sure if we are on the same page. 
I need help with this Instagram Scraper and thought you can help me a bit investigate the issue.

I have tried to solve this myself, but I am not able to.

**Comment by danielz0** [comment]
@iranappo are you able to run InstagramScraper and get correct results?

**Comment by iranappo** [comment]
Oh my god
Please help @zaivst Please,We are wronged  :))))

**Comment by iranappo** [comment]
@danielz0 I could get correct results in last but now i cannot
I feel instagram change their structure

**Comment by danielz0** [comment]
Well @zaivst it would be nice of you if you could take a look. 
Thanks in advance.

**Comment by zaivst** [comment]
I use not last version of scraper and it still ok for me on php 5.4, php 5.6 and php 7.1
I don't have much time for reproduce this issue now and I'm afraid to update the scrapper now )))

**Comment by danielz0** [comment]
@zaivst what exact version of this scraper are u using?

**Comment by zaivst** [comment]
v0.8.8 with this https://github.com/postaddictme/instagram-php-scraper/pull/251/files edits

**Comment by danielz0** [comment]
@zaivst OK thanks - this was the one to which I have updated recently and all broke. Maybe I need to fetch the pull.

**Comment by iranappo** [comment]
@danielz0 Could you use correct code?

**Comment by danielz0** [comment]
@iranappo No. I had to write the scraper myself. It is easy in my case because I need only images and I dont care about the rest. Additionally I need response's return code to be written in db which was not possible when I was using this code.

**Comment by truthuntold** [comment]
I don't have time to create a pull request however I made quick ~sloppy~ fix. Instagram is return html along with the json. 

I added this function to Instagram.php
```    
    public function patchHtml($rawBody){
        $body = $rawBody;
        $startString = 'window._sharedData = ';
        $start = strpos($body, $startString);
        $end = strpos($body, ';</script>', $start);
        $indexStart = $start+strlen($startString);
        $sub = substr($body, $indexStart, $end - $indexStart);
        return $sub;
    }
```

Then anywhere I had an issue, in my case it was getMedias, and getAccount, I used the patchHtml to remove the newly return html.

```
            // call to parse our new html returned from Instagram
            $sub = $this->patchHtml($response->raw_body);
            // Decode with the parsed json string from the html
            $arr = json_decode($sub, true, 512, JSON_BIGINT_AS_STRING);
            if (!is_array($arr)) {
                throw new InstagramException('Response code is ' . $response->code . '. Body: ' . static::getErrorBody($response->body) . ' Something went wrong. Please report issue.');
            }
            // base json structure changed so I linked it back up here.
            $arr = $arr['entry_data']['ProfilePage'][0];
            $nodes = $arr['user']['media']['nodes'];
```

**Comment by iranappo** [comment]
@truthuntold I use your code but it is not working
Is it working for you?
