### ISSUE TITLE
Instagram's undocumented ?__a=1 no longer works

### ISSUE THREAD

**Issue by FranciscoG** [postaddictme/instagram-php-scraper#263]
As of today it looks like the `?__a=1` query that this lib uses no longer works which is causing this library to break.  

Is anyone else experiencing this?

**Comment by rhcarlosweb** [comment]
Same here 😢

**Comment by rhcarlosweb** [comment]
started working again here

**Comment by FranciscoG** [comment]
it's now back for me too.   WTF Instagram?!

they probably deployed a released that messed something up and fixed/reverted it

**Comment by berkantipek** [comment]
Gone again.

**Comment by harinigunabalan** [comment]
It works now!

**Comment by karsa87** [comment]
Gone again.
:((

**Comment by Julianwan** [comment]
Seems back up again.
