### ISSUE TITLE
follow/unfollow/block/unblock

### ISSUE THREAD

**Issue by carlonicora** [postaddictme/instagram-php-scraper#267]
Hi,
Thanks for sharing this project!!

Not an issue, hope it is ok to post it here!

I was wondering if there is a specific reason for not implementing post actions as follow, unfollow, block and unblock.

Happy to help if needed!

Ciao
Carlo

**Comment by devboxr** [comment]
Would love to get an answer on this as well.

**Comment by Parviz-Turk** [comment]
me too.

**Comment by raiym** [comment]
Like/unlike: https://github.com/postaddictme/instagram-php-scraper/blob/master/examples/likeAndUnlikeMedia.php

Comment/uncomment: https://github.com/postaddictme/instagram-php-scraper/blob/master/examples/addAndDeleteComment.php
