### ISSUE TITLE
InstagramAuthException Error

### ISSUE THREAD

**Issue by evah** [postaddictme/instagram-php-scraper#278]
I ran the command `php -f getAccountById.php ` in the `examples` folder and got the following error. 

PHP Fatal error:  Uncaught InstagramScraper\Exception\InstagramAuthException: Something went wrong. Please report issue. in /development/work/image_analysis/porsche/instagram-php-scraper/src/InstagramScraper/Instagram.php:1056
Stack trace:
#0 /development/work/image_analysis/porsche/instagram-php-scraper/examples/getAccountById.php(9): InstagramScraper\Instagram->login()
#1 {main}
  thrown in /development/work/image_analysis/porsche/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 1056

**Comment by Simos455** [comment]
got the same error today

**Comment by andriy063** [comment]
Same error

**Comment by rcobelli** [comment]
I was able to fix this using the official Instagram app. Just open the app (assuming it is logged into the same account as `InstagramScraper`) and when the app alerts you to suspicious login attempts, allow the login attempt.
