### ISSUE TITLE
"Suspicious Login Attempt"

### ISSUE THREAD

**Issue by amauryleproux** [postaddictme/instagram-php-scraper#280]
Hello guys,

When I run the script manually from my local machine there is zero issues everything works like a charm but I tried to run a cron task on my AWS, every hours then every 6 hours and now every 12 hours but I always get issues cause Instagram seems to block the login attempt cause he doesn't know where the attempt come from... 

Did you get this king of errors? And do you have an idea how to counter instagram suspicious verification?

Cheers.

**Comment by bomboem** [comment]
Tried proxys?

**Comment by RobertGrubb** [comment]
To me it looks like they are starting to block IPs from AWS and such.. For instance, I was able to make use of the login method on localhost, but as soon as I tried it from an AWS instance, it was blocked. Definitely try to make use of a proxy and test it.
