### ISSUE TITLE
getAccountById return incorrect user data

### ISSUE THREAD

**Issue by shootgsm** [postaddictme/instagram-php-scraper#284]
Simplified piece of code. 
```
$tag = 'lalala';
$postLimit = 100;
$instagram = new Instagram();
$medias = $instagram->getMediasByTag($tag, $postLimit);
foreach ($medias as $media) {
//$media->getOwner()->getId() is 4110885322
$user = $instagram->getAccountById($media->getOwner()->getId());
var_dump($user); die;
}
```

returns 

> object(InstagramScraper\Model\Account)#7586 (18) {
>   ["id":protected]=>
>   string(10) "5327828452"
>   ["username":protected]=>
>   string(6) "follow"
>   ["fullName":protected]=>
>   string(7) "@Follow"
>   ["profilePicUrl":protected]=>
>   string(157) "https://scontent-sea1-1.cdninstagram.com/vp/bce3ef1d3e8e0cb80cfcd4506a4c8157/5B33E637/t51.2885-19/s150x150/26864243_144376576228875_1352546061196984320_n.jpg"
>   ["biography":protected]=>
>   string(19) "You know the drill."
>   ["externalUrl":protected]=>
>   NULL
>   ["followsCount":protected]=>
>   int(41)
>   ["followedByCount":protected]=>
>   int(15216)
>   ["mediaCount":protected]=>
>   int(1)
>   ["isPrivate":protected]=>
>   bool(true)
>   ["isVerified":protected]=>
>   bool(false)
>   ["isLoaded":protected]=>
>   bool(true)
>   ["isNew":protected]=>
>   bool(false)
>   ["isLoadEmpty":protected]=>
>   bool(false)
>   ["isFake":protected]=>
>   bool(false)
>   ["isAutoConstruct":protected]=>
>   bool(false)
>   ["modified":protected]=>
>   int(1520924395)
>   ["data":protected]=>
>   array(0) {
>   }
> }

So user data such as username, profilePicUrl and other are incorrect

**Comment by yazhog** [comment]
same problem

**Comment by yazhog** [comment]
getUsernameById now does not work with not auth.
need another way to find users by id

$responseUrl = $response->headers['Location']; //https://www.instagram.com/accounts/login/?next=/web/friendships/200169398/follow/

and we got username - "follow"
