### ISSUE TITLE
 Account with this username does not exist

### ISSUE THREAD

**Issue by mirabdolbaghi** [postaddictme/instagram-php-scraper#286]
Running the scraper in localhost get this error
Fatal error: Uncaught InstagramScraper\Exception\InstagramException: Account with this username does not exist in src/InstagramScraper/Instagram.php:593 Stack trace: #0 /examples/getAccountByUsername.php(10): InstagramScraper\Instagram->getAccount('kevin') #1 {main} thrown in src/InstagramScraper/Instagram.php on line 593

**Comment by limminho** [comment]
I'm having the same problem.

**Comment by hanbz** [comment]
get the same problem

**Comment by imanismailbox** [comment]
variable on output instagram has changed

**Comment by fattony80** [comment]
Same problem here, any quick fix?

**Comment by aik27** [comment]
@fattony80 https://github.com/postaddictme/instagram-php-scraper/pull/290

**Comment by fattony80** [comment]
Thanks! @aik27

**Comment by mirabdolbaghi** [comment]
@aik27 thanks
 how you know about new api like:

https://instagram.com/graphql/query/?query_id=17888483320059182&id=user_id&first=12&after=end_cursor

does instagram have api newsfeed ???

**Comment by aik27** [comment]
@mirabdolbaghi, just stackoverflow: https://stackoverflow.com/questions/49265013/instagram-a-1max-id-end-cursor-isnt-working-for-public-user-feeds/49266320#49266320

**Comment by pedropamn** [comment]
I have updated to the lastest version. but the error "Account with this username does not exist" appears....

**Comment by mzherikhova** [comment]
I have updated to the lastest version. but the error "Account with this username does not exist" appears.... :(

I use: $account = $instagram->getAccount($username);

the same I updated but error anyway apears

**Comment by pedropamn** [comment]
I've opened a new issue for this #294
