### ISSUE TITLE
Faced with media download problem

### ISSUE THREAD

**Issue by vanGary** [postaddictme/instagram-php-scraper#29]
# Hi, Raiym!

I want to get medias of several users, i launch "while endwhile" procedure, but as result got only info about around 500 insta posts, rest of them goes with empty info (**upd: not with empty info, but cannot download at all, if medias more than around 500**).

If i want to get medias of only 1 user(without while endwhile) - where is no problem.
## **Limited workable:**

<?php
error_reporting(-1);
header('Content-Type: text/html; charset=utf-8');

require "vendor/autoload.php";
 use InstagramScraper\Instagram;

include ("bd.php"); 

$result1 = mysql_query("SELECT idinst FROM users ORDER BY id",$db);
//take id
while($myrow = mysql_fetch_array($result1)):

```
$idinst=$myrow['idinst'];
$result2 = mysql_query ("DELETE FROM media WHERE idinst='$idinst'");

$account = Instagram::getAccountById($idinst);
$insta=$account->username;
```
### **//if less than 500 medias(working fine)**

```
if ($account->mediaCount<500)
```

  {  

```
$q=$account->mediaCount;
$medias = Instagram::getMedias($insta, $q);
```

for ($b = 0; $b<$q; $b++):

$mediaUrl = $medias[$b]->imageLowResolutionUrl;
$mediaLikes = $medias[$b]->likesCount;
$mediaComments = $medias[$b]->commentsCount;
$mediaDate = $medias[$b]->createdTime;
$mediaTag = $medias[$b]->caption;
$mediaType = $medias[$b]->type;
$mediaViews = $medias[$b]->videoViews;

$result3 = mysql_query ("INSERT INTO media            (url,insta,likes,comments,date,tags,number,type,videoviews,idinst) VALUES('$mediaUrl','$insta','$mediaLikes','$mediaComments','$mediaDate','$mediaTag','$b','$mediaType','$mediaViews','$idinst')");

```
endfor;
```

   }
### **//if more than 500 and less than 1000  medias(working only 1st part - from 0 to 500)**

```
elseif ($account->mediaCount>500 and $account->mediaCount<1000)
```

  { 

```
$q=500;
$medias = Instagram::getMedias($insta, $q);
```

**// for first 500 medias**
for ($b = 0; $b<$q; $b++):

$mediaUrl = $medias[$b]->imageLowResolutionUrl;
$mediaLikes = $medias[$b]->likesCount;
$mediaComments = $medias[$b]->commentsCount;
$mediaDate = $medias[$b]->createdTime;
$mediaTag = $medias[$b]->caption;
$mediaType = $medias[$b]->type;
$mediaViews = $medias[$b]->videoViews;

$result3 = mysql_query ("INSERT INTO media (url,insta,likes,comments,date,tags,number,type,videoviews,idinst) VALUES('$mediaUrl','$insta','$mediaLikes','$mediaComments','$mediaDate','$mediaTag','$b','$mediaType','$mediaViews','$idinst')");

endfor;

**// for the rest part of medias(dont work at all, return nothing)**

$q=$account->mediaCount;
$medias = Instagram::getMedias($insta, $q);

for ($b = 500; $b<$q; $b++):

$mediaUrl = $medias[$b]->imageLowResolutionUrl;
$mediaLikes = $medias[$b]->likesCount;
$mediaComments = $medias[$b]->commentsCount;
$mediaDate = $medias[$b]->createdTime;
$mediaTag = $medias[$b]->caption;
$mediaType = $medias[$b]->type;
$mediaViews = $medias[$b]->videoViews;

$result3 = mysql_query ("INSERT INTO media (url,insta,likes,comments,date,tags,number,type,videoviews,idinst) VALUES('$mediaUrl','$insta','$mediaLikes','$mediaComments','$mediaDate','$mediaTag','$b','$mediaType','$mediaViews','$idinst')");

endfor;

}
endwhile;

?>

```

## **Any ideas?**

```

**Comment by raiym** [comment]
Thank you for contribution. 
I will check

**Comment by raiym** [comment]
@vanGary  it seems that Instagram changed something. I will experiment and hope will find solution)

**Comment by vanGary** [comment]
@raiym I also hope) pray for u :laughing: 
upd: not with empty info, but cannot download at all, if medias more than around 500

**Comment by raiym** [comment]
@vanGary strange thing, I sat today to resolve issue and everything works fine -_-

**Comment by raiym** [comment]
I've just added response code in exception message and that is all

**Comment by raiym** [comment]
Code that I am running: 

```
$instagram = new Instagram();
try {
    $medias = Instagram::getMedias('kevin', 1000);
    echo $medias[998]->imageThumbnailUrl;
} catch (\Exception $ex) {
    print_r($ex);
}

```

**Comment by vanGary** [comment]
@raiym is that way working correctly also in "while endwhile"?
where to add this code? :)

**Comment by raiym** [comment]
It is quite hard to test your code since it is not formatted properly
If it is still important for you at the moment please format your code, re-open issue and I will take a look.
Thank you
