### ISSUE TITLE
Account with this username does not exist

### ISSUE THREAD

**Issue by pedropamn** [postaddictme/instagram-php-scraper#294]
Hi

I applied #290, but my script returns "Account with this username does not exist"

`$account = $instagram->getAccount($username);`

This is weird... Thanks

**Comment by bomboem** [comment]
Same problem here. It's even more confusing, because I'm running the exact same version of the scraper on an other machine, and that works fine. I have no clue. Does anyone have an idea?

**Comment by Johnnydoncom** [comment]
Please is there any fix to the above problem? "Account with this username does not exist". Everything works fine on localhost, but triggers the error when uploaded to remote hosting account. I'm comfused.

**Comment by UXandre** [comment]
@Johnnydoncom had the same issue back in 2018. Make sure when you deploy the site all the packages are updated, too. After upgrading the package to the latest version it was all sorted. Just tried again and the getAccount() method still works for me properly on both local and production with a version of "^0.8.22". 

If all looks good but still doesn't work, giving a go rebooting your server may give you some luck perhaps.

Good luck!

**Comment by erikkubica** [comment]
as @UXandre  mentioned 0.8.22 worked after downgrading the package, but only for single use, afterwards it throws the same error
