### ISSUE TITLE
getPaginateMedias() $hasNextPage is never changed

### ISSUE THREAD

**Issue by gthedev** [postaddictme/instagram-php-scraper#297]
I saw that this was changed on last hotfix, so was wondering if it's on purpose. On `getPaginateMedias` the returned variable `$hasNextPage` is initialized to `true` and never changed. While there is `$isMoreAvailable` variable that seems like it should be (as it was before) `$hasNextPage`. Currently it looks like it will always say there is next page so it could lead to infinite requests to get all the medias.

**Comment by bomboem** [comment]
What file is this variable stored in? I'd like to change it because paginateMedia isn't working properly at my side (i'm in no way able to fetch all images, only a small portion). Could you Point the file out please?

**Comment by gthedev** [comment]
@bomboem Looking at the code now seems like it has been fixed long time ago by this line:
`$hasNextPage = $arr['data']['user']['edge_owner_to_timeline_media']['page_info']['has_next_page'];`

Why is yours not working? We can sort that out here or perhaps better open a new issue for it?
