### ISSUE TITLE
It is possible to get only medias that are videos (is_video:true)?

### ISSUE THREAD

**Issue by gthedev** [postaddictme/instagram-php-scraper#298]
I need to scrape only videos from a profile. If a user has a lot of posts with scattered videos, I have to make _a lot_ of requests just to get few videos.

Is there a parameter for the query endpoint that would force it to return only video media objects?

**Comment by pedropamn** [comment]
I think you can get this if you loop each node and check the "isvideo" property

**Comment by gthedev** [comment]
@pedropamn That's true, but I was wondering if there is a query parameter that can do that on the IG side of things. If a user has 1000 posts and 5 videos, I will need to make 33+ requests (at 30 medias per request) just to get 5 video media objects.
