### ISSUE TITLE
not get media 

### ISSUE THREAD

**Issue by dickyeka** [postaddictme/instagram-php-scraper#305]
your url media 
![screen shot 2018-03-23 at 3 15 47 pm](https://user-images.githubusercontent.com/10336980/37818573-33bc6a1c-2ead-11e8-9c47-69ea798abfc2.png)
Access Denied

**Comment by aik27** [comment]
Use to fix: https://github.com/postaddictme/instagram-php-scraper/pull/303

**Comment by dickyeka** [comment]
merge master branch pls 👍
