### ISSUE TITLE
No thumbnail urls in Story

### ISSUE THREAD

**Issue by ipauler** [postaddictme/instagram-php-scraper#312]
Hello. Just updated my project and get v0.8.17,
and there are no thumbnails and other image urls, except main one.
` ["imageLowResolutionUrl":protected]=>
  string(0) ""
  ["imageThumbnailUrl":protected]=>
  string(0) ""
  ["imageStandardResolutionUrl":protected]=>
  string(0) ""
`

**Comment by pepzi** [comment]
Same problem with getMediaByCode(). Tried #315 but that give me the same url for getImageHighResolutionUrl() and getImageThumbnailUrl() and nothing from getImageLowResolutionUrl().

**Comment by ipauler** [comment]
I've already created pull request with fix, hope it will be merged soon.

**Comment by pepzi** [comment]
Awesome, thanks!
