### ISSUE TITLE
New 404 error with getMediasByTag without Login

### ISSUE THREAD

**Issue by sam-gnx** [postaddictme/instagram-php-scraper#314]
```php
$instagram = new Instagram();
$medias = $instagram->getMediasByTag($hashtag, 60);
```

Gives a 404 (Response code is 404 -  The link you followed may be broken, or the page may have been removed)

When you do the same with login it still works. Looks like Instagram changed an endpoint or something? (didn't investigated thoroughly yet, will do this evening, I feel it's a "global" issue though. I tried on several locations)

```php
$instagram = Instagram::withCredentials('user', 'password');
$instagram->login();
$medias = $instagram->getMediasByTag($hashtag, 60);
```

**Comment by tallesairan** [comment]
use curlOpts to set dedicated ip
