### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by socca1157** [postaddictme/instagram-php-scraper#32]
Thank you thus far for your efforts.

Worried building an app off of this will get my server banned.
Does anyone have any caching techniques or  ideas to limit how often you ping IG?

Even better, I'd love to see a wrapper for this that allows me to make a query that tries the API, then the Cache, then the scraper.

**Comment by socca1157** [comment]
I'm asking if you (or others) have had their server ip banned by using this and sending too many requests? Do you (or others) implement caching within your app to prevent getting banned?

Thank you

**Comment by raiym** [comment]
Yes, I had and I think @wrinkleydog had as well. 

I was waiting for some time to be unblocked and slowed down my activity.

I write to databse everything I need and update it after some actions. 

We use this library in postaddict.me

**Comment by raiym** [comment]
Not only by ip, but by user agent as well

**Comment by raiym** [comment]
No plans for caching for now
