### ISSUE TITLE
Instagram API changes 

### ISSUE THREAD

**Issue by jochenwichmann** [postaddictme/instagram-php-scraper#320]
Is it planned to keep this project up to date with the announced changes (deprecated functions starting in July 2018, see https://www.instagram.com/developer/) to the Instagram API?

**Comment by aik27** [comment]
Instagram-php-scraper does not use Endpoint (https://www.instagram.com/developer/) and Graph API. So "up to date" for this library means, it will works untill next change in undocumented web API. So no one know, when and how changes will come.

**Comment by bux21** [comment]
Most api is now disabled, effective immediately according to email just received from Instagram api platform. 12/11/18 Public Content and early 2020 Basic will be disabled. 

My question is when Basic is disabled will the auth also be disabled? like right now with tinder user can login once within web view inside app and connect/share photos with Tinder profile...
