### ISSUE TITLE
getMediasByLocationId caused Undefined index: location

### ISSUE THREAD

**Issue by filippodicostanzo** [postaddictme/instagram-php-scraper#321]
From today when i call this function

 $insta->getMediasByLocationId(222836363, 10);

this return the error 

'Undefined index: location'

/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php', 868

can i resolve this issue?

**Comment by e2ay** [comment]
same problem.. 
any fix yet?

**Comment by kumbe** [comment]
I noticed this problem as well while trying to obtain pictures related to a location.
While waiting for an update (and a final solution) I modified the code of the method **getMediasByLocationId** to make it work with the new structure returned by Instagram (_line 868 -> 880 of Instagram.php_).
```$nodes = $arr['graphql']['location']['edge_location_to_media']['edges'];
           foreach ($nodes as $mediaArray) {
                if ($index === $quantity) {
                    return $medias;
                }
                $medias[] = Media::create($mediaArray['node']);
                $index++;
            }
            if (empty($nodes)) {
                return $medias;
            }
            $hasNext = $arr['graphql']['edge_location_to_media']['page_info']['has_next_page'];
            $offset = $arr['graphql']['edge_location_to_media']['page_info']['end_cursor'];```

**Comment by filippodicostanzo** [comment]
@kumbe thank you!
it works
