### ISSUE TITLE
Something went wrong. Please report issue. at /vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:315

### ISSUE THREAD

**Issue by pgonzalezc80** [postaddictme/instagram-php-scraper#327]
`Please report issue." at /var/www/appxilon/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php line 315 {"exception":"[object] (InstagramScraper\\Exception\\InstagramException(code: 0): Response code is 403. Body:  message => forbidden; status => fail; Something went wrong. Please report issue. at /var/www/appxilon/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:315)"} []`

**Comment by rhcarlosweb** [comment]
#325

**Comment by pgonzalezc80** [comment]
Same as #325
