### ISSUE TITLE
Response code is 403. Body: Something went wrong. Please report issue.

### ISSUE THREAD

**Issue by aslan93** [postaddictme/instagram-php-scraper#336]
error : **Response code is 403. Body: Something went wrong. Please report issue.**
on    getMediasByUserId();
Please help me!

**Comment by wateengoedidee** [comment]
Use the quick fix from @AsgharRehman https://github.com/postaddictme/instagram-php-scraper/pull/335

In the vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php file in the vendor folder change the generateHeaders method to this:

`/**
     * @param $session
     *
     * @return array
     */
    private function generateHeaders($session)
    {
        $headers = [];
        if ($session) {
            $cookies = '';
            foreach ($session as $key => $value) {
                $cookies .= "$key=$value; ";
            }
            $headers = [
                'cookie' => $cookies,
                'referer' => Endpoints::BASE_URL . '/',
                'x-csrftoken' => $session['csrftoken'],
            ];
        } else {
            $headers = ['cookie' => 'Content-Type:application/x-www-form-urlencoded; sessionid=IGSC020ee8ab76d1e8b01223ab92304cbcd58075ce0bdbc771e872b77046bd82cf40:KXP3eyA1gJybewPt4CDR6ICsiF1y99Eq:{"_auth_user_id":7204036595,"_auth_user_backend":"accounts.backends.CaseInsensitiveModelBackend","_auth_user_hash":"","_platform":4,"_token_ver":2,"_token":"7204036595:iWyZVjjdX5sVFV5VsozthzDCIzBh0muN:99a84e59d3aa505f433844956d47d95e4bf095a24a6e1e397f2418c6384671d2","last_refreshed":1523431960.5035405159}; ',
            ];
        }

        if ($this->getUserAgent()) {
            $headers['user-agent'] = $this->getUserAgent();
        }

        return $headers;
    }`


This will work

**Comment by Birdmaaant** [comment]
I have the same problem.

**Comment by devguar** [comment]
@RobertGrubb exactly!

**Comment by aslan93** [comment]
now already started to work without fixing ...bizarre

**Comment by grohsfabian** [comment]
@aslan93 Yeah, it seems that they rolled back the public endpoint. We'll have to wait and see what they decide in the end to keep.

**Comment by engnaguib** [comment]
?__a=1 working put the problem with paging :(

**Comment by ndiiorio** [comment]
¿Could someone fix this problem?

**Comment by cseesea** [comment]
?__a=1 is not public anymore, it now requires Auth.

**Comment by engnaguib** [comment]
@cseesea  yes for now :(

**Comment by cookieguru** [comment]
Have a look at [pgrimaud/instagram-user-feed](https://github.com/pgrimaud/instagram-user-feed)

**Comment by karamusluk** [comment]
Hi, this is not actually working for me. I am getting 403 errors
