### ISSUE TITLE
Fatal error: Uncaught InstagramScraper\Exception\InstagramException: Response code is 403. Body: Something went wrong. Please report issue

### ISSUE THREAD

**Issue by bomboem** [postaddictme/instagram-php-scraper#338]
Pastebin includes the full error...
This error is returned whenever I try ANYTHING.
https://pastebin.com/raw/a0gzk0ba

Hope you fix this soon!

Thank you in advance,
C

**Comment by RobertGrubb** [comment]
This is because Instagram has locked down several routes, I'm sure quite a few people are looking into how to get through this. Hold tight!

**Comment by bomboem** [comment]
@RobertGrubb
Thank you for your quick response. After doing some research I found this (https://www.instagram.com/developer/changelog/) page. I hope they find a way around this.
Dev, if you reas this, we need you.

**Comment by yazhog** [comment]
Unavailable now:
`const ACCOUNT_JSON_INFO = 'https://www.instagram.com/{username}/?__a=1';`

**Comment by ZipDriver** [comment]
> Unavailable now:
> const ACCOUNT_JSON_INFO = 'https://www.instagram.com/{username}/?__a=1';
> UPD: now works, but still recommend #339

Available, if you do not send any specific headers.

**Comment by bomboem** [comment]
@yazhog Your fix seems to work for me, is this a permanent fix or will this one also start failing in the bext couple of days? Instagram seems to slowly change their platform. Thank you for providing this fix anyways, it's a big help!

**Comment by RobertGrubb** [comment]
@bomboem It's hard to tell how long this fix will last. They could have simply re-enabled the route due to problems on their side until they fix their issues, and disable it again.. There's really no real way to know yet.

**Comment by bomboem** [comment]
Looks like #339 got merged and fixed the problem. Closing issue.

**Comment by willrocha21** [comment]
Pessoal. Boa tarde.

O problema está nos ENDPOINTS.

Eu mudei o ENDPOINTS e funcionou perfeitamente.

const LOGIN_URL = 'https://www.instagram.com/accounts/login/ajax'; (ESTE ESTÁ LEGADO).

const LOGIN_URL = 'https://www.instagram.com/accounts/login/'; (NOVO).

Basta acessar o arquivo Endpoints.php, dentro da classe Endpoints, edite a constante LOGIN_URL.

Como a instalação deste SDK foi feita via composer, é necessário dar permissão as pastas e arquivos até que consiga alterar e salvar o arquivo. OK?

Espero ter ajudado.
