### ISSUE TITLE
 getMediasByUserId not working

### ISSUE THREAD

**Issue by engnaguib** [postaddictme/instagram-php-scraper#340]
Hey all
 i know the issue is listed before ,but when i work with https://www.instagram.com/{username}/?__a=1
it's working ,if i use https://www.instagram.com/{username}/?__a=1&max_id it's return the same data 
The problem with paging ,any help?

**Comment by rhcarlosweb** [comment]
I think this endpoint does not support paging, need to be use with graph query

**Comment by engnaguib** [comment]
@rhcarlosweb  Not working again ,any help :) ?
