### ISSUE TITLE
User credentials are wrong

### ISSUE THREAD

**Issue by pauloamorimbr** [postaddictme/instagram-php-scraper#342]
Hi there...since the recent instagram changes we are getting the errors and I've read people saying we need to be logged for stuff to work.

But when I try Instagram::withCredentials I get the message:
"User credentials are wrong."

I've tried using both e-mail and username for the login, but I always get the message. Is there a special way of sending the login data?

Thanks.

**Comment by bomboem** [comment]
It should work normally... Make sure to use your instagral username without the @. 
    <?php
    $instagram = \InstagramScraper\Instagram::withCredentials('username', 'password');
    //i'm not using cache here
    $instagram->login();
    ?>
This works for me

**Comment by bomboem** [comment]
It should work normally... Make sure to use your instagral username without the @. 
    `<?php
    $instagram = \InstagramScraper\Instagram::withCredentials('username', 'password');
    //i'm not using cache here
    $instagram->login();
    ?>`
This works for me

**Comment by rcobelli** [comment]
I'm having the same issue even using your code @bomboem . I know the credentials are right because I've been able to sign into instagram.com & the app with them

**Comment by bomboem** [comment]
It should work without any additional settings or changes. Maybe try another IP address or are the accounts your attempting to use new ones? I'm just guessing, but could be instagram changed some data in newly registered accounts since they're changing their undocumented API. If this isn't the case, i'm clueless. Hope you find a fix, and let us know if you do...

**Comment by sam-gnx** [comment]
Had the same issue today with a script running without problems for over a month... created a new instagram account and worked again with the new one. Strange thing though, is that the old account with another ip address works, so it feels like they block combination user + ip address or something.

**Comment by bomboem** [comment]
@sam-gnx Looks like instagram may block you if you login too often. Try using cached sessions/proxys to avoid getting logged out. Reffer to the docs on how to use proxys.
