### ISSUE TITLE
Problem with Login

### ISSUE THREAD

**Issue by tallesairan** [postaddictme/instagram-php-scraper#345]
Every time I try to log in, both with the wrong password and the right password accuses this error in Raw_body

"{"errors": {"error": ["Sorry, there was a problem with your request."]}, "status": "ok", "error_type": "generic_request_error"}"

When I try to log in with a user who is with two-factor authentication it does not block the request.
I tested with several dedicated IPs that I have on my server, also tested on a droplet on Digitalocean and accuses the same error, please someone is going through this?

**Comment by MUTOgen** [comment]
Have same issue

**Comment by engnaguib** [comment]
fixed for me when i cloned new one from the repository

**Comment by DDDia** [comment]
Dear, what does it mean:

> when i cloned new one from the repository

?
I have the same problem. So please, tell me what i should do.

Regards

**Comment by engnaguib** [comment]
@DDDia  it's did new changes in endpoint so you should use facebook instagram api  instead of it
https://developers.facebook.com/docs/instagram-api

**Comment by DDDia** [comment]
Problem was sold with new IP adress via proxy. May be it will help to omeone :)

**Comment by engnaguib** [comment]
i did it before but blocked me again :)
