### ISSUE TITLE
getCurrentTopMediasByTagName fail by code 429

### ISSUE THREAD

**Issue by Parviz-Turk** [postaddictme/instagram-php-scraper#346]
hi guys,

this function "getCurrentTopMediasByTagName" fail by response code 429 => "Please wait a few minutes before you try again."

i check the endpoint and its work on desktop browsers but fails on all of my web servers => "https://www.instagram.com/explore/tags/{tag}/?__a=1&max_id={max_id}"

any idea? maybe its about the user-agent?

**Comment by bomboem** [comment]
@Parviz-Turk I am experiencing this issue on 3/5 web servers running this repo. On ALL my local tests it works, but on my webservers it fails 3/5 times. I'm pretty sure Instagram is blacklisting/tracing serverd and refusing them access to the ''API''. Make sure you use good proxys if you want your services to run flawless.

**Comment by despecial** [comment]
?__a=1 parameter removed by Instagram and probably will never come back.
So this has nothing to do with blocking server requests: 429 because they track your requests per hour.

**Comment by bomboem** [comment]
@despecial Oh okay. Everything on my website works, so I guess it's not that big of an issue...

**Comment by despecial** [comment]
you sure that it works like before April 12th? 
After that day ?__a=1 request get no result. Only via API
