### ISSUE TITLE
getMedias Is not working after last update 

### ISSUE THREAD

**Issue by tarangpatel61** [postaddictme/instagram-php-scraper#347]

**Comment by rhcarlosweb** [comment]
#325

**Comment by tarangpatel61** [comment]
Thank you its works fine!!!!!

**Comment by Saiirex** [comment]
@despecial is there a way to do it without authentication?

**Comment by Saiirex** [comment]
@despecial thats sad, i need all the media...

**Comment by despecial** [comment]
Then use the official API

**Comment by Saiirex** [comment]
Which one? Graph api?

**Comment by engnaguib** [comment]
@Saiirex https://developers.facebook.com/docs/instagram-api
but you can't access the account without access token ,and must be business account

**Comment by itzfaraz** [comment]
So its official then.. anonymous scrapping is no longer possible without Instagram's own business account API.

**Comment by bomboem** [comment]
@itzfaraz Well that's a pitty, any chances in loading the userpage and actually retreiving all the <img> objects?

**Comment by itzfaraz** [comment]
As already pointed out by many people, the Instagram has changed its API once again; and the query_hash code has become IP and device specific. It is mandatory to work with all cookies that are returned on the first contact with `www.instagram.com/{username}`. But the query_hash keeps changing. I've been able to dig down to a JavaScript file that is from `https://www.instagram.com/static/bundles/base/ProfilePageContainer.js/{randomcode}.js` which contains the query_hash code every time you create a new session. Event that file has 3 different query_hash code, not sure which one the scrapper should pick up for communication.

But keep in mind.. **if your incognito/private mode web browser can communicate with Instagram without any user login, so can your application. Just need to figure out how to do it.** 

Instagram has made it's code very dynamic. The CSS stylesheets, linked files, script files, hash codes, etc. everything differs from session to session.

**Comment by Saiirex** [comment]
@itzfaraz is there a working solution right now?

**Comment by itzfaraz** [comment]
@pgrimaud Apologies Ive been busy elsewhere.
Yes it works brilliantly. Thanks a lot. Good job.
