### ISSUE TITLE
Replacement for https://www.instagram.com/{username}/?__a=1

### ISSUE THREAD

**Issue by pandoratoolbox** [postaddictme/instagram-php-scraper#349]
Does anybody have a way to get the bio, media URLs and also the users who like the media?

**Comment by mr-molodoy** [comment]
All the necessary information is in the _sharedData variable (javascript) on the page https://www.instagram.com/{username}/ you only need to extract her (use regular expression).

This library (instagram-php-scraper) already knows how to do this (getAccount method)

**Comment by mr-molodoy** [comment]
Most likely this will not work

**Comment by pandoratoolbox** [comment]
@mr-molodoy Is there any other way to get a list of likers? Even if it's not only 1 request? Is 50 the max amount?
