### ISSUE TITLE
getMediasByTag not returning username

### ISSUE THREAD

**Issue by kesienajoel** [postaddictme/instagram-php-scraper#351]
hello, getMediasByTag is not returning the users username , just the id
[owner:protected] => InstagramScraper\Model\Account Object
                (
                    [id:protected] => 11873593
                    [username:protected] => 
                    [fullName:protected] => 
                    [profilePicUrl:protected] => 
                    [profilePicUrlHd:protected] => 
                    [biography:protected] => 
                    [externalUrl:protected] => 
                    [followsCount:protected] => 0
                    [followedByCount:protected] => 0
                    [mediaCount:protected] => 0
                    [isPrivate:protected] => 
                    [isVerified:protected] => 
                    [isLoaded:protected] => 1
                    [isNew:protected] => 
                    [isLoadEmpty:protected] => 
                    [isFake:protected] => 
                    [isAutoConstruct:protected] => 
                    [modified:protected] => 1524202880
                    [data:protected] => Array
                        (
                        )

                )...

**Comment by devpyp** [comment]
I don't think the user name is part of Instagram's actual response either.
