### ISSUE TITLE
Fatal error on getFollowing(), getFollowers(), ...

### ISSUE THREAD

**Issue by StefLedof** [postaddictme/instagram-php-scraper#352]
Hello,
Since 2018-04-18 getFollowing(), getFollowers(), ... return error and fail
PHP Notice:  Array to string conversion in /instagram-php-scraper/src/InstagramScraper/Instagram.php on line 116
PHP Catchable fatal error:  Object of class stdClass could not be converted to string in /instagram-php-scraper/src/InstagramScraper/Instagram.php on line 116

**Comment by konkito** [comment]
I have exactly the same problem, I don't know if you could solve it. But appareantly no one is able to answer anymore.
