### ISSUE TITLE
Problem on getMediaByTags - stdClass::$authenticated

### ISSUE THREAD

**Issue by phoenixh** [postaddictme/instagram-php-scraper#353]
Hello there,
i am using latest version of this Lib, but when i want to scarp by tag i am getting the following error:
`Undefined property: stdClass::$authenticated`

instagram-php-scraper/src/InstagramScraper/Instagram.php on line 1225.

My code:
`            $instagram = \InstagramScraper\Instagram::withCredentials('username', 'password');
$instagram->login();
$medias = $instagram->getMediasByTag('trbvls', 10);`

What might be the problem?

**Comment by phoenixh** [comment]
My fault... i used the login() method, but i dont need that cause i am using withCredentials() before.

**Comment by farmgameowner** [comment]
> My fault... i used the login() method, but i dont need that cause i am using withCredentials() before.

Sry for asking, but if you use withCreditentials(), you don't should use login() at all?

**Comment by sanyisasha** [comment]
> My fault... i used the login() method, but i dont need that cause i am using withCredentials() before.

Worked for me.

**Comment by ffaady** [comment]
im still facing same issue is there quick fix?

**Comment by ffaady** [comment]
it does working fine on my local version but when im using it online its showing me erro
Undefined property: stdClass::$authenticated
