### ISSUE TITLE
squareThumbnailsUrl is empty

### ISSUE THREAD

**Issue by phoenixh** [postaddictme/instagram-php-scraper#355]
Hello there, 
I see that "squareThumbnailsUrl" of a media is empty. Is that a problem with the API or is the current version of the scrapper not working propper?

Thank you

**Comment by rhcarlosweb** [comment]
I have PR #332

**Comment by rupali-soni** [comment]
I'm facing the same problem. In `Model\Media.php` on line 451 there should be case `thumbnail_resources`, it is `display_resources` at the moment. Can you please resolve?

**Comment by rhcarlosweb** [comment]
@phoenixh @rupali-soni it depends of @raiym accept the PR #332 haha

**Comment by phoenixh** [comment]
Thank you @rhcarlosweb for your fix and thank you @raiym to accept the request.
Now the API is running again... YES!
