### ISSUE TITLE
Style throw new exception error help

### ISSUE THREAD

**Issue by maxhuro** [postaddictme/instagram-php-scraper#356]
Hello I'm not very good with php, can someone help me to style the throw new exception error?
For example this "throw new InstagramNotFoundException('Account with given username does not exist.')"
if username is wrong it shows a long fatal error, i want just to alert only the message.PLZ

**Comment by pgrimaud** [comment]
@maxhuro You can avoid fatal error using try catch :

```php
try {
    // your code
} Catch (InstagramNotFoundException $exception) {
    echo $exception->getMessage();
}
```
