### ISSUE TITLE
500 Internal server error

### ISSUE THREAD

**Issue by zubairsultan786** [postaddictme/instagram-php-scraper#357]
Hi,
I am working on instagram stories. it's work but sometimes it will gives error internal server error. I don't know why it's happening. Can you please help me out?
Here is my code:
`
$instagram = \InstagramScraper\Instagram::withCredentials('xxxx', 'xxxxx');
	    
	        $instagram->login();
	 	
	        //$instagram->login();
	        $username = $_POST['username'];
		$account = $instagram->getAccount($username);
	       // $account = $instagram->getMedias($username);
	       //echo '<pre>';
	       //print_r($account);
	      // echo '</pre>';
	       // die;
	        $id[] = $account->getid();
		
	        $stories = $instagram->getStories($id);
	      	if(!empty($stories)){
	      		$storySlides = $stories[0]->getstories();
	        	$count = count($storySlides);
	      	}
	      	else{
	      		$msg = 'No new stories. <a href="https://www.xxxxx.com/download-instagram-stories/">Click here to see other user stories</a>';
	      	}
        `

**Comment by zubairsultan786** [comment]
Now every times it give error internal server error. Anyone help me please

**Comment by pgrimaud** [comment]
@zubairsultan786 What error do you have?

**Comment by zubairsultan786** [comment]
when I execute my code it shows like that. I think the error is in getStories function  
![error_web](https://user-images.githubusercontent.com/34543883/39286992-d0989aae-4929-11e8-8d2c-1af7b197de8d.JPG)
"

**Comment by pgrimaud** [comment]
@zubairsultan786 Show php errors by adding this 2 lines in your code :

```php
ini_set('display_errors', 1);
error_reporting(E_ALL);
```

**Comment by andrewaolwatson** [comment]
Getting this error:

 Fatal error: Uncaught exception 'InstagramScraper\Exception\InstagramException' with message 'Response code is 403. Body: Unknown body format Something went wrong. Please report issue.' in inst/instagram-php-scraper-master/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:587 Stack trace: #0 getimages.php(92): InstagramScraper\Instagram->getAccount('instagram') #1 {main} thrown in inst/instagram-php-scraper-master/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 587

**Comment by zubairsultan786** [comment]
@andrewaolwatson hey!! which files i have to update?
