### ISSUE TITLE
$instagram->getMediaByUrl is not working in php

### ISSUE THREAD

**Issue by zubairsultan786** [postaddictme/instagram-php-scraper#359]
Hi ,

I am working on instagram medias If i used this function like that $instagram->getMediaByUrl('https://www.instagram.com/p/BHaRdodBouH'); it will worked but if i used something like that $instagram->getMediaByUrl('https://www.instagram.com/bbc/'); 
it will not worked. Please help me out what i have to do to work in both conditions. 

Thanks,

**Comment by puffpuffpuff** [comment]
you are trying to get medias by account name?
if it is then your code should be $instagram->getMedias('bbc') instead

**Comment by zubairsultan786** [comment]
and if urls have CODES instead of username then which function will be used??

**Comment by bomboem** [comment]
@zubairsultan786 I think you should use getMediasById() for that. I'm not sure about it though. Go trough the examples, thery're explained pretty well.

**Comment by zubairsultan786** [comment]
I already go through the examples but still have problems

**Comment by PoisonIvysaurBridge** [comment]
could it be because Instagram is shutting down its public API's?

**Comment by Kokil** [comment]
i too get this issue. Larave 8, PHP 8
