### ISSUE TITLE
Fatal error while login 

### ISSUE THREAD

**Issue by zubairsultan786** [postaddictme/instagram-php-scraper#365]
Hi,

 I am trying to login with creditionals but it's give error.

`Fatal error: Uncaught InstagramScraper\Exception\InstagramAuthException: Something went wrong. Please report issue. in /home/xxxx/public_html/vendor/xxx/instagram-php-scraper/src/InstagramScraper/Instagram.php:1220 Stack trace: #0 /home/aem37it2ujqa/public_html/stories-download.php(21): InstagramScraper\Instagram->login() #1 {main} thrown in /home/xxx/xxx/xxx/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 1220`
It's working before week ago. Now it's showing error after updating files week before back.
Can anybody help me out?

**Comment by zubairsultan786** [comment]
Please help me out. It's very urgent

**Comment by tallesairan** [comment]
i have a same issue

**Comment by zubairsultan786** [comment]
Before updating, login is working fine and getStories function was not working

**Comment by zubairsultan786** [comment]
Any solution to this problem?

**Comment by kerd1k** [comment]
Any solution?
Without login all works fine, but with  login credentials gets the same error.

**Comment by developedsoftware** [comment]
Is there any update on this? It still doesn't work.

**Comment by zubairsultan786** [comment]
Why my Instagram account always says suspicious login attempt?
