### ISSUE TITLE
Can't get followers/following list

### ISSUE THREAD

**Issue by konkito** [postaddictme/instagram-php-scraper#369]
Hello,

I'm having this issue when I try to list my followers/following.

<b>Notice</b>:  Array to string conversion in <b>composer\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php</b> on line <b>121</b><br />

Catchable fatal error</b>:  Object of class stdClass could not be converted to string in <b>composer\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php</b> on line <b>121</b><br />

Does anyone is having the same issue please ?

Greetings

**Comment by bilmiyore** [comment]
I'm getting this error too.

**Comment by Mrp12** [comment]
I get this error:

`"Response code is 429. Body:  message => rate limited; status => fail; Something went wrong. Please report issue."`

**Comment by SeanStayn** [comment]
429 means, that you have send too many requests:
https://httpstatuses.com/429 

You should use the delayed property. 
 
public function getFollowers($accountId, $count = 20, $pageSize = 20, **$delayed = true**)

**Comment by fsjdg** [comment]
Hi @SeanStayn, Do you know which is the maximum of followers i can get in one call. If try to get a complete list of follower by 20, i'd reach the limit quikly.
