### ISSUE TITLE
429 error

### ISSUE THREAD

**Issue by kamranfarshchi** [postaddictme/instagram-php-scraper#371]
I'm using the java code and i edited lots of its parts to work properly with new changes from instagram, but pushing lots of requests like getting all followers (as i ask for 24 follower in each request just like instagram does) gives me 429 after 3 or 4 requests, can you help me to solve this problem.
ps: i know this is the php scraper but it seems people are more up to date here :D

**Comment by lk77** [comment]
I have this error too, i have added `sleep(1)` at the beginning of my functions, it's a lot slower but it works,
i don't know if there is a better solution, like a random proxy or something like that.

**Comment by SeanStayn** [comment]
Instagram has changed their rate limits: [Click here](https://stackoverflow.com/questions/49585077/instagram-api-limit-reduced-to-200-from-5000 )
