### ISSUE TITLE
Uncaught phpFastCache\Exceptions\phpFastCacheDriverException: PLEASE CREATE OR CHMOD

### ISSUE THREAD

**Issue by maxhuro** [postaddictme/instagram-php-scraper#375]
Hello, can anyone help me to solve this error. It shows when i run getStories.php, it doesn't have permision to create files. On localhost it works great. This is the full error 

`Fatal error: Uncaught phpFastCache\Exceptions\phpFastCacheDriverException: PLEASE CREATE OR CHMOD /path/to/cache/folder/xxxxxxxx.pw/Files - 0777 OR ANY WRITABLE PERMISSION! in /home4/maxhuro/public_html/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/PathSeekerTrait.php:110 Stack trace: #0 /home4/maxhuro/public_html/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/PathSeekerTrait.php(146): phpFastCache\Drivers\Files\Driver->getPath() #1 /home4/maxhuro/public_html/vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/Files/Driver.php(58): phpFastCache\Drivers\Files\Driver->getFileDir() #2 /home4/maxhuro/public_html/vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/Files/Driver.php(48): phpFastCache\Drivers\Files\Driver->driverCheck() #3 /home4/maxhuro/public_html/vendor/phpfastcache/phpfastcache/src/phpFastCache/CacheManager.php(107): phpFastCache\Drivers\Files\Driver->__construct(Array) #4 /home4/maxhuro/public_html/src/InstagramScraper/Instagram.php(61): phpFastCache\CacheManager::getInstance( in /home4/maxhuro/public_html/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/PathSeekerTrait.php on line 110`

**Comment by onlymytho** [comment]
I'm suffering the same issue. Had you solved it?

**Comment by boypanjaitan16** [comment]
can you please tell me how to fix it and why you closed this issue ?
