### ISSUE TITLE
getMediaByUrl doesnt work for this condition

### ISSUE THREAD

**Issue by ProfessorZer0** [postaddictme/instagram-php-scraper#377]
I am trying to get media by URL 
my URL looks something like this
https://www.instagram.com/p/BjNLTA0FITx/?taken-by=sidecardoughnuts

It shows an error if I use it in getMediaByUrl function. 
however, it works  if I change my URL to
https://www.instagram.com/p/BjNLTA0FITx/

i.e removing the "**?taken-by=sidecardoughnuts**" part

Most of my links are like that only. Any possible Solution?

**Comment by maxhuro** [comment]
Hello @ProfessorZer0   i'm using this code to remove everything after "?"

```
//grab the full url from input
$longurl = $_POST['url'];

if (strpos($longurl,'?') !== false) {
$url = explode("?", $longurl);
$url = $url[0]; 

$media = $instagram->getMediaByUrl($url);
```
