### ISSUE TITLE
Limits \ auth

### ISSUE THREAD

**Issue by RainGrid** [postaddictme/instagram-php-scraper#380]
Hello, guys! How do you work with these limits? I use auth, but the query limits are too small. Do you use many accounts?

**Comment by lukeenglish** [comment]
Rotate IPs

**Comment by RainGrid** [comment]
@lukeenglish I dont sure that it'll help if i use one account

**Comment by rhcarlosweb** [comment]
#330 Rotate IPs

**Comment by developedsoftware** [comment]
You can use 1 account with multiple IPs

**Comment by RainGrid** [comment]
@developedsoftware ok, I'll try
