### ISSUE TITLE
Has this code been comprimised?

### ISSUE THREAD

**Issue by developedsoftware** [postaddictme/instagram-php-scraper#384]
I've had instagram for over 5 years.

I started using this plugin a few months ago and my account has just been hacked and all my details have changed. 

I was using a password I wasnt using on any other site - so I have no idea how my password was obtained. 

For clarity I should add, the attacker did not reset my account password. He successfully logged in using my username and password and then changed the email address and contact number so I could not reset it back. 

Not one to point the finger - but it seems a bit odd thats happened just a few months after using this plugin...

**Comment by prince-code** [comment]
You can read the source code and inspect if your username and password are passed to a 3rd party or not. It is open-source and simple php.

**Comment by RainGrid** [comment]
Same problem today. The attacker changed my email and password, but i got access back.
