### ISSUE TITLE
Proxy error connect aborted

### ISSUE THREAD

**Issue by maxhuro** [postaddictme/instagram-php-scraper#385]
When i try to use proxy it shows me this error

`Fatal error: Uncaught Unirest\Exception: Proxy CONNECT aborted in /home1/xxxxxx/public_html/vendor/mashape/unirest-php/src/Unirest/Request.php:476 Stack trace: #0 /home1/xxxxxx/public_html/vendor/mashape/unirest-php/src/Unirest/Request.php(236): Unirest\Request::send('GET', 'https://www.ins...', NULL, Array, NULL, NULL) #1 /home1/xxxxxx/public_html/src/InstagramScraper/Instagram.php(1316): Unirest\Request::get('https://www.ins...') #2 /home1/xxxxxx/public_html/examples/instagram-story.php(33): InstagramScraper\Instagram->login() #3 {main} thrown in /home1/xxxxxxx/public_html/vendor/mashape/unirest-php/src/Unirest/Request.php on line 476`

This is my code 
```
require __DIR__ . '/../vendor/autoload.php';
use InstagramScraper\Instagram;
use InstagramScraper\Model\Media;
use phpFastCache\CacheManager;
use PHPUnit\Framework\TestCase;
$instagram = new Instagram();
Instagram::setProxy([
    'address' => '66.119.180.103',
    'port'    => '80',
    'tunnel'  => true,
    'timeout' => 30,
]);
$instagram = \InstagramScraper\Instagram::withCredentials($credUser, $credPsd, '/home1/xxxxxx/public_html/examples/path/to/cache/folder');
$instagram->login();
$stories = $instagram->getStories();
```

**Comment by zubairsultan786** [comment]
I am facing same issue... Please help me out

**Comment by maxhuro** [comment]
Does anyone know what to do? A'm i using wrong or it's a problem for all?

**Comment by christoph-werker** [comment]
What Proxy seller do You use?

**Comment by maxhuro** [comment]
I used a free proxy from free-proxy-list.net just for testing

**Comment by christoph-werker** [comment]
I ve tested a few free Proxy sides and none of them worked for me. Now i am searching a good seller for my Laravel application because i want to scale requests...

**Comment by maxhuro** [comment]
Can you give me an examle of how you use the proxy code?

**Comment by christoph-werker** [comment]
Same as you, just fill the Proxy Method.
