### ISSUE TITLE
How can I get stories highlights?

### ISSUE THREAD

**Issue by Al-Muhandis** [postaddictme/instagram-php-scraper#388]
I mean, not the usual stories (24 hours lifetime), but the special ones, like the "eternal stories".

**Comment by AidasK** [comment]
Have you found how to get highlights?

**Comment by Al-Muhandis** [comment]
> 
> 
> Have you found how to get highlights?

Yes, but I write the solution in another programming language

**Comment by AidasK** [comment]
It still can be helpful. Can you share it?

**Comment by Al-Muhandis** [comment]
> It still can be helpful. Can you share it?

I don't think it can help you, but here's a piece of code that parses the stories [https://gist.github.com/Al-Muhandis/b2bc7550413437442cd1d4911f818cea](https://gist.github.com/Al-Muhandis/b2bc7550413437442cd1d4911f818cea)
