### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by ProfessorZer0** [postaddictme/instagram-php-scraper#392]
How about making a function that allows to download the image,video or sidecar content of a private account when the user provides the source code of the page?

**Comment by Semne** [comment]
$instagram = new \InstagramScraper\Instagram();
$nonPrivateAccountMedias = $instagram->getMedias($user,$account->getMediaCount());
foreach($nonPrivateAccountMedias as $m){
if($m->getType()=='video'){
		$li = $instagram->getMediaByUrl($m->getLink());
		$video_link = $li['videoStandardResolutionUrl'];
		echo($video_link);				
	}
}
