### ISSUE TITLE
Add a comment on a media 

### ISSUE THREAD

**Issue by hetalvisaveliya** [postaddictme/instagram-php-scraper#395]
Hi raiym,

In API have function for add a comment to Instagram media? 
Like: addMediaComment($id, $text)?

**Comment by peelss** [comment]
Try this

<?php
use InstagramScraper\Exception\InstagramException;
require __DIR__ . '/../vendor/autoload.php';
$instagram = \InstagramScraper\Instagram::withCredentials('username', 'password', '/path/to/cache/folder');
$instagram->login();
try {
    // add comment to post
    $mediaId = '1663256735663694497';
    $comment = $instagram->addComment($mediaId, 'ADD YOUR COMMENT');
    $instagram->deleteComment($mediaId, $comment);
} catch (InstagramException $ex) {
    echo $ex->getMessage();
}

**Comment by peelss** [comment]
Try This
```
<?php
use InstagramScraper\Exception\InstagramException;
require __DIR__ . '/../vendor/autoload.php';
$instagram = \InstagramScraper\Instagram::withCredentials('username', 'password', '/path/to/cache/folder');
$instagram->login();
try {
    // add comment to post
    $mediaId = '1663256735663694497';
    $comment = $instagram->addComment($mediaId, 'ADD YOUR COMMENT');
   
    $instagram->deleteComment($mediaId, $comment);
} catch (InstagramException $ex) {
    echo $ex->getMessage();
}
```
