### ISSUE TITLE
How to `getMediasByTag()` if tag contains dot

### ISSUE THREAD

**Issue by mariusmateoc** [postaddictme/instagram-php-scraper#396]
There is a way to combines images that appear on 'Posts' tab with the images that appear on the 'Tagged' tab? I tried to get the medias that contains certain tag using the following code but I get an error.

```php
$instagram = new \InstagramScraper\Instagram();

// This works as it should
$medias = $instagram->getMediasByTag('name', 20);

// The problem is that the account is 'name.es' and when I use the dot I get an error.
$medias = $instagram->getMediasByTag('name.es', 20);
```

Also if there is a way to get the mentions.

Thanks in advance,
Marius

**Comment by hossamhossny** [comment]
Instagram changed something a couple of days ago. The tags endpoint require certain cookies set.
