### ISSUE TITLE
We Noticed a New Login, USERNAME

### ISSUE THREAD

**Issue by developedsoftware** [postaddictme/instagram-php-scraper#398]
Every time this is run an email like the attached is received. 

I am guessing instagram now set some cookie and check for this ? Not really sure but there is no way of turning this off!

![email](https://user-images.githubusercontent.com/19648131/44920840-dbab2380-ad38-11e8-8ec6-d56029fd579d.jpg)

**Comment by AidasK** [comment]
Have you found how to solve this?

**Comment by lalajon** [comment]
+1!  This is really annoying

**Comment by developedsoftware** [comment]
No I have not found out how to solve this yet.

**Comment by tallesairan** [comment]
@developedsoftware look pr #420  for ipv6 settings
