### ISSUE TITLE
Composer install

### ISSUE THREAD

**Issue by JOniiX** [postaddictme/instagram-php-scraper#40]
I have a problem when i use the command "composer require raiym/instagram-php-scraper" :

C:\wamp64\www\insta>composer require raiym/instagram-php-scraper
Using version ^0.4.1 for raiym/instagram-php-scraper
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package raiym/instagram-php-scraper No version set (parsed as 1.0.0) is satisfiable by raiym/instagram-php-scraper[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

Can you help me ?

Composer version: 1.2.1

**Comment by raiym** [comment]
@JOniiX hello.
Just checked in clean directory, works for me. It seems that you have dependency intersection or version collision (http://stackoverflow.com/questions/20996767/requirements-could-not-be-resolved-to-an-installable-set-of-packages)
Let me know if the problem persists. 
In future maybe we will give up unirest dependency.

**Comment by JOniiX** [comment]
I have changed the version of composer to 1.0.0 and it's doesn't work and i have update the lastest version and i have already this error
(sorry for my english)

**Comment by duy-tran** [comment]
I also have this problem

**Comment by raiym** [comment]
Sorry for long reply. 
If at the moment it is still important please re-open the issue

**Comment by madeluxe** [comment]
hey, i'm sorry. but what was the solution exactly? i tried to install same way like in first post here. and same result.

`composer require raiym/instagram-php-scraper
Using version ^0.4.1 for raiym/instagram-php-scraper
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- The requested package raiym/instagram-php-scraper No version set (parsed as 1.0.0) is satisfiable by raiym/instagram-php-scraper[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.`

best

**Comment by nickchong** [comment]
Hey all,

I ran into the same issue and then updated the composer.json file changing the "name" key's value from raiym/instagram-php-scraper to something else (whatever you want) and it worked.  

Thanks for the library raiym
