### ISSUE TITLE
getMediCommentsByCode - limit?

### ISSUE THREAD

**Issue by nikakhaburzania** [postaddictme/instagram-php-scraper#400]
I tried to get 12,000 comments from my instagram post and it failed, but when I had 10 comments it worked. now even 10 comments doesnt work it seems like I got IP banned?
what should I do, how can i fetch all 12k comments?

**Comment by nikakhaburzania** [comment]
`$instagram = \InstagramScraper\Instagram::withCredentials('id', 'pass');


$instagram->login();


// Get media comments by shortcode
$comments = $instagram->getMediaCommentsByCode('Bmn2wLpFqW8', 8000);


$commentsArr = array();

for ($x = 0; $x < sizeof($comments); $x++) {
    $commentsArr[] = array(
    	"username"	=>	$comments[$x]->getOwner()->getUsername(),
    	"comment"	=>	$comments[$x]->getText()
    );
}
`


Here is the code, I need all 12000 comments in this array with their usernames, could someone write a sample of code how would you solve this problem?

**Comment by RainGrid** [comment]
@nikakhaburzania  check [this PR](https://github.com/postaddictme/instagram-php-scraper/pull/393)
