### ISSUE TITLE
CHMOD  777 - Which directory?

### ISSUE THREAD

**Issue by Tvvinman** [postaddictme/instagram-php-scraper#402]
Please, explain, I don't know, which directory I should edit to:

Fatal error: Uncaught phpFastCache\Exceptions\phpFastCacheDriverException: PLEASE CREATE OR CHMOD /cache/testsite.ru/Files - 0777 OR ANY WRITABLE PERMISSION! 

Very strange path! :((

**Comment by Tvvinman** [comment]
I've found out that there is phpfastcache module error. There must be full path with variable in examples like that:

$instagram = \InstagramScraper\Instagram::withCredentials('login, 'password', dirname(__FILE__).'/cache');

**Comment by devboxr** [comment]
Can confirm that this was indeed the issue. Had the same and solved the same way.

**Comment by onlymytho** [comment]
I'm still suffering the issue. 
`$instagram = \InstagramScraper\Instagram::withCredentials('login, 'password', dirname(FILE).'/cache');` doesn't work for me. Any progress on it? @raiym

**Comment by lalajon** [comment]
Another way is to add the user www-data to the group in order not to give full access to the folder.
