### ISSUE TITLE
Can't get the video url from the response.

### ISSUE THREAD

**Issue by beckjiang218** [postaddictme/instagram-php-scraper#407]
Hi, I have a question about the method `\InstagramScraper\Instagram::getPaginateMedias()`. 

When I try to get Medias:
```
$instagram = new \InstagramScraper\Instagram();
$data = $instagram->getPaginateMedias('koleksiyoutube');

var_dump($data[0]->getType(), $data[0]->getVideoStandardResolutionUrl());
```
output: 
![image](https://user-images.githubusercontent.com/24934486/46663480-c1464e80-cbf0-11e8-8d7c-094723f9e737.png)

Indeed, it is a video, but the response does not contain the video infomation.

Is this a limitation of the API?

**Comment by beshoo** [comment]
```
    if ($instagram->getType() == 'video')
    {
        $link = $instagram->getLink();
        $json_media_by_url = $instagram_web->getMediaByUrl($link);
        $video_url = $json_media_by_url['videoStandardResolutionUrl'];
    }
```
