### ISSUE TITLE
$cookies['mid'] is not exist?

### ISSUE THREAD

**Issue by Semne** [postaddictme/instagram-php-scraper#408]
Hello! 
$cookies = static::parseCookies($response->headers['Set-Cookie']); return only csrftoken

Example:
["headers"]=>
--
  | array(15) {
  | [0]=>
  | string(15) "HTTP/1.1 200 OK"
  | ["Content-Type"]=>
  | string(24) "text/html; charset=utf-8"
  | ["Cache-Control"]=>
  | string(44) "private, no-cache, no-store, must-revalidate"
  | ["Pragma"]=>
  | string(8) "no-cache"
  | ["Expires"]=>
  | string(29) "Sat, 01 Jan 2000 00:00:00 GMT"
  | ["Vary"]=>
  | string(40) "Accept-Language, Cookie, Accept-Encoding"
  | ["Content-Language"]=>
  | string(2) "en"
  | ["Content-Encoding"]=>
  | string(4) "gzip"
  | ["Date"]=>
  | string(29) "Thu, 11 Oct 2018 15:56:37 GMT"
  | ["Strict-Transport-Security"]=>
  | string(10) "max-age=60"
  | ["X-Frame-Options"]=>
  | string(10) "SAMEORIGIN"
  | ["content-security-policy-report-only"]=>
  | string(1241) "report-uri /security/csp_report/; default-src 'self' https://www.instagram.com; img-src https: data: blob:; font-src https: data:; media-src 'self' https://www.instagram.com https://*.cdninstagram.com https://*.fbcdn.net; manifest-src 'self' https://www.instagram.com; script-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://*.cdninstagram.com wss://www.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' https://*.www.instagram.com https://www.instagram.com 'unsafe-inline'; connect-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://graph.instagram.com https://*.graph.instagram.com https://*.cdninstagram.com https://api.instagram.com wss://www.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net chrome-extension://boadgeojelhgndaghljhdicfkmllpafd; worker-src 'self' https://www.instagram.com; frame-src 'self' https://instagram.com https://www.instagram.com https://staticxx.facebook.com https://www.facebook.com https://web.facebook.com https://connect.facebook.net https://m.facebook.com; object-src 'none'; upgrade-insecure-requests"
  | ["Set-Cookie"]=>
  | string(138) "csrftoken=2lg6SMLQT3CcJQ58RwIMpobSW3D25WDX; Domain=.instagram.com; expires=Thu, 10-Oct-2019 15:56:37 GMT; Max-Age=31449600; Path=/; Secure"
  | ["Connection"]=>
  | string(10) "keep-alive"
  | ["Content-Length"]=>
  | string(4) "7385"
  | }

It's normal?

**Comment by Sarimarcus** [comment]
+1

**Comment by sharokh1** [comment]
+1
