### ISSUE TITLE
New login to Instagram from Unknown browser

### ISSUE THREAD

**Issue by lalajon** [postaddictme/instagram-php-scraper#412]
Every time I made a login, I received this message
<img width="470" alt="screen shot 2018-10-28 at 11 38 25 pm" src="https://user-images.githubusercontent.com/12515811/47621568-e13fa280-db0a-11e8-85ea-47035d322ed0.png">
Has anyone already encountered this problem? Is there a way to solve it?

**Comment by Shamim1977** [comment]
seems it has become impossible to login now, facing the exact issue as @alajon is facing.
Anybody has any solution? Specially, Raiym, you have to say anything, sir?
