### ISSUE TITLE
get comments without Login

### ISSUE THREAD

**Issue by ismailoezcan** [postaddictme/instagram-php-scraper#414]
Hi,

is there or will there be the possibility to get Comments of Media without login? Wouldn't this be a "safe" version to prevent limits?

**Comment by tallesairan** [comment]
I'm also trying the same, if there is any news inform me

**Comment by beshoo** [comment]
any update?

**Comment by ebulku** [comment]
I got the Comments without login, so this Issue is irrelevant.
