### ISSUE TITLE
Suspicious login attempt in Instagram

### ISSUE THREAD

**Issue by sfatfarma** [postaddictme/instagram-php-scraper#415]
This is still working from my localhost machine, but when I try using it on a server (or on any server I tried so far), a 'Suspicious login attempt' window pops for me in my Instagram account each time when I try to run this script (regardless that I click 'It was me' when prompted in Instagram).

This is happening since 1st November 2018, when Instagram seems to have made some major changes to it's security settings.

I tried also proxies, but haven't found one that works yet.

**Comment by tallesairan** [comment]
Use IPv6

Em Qui, 8 de nov de 2018 04:09, SfatFarma <notifications@github.com
escreveu:

**Comment by developedsoftware** [comment]
> Use IPv6

Can you explain why this would help?

**Comment by tallesairan** [comment]
pr #420

**Comment by sfatfarma** [comment]
And if I have no IPv6 usage possibility? :)
