### ISSUE TITLE
phpFastCache and Unirest?

### ISSUE THREAD

**Issue by Shamim1977** [postaddictme/instagram-php-scraper#419]
These lines are used in instagram.php file-

use phpFastCache\Cache\ExtendedCacheItemPoolInterface;
use phpFastCache\CacheManager;
use Unirest\Request;

These are not added in the repo by default for sure. Also, when I checked @ https://github.com/PHPSocialNetwork/phpfastcache, it seems there is no folder called "Cache" under phpFastCache. ...I really doubt if anybody was successful using "instagram-php-scraper" at all. ...This is a total frustration and waste of time.

**Comment by raiym** [comment]
@Shamim1977 do you use composer?

**Comment by Shamim1977** [comment]
Yes, I am on a mac. I did use composer. But no trace of phpFastCache or Unirest.

**Comment by Shamim1977** [comment]
Ok, I got everything installed locally via composer. It seems to have a load of files and directories, but it's ok. I just wrote a simple script like this-

        require 'autoload.php';

	use InstagramScraper\Instagram;
	use InstagramScraper\Model\Media;
	use InstagramScraper\Model\Tag;
	use InstagramScraper\Model\AbstractModel;
	use InstagramScraper\Model\Account;
	use InstagramScraper\Model\CarouselMedia;
	use InstagramScraper\Model\Comment;
	use InstagramScraper\Model\Location;
	use InstagramScraper\Exception\InstagramException;
	use InstagramScraper\Exception\InstagramAuthException;
	use InstagramScraper\Exception\InstagramNotFoundException;	
	use InstagramScraper\Endpoints;
	use InstagramScraper\InstagramQueryId;
	use InstagramScraper\ArrayLikeTrait;
	use InstagramScraper\InitializerTrait;
	use phpFastCache\CacheManager;
	use Unirest\Request;

		$instagram = Instagram::withCredentials(UUUUUU', 'PPPPPP');
		$instagram->login();
		$account = $instagram->getAccountById(3);
		echo "User Name: " + $account->getUsername();


Now, I am getting this weird message:

Fatal error: Uncaught InstagramScraper\Exception\InstagramAuthException: Something went wrong. Please report issue. in /home/mysite/public_html/inscraper/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:1238 Stack trace: #0 /home/mysite/public_html/inscraper/media.php(31): InstagramScraper\Instagram->login() #1 {main} thrown in /home/mysite/public_html/inscraper/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 1238

What am I doing wrong, btw? I became a nightmare, though.

**Comment by lalajon** [comment]
https://github.com/postaddictme/instagram-php-scraper/issues/409
