### ISSUE TITLE
Instagram::getPaginateMedias('durov')

### ISSUE THREAD

**Issue by borysov** [postaddictme/instagram-php-scraper#42]
Fatal error: Uncaught exception 'InstagramScraper\Exception\InstagramException' with message 'Response code is 301. Body: Something went wrong. Please report issue.' in /srv/www/4develop.com.ua/htdocs/wp-content/plugins/instapin/instagraber/src/InstagramScraper/Instagram.php:106 Stack trace: #0 /srv/www/4develop.com.ua/htdocs/wp-content/plugins/instapin/index.php(465): InstagramScraper\Instagram::getPaginateMedias('durov') #1 /srv/www/4develop.com.ua/htdocs/wp-content/plugins/instapin/index.php(586): INSTAPIN->InstagramGetUserImages('durov') #2 [internal function]: INSTAPIN->instapin_ajax('') #3 /srv/www/4develop.com.ua/htdocs/wp-includes/plugin.php(524): call_user_func_array(Array, Array) #4 /srv/www/4develop.com.ua/htdocs/wp-admin/admin-ajax.php(91): do_action('wp_ajax_instapi...') #5 {main} thrown in /srv/www/4develop.com.ua/htdocs/wp-content/plugins/instapin/instagraber/src/InstagramScraper/Instagram.php on line 106

**Comment by raiym** [comment]
If problem persists please re-open issue with steps that reproduce the issue.
Thank you

**Comment by axxler** [comment]
Hi! 

How did you repair this? On local is ok, but on server with same php 5.4.45 don't works with 301 redirect when media loading
