### ISSUE TITLE
The file you uploaded, eval-stdin.php, contains a virus so the upload was canceled

### ISSUE THREAD

**Issue by prafullwizorbit** [postaddictme/instagram-php-scraper#421]
Hello,
         while uploading this library on serve one of file is showing error like:
The file you uploaded, eval-stdin.php, contains a virus so the upload was canceled:      HG.PHP.Malware.28531.UNOFFICIAL FOUND
Here is attach
![cpanel file manager v3 file upload](https://user-images.githubusercontent.com/16131039/48554594-d48dbd80-e904-11e8-83aa-ea6bf09e0edb.png)

---------------------------------------------------------------------------------------------------------------------------
The file eval-stdin.php is located at vendor/phpunit/phpunit/src/Util/PHP/
I am attaching the result of virustotal.com after scan, it is ok.
![virustotal](https://user-images.githubusercontent.com/16131039/48554348-27b34080-e904-11e8-8a7c-2b1a37c7be7d.png)

Pls help to upload this file on server.
Thanks

**Comment by adgray** [comment]
The file you've identified is not part of this library.
