### ISSUE TITLE
Get Account By ID not working

### ISSUE THREAD

**Issue by manchdev** [postaddictme/instagram-php-scraper#433]
Getting this error while calling this function getAccountById()

PHP Fatal error:  Uncaught InstagramScraper\Exception\InstagramException: Respons
e does not JSON

**Comment by yazhog** [comment]
`const ACCOUNT_JSON_PRIVATE_INFO_BY_ID = 'https://i.instagram.com/api/v1/users/{userId}/info/';`

Does not work any more.

I doubt there is any other way

**Comment by sharokh1** [comment]
Same thing here.. Is there any other way to fetch account information by using an Id ?

**Comment by marty90** [comment]
+1

**Comment by lemon57** [comment]
+1

**Comment by antonPaluhin** [comment]
+1

**Comment by joeygallegos** [comment]
+1

**Comment by soltancode** [comment]
+1

**Comment by soltancode** [comment]
> Getting this error while calling this function getAccountById()
> 
> PHP Fatal error: Uncaught InstagramScraper\Exception\InstagramException: Respons
> e does not JSON

+1

**Comment by waqar-husain** [comment]
can any one post working example ? or any link
