### ISSUE TITLE
getMediasByUserId pagination is not work

### ISSUE THREAD

**Issue by Aliaxander** [postaddictme/instagram-php-scraper#435]
getMediasByUserId
   $result = $content->getAccount($name);
   $media = $content->getMediasByUserId($result->getId(), 12, $page);
if $page==null - all right
if $page = last media:

Exception instagram.php
$str .= ' ' . $key . ' => ' . $value . ';';
(error array to string conversion)

Debug:
$value=
stdClass Object ( [message] => execution error [locations] => Array ( ) )

**Comment by Aliaxander** [comment]
It is not obvious that it is necessary to refer separately to paginaia, that you should get the id of the next page (there is no point in the method without pagination).
Made a few corrections.

https://github.com/postaddictme/instagram-php-scraper/pull/437

**Comment by obmenltd** [comment]
> It is not obvious that it is necessary to refer separately to paginaia, that you should get the id of the next page (there is no point in the method without pagination).
> Made a few corrections.
> 
> #437

заебал ответь мне
