### ISSUE TITLE
how it work?

### ISSUE THREAD

**Issue by gurenovich** [postaddictme/instagram-php-scraper#436]
i install it with composer success. But it don't work
I create index.php and I see `Uncaught Error: Class 'Instagram' not found` why?
Can you write instruction how it work? How I can do "hello world" for example? 
And I try your examples, but not result.

**Comment by gurenovich** [comment]
help please! How I can start use your project?

**Comment by snewer** [comment]
@gurenovich include autloloader to you script:

<?php

require '/vendor/autloload.php';

/* you cide */

**Comment by pofulu** [comment]
This works for me.

`
<?php
require_once 'vendor/autoload.php';

$instagram = new InstagramScraper\Instagram();
$nonPrivateAccountMedias = $instagram->getMedias('kevin');
echo $nonPrivateAccountMedias[0]->getLink();
`

**Comment by pofulu** [comment]
This works for me.

```php
<?php
require_once 'vendor/autoload.php';

$instagram = new InstagramScraper\Instagram();
$nonPrivateAccountMedias = $instagram->getMedias('kevin');
echo $nonPrivateAccountMedias[0]->getLink();

**Comment by gurenovich** [comment]
Thank you so much! It's work 👍 
Why I shall use cache? I think if I send so many requests, right? Maybe get list 1000 followers or more.

**Comment by StringKe** [comment]
```php
$instagram->getPaginateMedias($userName)[0]->toArray(); // []? why?
```
