### ISSUE TITLE
Video media not returning video URL in response

### ISSUE THREAD

**Issue by sfatfarma** [postaddictme/instagram-php-scraper#440]
Hello,

I tried importing video posts, but I get empty responses in video media URL fields:
    [videoLowResolutionUrl:protected] => 
    [videoStandardResolutionUrl:protected] => 
    [videoLowBandwidthUrl:protected] =>

I tried importing this: https://www.instagram.com/p/BnK6nu-B7h8/

Please let me know how to fix this. Thank you.

**Comment by Nooxm** [comment]
Tell me how to get a link to the video?

**Comment by sfatfarma** [comment]
I cannot get it now.
