### ISSUE TITLE
Notice: Undefined index: Set-Cookie when access over HTTPS

### ISSUE THREAD

**Issue by mnajafzadeh** [postaddictme/instagram-php-scraper#442]
Hi,

I get the following notice errors when accessing the getMediasByTag() method over HTTPS.

Notice: Undefined index: Set-Cookie in /home/.../library/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 841

Notice: Undefined index: csrftoken in /home/.../library/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 842

Release: v0.8.26

Best Regards.

**Comment by sivasubramanian1995** [comment]
I'm facing the same issue.
