### ISSUE TITLE
Method to extract media a user is tagged in?

### ISSUE THREAD

**Issue by kerranm** [postaddictme/instagram-php-scraper#448]
Hey ya'all, i've had a good look but I dont think I can find one. Is there a way to extract all media tagged to user (not posted by the user like the method getAccountMediaByUser)?

**Comment by jah-mann** [comment]
This is also something that interests me. When you change your account settings to go from having to add tagged photos manually to your profile to adding them automatically, it does not retroactively add the previous tagged photos to your profile (only applies for tagged photos going forward). So it would be nice to have a tool which can identify all of those if they are indexed somehow, or at least search over all your followers/following's photos to see which ones you are tagged in.

**Comment by raiym** [comment]
https://github.com/postaddictme/instagram-php-scraper/pull/471 need to test

**Comment by jah-mann** [comment]
Hello - After looking over #471 it appears that this would not solve the problem that this post requests.

#471: input is a media file, output is an array of tagged users
#448: input is a user, output is an array of media files
