### ISSUE TITLE
Instagram::getAccountById() returning 405

### ISSUE THREAD

**Issue by zachlloyd** [postaddictme/instagram-php-scraper#45]
Hi - this method is now returning 405 errors for me, starting last night.  I was using it fine beforehand.

Instagram::getAccount() works fine.

Any ideas?

Thanks

**Comment by raiym** [comment]
@zachlloyd hello! 
Same problem, don't know how to fix. 
If you find out please report. 
I have changed getAccountById to getAccountByUsername in my project

**Comment by fabianoroberto** [comment]
Hi @raiym i found the problem: The Request Method for query call now is only POST.
I'm trying to fix it, but if anyone can solve before is welcome

**Comment by raiym** [comment]
@fabianoroberto thank you for identifying problem!

**Comment by raiym** [comment]
@fabianoroberto just checked 
Doesn't work for me. Changed get to post in getAccountById(). returning 403 error 

![screenshot from 2016-11-24 11-25-01](https://cloud.githubusercontent.com/assets/5698585/20591254/17df0960-b241-11e6-8d82-fa2a9c1640c5.png)

**Comment by maxPalmira** [comment]
Looks like it's not a big disaster. Here is what I have found so far: 
1) As fabianoroberto mentioned above the /query/ requests are now working only through POST method
2) Since above we are only able to send those requests from instagram domain (since CORS)
3) We have to add the csrftoken http header in the request so it match the one which is stored in the cookies (unique for the session) 

Working example (sent from Instagram.com, using jquery):

`
$.ajax({
  type: "POST",
  url: "https://www.instagram.com/query/",
 headers: {
        "x-csrftoken":'PWwmPEkOF8QjKbNwXXhKipaK7RAQNOLQ'
    },
 data:'q=ig_user(447508939){username,profile_pic_url}',
  success: function(response) { console.log(response) }
});
`

**Comment by fabianoroberto** [comment]
Well @maxPalmira but:

- how we get a valid x-csrftoken?
- how we can change request to use CORS?

I tried to use this snippet:

`
$endpoint  = Endpoints::getAccountJsonInfoLinkByAccountId($id);
$parsedUrl = parse_url($endpoint);
$url = $parsedUrl['scheme'] . '://' . $parsedUrl['host'];

$headers = [
    'Access-Control-Allow-Origin' => '*',
    'x-requested-with' => 'XMLHttpRequest',
    'x-instagram-ajax' => 1,
    'x-csrftoken'      => '52LEHAztxZKjLCHolWTyyIiMvsDC5rev',
];

parse_str($parsedUrl['query'], $query);

$response = Request::post($url, $headers, $query);
`

**Comment by maxPalmira** [comment]
Actually, I have no idea how to bypass the CORS restrictions from php.
I myself am using phantomjs to open an instagram.com page in the headless browser and then send all needed requests from that page using ajax calls. 
So both those questions are not the issues for me as you can see from my example above.

**Comment by vadimonster** [comment]
it's no way to bypass CORS by yourself. Instagram reject all incoming query from non authorised urls

**Comment by zachlloyd** [comment]
I worked around this in my case by using the fact that I had a posting from the user available.  So I added a query to Instagram::getPostInfo which returned the username that I could then feed into Instagram::getAccount.  Hope this helps.

**Comment by jasoncartercs** [comment]
Is there anyway to get around this issue? 

I am using getMediasByTag and it is only returning the ownerId and not the owner.

**Comment by fabianoroberto** [comment]
I solved using getMediasByTag and then calling getMediaById using ownerId

**Comment by raiym** [comment]
Hello guys I released fix for this error. Please update your project and check for errors

**Comment by jasoncartercs** [comment]
The fix did not work for me.  The error message I get is: string(45) "{"status": "fail", "message": "syntax error"}".

Additionally, I had to make the getContentsFromUrl method and the generateRandomString method static to get the code to run.

When I do,   var_dump(self::getContentsFromUrl($parameters)) in the getAccountById method, I get the error (string(45) "{"status": "fail", "message": "syntax error"}").
