### ISSUE TITLE
Response code is 429. Body in new version

### ISSUE THREAD

**Issue by rrhanim** [postaddictme/instagram-php-scraper#453]
have this error shown every time when i tried to call getMediabyTag?
Response code is 429. Body: message => Please wait a few minutes before you try again.; status => fail; Something went wrong. Please report issue.

**Comment by zaivst** [comment]
429 is "too many requests". And sometimes it appers from the first request ))) I solved it with using random proxy from the list.

**Comment by SterioZe** [comment]
Which list & how please ? :)

**Comment by zaivst** [comment]
Use Instagram::setProxy() and proxy list try to fint yourself )))
