### ISSUE TITLE
Follower and Following API Changes

### ISSUE THREAD

**Issue by tkrause** [postaddictme/instagram-php-scraper#456]
From the looks of it, instagram changed the endpoint that data is pulled from for following and followers endpoints. 

It seems to use the variable JSON scheme that they use now instead of the old query_id style. Here's a relevant hash: 

```
https://www.instagram.com/graphql/query/?query_hash=56066f031e6239f35a904ac20c9f37d9&variables=%7B%22id%22%3A%227133437244%22%2C%22include_reel%22%3Atrue%2C%22fetch_mutual%22%3Atrue%2C%22first%22%3A24%7D
```

which decodes to 

```
https://www.instagram.com/graphql/query/?query_hash=56066f031e6239f35a904ac20c9f37d9&variables={"id":"7133437244","include_reel":true,"fetch_mutual":true,"first":24}
```

**Comment by tkrause** [comment]
Here's the query as well for the next page. Looks like pagination is the same. 

```
https://www.instagram.com/graphql/query/?query_hash=56066f031e6239f35a904ac20c9f37d9&variables={"id":"7133437244","include_reel":true,"fetch_mutual":false,"first":12,"after":"QVFCdFg5THBnVWUwZVFHdVJfc0JqMGtWb1F2S0djcktfWGRIX3hfTVRkRTQ5WkFRTXNNdmFWcC10NWU2WjFCY0pIQWUxaFZTU3J1MXZLSl9mTnBjVmlPYg=="}
```

**Comment by SterioZe** [comment]
Can you give us the exact modification please ?

**Comment by tkrause** [comment]
The endpoint is completely different and seems to require security headers now like the getMedias route.

The change is from query_id to query_hash which also requires a variables get parameter now with json encoded data

**Comment by Parham-sagharchi** [comment]
how we can get url ?
i mean which application should be use to monitor this url ?
