### ISSUE TITLE
 Use array_key_exists() instead of isset() when checking the presence of the $headers array key

### ISSUE THREAD

**Issue by 41st** [postaddictme/instagram-php-scraper#459]
I think you need to use the array_key_exist() function. it will be safer. Now I ran into undefined index set-cookie instagram. The Set-Cookie key is in the array, but the isset($headers ['Set-Cookie']) condition returns false and then tries to find the $headers['set-cookie'] key (with lower case). If you check the function array_key_exist() instead of isset(), then there will be no problem.

https://github.com/postaddictme/instagram-php-scraper/blob/d5aa635f961449e9f5eb888576777679bdecabb5/src/InstagramScraper/Instagram.php#L690

**Comment by abdelazizmirasoft** [comment]
@LSandrov a bit late but might help someone else, you can normalize the case of the array keys before checking for their existence, ensuring that both Set-Cookie and set-cookie are treated the same:
```
$headers = array_change_key_case($headers, CASE_LOWER); // Normalize to lowercase

$rawCookies = array_key_exists('set-cookie', $headers) ? $headers['set-cookie'] : [];
```
This way, you avoid issues with `isset()` and works regardless of the capitalization of `Set-Cookie` in the headers.
