### ISSUE TITLE
Instagram::getMediaCommentsByCode() returning 405

### ISSUE THREAD

**Issue by alejoxps** [postaddictme/instagram-php-scraper#46]
Hello - this method is now returning 405 errors with the example provied.
Any idea?
Thanks!

**Comment by joseflorido** [comment]
Hi, I am seeing the same problem. getMediaCommentsByCode returns 405 
error is on src/InstagramScraper/Instagram.php on line 347

Any idea how to solve it?
Thanks!

**Comment by vadimonster** [comment]
405 means method not allowed(GET)
Use POST

**Comment by joseflorido** [comment]
Thanks, but isn't that something that should be changed in the API itself?

**Comment by joseflorido** [comment]
I did try to change request method to post on [Instagram.php:339](https://github.com/postaddictme/instagram-php-scraper/blob/master/src/InstagramScraper/Instagram.php#L339) but now I am getting a 403. Was someone able to get around this issue? Maybe we need a new endpoint to get comments?

Thanks!

**Comment by raiym** [comment]
@joseflorido I will release fix soon

**Comment by raiym** [comment]
I have released fix for this issue

**Comment by joseflorido** [comment]
Thanks @raiym, @Bolandish!

It's working again.

**Comment by alejoxps** [comment]
Thanks everyone!

**Comment by levicosta201** [comment]
I'm having the following error

InstagramScraper\Exception\InstagramException thrown with message "Response code is 403. Body:  Something went wrong. Please report issue."

**C:\xampp\htdocs\instagram_api\instagram\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php Line 603**
