### ISSUE TITLE
429 Error and proxy enabling

### ISSUE THREAD

**Issue by mflash123** [postaddictme/instagram-php-scraper#464]
I am using getAccountById method in loop. After few times I get this message
`Exception: Response code is 429. Body:  message => Please wait a few minutes before you try again.;`
And code stoping. I want continue runing, using another proxy when I get this error. Can somebody make code example for that?

**Comment by evaldemar** [comment]
```
try {
  $instagram->getAccountById(...);
} catch(InstagramException $e) {
  if ($e->getCode() == 429) {
    // ...
  }
}
```
