### ISSUE TITLE
How can i use this script on cpanel?

### ISSUE THREAD

**Issue by emobin** [postaddictme/instagram-php-scraper#469]
hi buddy, I use this script on local and it has no error and works like a charm, but when i upload it on Cpanel i got error 500 and it's not work anymore, is there anyone here that can help me?

**Comment by zaivst** [comment]
may be some problems with php version or php settings?

**Comment by emobin** [comment]
it works on windows hosting, i got a windows host but still i can not use this script on linux hosting and cpanel!!!!

**Comment by developedsoftware** [comment]
Works fine for me and I am on cpanel? What is the error you are getting ?


________________________________

**Comment by evaldemar** [comment]
may be use ipv6? if it is true, force use ipv4.
example:
Request::curlOpts([CURLOPT_IPRESOLVE => CURL_IPRESOLVE_V4]);

**Comment by emobin** [comment]
Error 500 Instagram return blank value or not found page , it is only work
on getmediabytags. But in Windows hosting everything is ok.
