### ISSUE TITLE
how can i keep account  logged in by file or database?

### ISSUE THREAD

**Issue by Nasirinejad** [postaddictme/instagram-php-scraper#473]
Hi,
How can i do login with "username" and "password" one time and store connected session in database or file and use this file or record for next authentication?
There is any method for store and load connection?

**Comment by zubairsultan786** [comment]
?

**Comment by raiym** [comment]
caching supported with phpfastcache 

there is no exact plans of database or file support just yet

**Comment by alimahmoodvand** [comment]
Hi you can cookie string in any store(file,db) and reuse this string
