### ISSUE TITLE
Error on try to login withCredentials

### ISSUE THREAD

**Issue by Nasirinejad** [postaddictme/instagram-php-scraper#481]
hi, I can login just for first time and in the next try to login i have this error:

> [13-May-2019 10:45:57 Asia/Tehran] PHP Fatal error:  Uncaught exception 'InstagramScraper\Exception\InstagramAuthException' with message 'Something went wrong. Please report issue.' in instagram/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:1292
> Stack trace:
> #3 {main}
>   thrown in instagram/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 1292
> 
This is my code:
`
        $instagram = \InstagramScraper\Instagram::withCredentials($user, $pl, BMPATH.'file/cach/instagram/'.$user);
        $instagram->login();
        return $instagram;`

**Comment by luengwaiban** [comment]
maybe you should try 
```php
$instagram->login(true, true);
```
to see if you need to do two step verify

**Comment by zubairsultan786** [comment]
@luengwaiban same thing i did but still getting error.
