### ISSUE TITLE
Could not extract gis from page

### ISSUE THREAD

**Issue by KirillK90** [postaddictme/instagram-php-scraper#484]
Hello. today something happened with instagram. And no more 'rhx_gis' key in sharedData json. Can't use graphql methods for get medias. Any ideas? Thank's

**Comment by lwiml** [comment]
Same issue, It seems Instagram updated it's public json structure.

**Comment by lwiml** [comment]
same issue

**Comment by BB-000** [comment]
Yes "Could not extract gis from page" error happening here too, the error is not on _all_ my sites that are using it, although perhaps they are cached..

**Comment by brebvix** [comment]
Working code here: https://github.com/brebvix/instagram-php-scraper, you can see commits

**Comment by fsjdg** [comment]
Got same error too. For me, it is trhown when i run getMedias() method. I temporarily solved it by commenting the line 417 on Instagram.php file. I still looking for a better solution 

```
/**
     * @return null
     * @throws InstagramException
     */
    private function getRhxGis()
    {
        if ($this->rhxGis === null) {
            try {
                $sharedData = $this->getSharedDataFromPage();
                $this->rhxGis = $sharedData['rhx_gis'];
            } catch (\Exception $exception) {
                //throw new InstagramException('Could not extract gis from page');
            }
        }

        return $this->rhxGis;
    } 
```

**Comment by brebvix** [comment]
> Got same error too. For me, it is trhown when i run getMedias() method. I temporarily solved it by commenting the line 417 on Instagram.php file. I still looking for a better solution
> 
> ```
> /**
>      * @return null
>      * @throws InstagramException
>      */
>     private function getRhxGis()
>     {
>         if ($this->rhxGis === null) {
>             try {
>                 $sharedData = $this->getSharedDataFromPage();
>                 $this->rhxGis = $sharedData['rhx_gis'];
>             } catch (\Exception $exception) {
>                 //throw new InstagramException('Could not extract gis from page');
>             }
>         }
> 
>         return $this->rhxGis;
>     } 
> ```

I think that "RhxGis" no longer needed. I'm removed it, and all working

**Comment by fsjdg** [comment]
> > Got same error too. For me, it is trhown when i run getMedias() method. I temporarily solved it by commenting the line 417 on Instagram.php file. I still looking for a better solution
> > ```
> > /**
> >      * @return null
> >      * @throws InstagramException
> >      */
> >     private function getRhxGis()
> >     {
> >         if ($this->rhxGis === null) {
> >             try {
> >                 $sharedData = $this->getSharedDataFromPage();
> >                 $this->rhxGis = $sharedData['rhx_gis'];
> >             } catch (\Exception $exception) {
> >                 //throw new InstagramException('Could not extract gis from page');
> >             }
> >         }
> > 
> >         return $this->rhxGis;
> >     } 
> > ```
> 
> I think that "RhxGis" no longer needed. I'm removed it, and all working

I agree with you. However i've been reading about similar problems and it seems to be temporarily. I mean, maybe it will be necessary in the future.

**Comment by KirillK90** [comment]
> Working code here: https://github.com/brebvix/instagram-php-scraper, you can see commits

Thank's a lot. This works.

**Comment by brebvix** [comment]
> > > Got same error too. For me, it is trhown when i run getMedias() method. I temporarily solved it by commenting the line 417 on Instagram.php file. I still looking for a better solution
> > > ```
> > > /**
> > >      * @return null
> > >      * @throws InstagramException
> > >      */
> > >     private function getRhxGis()
> > >     {
> > >         if ($this->rhxGis === null) {
> > >             try {
> > >                 $sharedData = $this->getSharedDataFromPage();
> > >                 $this->rhxGis = $sharedData['rhx_gis'];
> > >             } catch (\Exception $exception) {
> > >                 //throw new InstagramException('Could not extract gis from page');
> > >             }
> > >         }
> > > 
> > >         return $this->rhxGis;
> > >     } 
> > > ```
> > 
> > 
> > I think that "RhxGis" no longer needed. I'm removed it, and all working
> 
> I agree with you. However i've been reading about similar problems and it seems to be temporarily. I mean, maybe it will be necessary in the future. Take a look at this -> #363

Yes, today I found a similar issue with getting comments. Sometimes different comment formats come from the same request, as an example: https://github.com/brebvix/instagram-php-scraper/commit/272c8a29a3fd1d0433d9ab3496bc67f8e487de04

**Comment by pckz** [comment]
any way to solve this bug using this same repo?

**Comment by KirillK90** [comment]
> any way to solve this bug using this same repo?
For me the way was to copy Instagram class to project files and replace some strings until new commits to this repo will come. Unfortunately methods related to Gis are private and I can't to override it in my child class and have to copy whole parent class. It will better to make all methods protected in future to make this project more customizable.

**Comment by MathiasGmeiner** [comment]
My way was to add a `@` to the call:

```
    $instagram = new \InstagramScraper\Instagram();
    $nonPrivateAccountMedias = @$instagram->getMedias('example', 30);
```

**Comment by pckz** [comment]
> My way was to add a `@` to the call:
> 
> ```
>     $instagram = new \InstagramScraper\Instagram();
>     $nonPrivateAccountMedias = @$instagram->getMedias('example', 30);
> ```

practical and simple solution, I don't know how I could forget. 
now wait for the update :D
