### ISSUE TITLE
How to get likes count?

### ISSUE THREAD

**Issue by MUTOgen** [postaddictme/instagram-php-scraper#49]
Can't find any method for this.
Is it possible?

**Comment by raiym** [comment]
Media? 
$media->likesCount

**Comment by MUTOgen** [comment]
@raiym Ah, ok, thanks.
I think it should be in README

**Comment by raiym** [comment]
Yes, I think so too =D

**Comment by MUTOgen** [comment]
@raiym Great! 👍 
Btw, maybe there are other additional things to know in README
Would be very nice to see it
