### ISSUE TITLE
getAccountById error

### ISSUE THREAD

**Issue by Luigidefra** [postaddictme/instagram-php-scraper#496]
Hi, when i try $instagram->getAccountById(46071423), it show error "Response code is 500. Body: Oops, an error occurred. Something went wrong. Please report issue." , it appears only with this id

**Comment by luengwaiban** [comment]
It seems like is a instagram's internal error.
Same code in my PC runs as expecting.

![image](https://user-images.githubusercontent.com/26041575/58846368-8201cc00-86b1-11e9-8c8b-38419eabe742.png)
