### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by luengwaiban** [postaddictme/instagram-php-scraper#498]
@raiym 
Hi raiym, I wrote a instagram scraper in python which is much base on this php version.I don't know wether it legal or be impolite to you if I do so.Can you take a look at this and let me know your attitude?Thanks a lot!

link:https://github.com/luengwaiban/instagram-python-scraper

**Comment by raiym** [comment]
@luengwaiban hello! 
It is great! 
Not sure what I need to say in this situation. I don't object if you converted codebase to python! You could use anything in this repo as you wish (MIT license). 
So, great work! =)

**Comment by luengwaiban** [comment]
@raiym
Thank you very much!
And can I put this repo link on my version’s README.md?

**Comment by raiym** [comment]
Yes. Sure.

**Comment by luengwaiban** [comment]
@raiym already did so.Thanks again~

**Comment by raiym** [comment]
@luengwaiban I saw you deprecated your library. 
If your python version works fine and after my review we could transfer it to postaddictme account, so it could get more contributors

**Comment by luengwaiban** [comment]
@raiym any way I can contact you? email or telegram or any social medium?need communication~

**Comment by raiym** [comment]
Same nickname in telegram

**Comment by luengwaiban** [comment]
@raiym
It seems that I can’t talk to you on telegram. I don’t know why but can you search me?nickname is luengwaiban or lueng ,one of them🤔

**Comment by raiym** [comment]
@luengwaiban wrote to you

**Comment by luengwaiban** [comment]
@raiym sorry for the wrong nickname, the correct one should be lueng_seven . Can you write again?
