### ISSUE TITLE
getAccountById throws 405 exception

### ISSUE THREAD

**Issue by playak** [postaddictme/instagram-php-scraper#50]
The endpoints like:
https://www.instagram.com/query/?q=ig_user(420436054){id,username,external_url,full_name,profile_pic_url,biography,followed_by{count},follows{count},media{count},is_private,is_verified}
seem to return 405 errors now. from my error log:

 Unirest\\Response Object
(
    [code] => 405
    [raw_body] => 
    [body] => 
    [headers] => Array
        (
            [0] => HTTP/1.1 405 Method Not Allowed
            [Strict-Transport-Security] => max-age=86400
            [Allow] => POST
            [Content-Language] => en
            [Expires] => Sat, 01 Jan 2000 00:00:00 GMT
            [Vary] => Cookie, Accept-Language
            [Pragma] => no-cache
            [Cache-Control] => private, no-cache, no-store, must-revalidate
            [Date] => Mon, 05 Dec 2016 08:20:31 GMT
            [Content-Type] => text/html; charset=utf-8
            [Set-Cookie] => Array
                (
                    [0] => csrftoken=YXSSML01CRpcnCApc3URmckHHpBDei0q; expires=Mon, 04-Dec-2017 08:20:31 GMT; Max-Age=31449600; Path=/; secure
                    [1] => mid=WEUjTwAEAAEJkwJfoC3HLdDTlgUq; expires=Sun, 30-Nov-2036 08:20:31 GMT; Max-Age=630720000; Path=/
                )
            [Connection] => keep-alive
            [Content-Length] => 0
        )
)

**Comment by raiym** [comment]
Hello, this issue has been resolved https://github.com/postaddictme/instagram-php-scraper/issues/45

It seems that you use older version of library. Please update and try again

**Comment by playak** [comment]
thanks for the fast answer. that's weird - i just used composer to update the package yesterday. let me double check what went wrong.

**Comment by playak** [comment]
Look like my composer update just pretended to be updating. I manually updated the package now. Sorry about that. Great package, great help!

**Comment by raiym** [comment]
Thanks
Glad to hear that
