### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by realsirjoe** [postaddictme/instagram-php-scraper#500]
hey I created a python version of the scraper: https://github.com/SergioWagenleitner/instagram-scraper

the getFollowing and getFollowers don't seem to work any longer do you experience the same issues and any ideas yet how to resolve them

**Comment by luengwaiban** [comment]
oh my friend @SergioWagenleitner  YOU DID THE SAME THING [#498](https://github.com/postaddictme/instagram-php-scraper/issues/498)...But I am going to learn your code coz I am new to python

**Comment by luengwaiban** [comment]
hey @SergioWagenleitner  buddy, 99% of those who star you, star the same project MaslowCommunityGarden / Maslow-kits-Pre-Order-, and all of them had only stared 2 project(your new release project and MaslowCommunityGarden / Maslow-kits-Pre-Order-).
Why did you collect these fake star？？？Do not do the Taobao stuff here! 
Shamed!

**Comment by SergioWagenleitner** [comment]
@luengwaiban I didn't collect any stars whats the issue when they star MaslowCommunityGarden.

anyway lets get productive your project looks quite good, do you have any new method yet how to scrape followers and followings or some ideas (did some reversing yet)？

**Comment by luengwaiban** [comment]
@SergioWagenleitner I don't know where you locate.But getFollower and getFollowing work perfectly here.You submited an issue but not showing any exception message or code,then what we should talk about?
You can totally be a maintainer of this python version repo but you choose to copy it and do a little bit modify and release it as a new one...?Ok, that's fine.But yuo should never try to make fake stars.
I don't know what to say in this situation.Good luck！
