### ISSUE TITLE
library is not able to get stories

### ISSUE THREAD

**Issue by sagitaire123** [postaddictme/instagram-php-scraper#503]
Hello,

from yesterday, library is not able to get stories, is there any new update ?

Thank you

**Comment by zubairsultan786** [comment]
I have the same issue.

**Comment by sagitaire123** [comment]
@raiym is there any new update of library to make get stories function works correctly ?

**Comment by sagitaire123** [comment]
Hi @zubairsultan786 
did you find any solution to fix that ?

**Comment by zubairsultan786** [comment]
Not yet .. still searching and finding solution.. what about you?

**Comment by sagitaire123** [comment]
@zubairsultan786  I tried many things but its still returning blank in return to getstories function

**Comment by zubairsultan786** [comment]
the problem is in login function

**Comment by sagitaire123** [comment]
OK thank you @zubairsultan786 , did you manage to solve it?

**Comment by zubairsultan786** [comment]
I tried but failed to solve the problem

**Comment by sagitaire123** [comment]
Try to use another account to check stories, it's seems working now
1 IP per account

**Comment by zubairsultan786** [comment]
So it means everytime whenever i will get this error so i need new account?

**Comment by sagitaire123** [comment]
Instagram is blocking if you send a lot of request, so yes you need to change account eveerytime when you get this error.
i don't know how many request we need to send to avoid accounts blocks

**Comment by raiym** [comment]
Are getting stories is not working for you all the time? 
or maybe you reach the api requests limits?

**Comment by sagitaire123** [comment]
@raiym accounts are blocked after too many api request, but we don't know what's the new limit or the way to avoid that.
