### ISSUE TITLE
Fatal error: Uncaught InstagramScraper\Exception\InstagramException: Response code is 502.

### ISSUE THREAD

**Issue by xavikhattak** [postaddictme/instagram-php-scraper#506]
I am getting this error after to many request ... 
Any idea how to by pass or fix it .. 
thanks in advanced

instagram-scrapper\src\InstagramScraper\Instagram.php on line 519
line : 519
 if (static::HTTP_OK !== $response->code) {
            throw new InstagramException('Response code is ' . $response->code . '. Body: ' . static::getErrorBody($response->body) . ' Something went wrong. Please report issue.', $response->code);
        }

**Comment by saki117** [comment]
I got the same problem. My script runs every 10-15 minutes, using login() or login(true) will cause my account being blocked for about 1 day. I also notice that every time I call the login() method, Instagram server will treat as a new login activity and send an email notification for new login, is it the reason for blocking my account?

**Comment by Effectik** [comment]
Same Problem

**Comment by Effectik** [comment]
Just change the url auth oalba:patch-1

**Comment by saki117** [comment]
url auth?

**Comment by Effectik** [comment]
> 
> 
> url auth?

Yes, just check pull requests.

**Comment by saki117** [comment]
Thanks!

**Comment by zubairsultan786** [comment]
What it will be ??
