### ISSUE TITLE
The account is private

### ISSUE THREAD

**Issue by InNovaTherGames** [postaddictme/instagram-php-scraper#509]
Hi, 
I try to access to the list of the followers of my account.
I have this issue : 
PHP Fatal error:  Uncaught InstagramScraper\Exception\InstagramException: Failed to get followers of account id ****. The account is private. in /****/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:1244
Stack trace:
#0 /***.php(27): InstagramScraper\Instagram->getFollowing(****, 100, 100, true)
#1 {main}
  thrown in /**/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 1244

My account isn't private and I have no idea to solve this problem.
Thanks for your help.

**Comment by felipe-tonon** [comment]
I am facing the same issue.

**Comment by felipe-tonon** [comment]
I managed to do a work around by adding this code to the method Instagram::login(...)

`
            $mid = '';
            if ($cookies) {
                $mid = $cookies['mid'];
            }
`

Now it allows me to retrieve followers without any issues

**Comment by raiym** [comment]
Should be closed in v0.8.32. 
@InNovaTherGames could you please confirm?
