### ISSUE TITLE
Follow/unfollow

### ISSUE THREAD

**Issue by thallysbr** [postaddictme/instagram-php-scraper#511]
Not a issue but, i would like to know if there is a way in this lib to follow or unfollow a user ?

**Comment by sclavel** [comment]
Just add at the end of the Instagram.php file, this function:

public function follow($accountId)
{
  Request::post(Endpoints::getFollowUrl($accountId), $this->generateHeaders($this->userSession));
}

**Comment by raiym** [comment]
I thought it was there. But apparently only like/unlike, comment/uncomment.

**Comment by erfanmola** [comment]
> Just add at the end of the Instagram.php file, this function:
> 
> public function follow($accountId)
> {
> Request::post(Endpoints::getFollowUrl($accountId), $this->generateHeaders($this->userSession));
> }

it's not working for me,
has anyone tested ?
