### ISSUE TITLE
Undefined index: mid

### ISSUE THREAD

**Issue by sergeizhukov** [postaddictme/instagram-php-scraper#512]
Hello. 
Version is "^0.8.31"
After install wrote the example code.

```

        $instagram = Instagram::withCredentials('login', 'password');

        $instagram->login();

        $account = $instagram->getAccount('realuser');

        var_dump($account); exit;

```
Received:

> Undefined index: mid

> yii\base\ErrorException: Undefined index: mid in /vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:1359

Any ideas for resolve?

**Comment by lukaspicha** [comment]
I have same problem, but I use login method  for getting list of followers, for getting account info you musn't be logged.

**Comment by adisazhar123** [comment]
I'm getting this problem on a live server. Logging in on my local machine works though. My live server is hosted overseas. The problem may be because IG identifies a different login location, thus causing it not to login properly and returning incomplete response headers. 

Does anyone have a solution for this?

**Comment by lukaspicha** [comment]
In InstagramScraper/Instagram.php class I remove all variables $mid and now it works for me.

**Comment by adisazhar123** [comment]
@lukaspicha does it work if you're calling a function that requires a user to be logged in?

**Comment by lukaspicha** [comment]
> @lukaspicha does it work if you're calling a function that requires a user to be logged in?

yes

**Comment by timmoh** [comment]
see #501  @raiym

**Comment by raiym** [comment]
thank you
