### ISSUE TITLE
getting all comments

### ISSUE THREAD

**Issue by kimia000** [postaddictme/instagram-php-scraper#520]
I tried to get all comments of a media by the example given at https://github.com/postaddictme/instagram-php-scraper/blob/master/examples/getMediaComments.php

but it only returns 10 or 11 comments.

If I omit the second parameter, as 
`$comments = $instagram->getMediaCommentsById('1130748710921700586');
`
it will return 10 comments, and if I put a large number like the example,
`$comments = $instagram->getMediaCommentsById('1130748710921700586', 10000);
`
it will return 11 comments.

**Comment by farrusete** [comment]
same here
