### ISSUE TITLE
Get comments error

### ISSUE THREAD

**Issue by lewbor** [postaddictme/instagram-php-scraper#523]
Threre is a 403 response while getting the comments using getMediaCommentsByCode() method. After debugging I find a some reasons for it:
1) Invalid  query_hash request parameter (possible it changed)
2) No cookies. New endpoint requres a session cookies, but when makiing first request no cookies is set (need to call getMediaById() first to set cookies)
3) old response key was "edge_media_to_comment" but new is "edge_media_to_parent_comment"

**Comment by benlumley** [comment]
Looking at this, you appear to need the x-csrftoken set now, even when not logged in... quick testing suggests it doesn't matter what it's set to.

**Comment by benlumley** [comment]
https://github.com/postaddictme/instagram-php-scraper/pull/524

**Comment by sportakal** [comment]
Is that way solve? I still get 403

**Comment by pgrimaud** [comment]
@sportakal You just have to wait for the approval of PR.

**Comment by benlumley** [comment]
> @sportakal You just have to wait for the approval of PR.

Or reference my repo in composer.json - https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

This in repositories:

```
        {
            "type": "vcs",
            "url": "https://github.com/benlumley/instagram-php-scraper"
        }
```

and then

```
        "raiym/instagram-php-scraper": "dev-master@dev"
```
