### ISSUE TITLE
GetMediasByLocationId return empty array

### ISSUE THREAD

**Issue by filippodicostanzo** [postaddictme/instagram-php-scraper#526]
From today this method return empty array
$medias = $instagram->getMediasByLocationId('1', 20);

I've fix the headers request with this code 
```
        if (empty($headers['x-csrftoken'])) {
            $headers['x-csrftoken'] = md5(uniqid()); // this can be whatever, insta doesn't like an empty value
        }

```
other methods works but this doesn't work

**Comment by jstrobel** [comment]
Seems there is a PR waiting for merge: https://github.com/postaddictme/instagram-php-scraper/pull/524

**Comment by filippodicostanzo** [comment]
Still doesn't work.
Other methods works fine with a residential IP
This call return an empty array.

Any solution?
