### ISSUE TITLE
Server is down on request of 1000 followers  getAccountFollowers

### ISSUE THREAD

**Issue by livindead** [postaddictme/instagram-php-scraper#527]
I am use this example https://github.com/postaddictme/instagram-php-scraper/blob/master/examples/getAccountFollowers.php
but after execution server not response.
Is this a normal script job? Is this a large sample of people or not?

**Comment by Mo9a7i** [comment]
try changing to 40

**Comment by dragosite** [comment]
I _think_ you can do up to 50 per hour, if I'm not mistaking.
