### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by raiym** [postaddictme/instagram-php-scraper#53]
Like @ShiawasenaHoshi did in Java Scraper

https://github.com/postaddictme/instagram-java-scraper/commit/e4acbc9af86b65dc19c6dab7dd95e28a6bf67249

**Comment by Lestx** [comment]
It should be possible to proxy a request using the unirest library. After all the library has proxy support.

https://github.com/Mashape/unirest-php#proxy

**Comment by TorbenL** [comment]
Anything new here? Would be really helpful if the library is able to deal with proxies! :)

**Comment by raiym** [comment]
@TorbenL it will be available soon
