### ISSUE TITLE
Account with this username does not exist

### ISSUE THREAD

**Issue by Johnnydoncom** [postaddictme/instagram-php-scraper#531]
Please, I need help. I kept seeing **"Account with this username does not exist"** each time I run $instagram->getAccount($username);. The weird aspect of it is that, when I run the on localhost, it works well, but that's not the case when I upload to my remote server. I'm really confused. Please someone should help me out with a solution.

**Comment by Jurigag** [comment]
Duplicate of #529

**Comment by jamalapriadi** [comment]
i have same issue, but its work in my local computer and doesnt work in  my production server :(

**Comment by mnajafzadeh** [comment]
Hi guys,

This problem is related to getAccount($username) function. You need to use searchAccountsByUsername($username) but, need to limit the results.
I try to do the change and create a pull request for limiting the results on this function.

**Comment by mnajafzadeh** [comment]
Pull request created #578

**Comment by trebaxa** [comment]
Workaround for me:
$instagram = new \InstagramScraper\Instagram();

                ```
    $account = $instagram->searchAccountsByUsername($this->gblconfig->insta_account);
                    $account = $account[0];
                    $nonPrivateAccountMedias = $instagram->getMediasByUserId($account->getId(), $ele_count, "");
```
