### ISSUE TITLE
How to return all usernames of those who've commented

### ISSUE THREAD

**Issue by SuperN00b** [postaddictme/instagram-php-scraper#54]
I just want usernames of commenters scraped. I've tried `$usernames = ($data[0]->username);`
and received this: 
Undefined property: InstagramScraper\Model\Comment::$username 

Ultimately, I want to be able to find all of the usernames scraped from the post. When I try 
```
foreach($data as $value){
  echo $value->text, "<br />";
}
```

**I get each comment in the post.** 

But when I try
```
foreach($data as $value){
  echo $value->user, "<br />";
}
```

> Object of class InstagramScraper\Model\Account could not be converted to string

And

```
 foreach($data as $value){
  echo $value->username, "<br />";
}
```

> Undefined property: InstagramScraper\Model\Comment::$username

Why can't I access anything past the actual comment/text? I really appreciate any help. I've only been teaching myself to program by working on this project.

**Comment by raiym** [comment]
Hello. 
As I see you trying to get username like this: $comment->username. But username lays inside user object. 
Try this:
    $comments = Instagram::getMediaCommentsById('1130748710921700586', 20);
    foreach($comments as $comment) {
         echo $comments[0]->user->username . '</br>';
    }

**Comment by SuperN00b** [comment]
Thank youuuuuu 😅
