### ISSUE TITLE
Can update to use scraperapi.com api  ???

### ISSUE THREAD

**Issue by hopye** [postaddictme/instagram-php-scraper#541]
Hey guys, I have been testing plain several proxies, not even using the instagram scraper, .. they are able to detect each of the proxies tested. the only working service I have tested that will give me the instagram correct output is scraperapi.com ,

so I guess the instagram scraper can be update to using scraperapi.com api to retrieve the data, this will definitely be the best course of action.

particularly for my use im caching the data into a .json and and checking the last updated before using any scraping again :)

**Comment by dragosite** [comment]
Hey, how did you manage to implement scraperapi?

I’ve been trying but I kee getting 400s. 

Can you please show some code examples?

**Comment by illiamorkva** [comment]
> Hey, how did you manage to implement scraperapi?
> 
> I’ve been trying but I kee getting 400s.
> 
> Can you please show some code examples?

Same too

**Comment by illiamorkva** [comment]
> Hey guys, I have been testing plain several proxies, not even using the instagram scraper, .. they are able to detect each of the proxies tested. the only working service I have tested that will give me the instagram correct output is scraperapi.com ,
> 
> so I guess the instagram scraper can be update to using scraperapi.com api to retrieve the data, this will definitely be the best course of action.
> 
> particularly for my use im caching the data into a .json and and checking the last updated before using any scraping again :)

Can you provide an example of your code, please?
