### ISSUE TITLE
phpfastcache 7.*

### ISSUE THREAD

**Issue by CodingAnonymous** [postaddictme/instagram-php-scraper#543]
Hi there!

Please update the dependencies to phpfastcache 7.* 

Otherwise following error occurs: Problem 1
    - Installation request for raiym/instagram-php-scraper ^0.8.35 -> satisfiable by raiym/instagram-php-scraper[v0.8.35].
    - raiym/instagram-php-scraper v0.8.35 requires phpfastcache/phpfastcache 5.0.* -> satisfiable by phpfastcache/phpfastcache[5.0.0, 5.0.0-alpha1, 5.0.0-alpha2, 5.0.0-beta1, 5.0.0-beta2, 5.0.0-rc1, 5.0.0-rc2, 5.0.0-rc3, 5.0.1, 5.0.10, 5.0.11, 5.0.12, 5.0.13, 5.0.14, 5.0.15, 5.0.16, 5.0.17, 5.0.18, 5.0.19, 5.0.2, 5.0.20, 5.0.21, 5.0.3, 5.0.4, 5.0.5, 5.0.6, 5.0.7, 5.0.8, 5.0.9] but these conflict with your requirements or minimum-stability.

Thank you very much!

**Comment by aliazizi** [comment]
Same issue

**Comment by kw190** [comment]
Most likely it won't be updated, I already requested it long time ago...
https://github.com/postaddictme/instagram-php-scraper/issues/515

**Comment by Finesse** [comment]
phpfastcache 7 requires PHP ≥7 while instagram-php-scraper requires PHP ≥5.4.

A better solution in a long term would be to use a PSR cache interface instead of a specific cache library: https://github.com/postaddictme/instagram-php-scraper/issues/553

**Comment by raiym** [comment]
Will be addressed in #553

**Comment by raiym** [comment]
ЗЫК-16

**Comment by CodingAnonymous** [comment]
Thanks you very much! Could you please update the composer package?

**Comment by raiym** [comment]
It is done: v0.9.0
