### ISSUE TITLE
Useragent Mismatch

### ISSUE THREAD

**Issue by fsjdg** [postaddictme/instagram-php-scraper#544]
is somebody getting this error: Code: 400 Response code is 400. Body:  message => useragent mismatch; status => fail; Something went wrong. Please report issue?

**Comment by oalba** [comment]
I'm having the same problem. The problem is with the url `https://i.instagram.com/api/v1/users/{userId}/info/` it is not valid anymore

**Comment by Swagnus** [comment]
Same problem here!

**Comment by saki117** [comment]
> I'm having the same problem. The problem is with user agent from the call to the url `https://i.instagram.com/api/v1/users/{userId}/info/`. Instagram changed it and now only the app is able to access that url.
> 
> This PR fixes the problem #545

Problem solved with this change, thanks!

**Comment by dandyraka** [comment]
![image](https://user-images.githubusercontent.com/18587059/66755123-92c51880-eec1-11e9-8ea6-0db9a0e74e42.png)
Change the user agent will work

**Comment by Zeitwaechter** [comment]
Sorry, but did it change again?

![image](https://user-images.githubusercontent.com/1764348/66903084-1554f180-f002-11e9-8869-e85bf147c74c.png)

**Comment by mdeveloper20** [comment]
Uncaught InstagramScraper\Exception\InstagramException: Response code is 400. Body: message => useragent mismatch; status => fail; Something went wrong. Please report issue.

**Comment by MuetzeOfficial** [comment]
Same problem here since today.

**Comment by ThirupathiRaoM** [comment]
Hi,
Hope you are doing great,
I am Integrating Instagram in my App i am Getting Instagram id And Client id But i need to get user name On the Basis Of these Details i tried To use Instagram Graph Api And Above   Api's Which You shared Above i am Unable to Get the response From Those Please Help me to get the User name From Instagram it will help To Complete My App Functionality Please Any Body Have Solution Please respond here 

I am Waiting For your Valuable Response For Solve My Problem

Thanks&Regards
Thiru(IOS developer)

**Comment by avalanche1** [comment]
Anyone having those probs: 
change User-Agent to `Instagram 219.0.0.12.117 Android`

**Comment by prime-optimal** [comment]
> Anyone having those probs: change User-Agent to `Instagram 219.0.0.12.117 Android`

Worked like a charm, just popped it into postman.  Thanks so much!

**Comment by slashbasit** [comment]
![image](https://user-images.githubusercontent.com/80700518/223766555-0c3bba21-5e9b-4af0-bcbb-df2f67302df9.png)

**Comment by xx7Ahmed7xx** [comment]
@prime-optimal 
How exactly did you use that?

**Comment by BasitAli05** [comment]
Use this 
User-Agent : Mozilla/5.0 (iPhone; CPU iPhone OS 12_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Instagram 105.0.0.11.118 (iPhone11,8; iOS 12_3_1; en_US; en-US; scale=2.00; 828x1792; 165586599)

**Comment by akankshabhovar** [comment]
> Use this User-Agent : Mozilla/5.0 (iPhone; CPU iPhone OS 12_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Instagram 105.0.0.11.118 (iPhone11,8; iOS 12_3_1; en_US; en-US; scale=2.00; 828x1792; 165586599)

where did you get this value from?
