### ISSUE TITLE
No route to host

### ISSUE THREAD

**Issue by MUTOgen** [postaddictme/instagram-php-scraper#55]
I tried to use component in cron to update several accounts.

I got error of Unirest/Request **Failed connect to www.instagram.com:443; No route to host** pretty frequently

Why does it happen?

**Comment by raiym** [comment]
Hello! Don't know

How frequently cron job executes? 

Please provide code snippets.

**Comment by MUTOgen** [comment]
Actually i use 2 types of cron jobs.
To update user's profile (each 24 hours) and to update media info (each 30 mins). 

But also i use console command to load new accounts, may be once a day or 2 days.
During this command i have this errors, so i need to re-execute command and it continues job.

Code not so complicated

```
foreach(...){
$insta_account = Instagram::getAccount($convertedText);
echo "Data from Instagram recieved...\r\n";
///....save to db....////
}
```

As i now i don't use it for big amount of operations, but may be you have an idea how to fix this.

**Comment by raiym** [comment]
Maybe adding random sleep after every API call may help?

**Comment by MUTOgen** [comment]
@raiym may be...
I will try it.
But as i can imagine there are huge amount of user's request each seconds, so my crons not a big deal... But who knows...

**Comment by yura999999999** [comment]
+ 1, same issue

**Comment by raiym** [comment]
@yura999999999 maybe remote server is shared hosting and a lots of apps trying to reach instagram with same IP and instagram banned it (maybe temporary)

It is just hypothesis

**Comment by yura999999999** [comment]
@raiym check it, tnx
