### ISSUE TITLE
We Detected An Unusual Login Attempt

### ISSUE THREAD

**Issue by kostikag** [postaddictme/instagram-php-scraper#551]
**Hello! First of all, I would like to thank everyone who supports and works on this library! You are cool!**

Instagram behaves very strangely, some accounts work stably, but the other part of the accounts logs out (change of session ID) approximately every 20 minutes.
I do not send spam (or ML, MF), I only receive information about followers.
Each time he says: "We Detected An Unusual Login Attempt",  but In this case, nothing changes. Maybe someone came across? How does Instagram track suspicious activity? Accounts never work at the same time, proxies for each account are different and assigned to the same account. Request limits have also never been exceeded.

**Comment by powderblock** [comment]
Seems to be happening a lot lately...
I wonder if Instagram is getting more secure.

**Comment by Maksix** [comment]
Hello, getting this error for 3 days already every time i try to login to instagram. I use Ipv6 proxies, tried to change user agent, but still getting this message. Is there any way i can "press" the button "This was me", or maybe i should change something so this banner doesn't even show up?

**Comment by s-fraser2007** [comment]
Was there any success with this? Im having similar issues, im only managing arount 70-80 calls to IG per hour before im being blacked with this error :/

**Comment by Maksix** [comment]
No, im switching ig accounts every 5 mins so they dont get blocked

пт, 14 авг. 2020 г., 12:34 s-fraser2007 <notifications@github.com>:

**Comment by s-fraser2007** [comment]
Can I ask how youre doing this please? 😁 

currently im using 12 login accounts selected at random 
`
$Files = new Psr16Adapter('Files');
$instagram = Instagram::withCredentials($instagram_login->username, Crypt::decryptString($instagram_login->password), $Files);

if (rand(0,1) % 2 == 0)
    Instagram::setProxy(['address' => '10.10.0.11', 'port' => '3128']);
else
    Instagram::disableProxy();

$agent = $userAgents[array_rand($userAgents)];

$instagram->setUserAgent($agent);
$instagram->login();
$instagram->saveSession();`
