### ISSUE TITLE
Account with this username does not exist

### ISSUE THREAD

**Issue by tyurin-ilya** [postaddictme/instagram-php-scraper#552]
Hello.
I get an error:

Fatal error: Uncaught exception 'InstagramScraper\Exception\InstagramNotFoundException' with message 'Account with this username does not exist' in /dat/wwwroot/wedding-magazine.ru/instagram_api/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 366
--
1 | 0.0004 | 264280 | {main}( ) | .../getAccountMediasByUsername.php:0
2 | 0.0020 | 369192 | InstagramScraper\Instagram->getMedias( ) | .../getAccountMediasByUsername.php:61
3 | 0.0020 | 369512 | InstagramScraper\Instagram->getAccount( ) | .../Instagram.php:341

But this account exists.

**Comment by hoangcao10** [comment]
same problem

**Comment by tyurin-ilya** [comment]
Instagram blocked my IP address, because I send requests every 1 minute without login. Now I send a request every 1 hour with login and all is okay.
Also if I send requests through different proxies every 1 minute, also all is ok.
