### ISSUE TITLE
[Feature request] Use PSR cache

### ISSUE THREAD

**Issue by Finesse** [postaddictme/instagram-php-scraper#553]
PHP community nowadays goes to a standardisation. There are 2 standards of caching in PHP: [PSR-6](https://packagist.org/packages/psr/cache) (overcomplicated and deprecated) and [PSR-16](https://packagist.org/packages/psr/simple-cache) a.k.a. simple cache. A standard is a Composer package that contains only interfaces. Library authors (cache libraries and libraries like instagram-php-scraper) implement these interfaces and as a result the libraries can be used together.

If instagram-php-scraper requires a PSR-16 library rather than a concrete cache library ([phpfastcache](https://packagist.org/packages/phpfastcache/phpfastcache)), it's users will get more flexibility (e.g. use Redis); if somebody uses another cache library in his project, he will reuse the library and reduce the application size and response time.

Luckily, moving to PSR-6 or PSR-16 should be simple because phpfastcache implements PSR-6 and PSR-16 and follows their concepts. Installation of instagram-php-scraper will be a bit more "complicated":

```bash
composer require raiym/instagram-php-scraper phpfastcache/phpfastcache
# You can use any cache you like instead of phpfastcache: https://packagist.org/providers/psr/simple-cache-implementation
```

```php
phpFastCache\CacheManager::setDefaultConfig([
    'path' => '/path/to/cache/folder/',
    'ignoreSymfonyNotice' => true,
]);
$instagram = Instagram::withCredentials('username', 'password', CacheManager::getInstance('files'));
$instagram->login();
```

**Comment by raiym** [comment]
@Finesse  Thanks for this suggestions 

We will move to PSR-16 soon

**Comment by Finesse** [comment]
@raiym Cool! Thank you
