### ISSUE TITLE
We Noticed a New Login

### ISSUE THREAD

**Issue by joty0** [postaddictme/instagram-php-scraper#554]
I always get "**We Noticed a New Login**" mails on almost every login:

![pic](https://user-images.githubusercontent.com/56916285/67484056-9007b780-f667-11e9-93ef-836807640696.png)

I try to fix it with the given solutions here but unfortunately without success...

#420 
#551 
#398 

Someone any Ideas? 

Thanks

**Comment by mix359** [comment]
I'm experiencing the same problem.... Any news?

**Comment by Gugiman** [comment]
Same here
