### ISSUE TITLE
getMedias not working on prod

### ISSUE THREAD

**Issue by arthurpietruch** [postaddictme/instagram-php-scraper#557]
I'm trying to display a list of the last posts from an instagram account (not private) in my Symfony project :

```
$instagram = new \InstagramScraper\Instagram();
        try {
            $posts = $instagram->getMedias('nameoftheaccount', 6);
        }
        catch (Exception $e) {
            $posts = [];
        }
```
Perfecty working on my dev version in localhost, but exception caught on prod.
Any idea ?

**Comment by fsjdg** [comment]
Which error are you getting?

**Comment by rupak78** [comment]
Hi, I am getting this same problem. The code is running fine in development but not in production.

The error that I am getting is "Account doesn't exist". 

The error is occurring at line no.  353 Instagram.php .

 if (!isset($userArray['entry_data']['ProfilePage'][0]['graphql']['user'])) {
            throw new InstagramNotFoundException('Account with this username does not exist');
        }

Any help is much appreciated.

**Comment by fsjdg** [comment]
do you get that error with All accounts or just some? Try using dedicated proxies.

**Comment by rupak78** [comment]
The issue has got auto-resolved. The only thing I did was stop the code in development and was only using in production.

@fsjdg when I was getting the error , I was getting in all accounts.

**Comment by LimpopoWebAgency** [comment]
Have same error on prod when I try to get medias: "Uncaught exception 'InstagramScraper\Exception\InstagramException' with message 'Response code is 200. Body:" . Localy work fine without any errors.

**Comment by MadsWL** [comment]
I am experiencing the exact same problem. Locally it works perfectly, but I get the following error message on my live-site: Uncaught InstagramScraper\Exception\InstagramException: Response code is 200.' 

What to do?

**Comment by fsjdg** [comment]
Have you guys @bastluc @MadsWL tried using rotating proxies? it should help.

**Comment by fsjdg** [comment]
Also, if do several request to Instagram API, make sure you do some random pauses to avoid bot detection.

**Comment by bastluc** [comment]
@fsjdg Just tried to use a proxy, same error... even on localhost

**Comment by fsjdg** [comment]
@bastluc Can't be any proxy. Usually, Instagram detects datacenter's proxies. Are you making this request with a logged-in account or without it?

**Comment by bastluc** [comment]
@fsjdg I'm making de request without any account login
