### ISSUE TITLE
Uncaught Error: Class 'Phpfastcache\\Helper\\Psr16Adapter' not found

### ISSUE THREAD

**Issue by joty0** [postaddictme/instagram-php-scraper#558]
I updated the scraper and added following lines as described on the main page:

```
use Phpfastcache\Helper\Psr16Adapter;
$instagram = Instagram::withCredentials('username', 'password', new Psr16Adapter('Files'));
```

after reloading my php-file i get following error:

**`Uncaught Error: Class 'Phpfastcache\\Helper\\Psr16Adapter' not found`**

**Comment by arthurpietruch** [comment]
Did you install Phpfastcache first ?
` composer require phpfastcache/phpfastcache`

**Comment by joty0** [comment]
Oh man I'm so stupid, copied the wrong dictionary 

Thanks a lot

**Comment by nsoni244** [comment]
I'm getting same issue.
I have istalled composer require phpfastcache/phpfastcache
My file is stored on location app/Model/sessions/crawler.stylevore.com/Files/2b/74/2b74e312435895bfb18da7ab0961ff62.txt

is it correct?

How i can reuse file to login
