### ISSUE TITLE
getLastLikesByCodeLink - does it work?

### ISSUE THREAD

**Issue by ganego** [postaddictme/instagram-php-scraper#56]
Hi, I'm doing some IG scraping in python and came across your project here, I have a question regarding "getLastLikesByCodeLink". Does it work for you? I don't want to set up a php server to test, but I tested in Firefox (see below).

EDIT: To fix your code remove the `id` after `nodes{`.

It uses a shortcode, for example "`BOrcVwohLka`" and then invokes
`ig_shortcode(BOrcVwohLka){likes{nodes{id,user{id,profile_pic_url,username,follows{count},followed_by{count},biography,full_name,media{count},is_private,external_url,is_verified}},page_info}}`

~~You can test this in your browser with POST requests on their site, this works for example fine for what `getAccountJsonInfoLinkByAccountId` does, but for getLastLikesByCodeLink  I get an error "400 - invalid query" back.~~

~~If your code does not work, you can get the last 10 likes from `getMediaJsonLink`.~~

In the IG app I can get all likes for a pic (more than 10), does anybody know if this is somehow possible without API access?

**Comment by upphsa** [comment]
Hi, If you give your Skype address or WhatsApp number, we can discuss it in detail. If you do not want us to sell the system size or use it as a barter.

________________________________
Gönderen: ganego <notifications@github.com>
Gönderildi: 31 Aralık 2016 Cumartesi 22:28:03
Kime: postaddictme/instagram-php-scraper
Bilgi: Subscribed
Konu: [postaddictme/instagram-php-scraper] getLastLikesByCodeLink - does it work? (#56)


Hi, I'm doing some IG scraping in python and came across your project here, I have a question regarding "getLastLikesByCodeLink". Does it work for you? I don't want to set up a php server to test, but I tested in Firefox (see below).

It uses a shortcode, for example "BOrcVwohLka" and then invokes
ig_shortcode(BOrcVwohLka){likes{nodes{id,user{id,profile_pic_url,username,follows{count},followed_by{count},biography,full_name,media{count},is_private,external_url,is_verified}},page_info}}

You can test this in your browser with POST requests on their site, this works for example fine for what getAccountJsonInfoLinkByAccountId does, but for getLastLikesByCodeLink I get an error "400 - invalid query" back.

If your code does not work, you can get the last 10 likes from getMediaJsonLink.

In the IG app I can get all likes for a pic (more than 10), does anybody know if this is somehow possible without API access?

-

**Comment by raiym** [comment]
Hello @ganego . No it doesn't work for me. 
With this method I can't get all likes from media.

As I understand we can scrape likes after auth process. 

Take a look at this library: https://github.com/mgp25/Instagram-API

May be it will help.

@upphsa sorry, didn't understand your post, can you elaborate
