### ISSUE TITLE
Response code is 429. Body:  message => Please wait a few minutes before you try again

### ISSUE THREAD

**Issue by Aassifh** [postaddictme/instagram-php-scraper#561]
Hi, Does anyone have a solution for this kind of error ? Thanks in advance..

**Comment by joty0** [comment]
if u just look for the [http status code 429](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) u can see that there are too Many Requests, so just use proxys or a sleep in ur php-file

**Comment by Aassifh** [comment]
Thank you for your response, but even if i used a 5 seconds sleep or proxies i still get a 429 response, should i increase the sleeping time ?
