### ISSUE TITLE
429 Proxy how to switch

### ISSUE THREAD

**Issue by farmgameowner** [postaddictme/instagram-php-scraper#565]
Hey there. Please can you out code here for how to switch proxy to another when 429 error happens?
I am getting 14k followers and for one i can only copy 4k.
Where and what code should i put for change proxy when 429 is up?

**Comment by fsjdg** [comment]
Ji @farmgameowner, I set new proxies by calling Instagram::setProxy() after getting errors. This overwrites your old proxy setting with the new one you provide.

**Comment by farmgameowner** [comment]
> Ji @farmgameowner, I set new proxies by calling Instagram::setProxy() after getting errors. This overwrites your old proxy setting with the new one you provide.

@fsjdg man, i get it) But! I have list of proxys in array, Using getFollowers() function of Instagram.php.
Can you put here code exmple of what you mean?
Couse i need to understand what i doing wrong. 
Just put setProxy before logging not working

**Comment by farmgameowner** [comment]
@fsjdg or should i just put my array like
Instagram::setProxy($proxys);
?

**Comment by fsjdg** [comment]
I'm not doing nothing special, just calling `Instagram::setProxy([...])` after getting error or after a few random request numbers.

           ```
$proxySettings = [
                'port' => $proxy->port,
                'address' => $proxy->ip,
                'type' => CURLPROXY_HTTP,
                'tunnel'  => true,
                'timeout' => 30,
                'verifyPeer' => false,
            ];

            if( $proxy->username && $proxy->password ){
                $proxySettings['auth'] = [
                    'user' => $proxy->username,
                    'pass' => $proxy->password,
                    'method' => CURLAUTH_BASIC
                ];
            }

            self::$instagramInstance::setProxy( $proxySettings );
```

This touch directly the `\Unirest\Request::class` so every request you made through Request, will use the proxy you set.

Do you want to share your code? are you sure your proxies work fine?

**Comment by farmgameowner** [comment]
@fsjdg yeah! Proxies work great. 100%!
pls tell me how to get this in my script and how to switch proxy and put new login with password?

**Comment by fsjdg** [comment]
This is exactly what you have to do:

$proxySettings = [
    'port' => `PROXY_PORT`,
    'address' => `PROXY_IP`,
    'type' => CURLPROXY_HTTP,
    'tunnel' => true,
    'timeout' => 30,
    'verifyPeer' => false,
];

if( `PROXY_USERNAME` && `PROXY_PASSWORD` ){
         $proxySettings['auth'] = [
                'user' => PROXY_USERNAME,
                'pass' => PROXY_PASSWORD,
                'method' => CURLAUTH_BASIC
         ];
}

\InstagramScraper\Instagram::setProxy( $proxySettings );

Change `PROXY_PORT, PROXY_IP, PROXY_USERNAME, PROXY_PASSWORD` for your proxy information. This should work for you. If not, tell me what error are you getting
