### ISSUE TITLE
Fatal error: Uncaught TypeError: Argument 3 passed to InstagramScraper\Instagram::withCredentials() must be an instance of Psr\SimpleCache\CacheInterface, string given

### ISSUE THREAD

**Issue by girls-incode** [postaddictme/instagram-php-scraper#568]
Fatal error: Uncaught TypeError: Argument 3 passed to **InstagramScraper\Instagram::withCredentials()** must be an instance of **Psr\SimpleCache\CacheInterface**, string given, called in G:\workspace\instagram-php-scraper\examples\getMediaById.php on line 8 and defined in G:\workspace\instagram-php-scraper\src\InstagramScraper\Instagram.php on line 54

How should i make the call:
**$instagram = \InstagramScraper\Instagram::withCredentials('username', 'password', '????');**

Where i have to define **CacheInterface** ?

**Comment by mix359** [comment]
Hi @VVVIO 
It seam that they have changed the way you can cache the contents:
Now you need to pass a Psr16 compatible cache interface.

If you see on the project readme, there's this example that use phpfastcache:
`use Phpfastcache\Helper\Psr16Adapter;

$instagram = Instagram::withCredentials('username', 'password', new Psr16Adapter('Files'));`

If you need to specify the directory location, like before, you can specify some options like this
`Instagram::withCredentials('user', 'pass', new Psr16Adapter("Files",new ConfigurationOption(['path' => "/my/path"])))` 

Remember to install phpfastcache with composer:
`composer require phpfastcache/phpfastcache`

Hope this can help
Cheers
Mix

**Comment by KoIIIeY** [comment]
$ php5.6 composer.phar require phpfastcache/phpfastcache
Using version ^6.1 for phpfastcache/phpfastcache
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing psr/cache (1.0.1): Downloading (100%)         
  - Installing phpfastcache/phpfastcache (6.1.4): Downloading (100%)         
phpfastcache/phpfastcache suggests installing ext-apc (*)
phpfastcache/phpfastcache suggests installing ext-intl (*)
phpfastcache/phpfastcache suggests installing ext-memcached (*)
phpfastcache/phpfastcache suggests installing ext-memcache (*)
phpfastcache/phpfastcache suggests installing ext-redis (*)
phpfastcache/phpfastcache suggests installing ext-xcache (*)
phpfastcache/phpfastcache suggests installing ext-sqlite (*)
phpfastcache/phpfastcache suggests installing ext-wincache (*)
phpfastcache/phpfastcache suggests installing ext-leveldb (*)
phpfastcache/phpfastcache suggests installing ext-couchbase (*)
phpfastcache/phpfastcache suggests installing predis/predis (~1.1.0)
phpfastcache/phpfastcache suggests installing mongodb/mongodb (^1.1)
phpfastcache/phpfastcache suggests installing phpfastcache/phpssdb (~1.0.0)
phpfastcache/phpfastcache suggests installing phpfastcache/couchdb (~1.0.0)


Why we cant just not use cache?

**Comment by nsoni244** [comment]
I'm getting same issue.
My file is stored on location app/Model/sessions/crawler.stylevore.com/Files/2b/74/2b74e312435895bfb18da7ab0961ff62.txt

is it correct?

How i can reuse file to login

**Comment by sector7gp** [comment]
Use this, to store the session and reuse the log in
```
use Phpfastcache\Helper\Psr16Adapter;
$instagram = \InstagramScraper\Instagram::withCredentials('user', 'pass', new Psr16Adapter('files'));
$instagram->login();
$instagram->saveSession();
```

**Comment by NabiKAZ** [comment]
I suggest to you expand Argument 3 and Psr16Adapter in README project. And set this package by default.
And also seem should change argument 3 in all examples:
```
$instagram = \InstagramScraper\Instagram::withCredentials('username', 'password', '/path/to/cache/folder');
```
