### ISSUE TITLE
Can't get owner info from media object

### ISSUE THREAD

**Issue by joseflorido** [postaddictme/instagram-php-scraper#569]
After loading medias by tag, on each media I try
`$account = $media->getOwner();`
but the account object has all properties empty, so when I do:
`$account->getUsername();`
I just get an empty string. Every other $media method works fine.
Any idea?

**Comment by mattchete** [comment]
Maybe this can help you (don't use that lib anymore but it worked in the past) :
https://github.com/postaddictme/instagram-php-scraper/issues/433#issuecomment-445533330

**Comment by jakewhiteley-gc** [comment]
Same issue for me. Only owner ID comes through at the moment.

**Comment by raiym** [comment]
Because Instagram not giving it in this requested
