### ISSUE TITLE
Uncaught InstagramScraper\\Exception\\InstagramException: Response code is 429.

### ISSUE THREAD

**Issue by joty0** [postaddictme/instagram-php-scraper#574]
It seems that instagram updated some thinks, they kick me of after a few requests, no matter if I use the scraper or loading the Locations normally in the Browser...
Are they  just under high load or can someone confirm that issue? 

**Error:**
PHP Fatal error:  Uncaught InstagramScraper\\Exception\\InstagramException: Response code is 429.
(Error: Please wait a few minutes and try again.)

```
...
$location = $instagram->getLocationById("location-id");
$location_lat = "{$location->getLat()}";
$location_lng = "{$location->getLng()}";
sleep(6);
...
```

even if I sleep for more than 6 secs it doesn't work...

**Comment by romanoidV** [comment]
Hello, had you found solution?
