### ISSUE TITLE
how can I get stories from other public accounts?

### ISSUE THREAD

**Issue by Felnor96** [postaddictme/instagram-php-scraper#575]
how can I get stories from other public accounts?

**Comment by jangrewe** [comment]
I guess you have to follow them, just like their only shown on Instagram if you follow somebody.

**Comment by jangrewe** [comment]
To those 👎-voters, WTF? If you have a better/other solution, why don't you share it!

**Comment by sector7gp** [comment]
> how can I get stories from other public accounts?

you coulnt, you have to be a subscriber

**Comment by recoverjp** [comment]
I really need it! I know it is possible because I already used another lib that allowed me to download stories from other public accounts.

**Comment by recoverjp** [comment]
> how can I get stories from other public accounts?

I found out! You first take the account by the username, and then send the id in an array to getStories

`$account = $instagram->getAccount($username);
$instagram->getStories([$account->getId()])`
