### ISSUE TITLE
Two Step Verification

### ISSUE THREAD

**Issue by alireza5014** [postaddictme/instagram-php-scraper#577]
how can i use two step verification ?

**Comment by emtized** [comment]
in login Proccess ?

**Comment by alireza5014** [comment]
yes

**Comment by fsjdg** [comment]
"$support_two_step_verification true works only in cli mode - just run login in cli mode - save cookie to file and use in any mode"

**Comment by alireza5014** [comment]
thanks

**Comment by recoverjp** [comment]
> "$support_two_step_verification true works only in cli mode - just run login in cli mode - save cookie to file and use in any mode"

But how can I reply with the code I received?
