### ISSUE TITLE
::getMediasByTag - ошибка при определении следующей страницы

### ISSUE THREAD

**Issue by harlam** [postaddictme/instagram-php-scraper#58]
Ошибка проявляется при поиске по тэгу. В случае если выдача занимает одну страницу - выводится количество записей = $count (::getMediasByTag).

Возможно дополнительная проверка корректно решит проблему (только начал разбираться, поэтому не уверен):

$maxId = $arr['tag']['media']['page_info']['end_cursor'];
**$hasNextPage = (empty($maxId)) ? false : $arr['tag']['media']['page_info']['has_next_page'];**

**Comment by raiym** [comment]
Не очень понял, что вы имеете ввиду. 
Обратите внимание на #59 (исправлено в v0.4.7)
Если это не решает ваших проблем, то пере-откройте этот запрос пожалуйста
