### ISSUE TITLE
Location ID and Name

### ISSUE THREAD

**Issue by chaibialaa** [postaddictme/instagram-php-scraper#582]
Hi,

I am scrapping 30 medias per user, and testing in over 100 accounts. All accounts with medias are having :
```
locationId: null
locationName: ""
```

While I manually checked a few medias online that contains location slugs.

Any known issues about this, or may be I'm not using the code as it needs to ?

**Comment by halper03** [comment]
Hi,
Yes locationid  locationame and  locationslug - empty...
Do you have can solve the problem?

**Comment by ig0r74** [comment]
Hi,
Same problem.

**Comment by kamyweb** [comment]
change query_hash parament inside Endoints::ACCOUNT_MEDIAS from 42323d64886122307be10013ad2dcc44 to e769aa130647d2354c40ea6a439bfc08
I don't know why....... but it works!

**Comment by ig0r74** [comment]
> change query_hash parament inside Endoints::ACCOUNT_MEDIAS from 42323d64886122307be10013ad2dcc44 to e769aa130647d2354c40ea6a439bfc08
> I don't know why....... but it works!

For me it works too, thanks!

**Comment by giefferre** [comment]
The extraction of query hash strictly depends on IG, in particular with the version of the JS build of the frontend app

https://github.com/postaddictme/instagram-php-scraper/pull/603#pullrequestreview-354451584
