### ISSUE TITLE
Login Error 

### ISSUE THREAD

**Issue by henzan02** [postaddictme/instagram-php-scraper#583]
Hi, I have installed phpfastcache, and its getting error. 

`Fatal error: Uncaught Error: Class 'InstagramScraper\CacheManager' not found in C:\xampp\htdocs\insta\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php:57 Stack trace: #0 C:\xampp\htdocs\insta\tes.php(18): InstagramScraper\Instagram::withCredentials('myusername', 'mypassword', Object(Phpfastcache\Helper\Psr16Adapter)) #1 {main} thrown in C:\xampp\htdocs\insta\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php on line 57`

here's my code : 

`
require __DIR__ . '/vendor/autoload.php';

use Phpfastcache\Config\ConfigurationOption;
use Phpfastcache\Helper\Psr16Adapter;
$sessionFolder = __DIR__ . DIRECTORY_SEPARATOR . 'sessions' . DIRECTORY_SEPARATOR;
        $defaultDriver = 'Files';
        $options = new ConfigurationOption([
            'path' => $sessionFolder
        ]);
        $instanceCache = new Psr16Adapter($defaultDriver, $options);

$instagram = \InstagramScraper\Instagram::withCredentials(''myusername', 'mypassword', $instanceCache);
$instagram->login(true);

$account = $instagram->getAccount('bmw');
`

Please help, thanks

**Comment by sector7gp** [comment]
this has changed, use this:

```
use Phpfastcache\Helper\Psr16Adapter;

$instagram = Instagram::withCredentials('username', 'password', new Psr16Adapter('Files'));
$instagram->login(); // will use cached session if you can force login $instagram->login(true)
$account = $instagram->getAccountById(3);
echo $account->getUsername();
```
