### ISSUE TITLE
Add more properties to Models 

### ISSUE THREAD

**Issue by jobay** [postaddictme/instagram-php-scraper#597]
There are some models that can grab more information than what they currently have.

Location.php
- blurb : string
- website : string
- phone : string
- address_code : object | AddressCode
- profile_pic_url : string
All these 5 fields have direct access from graphql -> location. address_code would be more interesting to apply a json_decode, so it could either be a new Model AddressCode or a StdObject. Interesting properties of this object:
- street_address : string
- zip_code : string
- city_name : string
- region_name : string
- country_name : string

Post.php
- tagged_users : Account[]
- accessibility_caption : string
Both, tagged_users (edge_media_to_tagged_user) and accessibility_caption have direct access from graphql -> shortcode_media

**Comment by raiym** [comment]
still issue
