### ISSUE TITLE
First unirest error then Login error

### ISSUE THREAD

**Issue by rmznkapar** [postaddictme/instagram-php-scraper#599]
$instagram = \InstagramScraper\Instagram::withCredentials('username', 'pssword', new Psr16Adapter('Files'));
$instagram->login(true); 
$account = $instagram->getAccountById(3);

( ! ) Fatal error: Uncaught InstagramScraper\Exception\InstagramException: Response code is 400. Body: message => useragent mismatch; status => fail; Something went wrong. Please report issue. in C:\wamp64\www\instawer\instawer\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php on line 865

**Comment by mega94** [comment]
I have the same problem too

**Comment by cnhappier** [comment]
I have the same problem, and I changed user agent, but it's still not working...
