### ISSUE TITLE
Get Video Link from when using getMediasByTag()

### ISSUE THREAD

**Issue by jetonr** [postaddictme/instagram-php-scraper#60]
Is it possible to get the video link without making another request for that media when searching for tags or location. Also I only get the user ID back but can't dispaly username or other info when using these two options! Any ideas ? Thanks

**Comment by raiym** [comment]
@jetonr 

no, you must to do another request to Instagram. 
no, because response contains only user id. No info about username and video url.

**Comment by raiym** [comment]
take a look at raw response: https://www.instagram.com/explore/tags/video/?__a=1
