### ISSUE TITLE
direct

### ISSUE THREAD

**Issue by amirpdlll** [postaddictme/instagram-php-scraper#601]
Thank you ,
Can we create a real time chat bot using this library ? for example when a new messages arrive our software we get notice and send a response ?

**Comment by raiym** [comment]
Direct messages not supported. it is possible to send and get messages. 

but to subscribe for new messages is not possible, so for making real time chat you would be required to poll all existing direct messages to check if there is new messages received. 

For one average account it is seems possible (e.g.: https://github.com/igdmapps/igdm) but making chat bot which potentially could process thousands of messages I believe it is not. Your IP will be blocked.

**Comment by raiym** [comment]
@amirpdlll maybe official API is your choice.

**Comment by amirpdlll** [comment]
> @amirpdlll maybe official API is your choice.

Is there official API to manage direct ??
