### ISSUE TITLE
Help Me!

### ISSUE THREAD

**Issue by mohammadrezajiji** [postaddictme/instagram-php-scraper#604]
<?php
require __DIR__ . '/../vendor/autoload.php';
use Phpfastcache\Helper\Psr16Adapter;
$instagram = \InstagramScraper\Instagram::withCredentials('*****', '****', new Psr16Adapter('Files'));
$instagram->login();

-------------------------
Log :
InstagramScraper\Exception\InstagramAuthException: User credentials are wrong. in /home/mohammadrezajiji/public_html/bot/insta/src/InstagramScraper/Instagram.php:1462
Stack trace:
#0 /home/mohammadrezajiji/public_html/bot/insta/examples/getStories.php(7): InstagramScraper\Instagram->login()
#1 {main}
  thrown in /home/mohammadrezajiji/public_html/bot/insta/src/InstagramScraper/Instagram.php on line 1462
User credentials are wrong !? why ?

**Comment by mohammadrezajiji** [comment]
require __DIR__ . '/../vendor/autoload.php';

use Phpfastcache\Helper\Psr16Adapter;

$instagram = \InstagramScraper\Instagram::withCredentials('*****', '********', new Psr16Adapter('Files'));
$instagram->login();

**Comment by sector7gp** [comment]
nice title...... :/

Unirest\Request::verifyPeer(false);

..... credentials are wrong... what else?

**Comment by mohammadrezajiji** [comment]
> nice title...... :/
> 
> Unirest\Request::verifyPeer(false);
> 
> ..... credentials are wrong... what else?

This Script Is Working ? Can use For all account
