### ISSUE TITLE
README.md not up to date -> code example do not work

### ISSUE THREAD

**Issue by Hazzeldorn** [postaddictme/instagram-php-scraper#609]
When unsing the latest versions of **instagram-php-scraper (0.9.4)** it is no longer possible to use the login with credentials like this:
```
$instagram = Instagram::withCredentials('username', 'password');
$instagram->login();
```
The first snippet does not work because a CacheInterface is required as a third parameter:

**Comment by m00nk** [comment]
Duplicate of #636
