### ISSUE TITLE
Could anybody help me with foreach issue?

### ISSUE THREAD

**Issue by LorenaGp** [postaddictme/instagram-php-scraper#61]
Hi! 

I've been trying to search medias by tag name:
$medias = Instagram::getMediasByTag('zara', 30);
echo json_encode($medias);

But I haven't been able to rescue the values from the json file. My code is
$medias = Instagram::getMediasByTag('zara', 30);
$array = json_encode($medias);
foreach($array as $insta){
$link=$insta['link'];
echo $link;
}
I also tried to use json_decode instead of encode, but it returns null. 
Could anybody help me out about this issue? I'm really stuck on it :(

**Comment by jetonr** [comment]
Try this: 

  ```php
  $medias = Instagram::getMediasByTag('zara', 30);
	$links = array();
	foreach( $medias as $media ){
		$links[] = $media->link;
	}
	var_dump($links);
```

**Comment by raiym** [comment]
@jetonr thank you
