### ISSUE TITLE
Unable to get public-email and public-phone-number of a business account

### ISSUE THREAD

**Issue by ChaudharyHabib** [postaddictme/instagram-php-scraper#612]
I had used this tool (https://pro.leadsoda.com/#/dashboard/home) to extract the details of the Instagram business account.  It shows me a lot of details with public email and number.

But with this library when I call this method $account->isBusinessAccount(), I get 1 but can't get email and number of this business account by using the following methods.
$account->getBusinessEmail()
$account->getBusinessPhoneNumber()

You can try some of these business accounts
cczapek
ali_raza.raza
i_4_ijaz
paulabphoto
kristietaulman

**Comment by abdulrahman156** [comment]
Any progress?

**Comment by ChaudharyHabib** [comment]
No, I had tried a lot but to no avail.

**Comment by jackdellis** [comment]
Also getting issues with this

**Comment by theflyingmantis** [comment]
I use the chrome extension ProfileBud (https://chrome.google.com/webstore/detail/profilebud-targeted-leads/geanmonfjnphmeighphheddlmdlcjkho) to get this data. Works for me.

I tried by these methods but no avail. Some instagram endpoints changed I guess
```
$account->getBusinessEmail()
$account->getBusinessPhoneNumber()
```
