### ISSUE TITLE
İnstagram app secret

### ISSUE THREAD

**Issue by Menawan** [postaddictme/instagram-php-scraper#614]
hey! How can ı use my instagram app secret in this library?

**Comment by retrowaver** [comment]
You can't - it doesn't use official API.

**Comment by Menawan** [comment]
I want to use official api and find some api s for that but ı take same errors everytime ,
https://stackoverflow.com/questions/60399021/error-type-oauthexception-code-400-error-message-invalid-redirect

Do you know how ı can hadle with this.
