### ISSUE TITLE
Uncaught InstagramScraper\Exception\InstagramException

### ISSUE THREAD

**Issue by bastluc** [postaddictme/instagram-php-scraper#616]
Hello everyone, I'm getting an error message using the library: 

`Fatal error
: Uncaught InstagramScraper\Exception\InstagramException: Response code is 200. Body: <!DOCTYPE html> <html lang="en" class="no-js not-logged-in client-root"> <head> <meta charset="utf-8"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <title> Login • Instagram </title> <meta name="robots" content="noimageindex, noarchive"> <meta name="apple-mobile-web-app-status-bar-style" content="default"> <meta name="mobile-web-app-capable" content="yes"> <meta name="theme-color" content="#ffffff"> <meta id="viewport" name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover"> <link rel="manifest" href="/data/manifest.json"> <link rel="preload" href="/static/bundles/es6/ConsumerUICommons.css/8a2eb3d0ea9f.css" as="style" type="text/css" crossorigin="anonymous" /> <link rel="preload" href="/static/bundles/es6/ConsumerAsyncCommons.css/cf7e3d965842.css" a in
/home/zxjixad/thomas-helye/wp-content/plugins/altitude-elementor-widgets/widgets/instagram/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php
on line
353`

The message appears when I put my site into production.

Thanks for your help

**Comment by rikless** [comment]
looks related to https://github.com/postaddictme/instagram-php-scraper/issues/632
