### ISSUE TITLE
Wrong followers count on getFollowers() function

### ISSUE THREAD

**Issue by Charmer** [postaddictme/instagram-php-scraper#618]
Hi! Thanks to all, who support this project. I found strange issue, when I try to get followers of public account. I successfully logged by fake instagram account I made for my script. Then i get followers count by call:

**$p = $instagram->getAccount($profile->url);
$total = $p->getFollowedByCount();**

After it $total = 529. But when i try to get list of followers, I get error **Failed to get followers of account id ******. The account is private**
But this account isn't private. I tried to debug getFollowers() function. First of all, I added 

**echo "Getting ".count($accounts)." entries...".PHP_EOL;**
to Instagram.php, line 1251. Here is out of it:

Getting 50 entries...
Getting 100 entries...
Getting 150 entries...
Getting 200 entries...
Getting 250 entries...
Getting 300 entries...
Getting 350 entries...
**Getting 398 entries...**
Getting 446 entries...
Getting 496 entries...

After that I dumped the answer to this request - and **$jsonResponse['data']['user']['edge_followed_by']['edges']** realy contents only 48 entries.
So, if I request only 527 followers by **getFollowers(527, 50, true);** it's work fine. But, getFollowersCount() shows, that account has 529 followers. Also, when I login by my fake account from browser, I can see all 529 followers and I successfully can list them all

**Comment by retrowaver** [comment]
Okay, so there are in fact 2 problems:
1. Why some followers aren't scraped.
2. Why an inadequate / unnecessary exception is thrown.

Can you post the Instagram username that this issue is related to?

Also, are you 100% sure on this: 

> Also, when I login by my fake account from browser, I can see all 529 followers and I successfully can list them all

?

**Comment by Charmer** [comment]
Made some tests on 4 accounts and discovered, that this happens only with one. With another 3 accounts function also not always returns $pageSize elemetns in one request, but don't throw any exceptions and return right count in the end of requests cicle.
Here is an answer, that throws exception:
```php
array:2 [
  "data" => array:1 [
    "user" => array:1 [
      "edge_followed_by" => array:3 [
        "count" => 533
        "page_info" => array:2 [
          "has_next_page" => true
          "end_cursor" => "QVFCVmZ3Tk5iMHFhWVpMN3lOS2lOTXl4Tk4zMWZaTGtBWG9obDZXY1NOdmVVdXpMQVZEanFQTk5PbHc4NkprM0hITURKd3ZaVlRPSDFtd0p3WlQtRXhVRQ=="
        ]
        "edges" => []
      ]
    ]
  ]
  "status" => "ok"
]
```

> Can you post the Instagram username that this issue is related to?
I don't want to post link to "broken" account in public. Is it possible to send it to email?

**Comment by retrowaver** [comment]
It looks like an another version of a different issue (https://github.com/postaddictme/instagram-php-scraper/issues/605#issuecomment-587467176).

I'll make a PR, but it would be nice to be able to test it on live account first.

> Is it possible to send it to email?

Sure, send me the username to `retrowaver.github@gmail.com`
