### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by wijas** [postaddictme/instagram-php-scraper#62]
Hi sir

How to installation this script?

Thanks

**Comment by jetonr** [comment]
use composer

**Comment by raiym** [comment]
@jetonr thanks again

**Comment by Mehran** [comment]
after installation what am i must doing ? 

```
:~# use InstagramScraper\Instagram;
bash: use: command not found
```

where i must use `use InstagramScraper\Instagram;`  ??
