### ISSUE TITLE
Two step verification does not work

### ISSUE THREAD

**Issue by koninka** [postaddictme/instagram-php-scraper#621]
There is no input with name `security_code` on the page.
So this code does not work
```
        if (!preg_match('/name="security_code"/', $response->raw_body, $matches)) {
            throw new InstagramAuthException('Something went wrong when try two step verification. Please report issue.', $response->code);
        }
```

**Comment by ItsYogSothoth** [comment]
When trying to use cli for console verification it throws this exception:
`Message with security code sent to: Email: *@******.***
PHP Fatal error:  Uncaught InstagramScraper\Exception\InstagramAuthException: Something went wrong when try two step verification. Please report issue. in /.../vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:1557
Stack trace:
#0 /.../vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php(1456): InstagramScraper\Instagram->verifyTwoStep(Object(Unirest\Response), Array, Object(InstagramScraper\TwoStepVerification\ConsoleVerification))
#1 /.../instagramTwoStepAuth.php(12): InstagramScraper\Instagram->login(false, Object(InstagramScraper\TwoStepVerification\ConsoleVerification))
`
The file I wrote to implement this functionality:
`<?php

require_once 'vendor/autoload.php';

use InstagramScraper\Instagram;
use chillerlan\SimpleCache\MemoryCache;

$username = 'username';
$password = 'password';

$instagram = Instagram::withCredentials($username, $password, new MemoryCache());
$instagram->login(false, true);
$instagram->saveSession();`

**Comment by ItsYogSothoth** [comment]
When trying to use cli for console verification it throws this exception:
```
Message with security code sent to: Email: *@******.***
PHP Fatal error:  Uncaught InstagramScraper\Exception\InstagramAuthException: Something went wrong when try two step verification. Please report issue. in /.../vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:1557
Stack trace:
#0 /.../vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php(1456): InstagramScraper\Instagram->verifyTwoStep(Object(Unirest\Response), Array, Object(InstagramScraper\TwoStepVerification\ConsoleVerification))
#1 /.../instagramTwoStepAuth.php(12): InstagramScraper\Instagram->login(false, Object(InstagramScraper\TwoStepVerification\ConsoleVerification))
#2 {main}
  thrown in /.../vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 1557

```
The file I wrote to implement this functionality:
```
<?php

require_once 'vendor/autoload.php';

use InstagramScraper\Instagram;
use chillerlan\SimpleCache\MemoryCache;

$username = 'username';
$password = 'password';

$instagram = Instagram::withCredentials($username, $password, new MemoryCache());
$instagram->login(false, true); // I had to manually tell the code to use TwoStepVerification even though I'm running from CLI
$instagram->saveSession();
```

**Comment by fonclub** [comment]
>  if (!preg_match('/name="security_code"/', $response->raw_body, $matches)) {
>             throw new InstagramAuthException('Something went wrong when try two step verification. Please report issue.', $response->code);
>         }

change to

`if (!preg_match('/"input_name":"security_code"/', $response->raw_body, $matches)) {
            throw new InstagramAuthException('Something went wrong when try two step verification. Please report issue.', $response->code);
        }`

it works for me!

**Comment by fonclub** [comment]
> There is no input with name `security_code` on the page.
> So this code does not work
> 
> ```
>         if (!preg_match('/name="security_code"/', $response->raw_body, $matches)) {
>             throw new InstagramAuthException('Something went wrong when try two step verification. Please report issue.', $response->code);
>         }
> ```

change to

```
if (!preg_match('/"input_name":"security_code"/', $response->raw_body, $matches)) {
            throw new InstagramAuthException('Something went wrong when try two step verification. Please report issue.', $response->code);
        }
```

it works for me!

**Comment by fonclub** [comment]
https://github.com/postaddictme/instagram-php-scraper/pull/626

**Comment by fmchan** [comment]
> > There is no input with name `security_code` on the page.
> > So this code does not work
> > ```
> >         if (!preg_match('/name="security_code"/', $response->raw_body, $matches)) {
> >             throw new InstagramAuthException('Something went wrong when try two step verification. Please report issue.', $response->code);
> >         }
> > ```
> 
> change to
> 
> ```
> if (!preg_match('/"input_name":"security_code"/', $response->raw_body, $matches)) {
>             throw new InstagramAuthException('Something went wrong when try two step verification. Please report issue.', $response->code);
>         }
> ```
> 
> it works for me!

I still have this problem even though I updated to the latest version

**Comment by fmchan** [comment]
> > > There is no input with name `security_code` on the page.
> > > So this code does not work
> > > ```
> > >         if (!preg_match('/name="security_code"/', $response->raw_body, $matches)) {
> > >             throw new InstagramAuthException('Something went wrong when try two step verification. Please report issue.', $response->code);
> > >         }
> > > ```
> > 
> > 
> > change to
> > ```
> > if (!preg_match('/"input_name":"security_code"/', $response->raw_body, $matches)) {
> >             throw new InstagramAuthException('Something went wrong when try two step verification. Please report issue.', $response->code);
> >         }
> > ```
> > 
> > 
> > it works for me!
> 
> I still have this problem even though I updated to the latest version

because Instagram says I attempted many logins

**Comment by APTEMOH** [comment]
> change to

это где изменить?
