### ISSUE TITLE
Not working in production, working locally though? 

### ISSUE THREAD

**Issue by bengrzybowski** [postaddictme/instagram-php-scraper#622]
I'm working on a feature to pull in most recent posts from an instagram account based on the username. The feature works great locally however displays the following error that claims the account doesn't exist? (the username is valid) The request is possibly being blocked by Instagram? Not sure... 

Any direction or help would be awesome. thanks. 

Fatal error
: Uncaught InstagramScraper\Exception\InstagramNotFoundException: Account with this username does not exist in /home4/bengrzybow/skinny.bgrzdesigns.com/wp-content/themes/understrap/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:353 Stack trace: #0 /home4/bengrzybow/skinny.bgrzdesigns.com/wp-content/themes/understrap/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php(328): InstagramScraper\Instagram->getAccount('skinnybuddhatat...') #1 /home4/bengrzybow/skinny.bgrzdesigns.com/wp-content/themes/understrap/front-page.php(144): InstagramScraper\Instagram->getMedias('skinnybuddhatat...') #2 /home4/bengrzybow/skinny.bgrzdesigns.com/wp-content/themes/understrap/front-page.php(165): instagram_content('skinnybuddhatat...') #3 /home4/bengrzybow/skinny.bgrzdesigns.com/wp-includes/template-loader.php(98): include('/home4/bengrzyb...') #4 /home4/bengrzybow/skinny.bgrzdesigns.com/wp-blog-header.php(19): require_once('/home4/bengrzyb...') #5 /home4/bengrzybow/skinny.bgrzdesigns.com/in in
/home4/bengrzybow/skinny.bgrzdesigns.com/wp-content/themes/understrap/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php
on line
353

**Comment by retrowaver** [comment]
Yes, the request could be blocked by Instagram (possibly by IP).

Also the incorrect exception type (`InstagramNotFoundException`) was a bug fixed in #592. Update to the latest version and you should see `InstagramException` with response code / body.

**Comment by nam-co** [comment]
Dows any body know what's the limit rate by instagram? and if its the same when we use the api with app id? thanks
