### ISSUE TITLE
Too few arguments

### ISSUE THREAD

**Issue by nam-co** [postaddictme/instagram-php-scraper#625]
Hi, Im getting this error: Too few arguments to function InstagramScraper\Instagram::withCredentials(), 2 passed in laravel, hope you can help me, I don't want to use a cache, thanks for your work on this

```

<?php
use InstagramScraper\Instagram;
$instagram = Instagram::withCredentials('xxxx@hotmail.com', 'xxxxx');
$instagram->login();
sleep(1);
$media = $instagram->getMedias($username, 40);

```

**Comment by Potrac** [comment]
Is there a specific reason you don't want to use cache?
In a non-elegant way, you could set `$cache = null` in `public static function withCredentials($username, $password, $cache = null)` (src/InstagramScraper/Instagram.php line 55) and then make an `if($instanceCache !== null)` condition everywhere the cache is used (lines 1433, 1487, 1596).

Again, it's just an unelegant hotfix.

**Comment by nam-co** [comment]
Hi potrac thanks for the response, is going to be for multiple users and the result will be saved on files, I’m going to try what you said

**Comment by Potrac** [comment]
No worries, let me know if it works. I've tested it and could use the scraper without the cache on my side.
