### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by hasandahsin** [postaddictme/instagram-php-scraper#63]
Here is the error.

"

> Uncaught exception 'Unirest\Exception' with message 'SSL certificate problem: unable to get local issuer certificate' in C:\xampp\htdocs\insta\vendor\mashape\unirest-php\src\Unirest\Request.php:476 Stack trace: #0 C:\xampp\htdocs\insta\vendor\mashape\unirest-php\src\Unirest\Request.php(236): Unirest\Request::send('GET', 'https://www.ins...', NULL, Array, NULL, NULL) #1 C:\xampp\htdocs\insta\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php(272): Unirest\Request::get('https://www.ins...') #2 C:\xampp\htdocs\insta\dene\index.php(7): InstagramScraper\Instagram::searchAccountsByUsername('theellenshow') #3 {main} thrown in C:\xampp\htdocs\insta\vendor\mashape\unirest-php\src\Unirest\Request.php on line 476

"

**Comment by raiym** [comment]
Could you provide steps to reproduce this issue? 
Thank you

**Comment by danielmarkavis** [comment]
I have just installed this package, and receive the same error.

It stops (for me) on

$medias = Instagram::getMedias('mikeescamilla', 10);

**Comment by danielmarkavis** [comment]
Adding

`Unirest\Request::verifyPeer(false);`

before 

`use InstagramScraper\Instagram;`

fixes this

**Comment by pinotarantino** [comment]
Hello, 
I tried the solution proposed by danielmarkavis , but after some good results with 'getMediasByTag', I get the following error message:
"Fatal error: Uncaught exception 'Unirest\Exception' with message 'Unknown SSL protocol error in connection to www.instagram.com:443 ' in C:\Users\Administrator\vendor\mashape\unirest-php\src\Unirest\Request.php on line 476"
Unirest\Exception: Unknown SSL protocol error in connection to www.instagram.com:443 in C:\Users\Administrator\vendor\mashape\unirest-php\src\Unirest\Request.php on line 476

**Comment by pinotarantino** [comment]
Add: the problem seems occur in sporadic way...just made another query and all is gone fine, without error message...thanks a lot for you attention...;)

**Comment by pinotarantino** [comment]
The problem is solved if I make a call from a Linux/Lamp server...problem persist only on Wamp environment
