### ISSUE TITLE
Fatal Error Uncaught ArgumentCountError: Too few arguments to function InstagramScraper\Instagram::withCredentials(), 2 passed in 

### ISSUE THREAD

**Issue by rucesocial** [postaddictme/instagram-php-scraper#630]
`Fatal error: Uncaught ArgumentCountError: Too few arguments to function InstagramScraper\Instagram::withCredentials(), 2 passed in D:\xampp\htdocs\scraper\instagram-php-scraper-master\instagram-php-scraper-master\examples\twoStepAutoVerification\loginWithEmailAutoCponfirm.php on line 9 and exactly 3 expected in D:\xampp\htdocs\scraper\instagram-php-scraper-master\instagram-php-scraper-master\src\InstagramScraper\Instagram.php:55 Stack trace: #0 D:\xampp\htdocs\scraper\instagram-php-scraper-master\instagram-php-scraper-master\examples\twoStepAutoVerification\loginWithEmailAutoCponfirm.php(9): InstagramScraper\Instagram::withCredentials('u', 'p') #1 {main} thrown in D:\xampp\htdocs\scraper\instagram-php-scraper-master\instagram-php-scraper-master\src\InstagramScraper\Instagram.php on line 55`

**Comment by colorless1** [comment]
plz provide more info the func obviously expected 3 args received 2

**Comment by ItsYogSothoth** [comment]
You didn't pass cache session to withCredentials function

**Comment by Potrac** [comment]
As mentioned in the README.md, you have to use the following code to login:
```php
use Phpfastcache\Helper\Psr16Adapter;

$instagram = \InstagramScraper\Instagram::withCredentials($username, $password, new Psr16Adapter('Files'));
$instagram->login();
$instagram->saveSession();
```
