### ISSUE TITLE
Instagram Login Error Can you help me ? |   Something went wrong. Please report issue. in

### ISSUE THREAD

**Issue by rucesocial** [postaddictme/instagram-php-scraper#633]
`Fatal error: Uncaught InstagramScraper\Exception\InstagramAuthException: Something went wrong. Please report issue. in D:\xampp\htdocs\scraper\instagram-php-scraper-master\instagram-php-scraper-master\src\InstagramScraper\Instagram.php:1474 Stack trace: #0 D:\xampp\htdocs\scraper\instagram-php-scraper-master\instagram-php-scraper-master\examples\getAccountFollowings.php(9): InstagramScraper\Instagram->login() #1 {main} thrown in D:\xampp\htdocs\scraper\instagram-php-scraper-master\instagram-php-scraper-master\src\InstagramScraper\Instagram.php on line 1474`

` $instagram = \InstagramScraper\Instagram::withCredentials('tankifaruksoft', 'tankifaruk1', new Psr16Adapter("Files"));

  $instagram->login();
  $instagram->saveSession();`

Thank you !

**Comment by korell** [comment]
Hello,
Same issue here (the exception thrown line 1474) with the same code as epicsocial.

The code is fully working on my local machine but the error is thrown when i run the code on a dist machine...

Any idea of the reason ?

**Comment by epicsocial** [comment]
> Hello,
> Same issue here (the exception thrown line 1474) with the same code as epicsocial.
> 
> The code is fully working on my local machine but the error is thrown when i run the code on a dist machine...
> The connection is OK because i received a security email from Instagram telling me that a new connection was detected in a new place (the dist machine location).
> 
> The response code is 400 (`$response->code`). Could it be an error with the CSRF token ?
> 
> It's maybe related to security of multiples connections on Instagram account.
> 
> Any idea of the reason ?

The problem persists. It seems to be related to the website's thread. How can I login with this IP?
Thank you
