### ISSUE TITLE
Перестал работать без авторизации

### ISSUE THREAD

**Issue by m00nk** [postaddictme/instagram-php-scraper#635]
Пытаюсь получить ленту без авторизации. Код:
```
$instagram = new \InstagramScraper\Instagram();
try{
	$models = $instagram->getMedias('здесь-существующий-аккаунт', 20);
} catch(\Exception $e){
	echo '<!-- INSTAGRAM '.$e->getMessage().' -->';
}
```
Ловлю эксепшен с куском HTML-страницы:
![Снимок экрана_2020-03-31_21-40-34](https://user-images.githubusercontent.com/516574/78063095-4f3f6780-7398-11ea-820f-6cf8d53023f1.png)

Началось недавно. Еще несколько дней назад работало отлично. Аккаунт, к которому обращаюсь точно паблик. Результаты запросов кэширую, количество запросов жестко ограничено - не более одного в 30 минут.

Как побороть?

**Comment by igorbelikov** [comment]
@m00nk получилось?

**Comment by m00nk** [comment]
Что получилось? Никаких же идей по решению проблемы не предложено. 

Если имеете в виду, заработало ли само, то ответ отрицательный - все так же в ответ приходит HTML-страница.

**Comment by igorbelikov** [comment]
@m00nk уточнял, возможно вы нашли какие-то пути обхода, сейчас заметил, что если искать по тегу без авторизации, то пишет, что страница не найдена, имеется ввиду просто введя в поиск в веб версии инстаграм

думаю, что так быть не должно и инстаграм исправит эту проблему

**Comment by m00nk** [comment]
@igorbelikov странность в том, что на двух других сайтах код, приведенный в первом посте, работает прекрасно. Но они расположены на другом сервере. Возможно инстаграм блокирует неавторизованные подключения с определенных IP.

**Comment by igorbelikov** [comment]
@m00nk принял, спасибо за уточнение про момент с разными адресами

**Comment by ebulku** [comment]
I think Instagram checks the IPs coming from datacentres, so I think the solution is to use a residential proxy. Anyway, haven't tried it yet.

**Comment by Alumunia** [comment]
hey did u find the solution?

**Comment by m00nk** [comment]
@Alumunia still not ((

**Comment by oleg46** [comment]
same problem
