### ISSUE TITLE
Useragent mismatch, can not login

### ISSUE THREAD

**Issue by IvanF** [postaddictme/instagram-php-scraper#637]
After running it respons:

`PHP Fatal error:  Uncaught InstagramScraper\Exception\InstagramException: Response code is 400. Body:  message => useragent mismatch; status => fail; Something went wrong. Please report issue. in vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:890
`

what I should do? Maybe I can replace name of UserAgent somewhere??

**Comment by brianbruno** [comment]
Same problem here!

**Comment by etudor** [comment]
The python that copied this library has the same issue 
https://github.com/realsirjoe/instagram-scraper/issues/82


To fix it you can replace the user agent in `'InstagramScraper\Instagram` line 46 to this 
```
Instagram 126.0.0.25.121 Android (23/6.0.1; 320dpi; 720x1280; samsung; SM-A310F; a3xelte; samsungexynos7580; en_GB; 110937453)
```

**Comment by vwebtech** [comment]
> Instagram 126.0.0.25.121 Android (23/6.0.1; 320dpi; 720x1280; samsung; SM-A310F; a3xelte; samsungexynos7580; en_GB; 110937453)

Worked Life Charm , But For 1 Time Only :D
i guess blocked ip or something
