### ISSUE TITLE
Handle new album post

### ISSUE THREAD

**Issue by fabianoroberto** [postaddictme/instagram-php-scraper#64]
After last update of instagram (more photos into one post), scraper fail during take post.
Eg. in https://www.instagram.com/acmilanlive/media/ the first item is a new album post, but type is video and scraper fail here:

```php
if ($instance->type === 'video') {
       if (isset($mediaArray['video_views'])) {
           $instance->videoViews = $mediaArray['video_views'];
        }
        $instance->videoLowResolutionUrl = $mediaArray['videos']['low_resolution']['url'];
        $instance->videoStandardResolutionUrl = $mediaArray['videos']['standard_resolution']['url'];
        $instance->videoLowBandwidthUrl = $mediaArray['videos']['low_bandwidth']['url'];
}
```

Someone know a valid solution/new url?

**Comment by fabianoroberto** [comment]
Same problem with official API

**Comment by raiym** [comment]
@fabianoroberto 
Thank you for PR.
Let's wait for some time, maybe Instagram will fix it soon

**Comment by superyarik** [comment]
how handle "carousel" types? if i get images of user, i see megias with types "carousel", but i can see only first image in album. Can you handle this moment in docs?

**Comment by fabianoroberto** [comment]
I see now there use a new type

`"type": "carousel",`

and related field:

`"carousel_media": []`

**Comment by karatemaccie** [comment]
I added a pull request #134 to implement this feature.
