### ISSUE TITLE
Can't retrieve medias by hashtag

### ISSUE THREAD

**Issue by codypl** [postaddictme/instagram-php-scraper#642]
When I try to get medias of an hashtag I get this error : 
`Fatal error: Uncaught InstagramScraper\Exception\InstagramNotFoundException: This tag does not exists or it has been hidden by Instagram in C:\...\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php on line 924`
Its append with every hashtag I try

**Comment by codypl** [comment]
Well I guess it was an Instagram problem. 
The error changed to `Code: 400 Response code is 400. Body: message => useragent mismatch; status => fail;`
And I solved it using this #545

**Comment by xx7Ahmed7xx** [comment]
@codypl  how did you solve it please?

**Comment by codypl** [comment]
@xx7Ahmed7xx I used the code of the pull request #545

**Comment by xx7Ahmed7xx** [comment]
@codypl i cannot really find any code there....

**Comment by codypl** [comment]
@xx7Ahmed7xx You have to look at the commited file : https://github.com/postaddictme/instagram-php-scraper/pull/545/commits/39e8565e8446fa2c66dbcdee8807aa03fca2bbda
