### ISSUE TITLE
Phpfastcache issue

### ISSUE THREAD

**Issue by zubairsultan786** [postaddictme/instagram-php-scraper#648]
Hi,

While using phpfastcache , error is occurring. {. Fatal error: Uncaught Error: Call to undefined method Phpfastcache\Helper\Psr16Adapter::getItem() in /home/xxxx/xxxx/xxxx/xxxx/xxxx/src/InstagramScraper/Instagram.php:1346 Stack trace: #0 }

Please help me
Thank you,

**Comment by zubairsultan786** [comment]
Any hope?

**Comment by zubairsultan786** [comment]
anyone who faced that issue ?

**Comment by pencilvania** [comment]
find this method line in Instagram.php
public static function withCredentials
and change to
  public static function withCredentials($username, $password)
    {
        if (static::$instanceCache == null) {
            static::$instanceCache = new Psr16Adapter('Files');
        }
        $instance = new self();
        $instance->sessionUsername = $username;
        $instance->sessionPassword = $password;
        return $instance;
    }
