### ISSUE TITLE
Making getFollowers getFollowing externally pagable

### ISSUE THREAD

**Issue by avifatal** [postaddictme/instagram-php-scraper#652]
Hi,

Fetching the following/followers is not pageable from the outside...
I made a small change in my local by returning and passing the $endCursor
`getFollowers($accountId, $count = 20, $pageSize = 20, $delayed = true, $endCursor = '')`
The return will look like that:

```
return [
   'has_next_page' => $paging['has_next_page'], 
   'next_page' => $paging['end_cursor'], 
   'accounts' => $accounts];
```
I know its ugly and not backward compatible.  [the point is that it is working](https://gist.github.com/avifatal/d6471e41248de5e120541c8b7aae1cf4).

can I pull request new methods `getPaginateFollowers` and  `getPaginateFollowing` and make the current methods reuse them?

Thanks

**Comment by raiym** [comment]
Hello, yes, it would be great addition 
Could you please check current implementation of paginated medias. For example keys of the associated array is camel cased.

**Comment by avifatal** [comment]
Sure. thanks for the fast answer.
