### ISSUE TITLE
LOGIN ERROR - Something went wrong. Please report issue. in 

### ISSUE THREAD

**Issue by rucesocial** [postaddictme/instagram-php-scraper#657]
-----------------------------------------------

PHP Fatal error:  Uncaught InstagramScraper\Exception\InstagramAuthException: Something went wrong. Please report issue. in /home/mytakipc/public_html/tanki/src/InstagramScraper/Instagram.php:1534
Stack trace:

#0 /home/mytakipc/public_html/tanki/examples/cek.php(18): InstagramScraper\Instagram->login()

It does not accept the IP address of my website.

How do I get a confirmation email and confirm?

Please help

-----------------------------------------------
![LoginError](https://i.resimyukle.xyz/aATKAA.jpg)

**Comment by schmoove** [comment]
+1

**Comment by vwebtech** [comment]
Yes logged functions work fine in localhost , but when its come to the server (linux)
its showing the errors something went wrong. and does not return any data.

**Comment by jaebak** [comment]
You can look at this to fix the issue

https://github.com/postaddictme/instagram-php-scraper/issues/637#issuecomment-609416235
