### ISSUE TITLE
getMediaCommentsById is not working

### ISSUE THREAD

**Issue by ximrx** [postaddictme/instagram-php-scraper#66]
$commentsr = Instagram::getMediaCommentsById('1219620268472776128', 100); is returning error in library.

Also if possible add pagination in getLocationMediasById

**Comment by raiym** [comment]
Works for me, do you still have this problem? 
"Also if possible add pagination in getLocationMediasById" please open issue about it

**Comment by ximrx** [comment]
The problem was fixed using 
'Unirest\Request::verifyPeer(false);' 
before 
'use InstagramScraper\Instagram;'

**Comment by raiym** [comment]
#120
