### ISSUE TITLE
getMedias by username does not work

### ISSUE THREAD

**Issue by opensource-master** [postaddictme/instagram-php-scraper#661]
Hi, getMedias by username does not work on one server but another server this is working good. Can you help me what is issue? Is this domain or ip address blocked by Instagram or this is server specific error?

**

> Response on not working server

** 
**HTTP/1.1 301 Moved Permanently**
Content-Type: text/html; charset=utf-8
Location: https://www.instagram.com/bold_themes/
Vary: Accept-Language, Cookie
Content-Language: en
Date: Sun, 03 May 2020 15:32:33 GMT
Strict-Transport-Security: max-age=31536000
Cache-Control: private, no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: Sat, 01 Jan 2000 00:00:00 GMT
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
x-aed: 15
Access-Control-Expose-Headers: X-IG-Set-WWW-Claim
Set-Cookie: rur=ASH; Domain=.instagram.com; HttpOnly; Path=/; Secure
Date: Sun, 03 May 2020 15:32:33 GMT
X-FB-TRIP-ID: 1679558926
Connection: keep-alive
Content-Length: 0

**HTTP/1.1 302 Found**
Content-Type: text/html; charset=utf-8
Location: https://www.instagram.com/accounts/login/
Vary: Accept-Language, Cookie
Content-Language: en
Date: Sun, 03 May 2020 15:32:33 GMT
Strict-Transport-Security: max-age=31536000
Cache-Control: private, no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: Sat, 01 Jan 2000 00:00:00 GMT
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
x-aed: 15
Access-Control-Expose-Headers: X-IG-Set-WWW-Claim
Set-Cookie: csrftoken=B4xVybsHO1xPHAiZyH92542UevPhrQZA; Domain=.instagram.com; expires=Sun, 02-May-2021 15:32:33 GMT; Max-Age=31449600; Path=/; Secure
Set-Cookie: rur=ASH; Domain=.instagram.com; HttpOnly; Path=/; Secure
Set-Cookie: mid=Xq7kEQABAAGuIxCiRUWuKoCnr1t9; Domain=.instagram.com; expires=Wed, 01-May-2030 15:32:33 GMT; Max-Age=315360000; Path=/; Secure
Date: Sun, 03 May 2020 15:32:33 GMT
X-FB-TRIP-ID: 1679558926
Connection: keep-alive
Content-Length: 0

**HTTP/1.1 200 OK**
Content-Type: application/json; charset=utf-8
ig-set-password-encryption-web-key-id: 131
ig-set-password-encryption-web-pub-key: 0df137ea1da8ddb32dc398395554602ca30a7251ba5e974ec31b325a3f9ac10e
ig-set-password-encryption-web-key-version: 6
Last-Modified: Sun, 03 May 2020 15:52:56 GMT
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Cache-Control: private, no-cache, no-store, must-revalidate
Vary: Accept-Language, Cookie
Content-Language: en
Date: Sun, 03 May 2020 15:52:56 GMT
Strict-Transport-Security: max-age=31536000
Pragma: no-cache
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
x-aed: 15
Access-Control-Expose-Headers: X-IG-Set-WWW-Claim
Set-Cookie: csrftoken=odYDS8SGKRJ6P4IAWusSslHiELCrE7EU; Domain=.instagram.com; expires=Sun, 02-May-2021 15:52:56 GMT; Max-Age=31449600; Path=/; Secure
Set-Cookie: mid=Xq7o2AABAAHZnPvd6UrN4f6AuT7F; Domain=.instagram.com; expires=Wed, 01-May-2030 15:52:56 GMT; Max-Age=315360000; Path=/; Secure
Date: Sun, 03 May 2020 15:52:56 GMT
X-FB-TRIP-ID: 1679558926
Connection: keep-alive
Content-Length: 127

**{"errors": {"error": ["Sorry, there was a problem with your request."]}, "status": "ok", "error_type": "generic_request_error"}"**

**

> Response on working server

** 
**HTTP/2 301** 
content-type: text/html; charset=utf-8
location: https://www.instagram.com/bold_themes/
vary: Accept-Language, Cookie
content-language: en
date: Sun, 03 May 2020 15:40:44 GMT
strict-transport-security: max-age=31536000
cache-control: private, no-cache, no-store, must-revalidate
pragma: no-cache
expires: Sat, 01 Jan 2000 00:00:00 GMT
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
x-xss-protection: 0
x-aed: 15
access-control-expose-headers: X-IG-Set-WWW-Claim
content-length: 0
date: Sun, 03 May 2020 15:40:44 GMT
x-fb-trip-id: 1679558926
date: Sun, 03 May 2020 15:40:44 GMT

**HTTP/2 200** 
content-type: text/html; charset=utf-8
vary: Cookie, Accept-Language, Accept-Encoding
content-language: en
date: Sun, 03 May 2020 15:40:44 GMT
content-encoding: gzip
strict-transport-security: max-age=31536000
cache-control: private, no-cache, no-store, must-revalidate
pragma: no-cache
expires: Sat, 01 Jan 2000 00:00:00 GMT
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
x-xss-protection: 0
x-aed: 15
access-control-expose-headers: X-IG-Set-WWW-Claim
set-cookie: csrftoken=HdyZpoSz5aSSA7lCFyukZuH1Uy7IZm8H; Domain=.instagram.com; expires=Sun, 02-May-2021 15:40:44 GMT; Max-Age=31449600; Path=/; Secure
set-cookie: mid=Xq7l_AABAAFVZZKp4cqA-qqKc8Xv; Domain=.instagram.com; expires=Wed, 01-May-2030 15:40:44 GMT; Max-Age=315360000; Path=/; Secure
set-cookie: urlgen="{\"198.71.235.44\": 26496}:1jVGjU:96cSXAt9D9YfxvfQEoZ8aN286N4"; Domain=.instagram.com; HttpOnly; Path=/; Secure
content-length: 20503
date: Sun, 03 May 2020 15:40:44 GMT
x-fb-trip-id: 1679558926
date: Sun, 03 May 2020 15:40:44 GMT

**Comment by juangrimm** [comment]
So, i have this issue too, but, when i start application local all works, but, in my server it doesn't work, i don't know why, and work hard here to fix this.

I'm trying use proxy server, change the request and other things, but until now, nothing :/

**Comment by boazpoolman** [comment]
Same issue here.

**Comment by leonardooleg** [comment]
Same issue here.

**Comment by jstrobel** [comment]
Yes seems that is a security issue like mentioned before. If the request comes from an ISP Instagram redirects you to a Login-Page which leads to the "username not found" error.
