### ISSUE TITLE
Deprecation of the Instagram Legacy API

### ISSUE THREAD

**Issue by KinaneD** [postaddictme/instagram-php-scraper#664]
Hello all, 

Last week there was an [update](https://www.instagram.com/developer/) from Instagram that they will be postponing the deprecation of the Legacy API until June 29 2020.

Will this library be affected by this deprecation? If so, to what extent?
Some endpoints I am personally interested in are:
* `Endpoints::ACCOUNT_PAGE`
* `Endpoints::ACCOUNT_JSON_INFO`
* `Endpoints::ACCOUNT_JSON_INFO_BY_ID`
* `Endpoints::ACCOUNT_MEDIAS`
* `Endpoints::MEDIA_JSON_INFO`

Looking forward to your reply,
Thank you.

**Comment by mattkaye** [comment]
This is a really good point. Does anyone using this library have an answer for this?

**Comment by alipolatkan** [comment]
Instagram is planning to change the Old api on June 29. The new one should be the graphql api currently used. And it shouldn't be a problem for this library to work.

**Comment by mattkaye** [comment]
I'm pretty confident that's not the case. If you look at the new API documentation, it makes no mention of any /graphql/ endpoints. Everything now requires an access token. graph.instagram.com is the only endpoint to query data, and ONLY for a user that has authorized your app:

https://graph.instagram.com/{user-id}?fields=id,username&access_token={access-token}

You're only non-authentication option will be scraping the DOM which is a brittle solution.
This library will stop working when the cutover happens. Too bad, this is a super easy library to use

**Comment by KinaneD** [comment]
Hello @mattkaye @alipolatkan,

The new API would be the Instagram Graph API which certainly require authentication. It is a subgraph of the larger Facebook Graph API.
I believe this will eventually come down to whether Instagram will introduce any changes to its public data policy. Which i doubt it would be the case since it defies the purpose of public and/or business accounts.

The question is whether the Graphql API is considered part of the Legacy API.

My opinion is that endpoints to retrieve public insights would still work but which ever endpoint uses authorization would most probably need to be adapted to use the new Graph API.

Would love to hear the opinion of contributors to this package.
Cheers!

**Comment by roninit72** [comment]
any update?
