### ISSUE TITLE
video_url is not returning with its value from getMediaByUrl method

### ISSUE THREAD

**Issue by btworld-tr** [postaddictme/instagram-php-scraper#667]
Hi everyone,

I guess, Instagram is changing some requests and responses.

Yesterday, while I am working with this scraper everything was fine and working.
But today it has got some problems about getMedia method(s).
When you wanted to request with getMediaByUrl for a video post or sidecar posts including videos, it returns like below;

_Response includes like that:_
**[video_url] => https://static.cdninstagram.com/rsrc.php/null.jpg**

I checked getMediaByUrl($mediaUrl) method and print the JSON response and it seems like that.
This problems have got only includes the video post or sidecar video posts.

I am working from localhost and not using with Instagram::withCredentials() instance.

Has anybody got this issue like that?
Best Regards

**Comment by zaivst** [comment]
I have the same problem

**Comment by btworld-tr** [comment]
@zaivst yes I saw your issue. I wrote my opinions under the your issue.
