### ISSUE TITLE
class Phpfastcache\Helper\Psr16Adapter' not found 

### ISSUE THREAD

**Issue by Roosteridk** [postaddictme/instagram-php-scraper#669]
Did anyone manage to get this working with PHP7? I keep getting Phpfastcache\\Helper\\Psr16Adapter' not found error.

**Comment by erfanmola** [comment]
Firstly you have to install Phpfastcache :
`composer require phpfastcache/phpfastcache`

next you just need to add the following code to your project : 
`use Phpfastcache\Helper\Psr16Adapter;`

**Comment by Roosteridk** [comment]
> Firstly you have to install Phpfastcache :
> `composer require phpfastcache/phpfastcache`
> 
> next you just need to add the following code to your project :
> `use Phpfastcache\Helper\Psr16Adapter;`

Hi, I have already done that.

**Comment by gianfolli** [comment]
Same problem here

**Comment by gianfolli** [comment]
> Same problem here
Solved by deleting everything and installing via composer again
