### ISSUE TITLE
getAccountById error

### ISSUE THREAD

**Issue by pinotarantino** [postaddictme/instagram-php-scraper#67]
Hello, 
if I use the following code (with that id, mine or others taken from 'owner id' values):

...$account = Instagram::getAccountById(193886659);
echo $account->username;
...
I get the following error:
 Fatal error: Uncaught exception 'InstagramScraper\Exception\InstagramNotFoundException' with message 'User with this id not found' in C:\Users\Administrator\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php on line 46

Thanks a lot, very interesting project!
P;)

**Comment by raiym** [comment]
Thank you. 
FYI it has been fixed.

**Comment by alvinwiguna** [comment]
it is still returning the same error after logging in on the latest version

**Comment by e-beach** [comment]
It raises an exception, but not the same one as when the issue was created:
```
Fatal error: Uncaught InstagramScraper\Exception\InstagramNotFoundException: User exists but library could not pull information about user in /Users/elliott/me/projects/instagram-php-scraper/src/InstagramScraper/Instagram.php:330
Stack trace:
#0 /Users/elliott/me/projects/instagram-php-scraper/index.php(14): InstagramScraper\Instagram->getAccountById(193886659)
#1 {main}
  thrown in /Users/elliott/me/projects/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 330
```
This is caused by 
```
$userArray['data']['user']['edge_owner_to_timeline_media']['edges']
```
being empty, so the problem is the data we are trying to scrape just isn't there.

Unless we come up with a different way of scraping the data, it looks impossible to resolve.
