### ISSUE TITLE
Getting error 400 Bad request 

### ISSUE THREAD

**Issue by hamzadiaz** [postaddictme/instagram-php-scraper#670]
It was working very well till later today I started to get this error:

`Fatal error: Uncaught InstagramScraper\Exception\InstagramAuthException: Response code is 400. Body: Bad request Something went wrong. Please report issue. in /home2/hamzadiaz/public_html/instagram/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:1664 Stack trace: #0 /home2/hamzadiaz/public_html/instagram/profile.php(26): InstagramScraper\Instagram->login() #1 {main} thrown in /home2/hamzadiaz/public_html/instagram/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 1664`

I tried using different Instagram account for login but getting same error. Here is what line 1664 **Instagram.php** of code has:

```
} elseif ((is_string($response->code) || is_numeric($response->code)) && is_string($response->body)) {
    throw new InstagramAuthException('Response code is ' . $response->code . '. Body: ' . $response->body . ' Something went wrong. Please report issue.', $response->code);
}
```
Can't figure out how to get it fixed, Maybe Instagram made some update?

Thanks in advance

**Comment by movAX13h** [comment]
I get the same ... since yesterday. I guess there was an update on the IG page somewhere.

**Comment by gianfolli** [comment]
I have exactly same problem here

**Comment by eldark** [comment]
Same problem. Nothing to add to the report.

**Comment by pgrimaud** [comment]
We need to find a way to generate enc_password form field value.

Got the same error on my scraper too : https://github.com/pgrimaud/instagram-user-feed/issues/65

I found this, which could help us : https://www.bountysource.com/issues/87593270-add-enc_password-header-for-requests-version

I'm actually working on it. If someone has good knowledge about crypto in JavaScript (AES), please contact me.

**Comment by hamzadiaz** [comment]
> We need to find a way to generate enc_password form field value.
> 
> Got the same error on my scraper too : [pgrimaud/instagram-user-feed#65](https://github.com/pgrimaud/instagram-user-feed/issues/65)
> 
> I found this, which could help us : https://www.bountysource.com/issues/87593270-add-enc_password-header-for-requests-version
> 
> I'm actually working on it. If someone has good knowledge about crypto in JavaScript (AES), please contact me.

Hello @pgrimaud could this work?
```
function encrypt($key, $data) {
    $encryptionKey = base64_decode($key);
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-gcm'));
    $encrypted = openssl_encrypt($data, 'aes-256-gcm', $encryptionKey, 0, $iv, $tag);
    return base64_encode($encrypted . '::' . $iv . '::' . $tag);
}


function decrypt($key, $data) {
    $encryptionKey = base64_decode($key);
    list($encryptedData, $iv, $tag) = explode('::', base64_decode($data), 3);
    return openssl_decrypt($encryptedData, 'aes-256-gcm', $encryptionKey, 0, $iv, $tag);
}

$encrypt = encrypt('key', 'test data');
$decrypt = decrypt('key', $encrypt);

echo $encrypt . ' : ' . $decrypt;
```

It is basically encryption and decryption of aes-256-gcm with php using openssl, but don't know if it can be integrated in the scrapper?

**Comment by pgrimaud** [comment]
Hi @hamzadiaz 

Yeah, I read lot of documentation about AES 256 GCM, but I can't find any public key available.

The data I could found are given into this page : https://www.instagram.com/data/shared_data/

```
"encryption": {
  "key_id": "87",
  "public_key": "8dd9aad29d9a614c338cff479f850d3ec57c525c33b3f702ab65e9e057fc087e",
  "version": "9"
}
```

Someone adapted JavaScript into Python here : https://github.com/instaloader/instaloader/issues/615#issuecomment-629435096
As you can see, new encryption seems a little bit more tricky than a simple AES encryption.

**Comment by pgrimaud** [comment]
I tried this shit : https://gist.github.com/pgrimaud/3d2b2f090a7121ba28509db646f3eecb

It has the same byte length as the JavaScript encryption script, but I doesn't work when I used it for login.



![](https://media.giphy.com/media/5KfM3QCeN1vvW/giphy.gif)

I'm gonna be crazy 🙂🔫

**Comment by ibnux** [comment]
i try to change variable password to enc_password

https://github.com/postaddictme/instagram-php-scraper/blob/6503db29f6bfbf36bbd281da88f73fda279033f5/src/InstagramScraper/Instagram.php#L1540-L1548

```
$headers = [
                'ig-set-password-encryption-web-key-id' => 33,
                'ig-set-password-encryption-web-pub-key' => '0d85544e7b7b43e0e4465d0a35690925cc7c53c04dc07a6fbffdb45be2718c52',
                'ig-set-password-encryption-web-key-version' => 10,
                'cookie' => $cookieString,
                'referer' => Endpoints::BASE_URL . '/',
                'x-csrftoken' => $csrfToken,
                'X-CSRFToken' => $csrfToken,
                'user-agent' => $this->getUserAgent(),
            ];
            $response = Request::post(Endpoints::LOGIN_URL, $headers,
                ['username' => $this->sessionUsername, 'enc_password' => $this->sessionPassword,'optIntoOneTap'=>false]);
```

but got respond like this

{"code":400,"raw_body":"{\"message\": \"checkpoint_required\", \"checkpoint_url\": \"\/challenge\/6242737647\/GMoK4dsqH9\/\", \"lock\": false, \"status\": \"fail\"}","body":{"message":"checkpoint_required","checkpoint_url":"\/challenge\/6242737647\/GMoK4dsqH9\/","lock":false,"status":"fail"}

using encoded password from browser login

and then confirmation show up
<img width="592" alt="Jepretan Layar 2020-05-17 pukul 19 10 30" src="https://user-images.githubusercontent.com/811955/82145073-6831a880-9872-11ea-8769-1d3958e8853a.png">

**Comment by Tom1380** [comment]
I'm having this same problem.

**Comment by pgrimaud** [comment]
I published a workaround on my scrapper. 
**It seems working for me**, some people could try it : https://github.com/pgrimaud/instagram-user-feed/commit/96ad4cf54d1ad331b337f325c73e664999a6d066 ?

Just clone my repository, edit this [file](https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/getProfileWithLogin.php) and run it.

If it will conclusive, I will open a PR on this repository.

Thanks for tests and feedback 😄

**Comment by hamzadiaz** [comment]
> I published a workaround on my scrapper.
> **It seems working for me**, some people could try it : [pgrimaud/instagram-user-feed@96ad4cf](https://github.com/pgrimaud/instagram-user-feed/commit/96ad4cf54d1ad331b337f325c73e664999a6d066) ?
> 
> Just clone my repository, edit this [file](https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/getProfileWithLogin.php) and run it.
> 
> If it will conclusive, I will open a PR on this repository.
> 
> Thanks for tests and feedback 😄

Thank you so much @pgrimaud!!!!! I changed Login() function of Instagram.php file to your approach and now I no longer get error 400 Bad Request:

```
 $headers = [
                'cookie' => $cookieString,
                'referer' => Endpoints::BASE_URL . '/',
                'x-csrftoken' => $csrfToken,
                'X-CSRFToken' => $csrfToken,
                'user-agent' => $this->getUserAgent(),
            ];
            $response = Request::post(Endpoints::LOGIN_URL, $headers,
                ['username' => $this->sessionUsername, 'enc_password' => '#PWD_INSTAGRAM_BROWSER:0:' . time() . ':' . $this->sessionPassword]);
```

**Comment by eldark** [comment]
> > I published a workaround on my scrapper.
> > **It seems working for me**, some people could try it : [pgrimaud/instagram-user-feed@96ad4cf](https://github.com/pgrimaud/instagram-user-feed/commit/96ad4cf54d1ad331b337f325c73e664999a6d066) ?
> > Just clone my repository, edit this [file](https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/getProfileWithLogin.php) and run it.
> > If it will conclusive, I will open a PR on this repository.
> > Thanks for tests and feedback 😄
> 
> Thank you so much @pgrimaud!!!!! I changed Login() function of Instagram.php file to your approach and now I no longer get error 400 Bad Request:
> 
> ```
>  $headers = [
>                 'cookie' => $cookieString,
>                 'referer' => Endpoints::BASE_URL . '/',
>                 'x-csrftoken' => $csrfToken,
>                 'X-CSRFToken' => $csrfToken,
>                 'user-agent' => $this->getUserAgent(),
>             ];
>             $response = Request::post(Endpoints::LOGIN_URL, $headers,
>                 ['username' => $this->sessionUsername, 'enc_password' => '#PWD_INSTAGRAM_BROWSER:0:' . time() . ':' . $this->sessionPassword]);
> ```

DId you do anything else besides editing that part? Because I still get errors.

**Comment by hamzadiaz** [comment]
> > > I published a workaround on my scrapper.
> > > **It seems working for me**, some people could try it : [pgrimaud/instagram-user-feed@96ad4cf](https://github.com/pgrimaud/instagram-user-feed/commit/96ad4cf54d1ad331b337f325c73e664999a6d066) ?
> > > Just clone my repository, edit this [file](https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/getProfileWithLogin.php) and run it.
> > > If it will conclusive, I will open a PR on this repository.
> > > Thanks for tests and feedback 😄
> > 
> > 
> > Thank you so much @pgrimaud!!!!! I changed Login() function of Instagram.php file to your approach and now I no longer get error 400 Bad Request:
> > ```
> >  $headers = [
> >                 'cookie' => $cookieString,
> >                 'referer' => Endpoints::BASE_URL . '/',
> >                 'x-csrftoken' => $csrfToken,
> >                 'X-CSRFToken' => $csrfToken,
> >                 'user-agent' => $this->getUserAgent(),
> >             ];
> >             $response = Request::post(Endpoints::LOGIN_URL, $headers,
> >                 ['username' => $this->sessionUsername, 'enc_password' => '#PWD_INSTAGRAM_BROWSER:0:' . time() . ':' . $this->sessionPassword]);
> > ```
> 
> DId you do anything else besides editing that part? Because I still get errors.

Just that part and this is how I log in:

```
$instagram = \InstagramScraper\Instagram::withCredentials('user', 'pass', new Psr16Adapter('Files'));
$instagram->login(); 
$instagram->saveSession(); 
```

**Comment by jangrewe** [comment]
I pulled the latest version, but unfortunately i still get an exception - it's for a 200 now, though...
```
<b>Fatal error</b>:  Uncaught InstagramScraper\Exception\InstagramException: Response code is 200. Body: 
&lt;!DOCTYPE html&gt;
&lt;html lang=&quot;en&quot; class=&quot;no-js logged-in client-root touch&quot;&gt;
    &lt;head&gt;
        &lt;meta charset=&quot;utf-8&quot;&gt;
        &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;

        &lt;title&gt;
Instagram
&lt;/title&gt;
[...]
in <b>[REDACTED]/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php</b> on line <b>385</b><br />
```

**Comment by jangrewe** [comment]
If i comment out the throw in line 385, it now works for me, too.

**Comment by eldark** [comment]
Strange. I tried everything suggested since the temporary fix, but no luck.

**Comment by ibnux** [comment]
> > I published a workaround on my scrapper.
> > **It seems working for me**, some people could try it : [pgrimaud/instagram-user-feed@96ad4cf](https://github.com/pgrimaud/instagram-user-feed/commit/96ad4cf54d1ad331b337f325c73e664999a6d066) ?
> > Just clone my repository, edit this [file](https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/getProfileWithLogin.php) and run it.
> > If it will conclusive, I will open a PR on this repository.
> > Thanks for tests and feedback 😄
> 
> Thank you so much @pgrimaud!!!!! I changed Login() function of Instagram.php file to your approach and now I no longer get error 400 Bad Request:
> 
> ```
>  $headers = [
>                 'cookie' => $cookieString,
>                 'referer' => Endpoints::BASE_URL . '/',
>                 'x-csrftoken' => $csrfToken,
>                 'X-CSRFToken' => $csrfToken,
>                 'user-agent' => $this->getUserAgent(),
>             ];
>             $response = Request::post(Endpoints::LOGIN_URL, $headers,
>                 ['username' => $this->sessionUsername, 'enc_password' => '#PWD_INSTAGRAM_BROWSER:0:' . time() . ':' . $this->sessionPassword]);
> ```

it works using this

But I need to create new account

Old account always ask confirmation everytime script running

**Comment by eldark** [comment]
Stupid question: do changes in the repository impact on Composer repositories?
I mean, I did a composer update. Did I get the fixed file?

**Comment by eldark** [comment]
Now I'm getting this error:
`PHP Fatal error:  Uncaught InstagramScraper\Exception\InstagramAuthException: Something went wrong. Please report issue. in D:\Work\Projects\apps\instagram-php-scraper\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php:1561
Stack trace:
#0 D:\Work\Projects\apps\instagram-php-scraper\getAccountMediasByUsername.php(146): InstagramScraper\Instagram->login()
#1 {main}
  thrown in D:\Work\Projects\apps\instagram-php-scraper\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php on line 1561`

**Comment by bocanhcam** [comment]
> I published a workaround on my scrapper.
> **It seems working for me**, some people could try it : [pgrimaud/instagram-user-feed@96ad4cf](https://github.com/pgrimaud/instagram-user-feed/commit/96ad4cf54d1ad331b337f325c73e664999a6d066) ?
> 
> Just clone my repository, edit this [file](https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/getProfileWithLogin.php) and run it.
> 
> If it will conclusive, I will open a PR on this repository.
> 
> Thanks for tests and feedback 😄

This is working now. But just prepare for future cause it's version 10 now.
Is there anyone good at nodejs can convert this one to PHP will be helpful cause I think it work

https://github.com/dilame/instagram-private-api/pull/1052/files#diff-aba9581ea6872bcf7c1aef75405c8783R77
```
public encryptPassword(password: string): { time: string, encrypted: string } {
    const randKey = crypto.randomBytes(32);
    const iv = crypto.randomBytes(12);
    const rsaEncrypted = crypto.publicEncrypt({
      key: Buffer.from(this.client.state.passwordEncryptionPubKey, 'base64').toString(),
      // @ts-ignore
      padding: crypto.constants.RSA_PKCS1_PADDING,
    }, randKey);
    const cipher = crypto.createCipheriv('aes-256-gcm', randKey, iv);
    const time = Math.floor(Date.now() / 1000).toString();
    cipher.setAAD(Buffer.from(time));
    const aesEncrypted = Buffer.concat([cipher.update(password, 'utf8'), cipher.final()]);
    const sizeBuffer = Buffer.alloc(2, 0);
    sizeBuffer.writeInt16LE(rsaEncrypted.byteLength, 0);
    const authTag = cipher.getAuthTag();
    return {
      time,
      encrypted: Buffer.concat([
        Buffer.from([1, this.client.state.passwordEncryptionKeyId]),
        iv,
        sizeBuffer,
        rsaEncrypted, authTag, aesEncrypted])
        .toString('base64'),
    };
  }
```

**Comment by ibnux** [comment]
Short solution is to create new account

i search on the internet to fix challenge, it need to Temporarily disable account,
i do this for old account, and maybe wait 3days or 1 week, before enabling again.

**Comment by movAX13h** [comment]
I think the fix above has worked only for 1 or 2 days. Even tried a new account but no luck. A failed login is not captured by an exception. Only calling one of the methods above raises the exception "Media with this code does not exist" because the response is a "not logged in page".

**Comment by eldark** [comment]
> for **checkpoint_required**
> i search on the internet to fix challenge, it need to Temporarily disable account,
> i do this for old account, and maybe wait 3days or 1 week, before enabling again.

Did this work?

**Comment by ibnux** [comment]
@eldark Nope, it doesnt work, 
today i activate my account, try to login, and get checkpoint_url again.

i think we need to scrape checkpoint_url too

**Comment by pgrimaud** [comment]
> i think we need to scrape checkpoint_url too

Sure, I will work on it this next week-end

**Comment by eldark** [comment]
I created #676 for that purpose. Please, do tell if you need help. And thanks for replying!

**Comment by aldrin431** [comment]
> @eldark Nope, it doesnt work,
> today i activate my account, try to login, and get checkpoint_url again.
> 
> i think we need to scrape checkpoint_url too

I followed your recommendation and it's fine for me.

Steps
1. Create a new email account
2. Create an Instagram account (never wrote a phone in my configuration)
3. Just I'm following 3 accounts
4. Try to login

**Comment by jangrewe** [comment]
Has anybody of you tried what i mentioned before, commenting out the throwing of the exception? It kinda looks like it doesn't make sense to have that there... and it's working perfectly fine for me since then, with the existing account.

**Comment by Te7a-Houdini** [comment]
am still getting same exception after pulling the latest package version.
and here's a debug from **$userArray**

would appreciate if someone can help

![Screenshot from 2020-06-02 12-28-27](https://user-images.githubusercontent.com/17250137/83515265-5dfbe500-a4d5-11ea-8388-ae6a156f1d1a.png)

**Comment by aldrin431** [comment]
> am still getting same exception after pulling the latest package version.
> and here's a debug from **$userArray**
> 
> am using **getAccount('some Instagram username')** without login
> 
> would appreciate if someone can help
> 
> ![Screenshot from 2020-06-02 12-28-27](https://user-images.githubusercontent.com/17250137/83515265-5dfbe500-a4d5-11ea-8388-ae6a156f1d1a.png)

Yesterday I had the same problem but with another code, I used getAccount of this scraper with login and it's working.

I think now we should make all request with login.

**Comment by Te7a-Houdini** [comment]
@aldrin431 not sure if it a login problem . as on my local machine i use it without login and it works but on dev & production server it doesn't work 

also there's #685 related to this

**Comment by eldark** [comment]
I believe it's a rate limiting problem. Instagram's rate limiting, that is.

**Comment by aldrin431** [comment]
> @aldrin431 not sure if it a login problem . as on my local machine i use it without login and it works but on dev & production server it doesn't work
> 
> also there's #685 related to this

Yes I have the same problem, when I work in my localhost I work without login and in production I make the login.

**Comment by zaden1** [comment]
I have been getting the 200 error as well. I tried to comment out line 385 and I even though I no longer get the error I also can not access any images. This is what I get on sentry

Response code is 200. Body: <!DOCTYPE html>
<html lang="en" class="no-js not-logged-in client-root touch">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title>
Login • Instagram
</title>

        
        <meta name="robots" content="noimageindex, noarchive">
        <meta name="apple-mobile-web-app-status-bar-style" content="default">
        <meta name="mobile-web-app-capable" content="yes">
        <meta name="theme-color" content="#ffffff">
        <meta id="viewport" name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover">
        <link rel="manifest" href="/data/manifest.json">

        <link rel="preload" href="/static/bundles/es6/ConsumerUICommons.css/f642bd753a44.css" as="style" type="text/css" crossorigin="anonymous" />
<link rel="preload" href="/static/bundles/es6/ConsumerAsyncCommons.css/638f1bd337c8.css" as="style" type="text/css" crossorigin="anonymous" />
<li {clipped}

**Comment by asolopovas** [comment]
+1

**Comment by gutosan** [comment]
+1

**Comment by filippodicostanzo** [comment]
+1

**Comment by roninit72** [comment]
+1

**Comment by pckz** [comment]
same for me.
please someone say something :/

**Comment by hamzadiaz** [comment]
If you get these errors try using a new Instagram account and login with:
$instagram->login(true);
$instagram->saveSession();

**Comment by Mehrdad-Dadkhah** [comment]
+1

**Comment by ibnux** [comment]
i found a solution,
i change User Agent to another, and it works

https://github.com/postaddictme/instagram-php-scraper/blob/c9df4728c2b8a38e46bedea0c458bb6d9073f1f5/src/InstagramScraper/Instagram.php#L50

i change to
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:77.0) Gecko/20100101 Firefox/77.0`

**Comment by jangrewe** [comment]
@ibnux: Read the docs, there's a better way to do this.
```
$instagram->setUserAgent($userAgent);
```
I thought it was kinda well-known by now that you have to set the user-agent string to whatever string is used by the client you use to register/login/unblock logins/etc. when you do it manually. ;-)

**Comment by ibnux** [comment]
@jangrewe  hehe sorry i never thought UA not to important, after getting this error again, i try to change it, and it works,

just debugging thing, sometimes try to hardcode 😅 

thanks for mention the function 😃
