### ISSUE TITLE
2 Factor Verification

### ISSUE THREAD

**Issue by Roosteridk** [postaddictme/instagram-php-scraper#671]
Is it possible to do 2 factor verification with SMS?
There only seems to be email.

**Comment by MadRac** [comment]
**sonata-project/google-authenticator**

`<?php

namespace App;

use InstagramScraper\TwoStepVerification\TwoStepVerificationInterface;
use Sonata\GoogleAuthenticator\GoogleAuthenticator;

class Google2FAVerification implements TwoStepVerificationInterface
{
    private string $secret;

    public function __construct(string $secret = '')
    {
        $this->secret = $secret;
    }

    public function getVerificationType(array $possible_values)
    {
        return [];
    }

    public function getSecurityCode()
    {
        return (new GoogleAuthenticator())->getCode($this->secret);
    }
}`
example $secret = ' AAAA  AAAA  AAAA  AAAA  AAAA  AAAA  AAAA  AAAA'
