### ISSUE TITLE
getMediaByUrl() and getMediaByCode() not working

### ISSUE THREAD

**Issue by zaivst** [postaddictme/instagram-php-scraper#677]
It seems that getMediaByUrl() and getMediaByCode() not working now.

I see [InstagramScraper\Exception\InstagramException] Media with this code does not exist (500) error for both functions

**Comment by fonclub** [comment]
Same error..

**Comment by artursantos-fba** [comment]
Same! Sometimes it works, sometimes it doesn't...

**Comment by jordipolo87** [comment]
Same error, I think that it's related with the IP that made the call but not sure yet.

**Comment by btworld-tr** [comment]
Maybe it is related with ip but I saw some new is generated media codes like that https://www.instagram.com/p/Bqj2ER_lsaqx8hNTQ8xa3FjmpPNyGReGKhSF7E0
I think, they are making test for some regions or IPs. This urls are not for all post media at now but it seems it will be at the future. 
Other hand, cdninstagram.com can have some DNS problems. When i requested this domain I got 500 status code error on browser.

**Comment by kctrud** [comment]
Same error...

**Comment by congkv** [comment]
Instagram no longer allows people without an account to view posts. You need to login .

**Comment by zaivst** [comment]
Seems they soon will not allows to use instagram with login too )))

**Comment by sergshyn** [comment]
The same problem, I experienced with a redirect to a login page  https://www.instagram.com/accounts/login/?next=/p/CAc_aEAFO1v/%3F__a%3D1

**Comment by movAX13h** [comment]
@congkv Not sure if that's true ... I can still load public accounts and posts in the browser without being logged-in. https://www.instagram.com/redbull/

**Comment by juangrimm** [comment]
the same problem here, but the curious is that in my local, all work, the response is OK, and have all data that i need, but when i put this in my Digital Ocean server, with the same configs, doesn't work.

**Comment by juangrimm** [comment]
> Same error, I think that it's related with the IP that made the call but not sure yet.

I think it's not true dude, because i'm using proxy here, and nothing works, thought.

**Comment by hrmoh** [comment]
I'm getting some kind of 404 errors for a code working previously. I've checked with sample intagram posts mentioned here (getting errors) and I updated instagram-php-scraper to the latest version (v0.9.10) and the error persists. 

This is my exception (my app path is replaced by [MyAppPath]):

Fatal error: Uncaught exception 'InstagramScraper\Exception\InstagramException' with message 'Media with this code does not exist' in [MyAppPath]/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:590 Stack trace: #0 [MyAppPath]/index.php(125): InstagramScraper\Instagram->getMediaByUrl('https://www.ins...') #1 {main} thrown in [MyAppPath]//vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 590

and this is the code I'm using (no user is logged on):

require __DIR__ . '/vendor/autoload.php';
                $instagram = new \InstagramScraper\Instagram();
                $media = $instagram->getMediaByUrl($instagram_url);
                $img = $media->getImageHighResolutionUrl();
                $relText = $media->getCaption();

**Comment by congkv** [comment]
> @congkv Not sure if that's true ... I can still load public accounts and posts in the browser without being logged-in. https://www.instagram.com/redbull/ and https://www.instagram.com/p/B0YKatOontz/
> Only navigation via click requires login.



> @congkv Not sure if that's true ... I can still load public accounts and posts in the browser without being logged-in. https://www.instagram.com/redbull/ and https://www.instagram.com/p/B0YKatOontz/
> Only navigation via click requires login.

Actually Instagram don't implement it for all. It depends on the region. I tried with proxy Japan, I got results like yours.

**Comment by nteath** [comment]
I am facing the same issue as well. When I visit a public account from browser I have no problem viewing its content, eg: https://www.instagram.com/p/CAf2RyvpsHG/ . When using the library I get an error 'Media with this code does not exist (500)'. 

I tried using raw curl and instagram responds with 302 Redirect to login page. I don't know if instagram does an IP detection or agent but it seems like it is blocking bots. 
I don't know if it's relevant but I am using Digital Ocean as well.

**Comment by psegovias** [comment]
Just to you know, i have the same issue, but now i try in my local PC and works like a charms, maybe is time to use Proxy?

**Comment by jordipolo87** [comment]
> Just to you know, i have the same issue, but now i try in my local PC and works like a charms, maybe is time to use Proxy?
> 
> Anyone know how to use it?

No, as @congkv says, it seems that depends on the region or other aspects like the IP, the number of people that have logged in from this IP or something like this. We are currently using a pool of around 30 proxies and we are experiencing the same issues.

You have an example of how to use a proxy in the repository readme.md

**Comment by psegovias** [comment]
> > Just to you know, i have the same issue, but now i try in my local PC and works like a charms, maybe is time to use Proxy?
> > Anyone know how to use it?
> 
> No, as @congkv says, it seems that depends on the region or other aspects like the IP, the number of people that have logged in from this IP or something like this. We are currently using a pool of around 30 proxies and we are experiencing the same issues.
> 
> You have an example of how to use a proxy in the repository readme.md

Are u using residential proxy?

**Comment by sergshyn** [comment]
> > > Just to you know, i have the same issue, but now i try in my local PC and works like a charms, maybe is time to use Proxy?
> > > Anyone know how to use it?
> > 
> > 
> > No, as @congkv says, it seems that depends on the region or other aspects like the IP, the number of people that have logged in from this IP or something like this. We are currently using a pool of around 30 proxies and we are experiencing the same issues.
> > You have an example of how to use a proxy in the repository readme.md
> 
> Are u using residential proxy?
It works good with residential proxies, but it is not cheap. Looks like IG bans the most popular hosting IPs.

**Comment by jordipolo87** [comment]
After some tests with different residential proxy providers and with some of our own proxy servers I observed that the 500 error is only returned from some countries. I don't know if the restrictions are only deployed in some countries for some reason or the deploy is still pending.
For example, the restrictions are applied in USA and France but not in Canada and Italy.

**Comment by ActiveNothing** [comment]
#693 Use this to fix this problem after login.

**Comment by ActiveNothing** [comment]
#694 Use this PR to fix this problem after logging in.
