### ISSUE TITLE
Top media in tags

### ISSUE THREAD

**Issue by alex051186** [postaddictme/instagram-php-scraper#68]
Hi @raiym,
First, thank you for your library, that is awesome and helpfull, i love it.

Please tell me how get top result in function: getPaginateMediasByTag ??

**Comment by raiym** [comment]
@alex051186 hello. Thank you.

I think you should use this function to get top posts by tag: `Instagram::getTopMediasByTagName()`

There is no pagination since instagram returns only ~8 (?) images or videos

**Comment by alex051186** [comment]
Thank you for you reply, now the instargram not reponse any json any api function, please check

**Comment by raiym** [comment]
@alex051186 yes. 
Please refer to: #70
