### ISSUE TITLE
Can we get also Stories from specific user, like their medias?

### ISSUE THREAD

**Issue by nicolass2002** [postaddictme/instagram-php-scraper#681]
Hi,
Is it possible to get also stories for some user or only for logged in user?

**Comment by Const1** [comment]
Hi,
Yes you can, try this
`$account = $instagram->getAccount($username);`
`$stories = $instagram->getStories($account->getId())[0]->getStories();`

**Comment by nicolass2002** [comment]
It looks that work, tnx Const1
