### ISSUE TITLE
olm senin taşşaayı yesinler raiym nası bi kral adamsın

### ISSUE THREAD

**Issue by apexible** [postaddictme/instagram-php-scraper#683]
ne güzel kütüphane yapmışsın gardaşım benim be. angaraya gel sana ulusta döner yediricem lan karetta karetta kaplumbaası seni.

**Comment by berkayoztunc** [comment]
Ağam ne güzel yazmışsın ama`withCredentials` metodu için `Psr16Adapter` kütüphanesi lazım, onu kurmak lazım.

`composer require phpfastcache/phpfastcache`

Yoksam loginli istekler çalıştırmak zor

**Comment by apexible** [comment]
> Ağam ne güzel yazmışsın ama`withCredentials` metodu için `Psr16Adapter` kütüphanesi lazım, onu kurmak lazım.
> 
> `composer require phpfastcache/phpfastcache`
> 
> Yoksam loginli istekler çalıştırmak zor

kaçar mı sence aga? tabikisi de yaptım. zehir gibi akıyo maşallah.

**Comment by alipolatkan** [comment]
Şu an tüm projelerde bu kütüphaneyi ve instagram https://www.instagram.com/{username}/?__a=1 isteklerini kullanamıyorum. Herhangi bir çözüm bulan var mı? Genel bir güncelleme mi yapılmış acaba?

**Comment by rucesocial** [comment]
> Şu an tüm projelerde bu kütüphaneyi ve instagram [https://www.instagram.com/{username}/?__a=1](https://www.instagram.com/%7Busername%7D/?__a=1) isteklerini kullanamıyorum. Herhangi bir çözüm bulan var mı? Genel bir güncelleme mi yapılmış acaba?

Aynen takipteyim.

Bu arada bir çok hata almaktayım yardımcı olmak isteyen varsa olabilir 🌝

**Comment by apexible** [comment]
> Şu an tüm projelerde bu kütüphaneyi ve instagram [https://www.instagram.com/{username}/?__a=1](https://www.instagram.com/%7Busername%7D/?__a=1) isteklerini kullanamıyorum. Herhangi bir çözüm bulan var mı? Genel bir güncelleme mi yapılmış acaba?



> > Şu an tüm projelerde bu kütüphaneyi ve instagram [https://www.instagram.com/{username}/?__a=1](https://www.instagram.com/%7Busername%7D/?__a=1) isteklerini kullanamıyorum. Herhangi bir çözüm bulan var mı? Genel bir güncelleme mi yapılmış acaba?
> 
> Aynen takipteyim.
> 
> Bu arada bir çok hata almaktayım yardımcı olmak isteyen varsa olabilir 🌝




beyler:
https://www.instagram.com/{username}/?__a=1  bunu kullanmanız için giriş yapmanız gerekmiyor mu acaba instagrama?

**Comment by alipolatkan** [comment]
> > Şu an tüm projelerde bu kütüphaneyi ve instagram [https://www.instagram.com/{username}/?__a=1](https://www.instagram.com/%7Busername%7D/?__a=1) isteklerini kullanamıyorum. Herhangi bir çözüm bulan var mı? Genel bir güncelleme mi yapılmış acaba?
> 
> > > Şu an tüm projelerde bu kütüphaneyi ve instagram [https://www.instagram.com/{username}/?__a=1](https://www.instagram.com/%7Busername%7D/?__a=1) isteklerini kullanamıyorum. Herhangi bir çözüm bulan var mı? Genel bir güncelleme mi yapılmış acaba?
> > 
> > 
> > Aynen takipteyim.
> > Bu arada bir çok hata almaktayım yardımcı olmak isteyen varsa olabilir 🌝
> 
> beyler:
> [https://www.instagram.com/{username}/?__a=1](https://www.instagram.com/%7Busername%7D/?__a=1) bunu kullanmanız için giriş yapmanız gerekmiyor mu acaba instagrama?

Haziran ayından önce gerekmiyordu fakat Instagram'ın 2018'den haberini verdiği 29 Haziran 2020 Graph apisine geçişi için işlemlere erken başlandı sanırım. Projelerimde Instagram Graph Apisini kullanmaya başladım. Bu kütüphane [https://www.instagram.com/{username}/?__a=1] gibi url request istekleri ile dönen json verilerini işleyerek çalışıyordu ama artık login olmadan bu bilgilere erişim kapatıldı.

**Comment by apexible** [comment]
> > > Şu an tüm projelerde bu kütüphaneyi ve instagram [https://www.instagram.com/{username}/?__a=1](https://www.instagram.com/%7Busername%7D/?__a=1) isteklerini kullanamıyorum. Herhangi bir çözüm bulan var mı? Genel bir güncelleme mi yapılmış acaba?
> > 
> > 
> > > > Şu an tüm projelerde bu kütüphaneyi ve instagram [https://www.instagram.com/{username}/?__a=1](https://www.instagram.com/%7Busername%7D/?__a=1) isteklerini kullanamıyorum. Herhangi bir çözüm bulan var mı? Genel bir güncelleme mi yapılmış acaba?
> > > 
> > > 
> > > Aynen takipteyim.
> > > Bu arada bir çok hata almaktayım yardımcı olmak isteyen varsa olabilir 🌝
> > 
> > 
> > beyler:
> > [https://www.instagram.com/{username}/?__a=1](https://www.instagram.com/%7Busername%7D/?__a=1) bunu kullanmanız için giriş yapmanız gerekmiyor mu acaba instagrama?
> 
> Haziran ayından önce gerekmiyordu fakat Instagram'ın 2018'den haberini verdiği 29 Haziran 2020 Graph apisine geçişi için işlemlere erken başlandı sanırım. Projelerimde Instagram Graph Apisini kullanmaya başladım. Bu kütüphane [https://www.instagram.com/{username}/?__a=1] gibi url request istekleri ile dönen json verilerini işleyerek çalışıyordu ama artık login olmadan bu bilgilere erişim kapatıldı.






bende onu diyorum işte bu kütüphane login olabiliyor. neden bu kütüphanenin loginini kullanmıyorsunuz?

**Comment by alipolatkan** [comment]
> > > > Şu an tüm projelerde bu kütüphaneyi ve instagram [https://www.instagram.com/{username}/?__a=1](https://www.instagram.com/%7Busername%7D/?__a=1) isteklerini kullanamıyorum. Herhangi bir çözüm bulan var mı? Genel bir güncelleme mi yapılmış acaba?
> > > 
> > > 
> > > > > Şu an tüm projelerde bu kütüphaneyi ve instagram [https://www.instagram.com/{username}/?__a=1](https://www.instagram.com/%7Busername%7D/?__a=1) isteklerini kullanamıyorum. Herhangi bir çözüm bulan var mı? Genel bir güncelleme mi yapılmış acaba?
> > > > 
> > > > 
> > > > Aynen takipteyim.
> > > > Bu arada bir çok hata almaktayım yardımcı olmak isteyen varsa olabilir full_moon_with_face
> > > 
> > > 
> > > beyler:
> > > [https://www.instagram.com/{username}/?__a=1](https://www.instagram.com/%7Busername%7D/?__a=1) bunu kullanmanız için giriş yapmanız gerekmiyor mu acaba instagrama?
> > 
> > 
> > Haziran ayından önce gerekmiyordu fakat Instagram'ın 2018'den haberini verdiği 29 Haziran 2020 Graph apisine geçişi için işlemlere erken başlandı sanırım. Projelerimde Instagram Graph Apisini kullanmaya başladım. Bu kütüphane [https://www.instagram.com/{username}/?__a=1] gibi url request istekleri ile dönen json verilerini işleyerek çalışıyordu ama artık login olmadan bu bilgilere erişim kapatıldı.
> 
> bende onu diyorum işte bu kütüphane login olabiliyor. neden bu kütüphanenin loginini kullanmıyorsunuz?

Benim projemde picuki.com veya gramho.com gibi public bir erişim söz konusu o yüzden login işlemini kullanamam yada şöyle düşünün kendi web sitenizde instagram postlarınızı göstermek istiyorsunuz bunun için ziyaretçiden giriş yapmasını bekleyemezsiniz. Bunun gibi unofficial apiler bu tarz değişiklikler için sürekli güncellenmeli ama instagram'ın son hamlesi kendi graph apisini mecbur kılacak gibi

**Comment by apexible** [comment]
> > > > > Şu an tüm projelerde bu kütüphaneyi ve instagram [https://www.instagram.com/{username}/?__a=1](https://www.instagram.com/%7Busername%7D/?__a=1) isteklerini kullanamıyorum. Herhangi bir çözüm bulan var mı? Genel bir güncelleme mi yapılmış acaba?
> > > > 
> > > > 
> > > > > > Şu an tüm projelerde bu kütüphaneyi ve instagram [https://www.instagram.com/{username}/?__a=1](https://www.instagram.com/%7Busername%7D/?__a=1) isteklerini kullanamıyorum. Herhangi bir çözüm bulan var mı? Genel bir güncelleme mi yapılmış acaba?
> > > > > 
> > > > > 
> > > > > Aynen takipteyim.
> > > > > Bu arada bir çok hata almaktayım yardımcı olmak isteyen varsa olabilir full_moon_with_face
> > > > 
> > > > 
> > > > beyler:
> > > > [https://www.instagram.com/{username}/?__a=1](https://www.instagram.com/%7Busername%7D/?__a=1) bunu kullanmanız için giriş yapmanız gerekmiyor mu acaba instagrama?
> > > 
> > > 
> > > Haziran ayından önce gerekmiyordu fakat Instagram'ın 2018'den haberini verdiği 29 Haziran 2020 Graph apisine geçişi için işlemlere erken başlandı sanırım. Projelerimde Instagram Graph Apisini kullanmaya başladım. Bu kütüphane [https://www.instagram.com/{username}/?__a=1] gibi url request istekleri ile dönen json verilerini işleyerek çalışıyordu ama artık login olmadan bu bilgilere erişim kapatıldı.
> > 
> > 
> > bende onu diyorum işte bu kütüphane login olabiliyor. neden bu kütüphanenin loginini kullanmıyorsunuz?
> 
> Benim projemde picuki.com veya gramho.com gibi public bir erişim söz konusu o yüzden login işlemini kullanamam yada şöyle düşünün kendi web sitenizde instagram postlarınızı göstermek istiyorsunuz bunun için ziyaretçiden giriş yapmasını bekleyemezsiniz. Bunun gibi unofficial apiler bu tarz değişiklikler için sürekli güncellenmeli ama instagram'ın son hamlesi kendi graph apisini mecbur kılacak gibi


anladım sanırım ama benim anlatmak istediğim insanlara public olarak bu kütüphaneyle instagram bilgilerini istemeden yine istedikleri bilgileri sıunabilirsiniz. ben şuan öyle yapıyorum. onlardan hiçbir instagram bilgilerini almadan istedikleri postun veya hesabın (gizli olmayan) bilgilerini sunabiliyorum.
