### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by abubakar-iqbal** [postaddictme/instagram-php-scraper#687]
Hi,
I hope you doing great, I just deployed my code to live site, and once I request it's throwing the following error.
`Response code is 200. Body: <!DOCTYPE html> <html lang="en" class="no-js not-logged-in client-root"> <head> <meta charset="utf-8"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <title> Login • Instagram </title> <meta name="robots" content="noimageindex, noarchive"> <meta name="apple-mobile-web-app-status-bar-style" content="default"> <meta name="mobile-web-app-capable" content="yes"> <meta name="theme-color" content="#ffffff"> <meta id="viewport" name="viewport"  </script> </body> </html> Something went wrong. Please report issue.`

**Comment by kirilkirkov** [comment]
@abubakar-iqbal  Did you solve it ?

**Comment by impozzible** [comment]
Same Error here

**Comment by filippodicostanzo** [comment]
Same error with new instagram account

**Comment by abubakar-iqbal** [comment]
Hi All,
I need user stats for what I using this library. But I find the alternative solution
You just need to pass the username to the function and use your keys. This function will return you use Object.

`public function GetTwitterUserStat($username){
        $options=XenForo_Application::getOptions();
        $oauth_access_token         = $options->cb_twitter_access_token;
        $oauth_access_token_secret  = $options->cb_twitter_token_seceret;
        $consumer_key               = $options->cb_twitter_consumer_key;
        $consumer_secret            = $options->cb_twitter_consumer_secret;

        $twitter_timeline           = "user_timeline";  //  mentions_timeline / user_timeline / home_timeline / retweets_of_me

        //  create request
        $request = array(
            'screen_name'       => $username,
            'count'             => '3'
        );

        $oauth = array(
            'oauth_consumer_key'        => $consumer_key,
            'oauth_nonce'               => time(),
            'oauth_signature_method'    => 'HMAC-SHA1',
            'oauth_token'               => $oauth_access_token,
            'oauth_timestamp'           => time(),
            'oauth_version'             => '1.0'
        );

        //  merge request and oauth to one array
        $oauth = array_merge($oauth, $request);

        //  do some magic

        $base_info              = $this->buildBaseString("https://api.twitter.com/1.1/lists/list.json", 'GET', $oauth);
        $composite_key          = rawurlencode($consumer_secret) . '&' . rawurlencode($oauth_access_token_secret);
        $oauth_signature            = base64_encode(hash_hmac('sha1', $base_info, $composite_key, true));
        $oauth['oauth_signature']   = $oauth_signature;

        //  make request
        $header = array($this->buildAuthorizationHeader($oauth), 'Expect:');
        $options = array( CURLOPT_HTTPHEADER => $header,
            CURLOPT_HEADER => false,
            CURLOPT_URL => "https://api.twitter.com/1.1/lists/list.json?". http_build_query($request),
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_SSL_VERIFYPEER => false);

        $feed = curl_init();
        curl_setopt_array($feed, $options);
        $json = curl_exec($feed);
        curl_close($feed);

        return json_decode($json, true);`
