### ISSUE TITLE
Не работают лайки / дизлайки

### ISSUE THREAD

**Issue by tankist-web** [postaddictme/instagram-php-scraper#688]
```
$instagram = \InstagramScraper\Instagram::withCredentials('my_login', 'my_pass', new Psr16Adapter('Files'));
$instagram->login();
usleep(rand(1000000, 2000000));

$media = $instagram->getMediaByUrl('https://www.instagram.com/p/CA3B8C1M3B_/');
$likes = $instagram->like($media);
```
Метод не работает.  Посмотрел код, метод создает ссылку и получает информацию.
Сама ссылка _https://www.instagram.com/web/likes/2321332657187942527/like/_
Error 405

**Comment by vprivaloff** [comment]
//код публикации
$code = 'CA3B8C1M3B_';

//id публикации   
$media_id = \InstagramScraper\Model\Media::getIdFromCode($code);

//лайк
$instagram->like($media_id);
