### ISSUE TITLE
Scraper stopped working

### ISSUE THREAD

**Issue by joeforjoomla** [postaddictme/instagram-php-scraper#691]
As of now the scraper stopped working:

1. The login always fails, the mid param is no more available in the response cookies, the password is now encrypted in a parameter named enc_password and no longer sent in clear
2. Without the login the scraper client get a 302 http status code that redirects to a page https://www.instagram.com/accounts/login/?next=/accountusername/

**Comment by VarroReve** [comment]
+1

**Comment by emobin** [comment]
what should we do?? now there is no info for without login its all redirect to login page and now i can not login even with credentials!!

**Comment by joeforjoomla** [comment]
Yeah exactly, now it's no longer possible to even login with credentials... sadly this library has become totally useless

**Comment by KinaneD** [comment]
Could it be related to the [Instagram Legacy API deprecation](https://github.com/postaddictme/instagram-php-scraper/issues/664)?

**Comment by joeforjoomla** [comment]
I don't know if there is a relation to the API deprecation. Is there any update on this matter or the intention to find a fix? Otherwise it's likely i need to give up with this library and feature.

**Comment by joeforjoomla** [comment]
@raiym

**Comment by rikless** [comment]
I have 3 instances on my app, and 2 of them stopped working, with auth configuration.

**Comment by dieuz1** [comment]
The issue seems to be with the setProxy() function. Without proxy, the getAccount() return data just fine. Any update?

**Comment by impozzible** [comment]
> Sadly i had to give up with this library. Switcher to a JS-based scraper, works perfectly.

what's the name

**Comment by impozzible** [comment]
> Sadly i had to give up with this library. Switcher to a JS-based scraper, works perfectly.

Hello??

**Comment by roninit72** [comment]
same problem here.

Anyone able to fix it?

**Comment by nam-co** [comment]
Im having the same problem and getting a redirect to a login page, the error shows: Something went wrong. Please report issue. in xxx/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:431

@raiym maybe is possible to add the option for the api feature into this package?

thanks for your work on the package

**Comment by nicolass2002** [comment]
Check is tmp folder on remote server is writable..where phpfastcache store files ;)

**Comment by nicmare** [comment]
hi guys just want to tell you it works again. all you need is a user to login with: 
https://github.com/postaddictme/instagram-php-scraper/issues/697#issuecomment-646011759

**Comment by rikless** [comment]
@nicmare no, because on some account, **without** 2FA enabled, there is a challenge on login, and when Instagram flag you this way, there is just no option. My workaround was to create another account.
