### ISSUE TITLE
Get Medias return false

### ISSUE THREAD

**Issue by filippodicostanzo** [postaddictme/instagram-php-scraper#692]
$instagram->getMedias('kevin', 25); return false and i cannot retrieve the images

others methods works fine like

$instagram->getMediasByTag('youneverknow', 20);
or
$instagram->getMediasByLocationId('1', 20);

I just updated the package

**Comment by emobin** [comment]
Hi my bro filippo , would you please check your skype?

**Comment by moorl** [comment]
Yeah same issue here. On my local develop it works fine like before - but not on any remote webserver.

**Comment by moorl** [comment]
https://codeofaninja.com/tools/find-instagram-user-id

**Comment by filippodicostanzo** [comment]
> https://codeofaninja.com/tools/find-instagram-user-id

Thanks It Work, is possible to get the id of account with this library without use codeofaninja?

**Comment by impozzible** [comment]
> > https://codeofaninja.com/tools/find-instagram-user-id
> 
> Thanks It Works, is possible to get the id of account with this library without use codeofaninja?

yeah sure, get the users profile and that wiull contain the user id

**Comment by filippodicostanzo** [comment]
> > > https://codeofaninja.com/tools/find-instagram-user-id
> > 
> > 
> > Thanks It Works, is possible to get the id of account with this library without use codeofaninja?
> 
> yeah sure, get the users profile and that wiull contain the user id

It works only in localhost mode. If i upload the code on web server the function return false

**Comment by moorl** [comment]
It works for me aswell with the uid. But maybe you get blocked for to many requests. I try to prevent this with a 2hours cache.

**Comment by filippodicostanzo** [comment]
I use a residential proxy by luminati.io for request.
I don't think that's the problem.

**Comment by nicmare** [comment]
> > > > https://codeofaninja.com/tools/find-instagram-user-id
> > > 
> > > 
> > > Thanks It Works, is possible to get the id of account with this library without use codeofaninja?
> > 
> > 
> > yeah sure, get the users profile and that wiull contain the user id
> 
> It works only in localhost mode. If i upload the code on web server the function return false

same problem here. tested on several domains.
