### ISSUE TITLE
(Unirest\Exception) Received HTTP code 407 from proxy after CONNECT

### ISSUE THREAD

**Issue by vprivaloff** [postaddictme/instagram-php-scraper#695]
When trying to use a proxy, an error appears. However, if I use proxies in other projects, everything works fine. Any ideas for solving the problem?

`$instagram = new \InstagramScraper\Instagram();`
`Instagram::setProxy([`
`    'address' => '111.112.113.114',`
`    'port'    => '8080',`
`    'tunnel'  => true,`
`    'timeout' => 30,`
`     'auth' => [`
`        'user' => 'Vdsk4',`
`        'pass' => 'XcnR3c',`
`    ],`
`]);`

`// Request with proxy`
`$account = $instagram->getAccount('kevin');`

**Comment by KinaneD** [comment]
Hello @vprivaloff,
This is a proxy error, I suggest you review your provider's docs.
Cheers.

**Comment by vprivaloff** [comment]
> Hello @vprivaloff,
> This error originates from your proxy provider, I suggest you review their docs.
> Cheers.

Thank. I will deal with the problem!

**Comment by Scanyalx** [comment]
How to fix?
