### ISSUE TITLE
auth exception

### ISSUE THREAD

**Issue by rajatvermaiam** [postaddictme/instagram-php-scraper#696]
"message": "Something went wrong. Please report issue.",
    "exception": "InstagramScraper\\Exception\\InstagramAuthException",
    "file": "/home/u885648297/app/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php",
    "line": 1563

how to resolve unsual login detection from another location on login??

**Comment by rajatvermaiam** [comment]
can you guide me how to use verifytwostep

**Comment by cacing69** [comment]
i think same problem here, without 2fa, this error is appear
![image](https://user-images.githubusercontent.com/36250619/85025631-d3d4a180-b1a1-11ea-8aa5-ac30cbc18f86.png)

**Comment by adrianosmateus** [comment]
Same here. InstagramAuthException

**Comment by rajatvermaiam** [comment]
i got the solution but it is more manual.. looking for better approach...

just call login with :  login(false,true)
then put the security code that u got on email in ConsoleVerification.php
and call url again then remove that parameter from login method.
