### ISSUE TITLE
Only in localhost work on production server not work

### ISSUE THREAD

**Issue by nicolass2002** [postaddictme/instagram-php-scraper#697]
All work perfect on localhost, Apache, Xampp..etc...but on production server nothing work. Any solution?

"[2020-06-16 09:51:08] local.ERROR: Response code is 200. Body: <!DOCTYPE html>
<html lang="en" class="no-js not-logged-in client-root touch">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title>
Login • Instagram
</title>"

**Comment by Gercekefsane** [comment]
same

**Comment by lwxtd** [comment]
same

**Comment by tuqqu** [comment]
I have the similar issue. Once the proxy is set it stops working.

**Comment by tuqqu** [comment]
I have a similar issue. Once any proxy is set it stops working.

**Comment by nicolass2002** [comment]
How they know that we make API call from local machine? And not from some web server?
I can connect on Instagram via VNC from my remote server and Mozilla Firefox...from same IP...but when script do that..her make problem?

**Comment by xioren** [comment]
> How they know that we make API call from local machine? And not from some web server?

This is what I'm wondering. It's actually pretty worrisome.

**Comment by kekemeke** [comment]
same problem here.

**Comment by kekemeke** [comment]
> All work perfect on localhost, Apache, Xampp..etc...but on production server nothing work. Any solution?
> 
> "[2020-06-16 09:51:08] local.ERROR: Response code is 200. Body:
> 
> ```
>     <title>
> ```
> 
> Login • Instagram
> 
> </title>"

Are u logged in?

I mean i have the same issue, when i am trying to get images by getPaginateMedias(accountName) on localhost its work perfect(without login).
<pre><code>$instagram = new Instagram();  
$medias = $instagram->getPaginateMedias("anrotechnology");</code></pre>
BUT. When i just copy my code on prod. server i get always redirected to login page.
So i reg. acc an instagram and login in, and after that everything works without errors.
<pre><code>$instagram = \InstagramScraper\Instagram::withCredentials('user', 'password', new Psr16Adapter('Files'));  
$instagram->login();  
$instagram->saveSession();  
$medias = $instagram->getPaginateMedias("anrotechnology");</code></pre>

**Comment by nicolass2002** [comment]
Now work..tnx m8..on local machine you don't need to login..on remote you must..why don't know..but work :)

**Comment by nicmare** [comment]
wow this issue took me hours today. glad i found this closed issue here which solves it. i registered a new user for login procedure only. and then it works again!

**Comment by Gercekefsane** [comment]
How to add sessionid ?

**Comment by vladimir-oxe** [comment]
It returns me Error 400 with correct credentials.

**Comment by vladimir-oxe** [comment]
> wow this issue took me hours today. glad i found this closed issue here which solves it. i registered a new user for login procedure only. and then it works again!

Can you elaborate on how you logged in? I registered new account and I receive same error only in production.

**Comment by nicmare** [comment]
i created a new IG user and use his credentials:
```
require_once dirname(__FILE__).'/vendor/autoload.php';
use Phpfastcache\Helper\Psr16Adapter;
$instagram = \InstagramScraper\Instagram::withCredentials('user', 'password', new Psr16Adapter('Files'));
$instagram->login();
$instagram->saveSession();
$medias = $instagram->getPaginateMedias($ig_user);
```

**Comment by developerdevice** [comment]
Hello everyone.

The same occurred to me. Locally it works perfectly, but remote returns 400 using auth.

The solution appears to be great, but I need to create a account always it stops?

**Comment by ucola** [comment]
Hi all

Remote I have same issue

```
$instagram = \InstagramScraper\Instagram::withCredentials('USER', 'PASS', new Psr16Adapter('Files'));
$instagram->login(true); // will use cached session if you want to force login $instagram->login(true)
$instagram->saveSession();  //DO NOT forget this in order to save the session, otherwise have no sense
```

I always became
429 - Please wait a few minutes before you try again.

If I log in with this user and check the account activity all is fine... Any ideas?

**Comment by developerdevice** [comment]
Hi guys! I have a good news but not so pretty.

Using remote server like a dedicated or cloud server you're be able to use the lib without troubles, i've tested using windows server and debian server; if you guys are trying to use a website hosting just give up, at least until we release an update;
