### ISSUE TITLE
Get 404 when use function getMediasByTag

### ISSUE THREAD

**Issue by l3aipat** [postaddictme/instagram-php-scraper#70]
InstagramScraper\Exception\InstagramException Object ( [message:protected] => Response code is 404. Body:

**Comment by maxmaxme** [comment]
Unbelievable, but the problem is solved if you install cookies (I loaded https://www.instagram.com/explore/tags/video/?__a=1&max_id=1 and copied them from the query, then inserted in /Unirest/Request.php on line 236)

`$headers = [
			'cookie' => 'simple cookies'
		];`

**Comment by l3aipat** [comment]
It's work, Thank you @maxmaxme
