### ISSUE TITLE
Response decoding failed. Returned data corrupted or this library outdated. 

### ISSUE THREAD

**Issue by nocodelab** [postaddictme/instagram-php-scraper#701]
Hello,
I'm experiencing this error ONLY on the production server.
I believe Instagram is blacklisting non-residential IPs requests.
I have tried to deploy the script on different servers with no luck.

This is where the exception is thrown:

```
InstagramScraper\Instagram::getMediasByTag
vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:938
```

<img width="853" alt="Screenshot 2020-06-19 at 18 34 46" src="https://user-images.githubusercontent.com/4540118/85157325-9e8c8a00-b25b-11ea-9a6f-d962c57c4822.png">

Is anyone else experiencing the same issue?

**Comment by kekemeke** [comment]
#697 check this one.
