### ISSUE TITLE
Facing fatal error in browser when getaccount and getfollowedbycount functions are called

### ISSUE THREAD

**Issue by kamleshwebtech** [postaddictme/instagram-php-scraper#702]
**Php code**

require __DIR__ . '/vendor/Instagram/vendor/autoload.php';
$instagram = new \InstagramScraper\Instagram();
$account = $instagram->getAccount('zainoun_');
echo "Number of follows: {$account->getFollowedByCount()}\n";

**Output in browser:**

Fatal error: Uncaught InstagramScraper\Exception\InstagramException: Response code is 200. Body: <!DOCTYPE html> <html lang="en" class="no-js not-logged-in client-root touch"> <head> <meta charset="utf-8"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <title> Login • Instagram </title> <meta name="robots" content="noimageindex, noarchive"> <meta name="apple-mobile-web-app-status-bar-style" content="default"> <meta name="mobile-web-app-capable" content="yes"> <meta name="theme-color" content="#ffffff"> <meta id="viewport" name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover"> <link rel="manifest" href="/data/manifest.json"> <link rel="preload" href="/static/bundles/es6/ConsumerUICommons.css/ab9da11fae7d.css" as="style" type="text/css" crossorigin="anonymous" /> <link rel="preload" href="/static/bundles/es6/ConsumerAsyncCommons.css/638f1bd337c8.css" as="style in /var/www/html/domainname.com/public_html/vendor/Instagram/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 431

Kindly share your suggestion to fix above issue. Thanks in advance.

**Comment by tuqqu** [comment]
see [this](https://github.com/postaddictme/instagram-php-scraper/issues/697). For some reason instagram won't let you fetch info without logging in for certain ip addresses.
