### ISSUE TITLE
Private account exception on public Profile

### ISSUE THREAD

**Issue by calcifer1337** [postaddictme/instagram-php-scraper#706]
Everything works fine, except the getFollowers method on public profiles.  

In this case, i tried to get the followers of this insta account: https://www.instagram.com/desk2work/

Warning: count(): Parameter must be an array or an object that implements Countable in /Users/nicom/Desktop/InstaPHPTest/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 1282

Fatal error: Uncaught InstagramScraper\Exception\InstagramException: Failed to get followers of account id desk2work. The account is private. in /Users/nicom/Desktop/InstaPHPTest/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:1283
Stack trace:
#0 /Users/nicom/Desktop/InstaPHPTest/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php(1235): InstagramScraper\Instagram->getPaginateFollowers('desk2work', 20, 20, true, '')
#1 /Users/nicom/Desktop/InstaPHPTest/app.php(7): InstagramScraper\Instagram->getFollowers('desk2work')
#2 {main}
  thrown in /Users/nicom/Desktop/InstaPHPTest/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 1283

**Comment by CreeperMaxCZ** [comment]
Hello,
you are supposed to pass a user ID to the getFollowers method, not the username.

You can get the account like this:
`$account = $instagram->getAccount("username");`
and then get the ID:
`$followers = $instagram->getFollowers($account->getId());`

**Comment by 0815nico** [comment]
Hi @CreeperMaxCZ ,

i tried to get the followers by account id, but i still get the same result

`<?php

require_once('./vendor/autoload.php');

$instagram = new \InstagramScraper\Instagram();

$profile = $instagram->getAccount('desk2work');
$nonPrivateAccountMedias = $instagram->getFollowers($profile->getId());

print_r($nonPrivateAccountMedias);`

Fatal error: Uncaught InstagramScraper\Exception\InstagramException: Failed to get followers of account id 29641904088. The account is private. in /Users/nicom/Desktop/InstaPHPTest/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:1283
Stack trace:
#0 /Users/nicom/Desktop/InstaPHPTest/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php(1235): InstagramScraper\Instagram->getPaginateFollowers(29641904088, 20, 20, true, '')
#1 /Users/nicom/Desktop/InstaPHPTest/app.php(8): InstagramScraper\Instagram->getFollowers(29641904088)
#2 {main}
  thrown in /Users/nicom/Desktop/InstaPHPTest/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 1283

**Comment by lukaspicha** [comment]
I have a same problem, I think that IG block this function.

**Comment by calcifer1337** [comment]
I solved this by passing the account id instead of the account name to the "getAccount" method.
