### ISSUE TITLE
Best way to login and not to get "We noticed a login from a device you don't usually use" warrning?

### ISSUE THREAD

**Issue by nicolass2002** [postaddictme/instagram-php-scraper#709]
Hi guys,
what is best way to avoid warning from Instagram unusual access to account from Instagram where you need to approve that is you trying to login on Instagram? 

Can we somehow create new account and only login from our script or we must use proxy?

How I do:
1. Create new account from web browser (Germany). I use web browser from my dedicated linux server
2. I enter those initials in script and I access Instagram and all work well

But after some time, Instagram start to send me 
"We noticed a login from a device you don't usually use "

**Comment by payamomrani** [comment]
I have the same problem

**Comment by yinanchuan** [comment]
Instagram postponed the API change and the remaining Instagram Legacy API permission (“Basic Permission”) was disabled on June 29, 2020 not on the initially announced date – 2nd of March, 2020.

Instagram announced a depreciation of the Basic Permission for its Legacy API Platform and provided directions on how this Instagram API changes impact users and also third-party developers in providing tools for generating and displaying Instagram content.
