### ISSUE TITLE
Get 404 when use function getMediasByTag #70

### ISSUE THREAD

**Issue by senol01** [postaddictme/instagram-php-scraper#71]
InstagramScraper\Exception\InstagramException Object ( [message:protected] => Response code is 404. Body:

Unbelievable, but the problem is solved if you install cookies (I loaded https://www.instagram.com/explore/tags/video/?__a=1&max_id=1 and copied them from the query, then inserted in /Unirest/Request.php on line 236)

$headers = [ 'cookie' => 'simple cookies' ];

`    public static function get($url, $headers = array(), $parameters = null, $username = null, $password = null)
    {
		$headers = [ 'cookie' => 'simple cookies' ];
        return self::send(Method::GET, $url, $parameters, $headers, $username, $password);
    }`

`require '/vendor/autoload.php';

use InstagramScraper\Instagram;

$medias = Instagram::getMediasByTag('zara', 30);
echo json_encode($medias);`

**Comment by raiym** [comment]
Hello @senol01 thank you.

It seems that Instagram started require auth for those two links: 
```php
    const MEDIA_JSON_BY_LOCATION_ID = 'https://www.instagram.com/explore/locations/{{facebookLocationId}}/?__a=1&max_id={{maxId}}'; // doesn't work
    const MEDIA_JSON_BY_TAG = 'https://www.instagram.com/explore/tags/{tag}/?__a=1&max_id={max_id}'; // doesn't work
```

**Comment by filippodicostanzo** [comment]
From today instagram disabled access at your website without login.

There is any solution for bypass this problem?

**Comment by filippodicostanzo** [comment]
@senol01 how to install the cookie?

I insert the  $headers = [ 'cookie' => 'simple cookies' ]; in the specific line but i recive the same error!

InstagramScraper\Exception\InstagramException Object ( [message:protected] => Response code is 404. Body:

Any solution for this issue?

**Comment by pinotarantino** [comment]
This work : https://www.instagram.com/explore/tags/fitness/?__a=1&max_id=1

Tried at 17.30

**Comment by pinotarantino** [comment]
if you click on the link I posted above it works, also https://www.instagram.com/explore/tags/fitness/?__a=1 works; you get the json data... if this works, maybe they're stopping instagram-php-scraper? I don't know...

**Comment by filippodicostanzo** [comment]
If you are not logged into instagram the link doesn't work and return 
"Spiacenti, questa pagina non è disponibile
È possibile che il link che hai seguito sia corrotto o che la pagina sia stata rimossa. Torna su Instagram."

**Comment by maxmaxme** [comment]
@fabianoroberto 

1. Open [https://www.instagram.com/explore/tags/fitness/?__a=1&max_id=1](https://www.instagram.com/explore/tags/fitness/?__a=1&max_id=1)
2. Copy all cookies
3. Insert in /Unirest/Request.php on line 236 this code:
`$headers = [ 'cookie' => 'simple cookies' ];`

Sample:
![2017-03-15 19 44 13](https://cloud.githubusercontent.com/assets/26428493/23960126/19fd9c74-09b8-11e7-8f72-485193a51cc1.png)

**Comment by filippodicostanzo** [comment]
@maxmaxme how can i get this string for the cookie?

**Comment by maxmaxme** [comment]
@filippodicostanzo 
1. F12 (CMD+Option+I)
2. Console
3. console.log(document.cookie)

**Comment by filippodicostanzo** [comment]
@maxmaxme thank you but for me doesn't work

return anytime 404 :(

**Comment by senol01** [comment]
maxmaxme did   you try if it works?
console.log(document.cookie)
mid=WMl5gAAEAAHXmW0Bp5VYmEgeERhA; ig_pr=1; ig_vw=1366; ds_user_id=4211931173; s_network=""; csrftoken=BREKQUyRvTIOfomdbj2WvpYlAhZippmw
have only become this

**Comment by maxmaxme** [comment]
@filippodicostanzo @senol01 
Sorry. I took cookies from another place.

1. Open [https://www.instagram.com/explore/tags/fitness/?__a=1&max_id=1](https://www.instagram.com/explore/tags/fitness/?__a=1&max_id=1)
2. F12 (CMD+Option+I)
3. Network
4. F5
5. Click on "?__a=1&max_id=1"
6. Copy Cookies from "Request Headers"

![2017-03-15 20 39 48](https://cloud.githubusercontent.com/assets/26428493/23962735/202c0236-09c0-11e7-8af5-419d1728b2a1.png)

**Comment by senol01** [comment]
Bro thank you very much
https://www.instagram.com/explore/tags/usa/?__a=1
But i have one questition more, how i can find the popular Medias?

**Comment by maxmaxme** [comment]
@senol01 This is a question for @raiym

**Comment by senol01** [comment]
for maxmaxme

**Comment by pinotarantino** [comment]
Thanks to senol01 and maxmaxme, your solution worked for me...! ;) Do you think that this escamotage could resist for long time to Instagram countermeasure?  Anyway, Thank you very much!

**Comment by filippodicostanzo** [comment]
@maxmaxme & @senol01 thank you're saved my week :)

Anynone knows the duration of these cookie?

**Comment by ximrx** [comment]
This is not a solution, is this library going to work by adding authentication and API key or is it going to be shut down?

**Comment by raiym** [comment]
Thanks for support guys.
Really appreciate it. 
For now only to urls are require auth:
```php
const MEDIA_JSON_BY_LOCATION_ID = 'https://www.instagram.com/explore/locations/{{facebookLocationId}}/?__a=1&max_id={{maxId}}'; // doesn't work
const MEDIA_JSON_BY_TAG = 'https://www.instagram.com/explore/tags/{tag}/?__a=1&max_id={max_id}'; // doesn't work
```
related to tags and locations. 

All other functions work as before. 
Of course I do understand needs about tags and locations. 

We already have private instagram api: https://github.com/mgp25/Instagram-API developed by @mgp25 

So I don't know for now is postaddict library needs auth or not? 

Actually, I will be glad to hear your suggestions and feeback

**Comment by raiym** [comment]
Well. 
I have decided that library will support web login and scraping tags and locations will be fixed

And I think about add support of official API as well

**Comment by filippodicostanzo** [comment]
@raiym thank you! after this intensive work you can explain how to install this for scraping tags please :)

**Comment by aik27** [comment]
Hi. I know some commercial applications, witch use this endpoint:

`https://www.instagram.com/query/`

to grab data, without any authorization (only csrftoken cookie). And this works perfectly.

For example. Send this POST query to get tagged data: 

`ig_hashtag(' . $tag . ') { media.first(' . $limit . ') { count, nodes { id, caption, code, comments.last(10) { count, nodes { id, created_at, text, user { id, profile_pic_url, username } } }, date, dimensions { height, width }, filter_name, display_src, id, is_video, likes { count }, owner { id, username, full_name, profile_pic_url }, thumbnail_src, video_url, location { name, id } }, page_info} } `

Query headers:
```
            [0] => User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.87 Safari/537.36
            [1] => Origin: https://www.instagram.com
            [2] => Referer: https://www.instagram.com
            [3] => Connection: close
            [4] => X-Csrftoken: XXXXXXXXXX
            [5] => X-Requested-With: XMLHttpRequest
            [6] => X-Instagram-Ajax: 1
            [7] => Cookie: csrftoken=XXXXXXXXX
            [8] => Host: www.instagram.com
            [9] => Content-Type: application/x-www-form-urlencoded
            [10] => Content-Length: 489
```

Think about this.

**Comment by aik27** [comment]
Seems, this query (for tagged data) work without any authorization (only csrftoken cookie requered).

`ig_hashtag(' . $tag . ') { media.first(' . $limit . ') { count, nodes { id, caption, code, comments.last(10) { count, nodes { id, created_at, text, user { id, profile_pic_url, username } } }, date, dimensions { height, width }, filter_name, display_src, id, is_video, likes { count }, owner { id, username, full_name, profile_pic_url }, thumbnail_src, video_url, location { name, id } }, page_info} } `

**Comment by raiym** [comment]
almost done. please wait another hour or two

**Comment by matkozikowski** [comment]
@raiym 
So if you fix the problem we will able to get all images by tag ?
thx.

**Comment by raiym** [comment]
Yes

**Comment by raiym** [comment]
But login and password will be required

**Comment by matkozikowski** [comment]
Thats fine. After fix it please let us know what we should change :)

**Comment by aik27** [comment]
@raiym, really, don't rush with login and password. Some commercial plugins works without authorization. Just emulate browser request, get **csrftoken cookie** and grab tags and location data by http://instagram.com/query/ endpoint.

**Comment by raiym** [comment]
Thank you guys.
I already have done it.

https://github.com/postaddictme/instagram-php-scraper/releases/tag/v0.5.0
 
I am planning to add session caching (because now every time php dies login required). Maybe for now you will cache ```sessionId``` on your own

**Comment by pinotarantino** [comment]
Thank you veruy much raym, very good job, just installed now! It works fine but with a little change in my case:
- $medias = self::$instagram->getTopMediasByTagName("$kw"); // doesn't work, problem with self. "Fatal error: Cannot access self:: when no class scope is active"
- $medias = $instagram->getTopMediasByTagName("$kw"); // works ok without 'self::'

Thank you again! ;)

**Comment by jetonr** [comment]
Does this coockie ever expire, I created a dummy instagram account and got only the `sessionid` part from the coockie and it works when you send the request. My question is will this work when making multiple requests from different domains and do they ever expire?

**Comment by raiym** [comment]
@jetonr i think it will work, but because Instagram links session for ip and browser (I think)you need to perform login on each server
But I suggest to use one account only from one ip.
