### ISSUE TITLE
Inconsistent exception `getAccount` vs `getAccountById`

### ISSUE THREAD

**Issue by KinaneD** [postaddictme/instagram-php-scraper#710]
Recently we've been facing a lot of failures on our Production env. due to a sudden inconsistency in the Exceptions that are thrown between `Instagram::getAccount()` and `Instagram::getAccountById()`.

### Behaviour
Previously using `v0.9.2` we used to get a consistent `InstagramScraper\Exception\InstagramNotFoundException` exception all the following cases:
* Wrong `username`.
* Wrong `id`.
* Disabled account.

Now we get `InstagramScraper\Exception\InstagramException` when:
* Wrong `id`.
* Disabled account.

With message (just a snippet):
```html
Response code is 200. Body: <!DOCTYPE html>\n
      <html lang="en" class="no-js not-logged-in client-root touch">\n
          <head>\n
              <meta charset="utf-8">\n
              <meta http-equiv="X-UA-Compatible" content="IE=edge">\n
      \n
              <title>\n
      Instagram\n
      </title>\n
```

But we still get `InstagramScraper\Exception\InstagramNotFoundException` when the `username` is wrong.

Updated to latest release `v0.9.11` facing the same behaviour still.

### Expectations
Have a consistent Exception in all cases.

### Additional Context
I am not sure if this discrepancy was introduced to the package or is due to recent deprecations/changes on Instagram's side. I am hesitant though to consider the later unless we are sure it is not the former.
I see that some changes were introduced [here](https://github.com/postaddictme/instagram-php-scraper/commit/c9df4728c2b8a38e46bedea0c458bb6d9073f1f5#diff-90b6141340c3235d28e3ea9c881c6e72) specifically to `Instagram::getAccountById()` not long ago. Although this fix was only released in `v0.9.11`.

#### Debugging
`Instagram::getAccountById()` internally calls `Instagram::getUsernameById()` which given a wrong ID or the ID of a disabled account now returns `null`.

### Proposed Solution
Throw `InstagramScraper\Exception\InstagramNotFoundException` in case the username is `null`.
Specifically abide to `Instagram::getAccountPrivateInfo()` docs to throw said exception in this case.

Thoughts?
Thank you.

FYI @raiym

**Comment by mohsen-farahani** [comment]
I think there have been changes on Instagram again. Almost out of work
