### ISSUE TITLE
Why always work from localhost and not from remote?

### ISSUE THREAD

**Issue by nicolass2002** [postaddictme/instagram-php-scraper#712]
Same script on localhost work even without login..but from remote I got "Unusual login attempt"?

What is difference? How to solve that?

Local machine is Windows 10..and Instagram always allow script to work..Remote is Linux..and he not Allow??

**Comment by nicolass2002** [comment]
Solved with setting user agent only to browser

**Comment by cacing69** [comment]
> Solved with setting user agent only to browser

hey bro how u solve this problem, can u give me a example
