### ISSUE TITLE
Обход блокировки 

### ISSUE THREAD

**Issue by kaspsoftcom** [postaddictme/instagram-php-scraper#713]
Как обойти блокировку от instagram? 
Какой временной интервал выдерживать между запросами, чтобы не быть заблокированным? 

Мой сервер был заблокирован спустя 2 недели, после я подключил Proxy. На прокси проработал более месяца ( покупаю тут proxy-sale.com).  Теперь прокси уже не работает.

Решил запускать scraper из локальной сети и для этого написал программу которая:
1. получает от моего сервера тег, 
2. получает посты по этому тегу 
3. отправляет на мой сервер. 
Из локальной сети тоже не долго работает. Примерно после 10го запроса ( $instagram->getMediasByTag($tags->tag, 25); ) меня блокируют.

**Comment by sergshyn** [comment]
Generally blocking problems occurs with get profile and get post requests.
Get posts by tag should work much better.
Try to use Residential proxies, they works like a charm but they are quite expensive.
