### ISSUE TITLE
Response code is 429 for getAccount($username)

### ISSUE THREAD

**Issue by nicolass2002** [postaddictme/instagram-php-scraper#714]
Hi,
I got this today if I try to getAccount($username)?
That is rate limit error. Anyone have same problem?

I can get Instagram tags without problem..but user media not.

**Comment by nopenopenope** [comment]
Try to test slower, Rate Limit is reached when you hit a quote of Instagram internals APIs.

**Comment by nicolass2002** [comment]
But when website hit google bot how to get slower requests to Instagram? :(

**Comment by s-fraser2007** [comment]
Hi, Im having similar issues, Does anybody know what the rate limit is per minute? I've added in some random "sleeps" this seems to help things but it would be helpful to know the limit

Thanks

**Comment by nopenopenope** [comment]
Around 400 requests to each source per hour

**Comment by s-fraser2007** [comment]
Thanks
