### ISSUE TITLE
Missing documentation: How can I set useragent string?

### ISSUE THREAD

**Issue by crystaler4** [postaddictme/instagram-php-scraper#718]
Instagram returns "suspicious login". My tip it's no JS environment in PHP :) + missing useragent string (I log over browser from same IP).

How to add user agent (user_agent, useragent):

`$instagram->setUserAgent('your-string');`

Can you add this to documentation somewhere?

**Comment by NabiKAZ** [comment]
As you can see here:
https://github.com/postaddictme/instagram-php-scraper/blob/13c48b5d2eee23dfd4f3372a8f8fba60ff26c16e/src/InstagramScraper/Instagram.php#L271

You can set new user-agent by this command:

```PHP
$instagram->setUserAgent('.....');
```

And you can see default user-agent here:
https://github.com/postaddictme/instagram-php-scraper/blob/13c48b5d2eee23dfd4f3372a8f8fba60ff26c16e/src/InstagramScraper/Instagram.php#L51
