### ISSUE TITLE
Fatal error: Response code is 200.

### ISSUE THREAD

**Issue by filippodicostanzo** [postaddictme/instagram-php-scraper#719]
I just try to getMedias() and for the first time works but if i try again the server return 200 code error.

```
$instagram = \InstagramScraper\Instagram::withCredentials('username', 'password', new Psr16Adapter('Files'));
$instagram->login();
$instagram->saveSession();
$medias = $instagram->getMedias('kevin', 5);
var_dump($medias);
```

I also have a residential proxy by Luminati.io but it doesn't work in this case either!

There is a guide for save the credentials and i remove the limit of instagram login?

**Comment by ElKnarzo** [comment]
Any solutions for that problem?

**Comment by TimE90** [comment]
Also having this problem… did you fix it?

**Comment by webair-studio** [comment]
+
