### ISSUE TITLE
Instagram is not available without logging in

### ISSUE THREAD

**Issue by petertenhoor** [postaddictme/instagram-php-scraper#72]
Hi there,

You probably already noticed that Instagram made some changes which require a user to be logged in to get access to Instagram pages, which means that Instagram content is no longer public.

I use getMediasByTag, GetAccountById and getMediaByCode from your package to create an Instagram feed. These methods seem to have stop working due to the above change that Instagram made.

Is this something that you are planning to fix? Logging in to the Instagram API before scraping might be a possibility. Let me know!

Best regards,

Peter ten Hoor

**Comment by raiym** [comment]
hello @petertenhoor 
yes, getMediasByTag, getAccountById does not work (as well as urls related to locations).

getMediaByCode works

In short I don't know for now (about auth). 
For more info please refer to: https://github.com/postaddictme/instagram-php-scraper/issues/71

**Comment by raiym** [comment]
Library will support web login and official API

**Comment by petertenhoor** [comment]
Awesome, thank you!

**Comment by raiym** [comment]
@petertenhoor hello again
check new release

**Comment by petertenhoor** [comment]
Nice job. This works like a charm.
