### ISSUE TITLE
Account with this username does not exist

### ISSUE THREAD

**Issue by EvgeniySamusko** [postaddictme/instagram-php-scraper#720]
Hi. I get error "Account with this username does not exist"

Test code is

$instagram = new \InstagramScraper\Instagram();
$medias = $instagram->getMedias('foodmarket_centergoroda', 3);

**Comment by fdciabdul** [comment]
it's not like from that account , but from instagram itself 

i think instagram change their api and this library need to update

**Comment by vincent-lu** [comment]
Having the same problem. Same code, used to work, but stopped working recently.

**Comment by anabelle** [comment]
Any fix for this sudden error?

**Comment by vincent-lu** [comment]
@anabelle in my own case logging in before scrapping solved this problem for me.

Basically before any actual scrapping, you need to run the following lines (you will need to `composer require phpfastcache/phpfastcache` to get Psr16Adapter class).

```
$instagram = Instagram::withCredentials($botId, $botPassword, new Psr16Adapter('Files'));
$instagram->login();
$instagram->saveSession();
```
