### ISSUE TITLE
PHP Fatal Error: Uncaught InstagramScraper\Exception\InstagramException: Response decoding failed. Returned data corrupted or this library outdated. Please report issue

### ISSUE THREAD

**Issue by thjeng831** [postaddictme/instagram-php-scraper#722]
I have been using this Instagram PHP Scraper library for a couple months now. However when I ran this code that usually worked a month ago, it is suddenly not working anymore even though I haven't changed my code. I will attach screenshots of the code portion where the error occurs and the error message. Any help would be appreciated!
<img width="1165" alt="Screen Shot 2020-07-20 at 2 50 45 PM" src="https://user-images.githubusercontent.com/47009508/87990409-cd835f00-ca98-11ea-8181-2d111fa0af81.png">
<img width="653" alt="Screen Shot 2020-07-20 at 2 51 42 PM" src="https://user-images.githubusercontent.com/47009508/87990415-cf4d2280-ca98-11ea-8a00-931216629a2e.png">

**Comment by nicolass2002** [comment]
How you solved not getting "We noticed a login from a device you don't usually use" warrning?"

**Comment by thjeng831** [comment]
What do you mean not getting "We noticed a login from a device you don't usually use" warrning?" I never got that error

**Comment by nicolass2002** [comment]
When

> 
> 
> What do you mean not getting "We noticed a login from a device you don't usually use" warrning?" I never got that error

I'm getting "Suspicious Login Attempt" and I need to click on mobile "This was me" button..but still can't login.

Do you use lot of instagram accounts or?

**Comment by thjeng831** [comment]
I am not logging in with an account to crawl, I crawl without using authentication.

**Comment by nicolass2002** [comment]
> 
> 
> I am not logging in with an account to crawl, I crawl without using authentication.

You can get results for Search, get user media, get tags...without authentication?

**Comment by thjeng831** [comment]
Yes but currently my function calls do not work for some other reason.
