### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by illiamorkva** [postaddictme/instagram-php-scraper#725]
SSL certificate problem: unable to get local issuer certificate

**Comment by NabiKAZ** [comment]
1. Download the latest cacert.pem from https://curl.haxx.se/ca/cacert.pem
2. Add the following line to php.ini:
 `curl.cainfo="/path/to/downloaded/cacert.pem"`

reference: https://stackoverflow.com/a/31830614/1407491

**Comment by illiamorkva** [comment]
Thank you
