### ISSUE TITLE
FEATURE: Do you have any plan for get user's highlights?

### ISSUE THREAD

**Issue by NabiKAZ** [postaddictme/instagram-php-scraper#726]
Do you have any plan for get user's highlights?

**Comment by NabiKAZ** [comment]
I'm starting implement Highlights.
And I created a pull request.

- [x] Add model
- [x] Add example
- [x] Implement `getHighlights()` method
- [x] Add test
- [ ] Implement get media stories of a highlight

Regarding the last one, which is to implement taking story medias of highlight, for the best implementation, I need advice.

There is now `getStories` that can be expanded it or a new function can be created, such as `getHighlightStories`.

Both stories and highlights are available in the shared `$jsonResponse['data'] ['reels_media']`.

And in the output of each we have:

STORY: `user` AND `owner` (currently in `getStories` the `user` is used, which of course can be changed based on `owner`)
HIGHLIGHT: `owner`

Also the submitted send parameters needed of each:

STORY: `reel_ids`
HIGHLIGHT: `highlight_reel_ids`

URLs:

STORY:
`https://www.instagram.com/graphql/query/?query_hash=90709b530ea0969f002c86a89b4f2b8d&variables={"reel_ids":["1097615892"],"tag_names":[],"location_ids":[],"highlight_reel_ids":[],"precomposed_overlay":false,"show_story_viewer_list":true,"story_viewer_fetch_count":50,"story_viewer_cursor":"","stories_video_dash_manifest":false}`

HIGHLIGHT:
`https://www.instagram.com/graphql/query/?query_hash=90709b530ea0969f002c86a89b4f2b8d&variables={"reel_ids":[],"tag_names":[],"location_ids":[],"highlight_reel_ids":["17947844917345377","17850034517139791","17931385762360834"],"precomposed_overlay":false,"show_story_viewer_list":true,"story_viewer_fetch_count":50,"story_viewer_cursor":"","stories_video_dash_manifest":false}`

The differences between `story` and `highlight` are obvious. It remains to be seen what the best execution mode will be, whether everyone will focus on `getStories` or write a new function to do so.
Given that important note, both type are `Media` entity class.

**Comment by NabiKAZ** [comment]
@raiym 
I did not receive a comment on the previous issue I raised. So I went ahead with my ideas.
About get stories of highlight, I think it would have been better to use the same `getStories` function as the output material of both stories. But the following problems caused me to use a separate function:
- It was not possible to identify `reel_id` type, whether it is a user id or highlights id.
- Adding a second argument to the function was not interesting for the `reel_id` type.
- `reel_id` profile numbers are often much smaller than the number of highlights, but one cannot be sure that the numbers less than a certain value are necessarily related to the profile and more than that to the highlights based on which the operation was separated.
So for now it is preferable to use a standalone function called `getHighlightStories` which I executed and registered a pull request.

**Comment by ricdijk** [comment]
I tested the implementation, it didn't work for me. So I tried a different instagram query_hash:

const HIGHLIGHT_STORIES = 'https://www.instagram.com/graphql/query/?query_hash=45246d3fe16ccc6577e0bd297a5db1ab';

with variables:
$variables = [
                'highlight_reel_ids'=> $highlight_reel_ids,
                'reel_ids'=> [],
                'location_ids'=> [],
                'precomposed_overlay'=> False,
         ];

This works good for me, so I changed the query_hash in your function and made another pull request

**Comment by ricdijk** [comment]
You can use this query_hash for both Stories and HighlightStories, but with different variables
('highlight_reel_ids' and 'reel_ids'). If it is better to put it in one function (with two arguments) please let me now. I will then create a getStories function with 3 arguments, to also include 'location_ids'.

**Comment by NabiKAZ** [comment]
Shame for delay.

That `query_hash` still works for me, however I changed it to what you said. Although I'm not sure it works for everyone.

In terms of how to implement with 3 arguments, it may not be a bad way right now, but according to [Clean Code](https://www.google.com/search?q=Clean+Code+3+arguments&oq=Clean+Code+3+arguments) principles, a function should not have more than 3 arguments. Maybe in the future you need to add other parameters, which then will not be interesting code.
For example, in the current situation, in order to extract only the highlight stories, I have to set `null` for the first argument:
```PHP
getStories (null, $highlight_reel_ids);
```
I think you agree with me that it does not seem like a very interesting method.
Another solution is to create and use a general function, such as a `executeQuery($params)`, which is get an array or object that contains the parameters needed to extract the data.

`$param` can take values as follows:

```PHP
$params = [
'reel_ids'=> [111],
];

$params = [
'highlight_reel_ids'=> [222, 333, 444],
];

$params = [
'location_ids'=> [555],
];

$params = [
'reel_ids'=> [111],
'highlight_reel_ids'=> [222, 333, 444],
];

$params = [
'reel_ids'=> [111],
'highlight_reel_ids'=> [222, 333, 444],
'location_ids'=> [555],
'foo'=> ['bar'],
];

//And other combinations with more parameters
```
OR:
```PHP
$params = new PARAMS_STRUCTURED_CLASS();
//The methods ex.: highlight_reel_ids, reel_ids, location_ids,...Any other number of parameters.
```

Of course, research may still be needed.

**Comment by ricdijk** [comment]
I like the solution with the $params. However that will not be backwards compatible with the current implementation of getStories. For backwards compatibility a new function should be created, that will be called by getStories and e.g. getHighlightStories.
I would like more discussion next time.

However I did  create the getStories variant with 3 parameters and a getHighlightStories function (with 1 parameter) that calls the first function and are accepted and now in the code. If we still want to change it, that’s ok for me.


Verstuurd vanaf mijn iPad
