### ISSUE TITLE
Response code is 200 Login Instagram.

### ISSUE THREAD

**Issue by danielwijaw** [postaddictme/instagram-php-scraper#735]
<p>Hello , im developing instagram scraper using codeigniter. when developing in local run normaly but when uploaded to hosting and vps im got error.</p>
<p>this is screenshot my error</p>

![Screen Shot 2020-08-02 at 10 13 20](https://user-images.githubusercontent.com/34294481/89114634-fba96b80-d4a8-11ea-8720-c0e2b5760b54.png)

<p>This is my code</p>
<p>For GET Method</p>
<pre>
public function instagramInfo($accountGet = "")
	{
        
		header("Access-Control-Allow-Origin: *");

		// API Configuration
		$this->_apiConfig([
			'methods' => ['GET'],
        ]);

        if(isset($this->input->get()['id'])){
            $accountGet = $this->input->get('id');
        }

        $results = $this->instagramData($accountGet);

		// return data
		$this->api_return(
			[
				'status' => 1,
				"results" => $results,
			],
		200);
    }
</pre>

<p> This is for getting data </p>

<pre>
private function instagramData($accountGet){
        $this->load->driver('cache', array('adapter' => 'file'));
        $instagram = new \InstagramScraper\Instagram();

        $cacheName = $this->cleanChar($accountGet);
        $cacheControll = $this->cache->file->get($cacheName);

        if ( !$cacheControll ){
            $formulaMaxPost = 10;

            $account = $instagram->getAccount($accountGet);
            $resultMedia = $instagram->getPaginateMedias($accountGet);

            // Account Basic Information
            $getFollowedByCount = $account->getFollowedByCount();
            $accountInfo = [
                "Id" =>$account->getId(),
                "Username" =>$account->getUsername(),
                "Full name" =>$account->getFullName(),
                "Biography" =>$account->getBiography(),
                "Profile picture url" =>$account->getProfilePicUrl(),
                "External link" =>$account->getExternalUrl(),
                "Number of published posts" =>$account->getMediaCount(),
                "Number of following" =>$account->getFollowsCount(),
                "Number of followed" =>$getFollowedByCount,
                "Is private" =>$account->isPrivate(),
                "Is verified" =>$account->isVerified()
            ];

            $medias = $resultMedia['medias'];

            // Foreach Post and Logic
            $mediacatch = [];
            $totalEr = 0;
            $engagmentRate = 0;
            $likes = 0;
            $comments = 0;
            $count = 1;
            foreach ($medias as $keyMedia => $media) {
                $getCommentsCount = $media->getCommentsCount();
                $getLikesCount = $media->getLikesCount();
                if($count <= $formulaMaxPost){
                    $likes += $getLikesCount;
                    $comments += $getCommentsCount;
                    $totalEr += $getCommentsCount;
                    $totalEr += $getLikesCount;
                    $engagmentRate += ($getCommentsCount+$getLikesCount)/$getFollowedByCount;
                }
                $mediacatch[] = [
                    "Media info" => [
                        "Number of comments" => $getCommentsCount,
                        "Number of likes" => $getLikesCount,
                        "Get link" => $media->getLink(),
                        "Engagment Rate" => $this->intToPercentage($engagmentRate) . '%'
                    ]
                ];
                $count++;
            }

            $accountInfo['totalEngagmentsPercent'] = $this->intToPercentage($engagmentRate/$formulaMaxPost) . '%';
            $accountInfo['averageLike'] = round($likes/$formulaMaxPost);
            $accountInfo['averageComments'] = round($comments/$formulaMaxPost);

            $results = [
                "accountInfo" => $accountInfo,
                "mediaList" => $mediacatch
            ];

            $this->cache->file->save($cacheName, $results, 300);
        }else{
            $results = $this->cache->file->get($cacheName);
        }

		return $results;
    }
</pre>
<p>Can anybody help me ? or in my vps im wrong configuration ?</p>

**Comment by CodingAnonymous** [comment]
I have the same issue. This repository is so much out of date... It's a shame...

**Comment by danielwijaw** [comment]
> I have the same issue. This repository is so much out of date... It's a shame...

yeah i think its because security of instagram.
finally im using javascript ajax instagram API and then save data to php
i hope this will help you

<pre>
const urlInstagramBase = 'https://www.instagram.com/{username}';
const igId = $("#instagramID").val();
$.ajax({
        url: urlInstagramBase.replace("{username}", igId),
        contentType: false,
        cache: true,
        processData: false,
        crossDomain:true,
        success: function(data) {
          var splitJSONs = data.split('window._sharedData = ');
          var splitJSON = splitJSONs[1];
          var instaJSON = splitJSON.split(';<\/script>');
          var instaArray = JSON.parse(instaJSON[0]);
          $.ajax({
            type: "POST",
            crossDomain:true,
            data: {<?php echo $this->security->get_csrf_token_name(); ?>: '<?php echo $this->security->get_csrf_hash(); ?>', dataInstagram:instaArray},
            url: '<?php echo base_url('/backend/main/getPostdata') ?>/' + igId,
              success: function(data){
                if(data.status === 1){
                  ajax("<?php echo base_url("/") ?>"+igId,"#root_data");
                  window.history.pushState({href: igId}, '', igId);
                  return false
                }else{
                  alert("Get Some Error , Please contact Administrator or Click Analyse Again");
                  $("#buttonAnalyseInstagram").attr('disabled', false);
                  $("#buttonAnalyseInstagram").html('Analyse');
                  console.log(data)
                  return false
                }
              },
              error: function(XMLHttpRequest, textStatus, errorThrown) {
                $("#buttonAnalyseInstagram").attr('disabled', false);
                $("#buttonAnalyseInstagram").html('Analyse');
                $("#catching_error").html(XMLHttpRequest.responseText); 
                if (XMLHttpRequest.status == 0) {
                  alert(' Check Your Network.');
                } else if (XMLHttpRequest.status == 404) {
                  alert('Instagram ID Not Found');
                } else if (XMLHttpRequest.status == 500) {
                  alert('Internel Server Error.');
                }  else {
                  alert('Unknow Error.\n' + XMLHttpRequest.responseText);
                } 
              }
            });
        },
        error: function(XMLHttpRequest, textStatus, errorThrown) {
          $("#buttonAnalyseInstagram").attr('disabled', false);
          $("#buttonAnalyseInstagram").html('Analyse');
          $("#catching_error").html(XMLHttpRequest.responseText); 
          if (XMLHttpRequest.status == 0) {
            alert(' Check Your Network.');
          } else if (XMLHttpRequest.status == 404) {
            alert('Instagram ID Not Found');
          } else if (XMLHttpRequest.status == 500) {
            alert('Internel Server Error.');
          }  else {
            alert('Unknow Error.\n' + XMLHttpRequest.responseText);
          } 
        }
      });
</pre>

**Comment by ezequiel9** [comment]
Same here!!! wtf

**Comment by danielwijaw** [comment]
> Same here!!! wtf

LOL , i think we can use javascript frontend for catching instagram API

**Comment by danielwijaw** [comment]
> > > Same here!!! wtf
> > 
> > 
> > LOL , i think we can use javascript frontend for catching instagram API
> 
> Instagram is asking for a captcha or something similar, that is why is not working.
> 
> I have tried by using my credentials (the other way) and is not working neither. It shows an error in base of the Cache package used.
> 
> Do you know some good package to implement the proper api ?

im sorry im bad in english but i hope i can understand what you say hehe
im using javascript ajax for catching public instagram (this is my function https://github.com/postaddictme/instagram-php-scraper/issues/735#issuecomment-667993017)
core = <pre>
$.ajax({
        url: ''https://www.instagram.com/{instagramID}'',
        contentType: false,
        cache: true,
        processData: false,
        crossDomain:true,
        success: function(data) {
          var splitJSONs = data.split('window._sharedData = ');
          var splitJSON = splitJSONs[1];
          var instaJSON = splitJSON.split(';<\/script>');
          var instaArray = JSON.parse(instaJSON[0]);
}
});
</pre>
