### ISSUE TITLE
Response code is not equal 200. Help Please !

### ISSUE THREAD

**Issue by tenet912** [postaddictme/instagram-php-scraper#736]
hi everyone . i using this script . in localhost xampp work fine . but after upload this script to centos server (make online) when i want use the script i get this error . help me please . 

`Fatal error: Uncaught InstagramScraper\Exception\InstagramException: Response code is not equal 200. Something went wrong. Please report issue. in /opt/lampp/htdocs/zhav/src/InstagramScraper/Instagram.php:198 Stack trace: #0 /opt/lampp/htdocs/zhav/ajax.php(296): InstagramScraper\Instagram->searchAccountsByUsername('mdi') #1 {main} thrown in /opt/lampp/htdocs/zhav/src/InstagramScraper/Instagram.php on line 198`

**Comment by ivesbrito** [comment]
i am with the same problem, repentnently, suddenly this started to happen :(

**Comment by mahsa92** [comment]
@tenet912 @ivesbrito Have your problem solved?

**Comment by tenet912** [comment]
> 
> 
> @tenet912 @ivesbrito Have your problem solved?

yes . use login before doing something else

**Comment by ivesbrito** [comment]
i solved this problem scraping with an greater interval, 1 hour...

i was scraping using the interval of 5 minutes..
