### ISSUE TITLE
Found this error when i use on hosting but work perfectly on localhost

### ISSUE THREAD

**Issue by MrAndiw** [postaddictme/instagram-php-scraper#74]
Unirest\Exception Object ( [message:protected] => Could not resolve host: www.instagram.com; Unknown error [string:Exception:private] => [code:protected] => 0 [file:protected] => /storage/h4/910/1069910/public_html/application/libraries/instagram-php-scraper/vendor/mashape/unirest-php/src/Unirest/Request.php [line:protected] => 476 [trace:Exception:private] => Array ( [0] => Array ( [file] => /storage/h4/910/1069910/public_html/application/libraries/instagram-php-scraper/vendor/mashape/unirest-php/src/Unirest/Request.php [line] => 236 [function] => send [class] => Unirest\Request [type] => :: [args] => Array ( [0] => GET [1] => https://www.instagram.com/Shutterexplore/media?max_id= [2] => [3] => Array ( ) [4] => [5] => ) ) [1] => Array ( [file] => /storage/h4/910/1069910/public_html/application/libraries/instagram-php-scraper/src/InstagramScraper/Instagram.php [line] => 89 [function] => get [class] => Unirest\Request [type] => :: [args] => Array ( [0] => https://www.instagram.com/Shutterexplore/media?max_id= ) ) [2] => Array ( [file] => /storage/h4/910/1069910/public_html/application/libraries/Lib_instagram.php [line] => 47 [function] => getMedias [class] => InstagramScraper\Instagram [type] => :: [args] => Array ( [0] => Shutterexplore [1] => 30 ) ) [3] => Array ( [file] => /storage/h4/910/1069910/public_html/application/controllers/welcome.php [line] => 46 [function] => get_images [class] => Lib_instagram [type] => -> [args] => Array ( [0] => Shutterexplore [1] => 30 ) ) [4] => Array ( [file] => /storage/h4/910/1069910/public_html/system/core/CodeIgniter.php [line] => 359 [function] => gallery [class] => Welcome [type] => -> [args] => Array ( ) ) [5] => Array ( [file] => /storage/h4/910/1069910/public_html/index.php [line] => 202 [args] => Array ( [0] => /storage/h4/910/1069910/public_html/system/core/CodeIgniter.php ) [function] => require_once ) ) [previous:Exception:private] => )

**Comment by raiym** [comment]
@MrAndiw maybe it is happening because host machine located in different country (with different IP address) and Instagram asks to verify that it is you who has tried to login

**Comment by MrAndiw** [comment]
thanks for the response!! now on my website its worked again and i dont know why :D maybe its a hosting problem
