### ISSUE TITLE
Response code is 200

### ISSUE THREAD

**Issue by Rodeveer** [postaddictme/instagram-php-scraper#741]
When I try this on the production server I get the following error:

[2020-08-07 14:58:43] production.ERROR: InstagramScraper\Exception\InstagramException: Response code is 200. Body: <!DOCTYPE html>

While running tests and looking locally to the posts I can see them. Which is rather odd.

If I check the code I see this following line: `if (!isset($userArray['entry_data']['ProfilePage'][0]['graphql']['user'])) {`. Do I miss something? Or why is this not working on the prod, but working locally?!

And eh, 200 is an OK response, should this just be OK?!

**Comment by dinko** [comment]
Same here.

**Comment by tommy-snellman** [comment]
Same here. We managed to work around it by calling `getMediasByUserId(userId) `instead of `getMedias(instagramProfileName)`.

**Comment by dinko** [comment]
Thx, @tommy-snellman. That does the trick, nice workaround! Hopefully it keeps working…

**Comment by Rodeveer** [comment]
Thanks for the update. Is there also gonna be a release? Or shoul I checkout the master branch from now on? 👍

**Comment by Rodeveer** [comment]
@raiym Nice that this issue is closed. My issue still exists. 
[2020-08-14 14:33:48] production.ERROR: InstagramScraper\Exception\InstagramException: Response code is 200.

**Comment by MehdiMJ1** [comment]
I had the same issue with **getAccount($username)** , I tried to get user id then get stories,  so I fetched the user id from another web service and used it with **getStories([])** , it worked , so the issue is with fetching info from account , please help ..
