### ISSUE TITLE
Response Code 200

### ISSUE THREAD

**Issue by Rodeveer** [postaddictme/instagram-php-scraper#745]
I wrote last week this issue #741. But this Issue is not resolved just yet. The PullRequest that has been made is also not working.

Why is this just happening on the prod environment and not on local development? Both instances of php and packages are exactly the same.

Help would be appreciated! 👍

**Comment by zavodnoyapl1992** [comment]
Can you try use "getAccountInfo"? Are you getting the same error?

**Comment by Rodeveer** [comment]
Yes, I've tried it the way they suggested in the #741 with the getAccountInfo . The PR that was made duplicated sort of that functionality but also tried using that. Both solutions work locally but the moment it goes live or what so, it breaks.

**Comment by zavodnoyapl1992** [comment]
No, it's not duplicate, becouse of method uses different endpoint
Are you use login? And can you give me response html (tag head)?

**Comment by Rodeveer** [comment]
I'm not logging in. The profile I want to get is public. I'll see if I can get the HTML for you later today! I'll respond then again on this ticket.

**Comment by igorconde** [comment]
Same issue here

**Comment by zavodnoyapl1992** [comment]
@lefuturiste @igorconde  try with login and getAccountInfo
Instagram blocked suspicious non-auth requests,  i thinking  in production your application uses famous subnet (aws or similar)

**Comment by zavodnoyapl1992** [comment]
And for production you should use different accounts(for production, for test etc), becouse of instagram check location by ips.
For more reliability use two factor auth (check account email for two factor code parsing, or include something for mobile confirmation, if you use confirmation by phone)

**Comment by lefuturiste** [comment]
I really don't understand because I created a simple and ugly scrapper with file_get_contents().
And it's totally working on both development and production environment.

Code here:
[https://gist.github.com/lefuturiste/a8442b36510ad4ae2b3495a1de23b9ca](https://gist.github.com/lefuturiste/a8442b36510ad4ae2b3495a1de23b9ca)

API: [https://api.werobot.fr/photos](https://api.werobot.fr/photos)

**Comment by zavodnoyapl1992** [comment]
@lefuturiste and now try get profile_picture_url with graphql/query/ :) Look how this scrammer works and what endpoits it use, but I agree, for media maybe graphql/query/ is better solution

**Comment by Rodeveer** [comment]
Thanks @lefuturiste . Gonna test that simple class tomorrow. I really only need the media 👍

**Comment by Rodeveer** [comment]
@zavodnoyapl1992 Will try the login also. But I find it rather sketchy to use a login on a "scraper". If you know what I mean 🤔

**Comment by lefuturiste** [comment]
> Thanks @lefuturiste . Gonna test that simple class tomorrow. I really only need the media 
> 
> Tho I've got a question about that query hash. What is it? How is it generated?

I don't known I think I just copy/paste it from a code somewhere (or my browser network tab). I don't think this is too important

**Comment by Rodeveer** [comment]
@lefuturiste Tried your solution. This works fine. Feels weird to use it this way. The real scraper vibe haha.
Query hash is needed so the graph server knows it comes from a save address. Tried my own hash but that didnt work. 

Yet this doesnt mean that this package problem is solved yet.
