### ISSUE TITLE
Bug in the code

### ISSUE THREAD

**Issue by MadZee-M** [postaddictme/instagram-php-scraper#748]
_Sorry for my English._ 

I found a non-critical error in your code.

**The argument "$nextPage" can be passed here, but it is not used anywhere in the function**
https://github.com/postaddictme/instagram-php-scraper/blob/33db5ca5dcbecdb3bc0d11fc3427d954a55d4085/src/InstagramScraper/Instagram.php#L1400

**I suspect that it should be used here**
https://github.com/postaddictme/instagram-php-scraper/blob/33db5ca5dcbecdb3bc0d11fc3427d954a55d4085/src/InstagramScraper/Instagram.php#L1408

---

**Because, a similar situation here**
https://github.com/postaddictme/instagram-php-scraper/blob/33db5ca5dcbecdb3bc0d11fc3427d954a55d4085/src/InstagramScraper/Instagram.php#L1310

Thank you!😃

**Comment by congkv** [comment]
@MadZee-M The `getPaginateFollowing` function is not working properly. You should use the `getPaginateAllFollowing` instead.

**Comment by MadZee-M** [comment]
@congkv Yes thank you! I figured it out 😺 

I suffered for several hours, it turns out `composer require raiym/instagram-php-scraper` didn't install the latest version.
Had to force install the latest version `composer require raiym/instagram-php-scraper:dev-master` after that new methods appeared (such as the `getPaginateFollowing`)
