### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by slavame** [postaddictme/instagram-php-scraper#75]
Привет!
Установил через composer http://take.ms/uugED
Скопировал файл  index.php в корень запускаю - ошибка

>Warning: Invalid argument supplied for foreach() in /Applications/MAMP/htdocs/insta/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 351

Notice: Undefined index: csrftoken in /Applications/MAMP/htdocs/insta/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 522

Notice: Undefined index: sessionid in /Applications/MAMP/htdocs/insta/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 523

Fatal error: Uncaught InstagramScraper\Exception\InstagramNotFoundException: Account with given username does not exist. in /Applications/MAMP/htdocs/insta/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:418 Stack trace: #0 /Applications/MAMP/htdocs/insta/index.php(48): InstagramScraper\Instagram->getTopMediasByTagName('hello') #1 {main} thrown in /Applications/MAMP/htdocs/insta/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 418

Что я делаю не так?

**Comment by raiym** [comment]
```php
$instagram = Instagram::withCredentials('PASTE_LOGIN', 'PASTE_PASSWORD');
$instagram->login();
```
нужно ввести свой логин и пароль
