### ISSUE TITLE
Proxy ~ Response code is 200

### ISSUE THREAD

**Issue by MarkZuc** [postaddictme/instagram-php-scraper#753]
When using proxi's to scrape instagram accounts/media - i get the following "error":

```
caught Exception: Response code is 200. Body: <!DOCTYPE html>
<html lang="en" class="no-js not-logged-in client-root">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">

<title>
Login • Instagram
</title>
```

I tried both as logged in and not being logged in:

	```
	Unirest\Request::verifyPeer(false);
		$instagram = new \InstagramScraper\Instagram();
		$instagram->withCredentials('IGAccount', 'IGpassword');
		$instagram::setProxy([
		    'address' => '152.xx.xx.140',
		    'port'    => 'xxxx',
		    'tunnel'  => true,
		    'timeout' => 10,
		]);
		$account = $instagram->getAccountInfo('kevin');


Anyone having similar issues or know how to fix it? The proxis in question is datacenter proxies - and should be of a fairly good quality :)

**Comment by jefferylewis** [comment]
I am getting the same error when running at AWS, but not from home (occured on the 1st request)  So I think they are checking high risk address ranges to ensure the requestor has JS enabled.

**Comment by curiousteam** [comment]
Same problem faced.

**Comment by tenet912** [comment]
login before using the script

`$instagrams = \InstagramScraper\Instagram::withCredentials($usermain, $passmain, new Psr16Adapter('Files'));
$instagrams->login();
$instagrams->saveSession();`

**Comment by restyler** [comment]
I've encountered the same issues from my server, this happens because Instagram actively bans datacenter ip ranges. So I've implemented proxified version of scraper, feel free to try it out: https://github.com/restyler/instagram-php-scraper/tree/proxified  (this requires RapidAPI account).
I currently can't reliably recommend it for authenticated calls though - since proxy balancer actively switches ip addresses, and I've heard Instagram may track ip addresses during login.

**Comment by spapapan** [comment]
> I've encountered the same issues from my server, this happens because Instagram actively bans datacenter ip ranges. So I've implemented proxified version of scraper, feel free to try it out: https://github.com/restyler/instagram-php-scraper/tree/proxified (this requires RapidAPI account). I use it successfully for my own project (public Instagram analyzer bot https://t.me/instalyzebot ) I currently can't reliably recommend it for authenticated calls though - since proxy balancer actively switches ip addresses, and I've heard Instagram may track ip addresses during login.

@restyler The link for your instagram-php-scraper is broken. Do you have it somewhere else?
