### ISSUE TITLE
Response code is 200

### ISSUE THREAD

**Issue by sareban101** [postaddictme/instagram-php-scraper#756]
hi 

i use this sample:
'$instagram = new \InstagramScraper\Instagram();
$nonPrivateAccountMedias = $instagram->getMedias('kevin');
echo $nonPrivateAccountMedias[0]->getLink();`

but

Uncaught InstagramScraper\Exception\InstagramException: Response code is 200. Body: <!DOCTYPE html>
<html lang="en" class="no-js not-logged-in client-root">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

<title>
Login • Instagram
</title>

please help me``

**Comment by amurzaliev** [comment]
I get the same error

**Comment by masnatacion** [comment]
me too

**Comment by altuhovsu** [comment]
Seems Instagram blocks too much IPs

**Comment by curiousteam** [comment]
Same problem faced.

**Comment by tenet912** [comment]
after instagram new update , you must login first to use script . in first login after that you can use script 

`$instagrams = \InstagramScraper\Instagram::withCredentials($usermain, $passmain, new Psr16Adapter('Files'));
$instagrams->login();
$instagrams->saveSession();`

**Comment by MagnusTv** [comment]
I've made this:
`try {
    $instagram = Instagram::withCredentials('sneak.week', 'PASSWORD', new Psr16Adapter('Files'));
    $instagram->login();
    $instagram->saveSession();
} catch (InstagramAuthException $e) {} catch (InstagramException $e) {} catch (\Psr\SimpleCache\InvalidArgumentException $e) {}`

And always get this error: 
> InstagramScraper\Exception\InstagramException: Response code is 200. Body:
Something went wrong. Please report issue. in /home/webpages/lima-city/minekoss/beta.sneak-week.de/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:461 Stack trace: #0 /home/webpages/lima-city/minekoss/beta.sneak-week.de/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php(432): InstagramScraper\Instagram->getAccount('sneak.week') #1 /home/webpages/lima-city/minekoss/beta.sneak-week.de/assets/test.php(11): InstagramScraper\Instagram->getMedias('sneak.week') #2 {main}

I don't know why

**Comment by glushko3707** [comment]
InstagramScraper\Exception\InstagramException
Response code is 200: OK.Something went wrong. Please report issue.


Now this problem is relevant to me.
