### ISSUE TITLE
Found this error when use getTopMediasByTag() and getMediasByTag(). Caching user session

### ISSUE THREAD

**Issue by javagose** [postaddictme/instagram-php-scraper#76]
After several request (5 request or more) i get this error:

Catchable fatal error:  Object of class stdClass could not be converted to string in
C:\xampp\htdocs\instagram\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php 
 on line 519

**Comment by jonahfuller** [comment]
Getting the same error... dumping the $response var seems to be a security check from instagram... to verify that you are logging in to your account... Not sure the way around this

**Comment by raiym** [comment]
@javagose and @jonahfuller 
thank you for comments
In several mins I will push update and release new version which include session caching. Could you please check how new version works for you? 
Thanks

**Comment by jonahfuller** [comment]
So far so good... I'll update if I find any issues. Thanks again for your continued work on this... Library is just what I needed to build my hashtaged photos wall.

**Comment by pinotarantino** [comment]
Hello Raym and thank you for your job! 
I had the same issue, I followed your instruction (updated your version to 0.5.3 with composer; added the path for the cache) but I get the same error. 
This happens with php 7.1 and centOS 7 (if this could help you).
Thank you again!
P;)

**Comment by raiym** [comment]
@pinotarantino strange.
Can you please give more info about your situation. 

What exactly you do? (How many requests you send, how frequently, what is delay time)

**Comment by pinotarantino** [comment]
Hello Raiym, 
this issue happens immediatly, at the first request of top media by tags.
The issue happens with 'use phpFastCache\CacheManager' or without it. 
Note that I've the problem of SSL certificate, issue #63 (if this could matter).

Here you are an extract of my code, if this could help you:

"...
require '/root/vendor/autoload.php';

use phpFastCache\CacheManager;

Unirest\Request::verifyPeer(false);

use InstagramScraper\Instagram ;

$instagram = Instagram::withCredentials('pxxxxxx', 'pxxxxxxx', '/var/www/html/socialtool');
$instagram->login();
...
$medias_top = Instagram::getTopMediasByTagName("$kw");
..."

Thanks a lot!
P;)

**Comment by pinotarantino** [comment]
A clarification about SSL: I noticed now that with centOS, if I don't use 'Unirest\Request::verifyPeer(false)', it woks fine. I had the error of issue #63 in a previous project version developed on WAMP server. With Linux/Lamp the problem off SSL doesn't occur.

Thaks
P;)

**Comment by pinotarantino** [comment]
Problem solved if I make the call from the same IP I used when I registered my account on Istagram...;)

**Comment by javagose** [comment]
i still get the same error  
```
Object of class stdClass could not be converted to string in
C:\xampp\htdocs\instascrapper\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php on line
525
```
what i'm trying to build a website let users scrapp instagram content, so i build different php files, each file is calling a different Instgram.php Method.

for example, getTopMediasByTag.php call getTopMediasByTag(tags), getUserMedias.php calls getMedias(username), getUser.php call getAccount(username) ... etc

In each file i use 
```
$instagram = Instagram::withCredentials('PASTE_LOGIN', 'PASTE_PASSWORD', '/path/to/folder/');
$instagram->login();
```

**Comment by peyvand** [comment]
require('autoload.php');

use InstagramScraper\Instagram;
Unirest\Request::verifyPeer(false);

$instagram = Instagram::withCredentials('username', 'password', '/cached');
$instagram->login();
