### ISSUE TITLE
No examples work

### ISSUE THREAD

**Issue by NeoTechni** [postaddictme/instagram-php-scraper#760]
$instagram = \InstagramScraper\Instagram::withCredentials('username', 'password');
result: withCredentials must have 3 parameters

$instagram = new \InstagramScraper\Instagram();
result: Instagram function does not exist

**Comment by WebPajooh** [comment]
I have the first problem too.
What is the cache interface?

**Comment by nidaniel** [comment]
composer require phpfastcache/phpfastcache will fix "result: withCredentials must have 3 parameters" issue you have

**Comment by NeoTechni** [comment]
I don't have access to composer
