### ISSUE TITLE
 if (!isset($userArray['entry_data']['ProfilePage'][0]['graphql']['user'])) {              throw new InstagramException('Response code is ' . $response->code . '. Body: ' . static::getErrorBody($response->body) . ' Something went wrong. Please report issue.', $response->code);          }

### ISSUE THREAD

**Issue by kewcode** [postaddictme/instagram-php-scraper#770]
![image](https://user-images.githubusercontent.com/46804248/93325967-56710980-f842-11ea-9a5e-1df5733c4f00.png)
![image](https://user-images.githubusercontent.com/46804248/93325979-5b35bd80-f842-11ea-962b-f5b496d7e489.png)

**Comment by cuchac** [comment]
Started to receive same error.
I've fixed it by logging to account using web browser and confirming some popup windows. After that, everything is working again.

**Comment by crazyfree** [comment]
thanks @cuchac it works

**Comment by restyler** [comment]
I've encountered the same issues from my server, this happens because Instagram actively bans datacenter ip ranges. So I've implemented proxified version of scraper, feel free to try it out: https://github.com/restyler/instagram-php-scraper/tree/proxified
