### ISSUE TITLE
there is no return session

### ISSUE THREAD

**Issue by fastcd** [postaddictme/instagram-php-scraper#780]
getCacheKey() don't work properly
Cache and cookies saved in the file, but it can't access. So I notice reconnect after query, it's no sense to use savesession();

https://github.com/postaddictme/instagram-php-scraper/blob/71b85009f514c2c71bad52c9e4b767c29fc373c2/src/InstagramScraper/Instagram.php#L1647

**Comment by fastcd** [comment]
Ok, I fixed it by adding a path to the project folder, but there are 3 queries for 1 query - getAccount
I mean phpfastcache keep my session by previous query, but after the next run, it does 3 queries again instead 1.

**Comment by congkv** [comment]
@fastcd Can you create a pull request to fix it?

**Comment by fastcd** [comment]
> @fastcd Can you create a pull request to fix it?

I use @aporat branch, https://github.com/postaddictme/instagram-php-scraper/pull/768
It's working well, but the session lives only  15 minutes. And he removed TwoStepVerification..

**Comment by aporat** [comment]
I dont have any issues with short sessions. Are you sure you're setting TTL on the cache?


    $instance_cache = CacheManager::getInstance('Files', new Config([
      'path' => realpath(__DIR__.'/../../../storage/app/'),
      'defaultTtl' => 0
    ]));

I removed TwoStepVerification because it didn't login at all for me and the code associated with it was hard to work with.

**Comment by fastcd** [comment]
> I dont have any issues with short sessions. Are you sure you're setting TTL on the cache?
> 
> ```
> $instance_cache = CacheManager::getInstance('Files', new Config([
>   'path' => realpath(__DIR__.'/../../../storage/app/'),
>   'defaultTtl' => 0
> ]));
> ```
> 
> I removed TwoStepVerification because it didn't login at all for me and the code associated with it was hard to work with.

Thank you, it helped me!

Did you try to debug TwoStepVerification? I explored that Instagram requires the two-step auth after 300-500 queries to profiles.
