### ISSUE TITLE
login error on remote host

### ISSUE THREAD

**Issue by shahreahang** [postaddictme/instagram-php-scraper#781]
Hello,

the script works fine in my localhost but when I try to login on my remote host it give me this error 

Fatal error: Uncaught InstagramScraper\Exception\InstagramAuthException: $twoStepVerificator must be an instance of TwoStepVerificationInterface. 
......
: InstagramScraper\Instagram->login() #2 {main} thrown in

**Comment by mohammadrezajiji** [comment]
i have this problam too

**Comment by erfanmola** [comment]
+

**Comment by jasomdotnet** [comment]
Same here,

```
PHP Fatal error:  Uncaught InstagramScraper\Exception\InstagramAuthException: $twoStepVerificator must be an instance of TwoStepVerificationInterface. in /var/www/html/ig/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:1783
Stack trace:
#0 /var/www/html/ig/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php(1683): InstagramScraper\Instagram->verifyTwoStep(Object(Unirest\Response), Array, NULL)
#1 /var/www/html/ig/index.php(114): InstagramScraper\Instagram->login()
#2 {main}
  thrown in /var/www/html/ig/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 1783
```
Instagram added some kind of 2 step login verification since 26.9.2020. Login using this php lib seems to be "suspicious".

**Comment by APTEMOH** [comment]
Такая же беда. Что делать?

**Comment by wowagenciacriativa** [comment]
some idea?

**Comment by popmatik** [comment]
I've also had this problem. Any ideas? Have Instagram changed something? Thanks.

**Comment by APTEMOH** [comment]
No!
Update some lib and OK

**Comment by jasomdotnet** [comment]
word "some" makes your answer useless

**Comment by bonzinho** [comment]
same problem here

**Comment by jordan26** [comment]
I have this issue too, any progress on a fix?

**Comment by elope-developers** [comment]
having same issue. Unsure what to add to init test file. Project structure a little confusing to get setup

**Comment by sfatfarma** [comment]
Probably, Instagram has marked your account as suspicious, or you are logging in from a non-standard location. There are three solutions to this problem:

1. You have to use InstagramScraper\Instagram::login(false, true). Second flag (true) enables two step verification. You need to enter the code to console after it is sent.

2. Use function $instagram->setUserAgent($userAgent);, enter the useragent you usually use to login in instagram. Also check example file https://github.com/postaddictme/instagram-php-scraper/blob/master/examples/setCustomCookies.php. For more complex work with this scraper you have to save coockies and set custom in each login.

3. Check this file, if you need security code by email auto comfirm. https://github.com/postaddictme/instagram-php-scraper/blob/master/examples/twoStepAutoVerification/loginWithEmailAutoCponfirm.php
