### ISSUE TITLE
How to get someone's stories?

### ISSUE THREAD

**Issue by fmchan** [postaddictme/instagram-php-scraper#786]
There is a method of getting all stories but how to get specified user's stories?

**Comment by pilarik31** [comment]
You need to have logged in `Instagram` instance. In this case - it's `$instagram`.
```
// Specified user
$username = 'instagram';
$userId = $instagram->getAccountInfo($username)->getId();
```


This line retrieves array of `UserStories`. On that first element, we call `getStories()` to get an array of `Story`.
```
$stories = $instagram->getStories([$userId])[0]->getStories();
```
Now we can process the array of single stories. On these, you can call [Media methods](https://github.com/postaddictme/instagram-php-scraper/blob/cd9e475c83552f12b612416fb5a6b9ee2255f136/src/InstagramScraper/Model/Media.php#L233-L504).
```
foreach ($stories as $story) {
    var_dump($story->getImageHighResolutionUrl());
}
```
