### ISSUE TITLE
Media with this code does not exist

### ISSUE THREAD

**Issue by mohsenzia** [postaddictme/instagram-php-scraper#790]
Today I get this error: Fatal error: Uncaught InstagramScraper\Exception\InstagramException: Media with this code does not exist in ../vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:650

The $response of getMediaByUrl method has 200 status code, and some html code in raw_body!

This is my code:
`require 'include/InstagramScraper/vendor/autoload.php';
require 'include/Psr/vendor/autoload.php';
use Phpfastcache\Helper\Psr16Adapter;

$instagram = \InstagramScraper\Instagram::withCredentials('VALID USERNAME', 'VALID PASSWORD', new Psr16Adapter('Files'));
$instagram->login();
sleep(2); // Delay to mimic user

$media = $instagram->getMediaByUrl('VALID LINK');`

My code worked until yesterday!
Do I have to change anything?

**Comment by jeybin** [comment]
@mohsenzia , 
Can you please check is the function **getMediaById($mediaId)** is working with you or not.
If it the above function works with you, there will be something wrong in the **VALID LINK** that you are sending 
```
// actual function
    public function getMediaById($mediaId) {
        $mediaLink = Media::getLinkFromId($mediaId);
        return $this->getMediaByUrl($mediaLink);
    }

```

Please try

**Comment by mohsenzia** [comment]
Hi @jeybin 
Thanks for your reply. My problem was that my server was blocked by Instagram.
I'm sorry I didn't close this ticket.
