### ISSUE TITLE
Response code is 429 - Page Not Found / Please wait a few minutes before you try again

### ISSUE THREAD

**Issue by Zauberfisch** [postaddictme/instagram-php-scraper#791]
This previously working code now throws an exception:

```
$instagram = new \InstagramScraper\Instagram();
$medias = $instagram->getMedias('my-account', 8);
```
My installed version is: `v0.9.14` but I also tried `dev-master`

I get an exception:
```
Warning at vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php line 454: Response code is 429. Body: <!DOCTYPE html>
<html lang="en" class="no-js not-logged-in ">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title>
                  Page Not Found &bull; Instagram
                </title>

[...]
Error

Please wait a few minutes before you try again.
[...]
    </body>
</html>
 Something went wrong. Please report issue. (http://www.example.org/de/blog/)
```

Based on the content/message, this could very well be a throttling attempt by instagram to fight against scrapers like this.  
But if that's the case, could this be detected and a special exception be thrown?  
(but I am not sure because I still get the same response after waiting for a while)

The full exception message: https://paste.zauberfisch.com/t/5f85e00ce6bad/error.log.txt

**Comment by Zauberfisch** [comment]
Ok, should have tried that right away: It appears that this hosts IP address might be blacklisted. Switching to a different host it works again.

**Comment by Zauberfisch** [comment]
My issue is therefore resolved, but it might still be worth to keep this issue open and add a special exception for this response

**Comment by Simpleton350** [comment]
I ran into this today and it actually does throw an InstagramException. You can use `$exception->getCode()` to find out if it is HTTP 429 or something else.

**Comment by Zauberfisch** [comment]
Fair enough. I knew it was an exception, but didn't check the code. Thanks
