### ISSUE TITLE
Как получить сам текст комментария? | How to get the text of the comment itself?

### ISSUE THREAD

**Issue by APTEMOH** [postaddictme/instagram-php-scraper#794]
Как получить сам текст комментария? | How to get the text of the comment itself?

```
Exsamlpe: $instagram->getMediaByCode('***');

Number of comments: 3
Number of likes: 56
```

Только не количество, а именно кто прокомментировал и что написал. | Only not the number, but exactly who commented and what they wrote.

**Comment by jeybin** [comment]
Hi @APTEMOH ,

Try 
`$instagram->getMediaCommentsByCode($mediaCode, $count = 10, $maxId = null)`
