### ISSUE TITLE
Save and load session from text file

### ISSUE THREAD

**Issue by tschni** [postaddictme/instagram-php-scraper#797]
Is it possible to save the session (cookies?) in a text file & read and use it the next time the client is called?

Currently I use the following function to log in, but the cache doesn't seem to work because it tries to log in with every call:
```
public function login(string $username, string $password): \InstagramScraper\Instagram {
    $instagramSession = \InstagramScraper\Instagram::withCredentials($username, $password, new Psr16Adapter('Files'));
    $instagramSession->login();
    $instagramSession->saveSession();
    return $instagramSession;
}
```

I want to login via CLI (because of two-factor authentication) and use the saved session for various cron jobs.

**Comment by jeybin** [comment]
Hi @tschni,

You can save the value from $instagramSession into webpage session.

Since you are using the cron jobs, try to save the $cookies value from the login function 
 (line number: 1669 ) inside `vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php` 
to the database and whenever you need the instagram session pass the saved  $cookies from database through
generateHeaders() function (line number:200)

**Comment by tschni** [comment]
Hi @jeybin,

thanks for your comment.

I have tried it as follows:
```php
$cache = new Psr16Adapter('Files');
$igSession = Instagram::withCredentials($_ENV['INSTAGRAM_USERNAME'], $_ENV['INSTAGRAM_PASSWORD'], $cache);
$igSession->login(true, true);
$igSession->saveSession();

echo $cache->get(md5($_ENV['INSTAGRAM_USERNAME'])); // display the cookies
```

My response (formatted to json) is unfortunately always empty:
```json
{
   "mid":"",
   "ig_did":"\"\"",
   "urlgen":"\"\"",
   "csrftoken":"\"\""
}
```

I am trying to log in via cli & must enter a confirmation code, which I receive by e-mail:
```
λ php commander instagram:create-session
Select where to send security code
Phone: +49 **** *****23 - 0
Email: b*******s@s*****.de - 1
Your choice: 1
Enter security code: xxxxxx
```

Do you have an idea what this might be due to? Does the login with e-mail verification possibly fail?
