### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by albertorizzi** [postaddictme/instagram-php-scraper#799]
Hi,
I'm using the example of the code.
If I use the example of the pages `getAccountById.php` and `getAccountByUsername.php`, they don't work.
I think that the example `getAccountById.php` doesn't work because It uses the method `getAccount('account')` of `getAccountByUsername.php`, that doesn't work.

The error of `getAccountByUsername.php` is:
`Fatal error: Uncaught InstagramScraper\Exception\InstagramException: Response code is 302. Body: Something went wrong. Please report issue. in /membri/albertorizzi/scraper/src/InstagramScraper/Instagram.php:426 Stack trace: #0 /membri/albertorizzi/scraper/examples/getAccountByUsername.php(10): InstagramScraper\Instagram->getAccount('account') #1 {main} thrown in /membri/albertorizzi/scraper/src/InstagramScraper/Instagram.php on line 426`

The error of `getAccountById.php` is:
`Fatal error: Uncaught InstagramScraper\Exception\InstagramException: Response code is 302. Body: Something went wrong. Please report issue. in /membri/albertorizzi/scraper/src/InstagramScraper/Instagram.php:426 Stack trace: #0 /membri/albertorizzi/scraper/src/InstagramScraper/Instagram.php(889): InstagramScraper\Instagram->getAccount('account') #1 /membri/albertorizzi/scraper/examples/getAccountById.php(4): InstagramScraper\Instagram->getAccountById('id_account') #2 {main} thrown in /membri/albertorizzi/scraper/src/InstagramScraper/Instagram.php on line 426`

**Is there someone who can help me?**
Thank you

**Comment by Theder** [comment]
You are faced with this problem because Instagram does not allow you to visit any profile without authorization. 
Probably, if you log in or change ip. 

"Response code is 302" means that you're redirecting to log in page, and this this situation are not handled.

**Comment by albertorizzi** [comment]
Thank you very much!
I have solved this problem!

If someone needs, you must enter the code of log in the page.

**Comment by jerearaujo03** [comment]
How did you solved?

**Comment by albertorizzi** [comment]
> How did you solved?

You must insert in the page the authentication with username and password.
