### ISSUE TITLE
"Something went wrong. Please report issue." on OVH but not in local

### ISSUE THREAD

**Issue by leogarret** [postaddictme/instagram-php-scraper#803]
When I login to instagram with credentials, it work, but not on OVH :

`Fatal error: Uncaught InstagramScraper\Exception\InstagramAuthException: Something went wrong. Please report issue. in /home/ovhuser/www/Espyon/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:1689 Stack trace: #0 /home/ovhuser/www/Espyon/RealTimeInstagramAPI/RealTimeInstagramAPI.php(31): InstagramScraper\Instagram->login() #1 /home/ovhuser/www/Espyon/cron/compute_sponsored_content.php(15): Espyon\RealTimeInstagramAPI->login('*********', '**********', Object(Phpfastcache\Helper\Psr16Adapter)) #2 {main} thrown in /home/ovhuser/www/Espyon/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 1689`

The exactly same code work normaly on my computer.

**Comment by ujin001** [comment]
I have same problem

**Comment by janbarasek** [comment]
I have some problem, exception callstack is:

![Snímek obrazovky 2020-11-05 v 13 04 13](https://user-images.githubusercontent.com/4738758/98238915-6914de80-1f67-11eb-93c1-b359ab72c499.png)

I tried dump `$response` entity and server value is:

![Snímek obrazovky 2020-11-05 v 13 04 52](https://user-images.githubusercontent.com/4738758/98238963-7fbb3580-1f67-11eb-92c9-b22a73430bec.png)

Full value:

```
InstagramScraper\Http\Response #4f8b
code => 302
raw_body => ""
body => ""
headers => array (21)
Content-Type => array (1)
0 => "text/html; charset=utf-8"
Location => array (1)
0 => "https://www.instagram.com/accounts/login/?next=/clevermindseu/"
Vary => array (1)
0 => "Accept-Language, Cookie"
Content-Language => array (1)
0 => "en"
Date => array (1)
0 => "Thu, 05 Nov 2020 11:49:03 GMT"
Strict-Transport-Security => array (1)
0 => "max-age=31536000"
Cache-Control => array (1)
0 => "private, no-cache, no-store, must-revalidate"
Pragma => array (1)
0 => "no-cache"
Expires => array (1)
0 => "Sat, 01 Jan 2000 00:00:00 GMT"
X-Frame-Options => array (1)
0 => "SAMEORIGIN"
content-security-policy => array (1)
0 => "report-uri https://www.instagram.com/security/csp_report/; default-src 'self' https://www.instagram.com; img-src data: blob: https://*.fbcdn.net https ... "
X-Content-Type-Options => array (1)
0 => "nosniff"
X-XSS-Protection => array (1)
0 => "0"
x-ig-push-state => array (1)
0 => "c2"
x-aed => array (1)
0 => "30"
Access-Control-Expose-Headers => array (1)
0 => "X-IG-Set-WWW-Claim"
Set-Cookie => array (7)
0 => "csrftoken=""; Domain=instagram.com; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/"
1 => "csrftoken=""; Domain=.instagram.com; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/"
2 => "csrftoken=""; Domain=i.instagram.com; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/"
3 => "csrftoken=""; Domain=.i.instagram.com; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/"
4 => "csrftoken=""; Domain=www.instagram.com; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/"
5 => "csrftoken=""; Domain=.www.instagram.com; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/"
6 => "csrftoken=""; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/"
X-FB-TRIP-ID => array (1)
0 => "1679558926"
Alt-Svc => array (1)
0 => "h3-29=":443"; ma=3600,h3-27=":443"; ma=3600"
Connection => array (1)
0 => "keep-alive"
Content-Length => array (1)
0 => "0"
```

Thanks.

**Comment by igorbelikov** [comment]
```
{"message": "rate limited", "status": "fail"}
```

😢

**Comment by thomasbandit** [comment]
I guess OVH IPs are restricted. See this comment for more info and a possible solution:
https://github.com/postaddictme/instagram-php-scraper/issues/770#issuecomment-701519566

**Comment by bonzinho** [comment]
same problem, works only in localhost, i try some servers and same error

**Comment by 5baddi** [comment]
Also only work on localhost, tired to downgrade to v0.9.10 it's work but after a while get terms/unblock response.

**Comment by ujin001** [comment]
I installed last instagram-php-scraper version with cache, registered new instagram account and set delay between queries.
Also I approve activity on page https://www.instagram.com/session/login_activity/ every day.

It works

**Comment by restyler** [comment]
Instagram redirects to /login in case it thinks the ip is suspicious. All data centers and most of proxies are already banned.
Even residential proxies are actively banned by Instagram every day.  Take a look at https://github.com/restyler/instagram-php-scraper which is the proxified version of this scraper, it uses smart proxy network with retries under the hood (but this is applicable only if you need to access public accounts and content).
