### ISSUE TITLE
Can't use methods.

### ISSUE THREAD

**Issue by Fuadtag** [postaddictme/instagram-php-scraper#806]
Want to get media or followers of account.But response is 'Something went wrong. Please report issue.'

**Comment by igorbelikov** [comment]
```
{"message": "rate limited", "status": "fail"}
```

@Fuadtag do you have same response too?

**Comment by LuckyKing0307** [comment]
I have same problems with getMediaCommentsByCode,getMediaLikesByCode HELP PLS

**Comment by igorbelikov** [comment]
@LuckyKing0307 same issue(

**Comment by LuckyKing0307** [comment]
@igorbelikov,@raiym instagram did that we should login for parse contents.If u try open list of like or comments in instagram with out login(i think no one couldn't) :)

**Comment by Fuadtag** [comment]
@LuckyKing0307 Tried to get data after instagram login but nothing changed 😀

**Comment by LuckyKing0307** [comment]
@Fuadtag i think it is not work with getcomments and likes

**Comment by igorbelikov** [comment]
yes, I understand, but if you try to open comments as anonym for some publication in web version — you get all comments, but in graph api we have error, I think we should modify request headers

**Comment by LuckyKing0307** [comment]
@igorbelikov i need list of likes,but comment doesn't not working too

**Comment by Fuadtag** [comment]
Actually i can get user information but followers and following count are 0.

**Comment by igorbelikov** [comment]
@LuckyKing0307, I too

**Comment by LuckyKing0307** [comment]
can i send code?

**Comment by LuckyKing0307** [comment]
require 'vendor/autoload.php';
use Phpfastcache\Helper\Psr16Adapter;
$likes = array();
$instagram = \InstagramScraper\Instagram::withCredentials(new \GuzzleHttp\Client(), 'username', 'pass', new Psr16Adapter('Files'));
$instagram->login();

$comments = $instagram->getMediaCommentsByCode('BG3Iz-No1IZ', 10);


print_r($comments);

**Comment by LuckyKing0307** [comment]
that is working

**Comment by LuckyKing0307** [comment]
<?php
require 'vendor/autoload.php';
use Phpfastcache\Helper\Psr16Adapter;
$likes = array();
$instagram = \InstagramScraper\Instagram::withCredentials(new \GuzzleHttp\Client(), 'username', 'pass', new Psr16Adapter('Files'));
$instagram->login();

$comments = $instagram->getMediaLikesByCode('BG3Iz-No1IZ', 10);


print_r($comments);

**Comment by LuckyKing0307** [comment]
<?php
require 'vendor/autoload.php';
use Phpfastcache\Helper\Psr16Adapter;
$likes = array();
$instagram = \InstagramScraper\Instagram::withCredentials(new \GuzzleHttp\Client(), 'user', 'pass', new Psr16Adapter('Files'));
$instagram->login();
$comments = $instagram->getMediaLikesByCode('BG3Iz-No1IZ', 10);
print_r($comments);
that for likes works too

**Comment by Fuadtag** [comment]
Tried that but still cant get media by code.Error is 'Media with this code does not exist'
