### ISSUE TITLE
Class 'GuzzleHttp\Client' not found

### ISSUE THREAD

**Issue by kiskaserver** [postaddictme/instagram-php-scraper#809]
use Phpfastcache\Helper\Psr16Adapter;

$instagram = \InstagramScraper\Instagram::withCredentials(new GuzzleHttp\Client(), 'username', 'password', new Psr16Adapter('Files'));
$instagram->login();
$instagram->saveSession();

Error:  Fatal error: Uncaught Error: Class 'GuzzleHttp\Client' not found in W:\domains\insta-api.com\index.php:7 Stack trace: #0 {main} thrown in W:\domains\insta-api.com\index.php on line 7

**Comment by alabamaster** [comment]
And me exist this problem

**Comment by nekudo** [comment]
The guzzle dependency is missing. Jou can solve this by adding it using composer: `composer require guzzlehttp/guzzle`

**Comment by alabamaster** [comment]
install composer "require phpfastcache/phpfastcache" + "composer require guzzlehttp/guzzle" and successfully

**Comment by kiskaserver** [comment]
Thx all!!
