### ISSUE TITLE
Call to a member function get() on string

### ISSUE THREAD

**Issue by iFrez** [postaddictme/instagram-php-scraper#813]
Error: Call to a member function get() on string in file /vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 1647

#0 /app/Http/Controllers/ApiController.php(75): InstagramScraper\Instagram-&gt;login()

**Comment by adrianosmateus** [comment]
Same problem.

Call to a member function get() on string

/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:1647

**Comment by den-dev-icmy** [comment]
update package to latest. and add first argument \InstagramScraper\Instagram::withCredentials(new \GuzzleHttp\Client(), $login, $pass, $cache);

**Comment by listdev** [comment]
Same problem here

**Comment by filippodicostanzo** [comment]
Same problem here

Any solution?

**Comment by listdev** [comment]
> Same problem here
> 
> Any solution?

[This is what it fixed it for me mate](https://github.com/postaddictme/instagram-php-scraper/issues/822#issuecomment-735919239)
