### ISSUE TITLE
class Phpfastcache\Helper\Psr16Adapter

### ISSUE THREAD

**Issue by hosein79** [postaddictme/instagram-php-scraper#817]
Hi, I have a problem with this line
This is what I write
use Phpfastcache \ Helper \ Psr16Adapter;
This shows the error
Fatal error: Uncaught Error: Class 'Phpfastcache\Helper\Psr16Adapter' not found in D:\Wamp\www................................

**Comment by NimaN2D** [comment]
`composer require phpfastcache/phpfastcache`

**Comment by NimaN2D** [comment]
Duplicate of #558

**Comment by NimaN2D** [comment]
Duplicate of #558
Google.com is your best friend <3
