### ISSUE TITLE
Instagram access places

### ISSUE THREAD

**Issue by albertorizzi** [postaddictme/instagram-php-scraper#819]
Hi,
I would ask if using Instagram PHP scraper is right that the access is from this place?
Can Instagram blocked my account because this place isn't in my country?
Any advice to enhance this problem?

Thanks

![Screenshot_2020-11-26-09-22-09-758_com instagram android](https://user-images.githubusercontent.com/48057685/100325661-3a6bb000-2fc9-11eb-8261-5ede3da1c052.jpg)
![Screenshot_2020-11-26-09-22-15-144_com instagram android](https://user-images.githubusercontent.com/48057685/100325669-3c357380-2fc9-11eb-9b0a-dfcc2864ed33.jpg)

**Comment by jackaru** [comment]
I had the same issue, if you're running it on a local server there should not be any issue, otherwise consider using a safe proxy for instagram close to you. Instagram can be suspicious with many logins from strange places
