### ISSUE TITLE
Something went wrong. Please report issue.

### ISSUE THREAD

**Issue by iskrenpanteleev** [postaddictme/instagram-php-scraper#822]
Nothing can be obtained from Instagram anymore (tested with the current version and an older one). All the requests were made with residential proxies and still can not get any data. The response is:
Response code is 200.
Body: Something went wrong. Please report issue.

**Comment by 5baddi** [comment]
The same here. work only on localhost!

**Comment by listdev** [comment]
> The same here. work only on localhost!

I downgraded back to v0.9.10, used authentication and a residential proxy, and seems to work fine.

**Comment by jordan26** [comment]
@listdev - Would you be able to provide a code snippet of what is working for you?

**Comment by restyler** [comment]
I think Instagram just tightens their ip ranges bans so it's getting really tricky to get results unless you are not using your own residential network (which is not always feasible) and low req rates. Take a look at https://github.com/restyler/instagram-php-scraper which is the proxified version of this scraper using https://rapidapi.com/restyler/api/instagram40 under the hood, it uses smart proxy network and manages to get 95 of 100 reqs successfully even in the current situation.

**Comment by facuquilmes123** [comment]
Dont work for me
