### ISSUE TITLE
Fatal error: Uncaught InstagramScraper\Exception\InstagramException: Response code is 302. 

### ISSUE THREAD

**Issue by kagandev** [postaddictme/instagram-php-scraper#823]
My code is:

```
`require __DIR__ . '/vendor/autoload.php';
ini_set('display_errors', 1);
error_reporting(E_ALL);

$instagram = new \InstagramScraper\Instagram(new \GuzzleHttp\Client());

// For getting information about account you don't need to auth:

$account = $instagram->getAccount('kevin');

// Available fields
echo "Account info:\n";
echo "Id: {$account->getId()}\n";
echo "Username: {$account->getUsername()}\n";
echo "Full name: {$account->getFullName()}\n";
echo "Biography: {$account->getBiography()}\n";
echo "Profile picture url: {$account->getProfilePicUrl()}\n";
echo "External link: {$account->getExternalUrl()}\n";
echo "Number of published posts: {$account->getMediaCount()}\n";
echo "Number of followers: {$account->getFollowsCount()}\n";
echo "Number of follows: {$account->getFollowedByCount()}\n";
echo "Is private: {$account->isPrivate()}\n";
echo "Is verified: {$account->isVerified()}\n";`
```

It was working until 30 minutes ago. I can't understand why.

**Comment by goldfischart** [comment]
We have the same issue. Nearly ever request end in a 302 Error

**Comment by ddrv** [comment]
set follow redirects for your http client (you may use [webclient/ext-redirect](https://packagist.org/packages/webclient/ext-redirect) library)

**Comment by restyler** [comment]
If you are trying to access public account, chances are your ip just got banned by Instagram, so it redirects you to /login page when you try to access profile page. Take a look at proxified version of this scaper to mitigate the issue. https://github.com/restyler/instagram-php-scraper

**Comment by nalin88** [comment]
then how do we login on instagram with server IP?? i tried to login with this code 
```
$instagram = \InstagramScraper\Instagram::withCredentials(new \GuzzleHttp\Client(), 'its._nalin_', 'nalin@90027', new Psr16Adapter('Files'));
$instagram->login();
```
but it gives error because I need to verify it with server IP using opt or what so ever method... please guide us ... lot of us are facing the same issue

**Comment by rangelrmorais** [comment]
Same here
`
Warning: Undefined property: stdClass::$authenticated in /home/xxx/public_html/wp-content/themes/Newspaper-child/includes/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 2206

Fatal error: Uncaught InstagramScraper\Exception\InstagramAuthException: User credentials are wrong. in /home/xxx/public_html/wp-content/themes/Newspaper-child/includes/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:2207 Stack trace: #0 /home/xxx/public_html/wp-content/themes/Newspaper-child/includes/get.php(13): InstagramScraper\Instagram->login() #1 {main} thrown in /home/xxx/public_html/wp-content/themes/Newspaper-child/includes/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 2207`
