### ISSUE TITLE
where to execute code?

### ISSUE THREAD

**Issue by WebDevMike2018** [postaddictme/instagram-php-scraper#828]
I'm following the example to get account by user name but I don't know where to put this code. Any help would be greatly appreciated.
```
$instagram = new \InstagramScraper\Instagram(new \GuzzleHttp\Client());
$account = $instagram->getAccount('myspacetom');
```

**Comment by NimaN2D** [comment]
If you are in a deploy/testing environment, put in index.php and check your codes!
BUT if you are in a production environment, It could be better to use Queues for your requests and process in the background.
