### ISSUE TITLE
Getting Comments by Code is not working or has error

### ISSUE THREAD

**Issue by ALEX8C** [postaddictme/instagram-php-scraper#83]
$comments = Instagram::getMediaCommentsByCode('BR5Njq1gKmB',1000); is returning following error:

Fatal error: Using $this when not in object context in /vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 262

**Comment by raiym** [comment]
@ALEX8C since v0.5.* to get comments you must provide instagram credentials
and now method  is not static $instagram->getMediaCommentsByCode('BR5Njq1gKmB',1000);

**Comment by raiym** [comment]
I have added test case. You can check it on: 
589f44732e38c36ae9a9564e9c58bbae3a5e0212
