### ISSUE TITLE
How to get user's reels?

### ISSUE THREAD

**Issue by VarroReve** [postaddictme/instagram-php-scraper#842]
Hi, I'd like to scrape Instagram user's REELS. I overview the codes and I didn't find how to make it.
Have u considered add the REELS feature to the scraper?

**Comment by ricdijk** [comment]
From: https://stackoverflow.com/questions/63306324/does-instagram-reels-have-an-api-for-developers:

Reels it is IG Media with type "VIDEO". And you can fetch single "Reels" if you know his Facebook Media ID (It is not Media ID from instagram)


I think Reels are visible in user media ad type video, see e.g. mediaId: 2479643471846214320 from user Memezar.
