### ISSUE TITLE
Delay between requests

### ISSUE THREAD

**Issue by Theder** [postaddictme/instagram-php-scraper#843]
Are there any guidelines for the length of the delay between requests? I use a delay of 20 seconds between each request and 50 seconds after every 10 request. But sometimes error 302 occurs when it requires you to enter a security code sent by mail/sms. Error 429 sometimes occurs too, but rarely.
Is it worth increasing the delays between requests in this case? Or are there some other ways to avoid such errors?

**Comment by 5baddi** [comment]
To prevent many requests response use random delay between requests also delay by minutes very recommended.
