### ISSUE TITLE
Status code 302, Something went wrong when try two step verification and enter security code.

### ISSUE THREAD

**Issue by NabiKAZ** [postaddictme/instagram-php-scraper#846]
Version:
`raiym/instagram-php-scraper v0.10.1`

Code:
```PHP
$instagram = \InstagramScraper\Instagram::withCredentials(new \GuzzleHttp\Client(), $username, $password, new \Phpfastcache\Helper\Psr16Adapter('Files'));
$instagram->login(false, true);
$instagram->saveSession();
```

Result:
```
Select where to send security code
Phone: +** *** *** **** - 0
Email: *********@*****.*** - 1
Your choice: 1
Enter security code: 111111
```

Error:
```
Fatal error: Uncaught InstagramScraper\Exception\InstagramAuthException: Something went wrong when try two step verification and enter security code. Please report issue. in C:\Nabi\wamp\instagram\instagram-php-scraper\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php:1808
Stack trace:
#0 C:\Nabi\wamp\instagram\instagram-php-scraper\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php(1650): InstagramScraper\Instagram->verifyTwoStep(Object(InstagramScraper\Http\Response), Array, Object(InstagramScraper\TwoStepVerification\ConsoleVerification))
#1 C:\Nabi\wamp\instagram\instagram-php-scraper\save_medias.php(55): InstagramScraper\Instagram->login(false, Object(InstagramScraper\TwoStepVerification\ConsoleVerification))
#2 {main}
  thrown in C:\Nabi\wamp\instagram\instagram-php-scraper\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php on line 1808
```

Source:
https://github.com/postaddictme/instagram-php-scraper/blob/1e7545ec2df2c0532d6bd7255cb60d269a5ed113/src/InstagramScraper/Instagram.php#L1808

Response:
```
InstagramScraper\Http\Response Object
(
    [code] => 302
    [raw_body] =>
    [body] =>
    [headers] => Array
        (
            [Content-Type] => Array
                (
                    [0] => text/html; charset=utf-8
                )

            [Location] => Array
                (
                    [0] => https://www.instagram.com/
                )
:
:
```

Seem the `allow_redirects` was should be enable.

**Comment by NabiKAZ** [comment]
I was update to dev-master 530c2a5 but still have same error: Instagram.php:1846

**Comment by joe7pt** [comment]
Same issue here... @NabiKAZ have u been able to fix?

**Comment by joe7pt** [comment]
This is what i am getting on examples/twoStepAutoVerification/loginWithEmailAutoCponfirm.php

`{
code: 429,
raw_body: "{"message":"","spam":true,"status":"fail"}",
body: {
message: "",
spam: true,
status: "fail"
},
headers: {
Content-Type: [
"application/json; charset=utf-8"
],
Vary: [
"Accept-Language, Cookie"
],
Content-Language: [
"en"
],
Date: [
"Fri, 08 Jan 2021 10:58:59 GMT"
],
Strict-Transport-Security: [
"max-age=31536000"
],
Cache-Control: [
"private, no-cache, no-store, must-revalidate"
],
Pragma: [
"no-cache"
],
Expires: [
"Sat, 01 Jan 2000 00:00:00 GMT"
],
X-Frame-Options: [
"SAMEORIGIN"
],
content-security-policy: [
"report-uri https://www.instagram.com/security/csp_report/; default-src 'self' https://www.instagram.com; img-src data: blob: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com https://*.facebook.com https://*.giphy.com; font-src data: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com; media-src 'self' blob: https://www.instagram.com https://*.cdninstagram.com https://*.fbcdn.net; manifest-src 'self' https://www.instagram.com; script-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://*.cdninstagram.com wss://www.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' https://*.www.instagram.com https://www.instagram.com 'unsafe-inline'; connect-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://graph.instagram.com https://*.graph.instagram.com https://*.cdninstagram.com https://api.instagram.com https://i.instagram.com wss://www.instagram.com wss://edge-chat.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net chrome-extension://boadgeojelhgndaghljhdicfkmllpafd blob:; worker-src 'self' blob: https://www.instagram.com; frame-src 'self' https://instagram.com https://www.instagram.com https://*.instagram.com https://staticxx.facebook.com https://www.facebook.com https://web.facebook.com https://connect.facebook.net https://m.facebook.com; object-src 'none'; upgrade-insecure-requests"
],
cross-origin-embedder-policy-report-only: [
"require-corp;report-to="coep""
],
report-to: [
"{"group": "coep", "max_age": 86400, "endpoints": [{"url": "/security/coep_report/"}]},{"group": "coop", "max_age": 86400, "endpoints": [{"url": "/security/coop_report/"}]}"
],
origin-trial: [
"AuqWincgAuXeuu3KypEMnrrFEJHySaesyJS3EaIH40zvafzrU0Irhb7+5QwZpOqMZrPTjgvFl7Z5jJgy1dNAcQMAAAB6eyJvcmlnaW4iOiJodHRwczovL2luc3RhZ3JhbS5jb206NDQzIiwiZmVhdHVyZSI6IkNyb3NzT3JpZ2luT3BlbmVyUG9saWN5UmVwb3J0aW5nIiwiZXhwaXJ5IjoxNjEzNDExNjYyLCJpc1N1YmRvbWFpbiI6dHJ1ZX0="
],
cross-origin-opener-policy: [
"same-origin-allow-popups;report-to="coop""
],
X-Content-Type-Options: [
"nosniff"
],
X-XSS-Protection: [
"0"
],
x-aed: [
"37"
],
Access-Control-Expose-Headers: [
"X-IG-Set-WWW-Claim"
],
Set-Cookie: [
"ig_did=52A6277B-33A5-4799-BE11-71B1C97B1E69; Domain=.instagram.com; expires=Sun, 08-Jan-2023 10:58:59 GMT; HttpOnly; Max-Age=63072000; Path=/; Secure",
"mid=X_g68wALAAHqCuNQJGbMHHEaYefC; Domain=.instagram.com; expires=Sun, 08-Jan-2023 10:58:59 GMT; Max-Age=63072000; Path=/; Secure"
],
X-FB-TRIP-ID: [
"1679558926"
],
Alt-Svc: [
"h3-29=":443"; ma=3600,h3-27=":443"; ma=3600"
],
Connection: [
"keep-alive"
],
Content-Length: [
"42"
]
}
}`

**Comment by NabiKAZ** [comment]
The next day, after resetting my PC, The problem was solved by itself!
