### ISSUE TITLE
InstagramException not throwing error (but actually error 302)

### ISSUE THREAD

**Issue by andreasgom** [postaddictme/instagram-php-scraper#850]
Hello,

I've been running the getAccountByUsername example on my local computer using XAMPP. Works fine. But when I upload the files to my webspace provider, I get a blank page. For debugging, I've added some echos in the example.

```
<?php
require __DIR__ . '/vendor/autoload.php';
echo "1\n";

$instagram = new \InstagramScraper\Instagram(new \GuzzleHttp\Client());
echo "2\n";

$account = $instagram->getAccount('kevin');
echo "3\n";
```

Echo 1 and 2 are executed, echo 3 is not. I don't get any error message, but the script obviously stops on executing the getAccount function. Any help would be greatly appreciated.

Thanks,
Andreas

**Comment by andreasgom** [comment]
I don't know why but public function getAccount($username) is not throwing errors. I updated this function with some echos...

```
public function getAccount($username)
    {
        $response = Request::get(Endpoints::getAccountPageLink($username), $this->generateHeaders($this->userSession));
        echo "a ";
        if (static::HTTP_NOT_FOUND === $response->code) {
            echo "b ";
            throw new InstagramNotFoundException('Account with given username does not exist.');
            echo "c ";
        }
        if (static::HTTP_OK !== $response->code) {
            echo "d ";
            echo 'Response code is ' . $response->code . '. Body: ' . static::getErrorBody($response->body) . ' Something went wrong. Please report issue.';
            throw new InstagramException('Response code is ' . $response->code . '. Body: ' . static::getErrorBody($response->body) . ' Something went wrong. Please report issue.', $response->code);
            echo "e ";
        }
```

...and finally got:
`a d Response code is 302. Body: Something went wrong. Please report issue.`

**Comment by restyler** [comment]
https://github.com/postaddictme/instagram-php-scraper/issues/866#issuecomment-766557410
