### ISSUE TITLE
Response code is  560

### ISSUE THREAD

**Issue by Nicotroll** [postaddictme/instagram-php-scraper#853]
Hi, 
I started getting a new error today that i've never seen before. 
I tried with different proxies but it doesn't change anything. After a couple tries it works but this errors come back quite a lot.
Any help appreciated ! 
Thanks

`InstagramScraper\Exception\InstagramException: Response code is  560. Body:  Something went wrong. Please report issue. in  /var/www/vhosts/XXXX.com/site/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:454 Stack trace: #0 /var/www/vhosts/XXXX.com/site/order.php(434):  InstagramScraper\Instagram->getAccount('XXXXX') #1 {main}
`

**Comment by 0xboredagain** [comment]
hey @Nicotroll , were you able to figure out what caused this error?
