### ISSUE TITLE
Pagination just gives 60 media

### ISSUE THREAD

**Issue by darkcavalry** [postaddictme/instagram-php-scraper#861]
Hello,

I'm trying to fetch an user's all media links into array but result shows 60 record, target user account has 800~ media. Whats wrong on my code?

```
use Phpfastcache\Helper\Psr16Adapter;
$instagram = \InstagramScraper\Instagram::withCredentials(new \GuzzleHttp\Client(), 'user', 'pass', new Psr16Adapter('Files'));
$instagram->setUserAgent('User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0');
$instagram->login();
$instagram->saveSession(3600*24);

$result = $instagram->getPaginateMedias('kevin');
$medias = $result['medias'];

if ($result['hasNextPage'] === true) {
    $result = $instagram->getPaginateMedias('kevin', $result['maxId']);
    $medias = array_merge($medias, $result['medias']);
}

foreach($medias as $k=>$v){
    echo($k.' - '.$v->getImageHighResolutionUrl().'<br>');
}
```

Also is it possible to fetch less data into array? For example I want to get only media url, but getPaginateMedias and getMedias bring to all media informations and result array had too many unessesary keys on simple calls.

Regards.

**Comment by ricdijk** [comment]
your code makes 2 fetches:
1. $result = $instagram->getPaginateMedias('kevin');
2. $result = $instagram->getPaginateMedias('kevin', $result['maxId']);

Each fetch return (I think) max 30 rows, so 60 in total.

Change
**if** ($result['hasNextPage'] === true) {
    $result = $instagram->getPaginateMedias('kevin', $result['maxId']);
    $medias = array_merge($medias, $result['medias']);
}

in:
**while** ($result['hasNextPage'] === true) {
    $result = $instagram->getPaginateMedias('kevin', $result['maxId']);
    $medias = array_merge($medias, $result['medias']);
}

You can also use '$instagram->getAccount($username)->getId()' to get the userId and then '$instagram->getPaginateMediasByUserId($id, $count = xx, $maxId = '')

**Comment by darkcavalry** [comment]
Thank you so much! Its works fine now.

**Comment by ricdijk** [comment]
Hi,

Thanks for removing my passwords! Ans thanks for the good API.

Im am glad that the pull requests are generally approved very quickly. However with the ‘Highlight’ request it takes somewhat longer. Is there something I can do to help (maybe something you would like to have impolemented differently)?

Best regards,
Richard
