### ISSUE TITLE
Spam login fail - Something went wrong. Please report issue. (429)

### ISSUE THREAD

**Issue by OleksandrKalishchuk** [postaddictme/instagram-php-scraper#864]
Hi.
We use instagram-php-scraper to download posts by tag for our site.
Everything worked fine until 2020.12.27. But now all login requests end with an error with raw_body:
{"message": "", "spam": true, "status": "fail"}
(https://take.ms/6aSSN).
We run getMediasByTag only once every 24 hours.
What does this error mean and how can we fix it?
Thanks.

**Comment by owalerys** [comment]
I'm having issues as well, it appears Instagram has upped their bot detection. In our case, we are not even able to get through requests using proxies for residential or mobile IPs.

**Comment by OleksandrKalishchuk** [comment]
This worked for me - just log-in to instagram account and confirm all suspicious activity. And spam error in login request will gone.

**Comment by dzantiev** [comment]
still issue
