### ISSUE TITLE
Php Fatal Error Response code is 429. 

### ISSUE THREAD

**Issue by filippodicostanzo** [postaddictme/instagram-php-scraper#866]
If i get the request from webserver i recive this error.

PHP Fatal error:  Uncaught InstagramScraper\Exception\InstagramException: Response code is 429. 

But if i get the request from local all works fine.

Now you suggest a proxy service for fix it or there are other solutions?

My request is very simple: 

```
$instagram = new \InstagramScraper\Instagram(new \GuzzleHttp\Client());
$nonPrivateAccountMedias = $instagram->getMedias('kevin');
echo $nonPrivateAccountMedias[0]->getLink();
```

**Comment by solerc** [comment]
Same problem here.

**Comment by kkobana** [comment]
Same problem.
@solerc @filippodicostanzo @raiym 
What do you mean by : "But if i get the request from local all works fine" ?
How do you manage to do that ?
Thank you.

**Comment by owalerys** [comment]
Instagram has been blocking data centre IPs as of a few months ago, and now they are blocking residential IPs from scraper networks as well.

**Comment by restyler** [comment]
I got the same issue and had to create a proxified fork of this scraper as a result (makes sense to use only for public accounts read access)
https://github.com/restyler/instagram-php-scraper

**Comment by bahnecl** [comment]
Same here! Any solutions?

**Comment by YulZhak** [comment]
Same problem. I used the 

$instagram = new \InstagramScraper\Instagram(new \GuzzleHttp\Client());
$instagram = \InstagramScraper\Instagram::withCredentials(new \GuzzleHttp\Client(), 'login', 'pass', new Psr16Adapter('Files'));
$instagram->setUserAgent('usrAgent');
$instagram->login(true);
$instagram->saveSession();

$nonPrivateAccountMedias = $instagram->getMedias('login',10);

What to do now? Make the working example finally please. 

how to use isLogin() for examle?
