### ISSUE TITLE
getBusinessEmail don't work

### ISSUE THREAD

**Issue by do6an** [postaddictme/instagram-php-scraper#869]
```
$account = $instagram->getAccount('patron.pmc');
echo "Email: {$account->getBusinessEmail()}\n";
```

throughput:
![Ekran Alıntıs2ı](https://user-images.githubusercontent.com/49376903/106630095-92580180-658c-11eb-8306-9ee78bfb961a.PNG)

**Comment by emredkc23** [comment]
Likewise getbusinessPhoneNumber doesn't work either

**Comment by RoguePoma** [comment]
Any reason why this went stale?
