### ISSUE TITLE
[Suggestion] Implement session caching clearing method

### ISSUE THREAD

**Issue by sfatfarma** [postaddictme/instagram-php-scraper#87]
In case I change the password, the session is still cached and the old session will be used. I suggest that you implement a method that can be called any time when the user or password is changed, that will clear the session variable.
Thank you very much!

**Comment by sfatfarma** [comment]
Also, I made this little change (in the login method), to get if the used login credentials are incorrect: 
`$response = Request::post(Endpoints::LOGIN_URL, $headers, ['username' => $this->sessionUsername, 'password' => $this->sessionPassword]);
            if ($response->code !== 200) {
                throw new InstagramAuthException('Response code is ' . $response->code . '. Body: ' . $response->body . ' Something went wrong. Please report issue.');
            }
            else
            {
                if($response->body->authenticated != '1')
                {
                    throw new InstagramAuthException('Invalid login credentials used.');
                }
            }`

**Comment by raiym** [comment]
@sfatfarma hello! 
Thank you for issue. 
Yes it may be useful.
If you have time feel free to create pull request

**Comment by raiym** [comment]
FYI. If you have changed password you can force login by providint `true` in login method. 

https://github.com/postaddictme/instagram-php-scraper/blob/master/src/InstagramScraper/Instagram.php#L509

**Comment by sfatfarma** [comment]
ok thanks :)

**Comment by sfatfarma** [comment]
Another (noob) question: why do you require the login to be called when public content can be viewed on Instagram also if the user is not logged in (valid for the ?__a=1 paramenter, also)?

**Comment by jetonr** [comment]
@statfarma visit https://www.instagram.com/explore/tags/instagram from a browser that is not signed in!

**Comment by sfatfarma** [comment]
@jetonr tried it and it displays pictures and info. The single difference is the sign in popup... I'm confused

**Comment by jetonr** [comment]
Now again public content can be viewed without loggin in! @raiym

**Comment by sfatfarma** [comment]
yup

**Comment by raiym** [comment]
@jetonr @sfatfarma thanks.
It is weird. Let's wait for some time to see what happens next.
