### ISSUE TITLE
GuzzleHttp/Client does not exist

### ISSUE THREAD

**Issue by imollm** [postaddictme/instagram-php-scraper#875]
When I installed via composer, I see an error in my PhpStorm, it says that GuzzleHttp/Client class does not exist, any idea?

**Comment by SergeiKanerva** [comment]
God save this people.
Please run: composer require guzzlehttp/guzzle
If you will find yourself in same position, but with Phpfastcache
Run: composer require phpfastcache/phpfastcache

**Comment by imollm** [comment]
Thanks! Now it works!

**Comment by nalin88** [comment]
thanks a lot

**Comment by SergeiKanerva** [comment]
@imollm please close the issue if resolved
