### ISSUE TITLE
getMediasByTag doesn't return correct Owner object

### ISSUE THREAD

**Issue by thedevale** [postaddictme/instagram-php-scraper#881]
Hi,
when calling 

$instagramScraper->getMediasByTag($code)

the result has always empty user, containing no data except for the User ID

**Sample Response:**

`object(InstagramScraper\Model\Media)#2 (44) {
  ["id":protected]=>
  string(19) "2517840074352184599"
  ["shortCode":protected]=>
  string(11) "CLxKjUhAU0X"
  ["createdTime":protected]=>
  int(1614369948)
    ......
  ["owner":protected]=>
  object(InstagramScraper\Model\Account)#4 (36) {
    ["id":protected]=>
    int(8170730871)
    ["username":protected]=>
    string(0) ""
    ["fullName":protected]=>
    string(0) ""
    ["profilePicUrl":protected]=>
    string(0) ""
    ["profilePicUrlHd":protected]=>
    string(0) ""
    ["biography":protected]=>
    string(0) ""
    ["externalUrl":protected]=>
    string(0) ""
    ["followsCount":protected]=>
    int(0)
    ["followedByCount":protected]=>
    int(0)
    ["mediaCount":protected]=>
    int(0)
    ["isPrivate":protected]=>
    bool(false)
    ["isVerified":protected]=>
    bool(false)
    ["isLoaded":protected]=>
    bool(true)
    ["medias":protected]=>
    array(0) {
    }
    ["blockedByViewer":protected]=>
    bool(false)
    ["countryBlock":protected]=>
    bool(false)
    ["followedByViewer":protected]=>
    bool(false)
    ["followsViewer":protected]=>
    bool(false)
    ["hasChannel":protected]=>
    bool(false)
    ["hasBlockedViewer":protected]=>
    bool(false)
    ["highlightReelCount":protected]=>
    int(0)
    ["hasRequestedViewer":protected]=>
    bool(false)
    ["isBusinessAccount":protected]=>
    bool(false)
    ["isJoinedRecently":protected]=>
    bool(false)
    ["businessCategoryName":protected]=>
    string(0) ""
    ["businessEmail":protected]=>
    string(0) ""
    ["businessPhoneNumber":protected]=>
    string(0) ""
    ["businessAddressJson":protected]=>
    string(2) "{}"
    ["requestedByViewer":protected]=>
    bool(false)
    ["connectedFbPage":protected]=>
    string(0) ""
    ["isNew":protected]=>
    bool(false)
    ["isLoadEmpty":protected]=>
    bool(false)
    ["isFake":protected]=>
    bool(false)
    ["isAutoConstruct":protected]=>
    bool(false)
    ["modified":protected]=>
    int(1614426087)
    ["data":protected]=>
    array(0) {
    }
  }
  ["ownerId":protected]=>
  int(8170730871)

....
}`

**Comment by veuxx** [comment]
you solved this?

> Oi
> ao ligar
> 
> $ instagramScraper-> getMediasByTag ($ code)
> 
> o resultado sempre tem usuário vazio, não contendo dados, exceto para a ID do usuário
> 
> **Resposta de amostra:**
> 
> `object (InstagramScraper \ Model \ Media) [# 2](https://github.com/postaddictme/instagram-php-scraper/pull/2) (44) {
> [" id ": protected] =>
> string (19)" 2517840074352184599 "
> [" shortCode ": protected] =>
> string (11)" CLxKjUhAU0X "
> [" createdTime ": protected] =>
> int (1614369948)
> ......
> [" owner ": protected] =>
> objeto (InstagramScraper \ Model \ Account) [# 4](https://github.com/postaddictme/instagram-php-scraper/issues/4) (36) {
> [" id ": protected] =>
> int ( 8170730871)
> ["username": protected] =>
> string (0) ""
> ["fullName": protected] =>
> string (0) ""
> ["profilePicUrl": protected] =>
> string (0) ""
> ["profilePicUrlHd ": protegido] =>
> string (0)" "
> [" biografia ": protegido] =>
> string (0)" "
> [ "externalurl": protected] =>
> string (0) ""
> [ "followsCount": protected] =>
> int (0)
> [ "followedByCount": protected] =>
> int (0)
> [ "mediaCount": protected] =>
> int (0)
> ["isPrivate": protected] =>
> bool (false)
> ["isVerified": protected] =>
> bool (false)
> ["isLoaded": protected] =>
> bool (true)
> ["medias": protected] =>
> array (0) {
> }
> ["blocksByViewer": protected] =>
> bool (false)
> ["countryBlock": protected] =>
> bool (false)
> [" followingByViewer ": protected] =>
> bool (false)
> ["followingViewer": protected] =>
> bool (false)
> ["hasChannel": protected] =>
> bool (false)
> ["hasBlockedViewer": protected] =>
> bool (false)
> ["highlightReelCount": protected] =>
> int (0)
> ["hasRequestedViewer": protected] =>
> bool (false)
> ["isBusinessAccount": protected] =>
> bool (false)
> ["isJoinedRecently": protected] =>
> bool (false)
> ["businessCategoryName": protected] =>
> string (0) ""
> ["businessEmail": protected] =>
> string (0) ""
> [ "businessPhoneNumber": protected] =>
> string (0) ""
> ["businessAddressJson": protected] =>
> string (2) "{}"
> ["requiredByViewer": protected] =>
> bool (false)
> ["connectedFbPage": protected] =>
> string (0) ""
> ["isNew": protected] =>
> bool (false)
> ["isLoadEmpty": protected] =>
> bool (false)
> ["isFake": protected] =>
> bool (false)
> ["isAutoConstruct": protected] =>
> bool (false)
> ["modificado": protected] =>
> int (1614426087)
> ["dados": protegido] =>
> matriz (0) {
> }
> }
> ["ownerId": protegido] =>
> int (8170730871)
> 
> ....
> } `

**Comment by thedevale** [comment]
> you solved this?
> 
> > Oi
> > ao ligar
> > $ instagramScraper-> getMediasByTag ($ code)
> > o resultado sempre tem usuário vazio, não contendo dados, exceto para a ID do usuário
> > **Resposta de amostra:**
> > `object (InstagramScraper \ Model \ Media) [# 2](https://github.com/postaddictme/instagram-php-scraper/pull/2) (44) {
> > [" id ": protected] =>
> > string (19)" 2517840074352184599 "
> > [" shortCode ": protected] =>
> > string (11)" CLxKjUhAU0X "
> > [" createdTime ": protected] =>
> > int (1614369948)
> > ......
> > [" owner ": protected] =>
> > objeto (InstagramScraper \ Model \ Account) [# 4](https://github.com/postaddictme/instagram-php-scraper/issues/4) (36) {
> > [" id ": protected] =>
> > int ( 8170730871)
> > ["username": protected] =>
> > string (0) ""
> > ["fullName": protected] =>
> > string (0) ""
> > ["profilePicUrl": protected] =>
> > string (0) ""
> > ["profilePicUrlHd ": protegido] =>
> > string (0)" "
> > [" biografia ": protegido] =>
> > string (0)" "
> > [ "externalurl": protected] =>
> > string (0) ""
> > [ "followsCount": protected] =>
> > int (0)
> > [ "followedByCount": protected] =>
> > int (0)
> > [ "mediaCount": protected] =>
> > int (0)
> > ["isPrivate": protected] =>
> > bool (false)
> > ["isVerified": protected] =>
> > bool (false)
> > ["isLoaded": protected] =>
> > bool (true)
> > ["medias": protected] =>
> > array (0) {
> > }
> > ["blocksByViewer": protected] =>
> > bool (false)
> > ["countryBlock": protected] =>
> > bool (false)
> > [" followingByViewer ": protected] =>
> > bool (false)
> > ["followingViewer": protected] =>
> > bool (false)
> > ["hasChannel": protected] =>
> > bool (false)
> > ["hasBlockedViewer": protected] =>
> > bool (false)
> > ["highlightReelCount": protected] =>
> > int (0)
> > ["hasRequestedViewer": protected] =>
> > bool (false)
> > ["isBusinessAccount": protected] =>
> > bool (false)
> > ["isJoinedRecently": protected] =>
> > bool (false)
> > ["businessCategoryName": protected] =>
> > string (0) ""
> > ["businessEmail": protected] =>
> > string (0) ""
> > [ "businessPhoneNumber": protected] =>
> > string (0) ""
> > ["businessAddressJson": protected] =>
> > string (2) "{}"
> > ["requiredByViewer": protected] =>
> > bool (false)
> > ["connectedFbPage": protected] =>
> > string (0) ""
> > ["isNew": protected] =>
> > bool (false)
> > ["isLoadEmpty": protected] =>
> > bool (false)
> > ["isFake": protected] =>
> > bool (false)
> > ["isAutoConstruct": protected] =>
> > bool (false)
> > ["modificado": protected] =>
> > int (1614426087)
> > ["dados": protegido] =>
> > matriz (0) {
> > }
> > }
> > ["ownerId": protegido] =>
> > int (8170730871)
> > ....
> > } `

Sadly no

**Comment by veuxx** [comment]
@thedevale solved #909
