### ISSUE TITLE
Cover with test cases

### ISSUE THREAD

**Issue by raiym** [postaddictme/instagram-php-scraper#89]

**Comment by raiym** [comment]
Each function provided in Instagram.php

**Comment by jetonr** [comment]
I can help with testing! What do you need ?

**Comment by raiym** [comment]
@jetonr thank you. 

There are some functions in api that doesn't have test cases (like tags pagination), if you want you can start adding test cases and create PR.

**Comment by e-beach** [comment]
I'm going to write tests for 3-4 functions and make a PR, then maybe do more.

However, there are too many open issues in this project, which may be more important for maintenance than tests. People will assume a project with many issues not addressed by the maintainer is abandoned.

Issues that should be closed immediately include #127, #125, #118, #116, #115, #89, #81, and possibly #119.

**Comment by raiym** [comment]
@e

**Comment by raiym** [comment]
@e-beach thank you Elliot for being part of this library

**Comment by e-beach** [comment]
@raiym Do you know why testGetMediaCommentsByCode is failing?
In particular, why is the expected size exactly 4 less than the value of $count in the first place?
https://github.com/postaddictme/instagram-php-scraper/blob/dcfc4b0ac1247ba55c8e1ecf026cb33eb6a0c456/tests/InstagramTest.php#L110
