### ISSUE TITLE
getPaginateFollowing/getPaginateFollowers fails after a certain numbers of requests. Any solution

### ISSUE THREAD

**Issue by carlonicora** [postaddictme/instagram-php-scraper#895]
Hello Everyone,

I am testing the scraper (_thanks to the contributors BTW_) and I hit a wall when gathering the following or the followers for accounts with large numbers.

At the moment I just want a system that recognises which accounts are not following back, therefore I read the Following, the Followers, and I get which accounts are not reciprocating the follow.

I have notices that each call to Instagram only returns ~44 accounts per paginated request, therefore a large number of requests are needed to collect large accounts. However, after a LOT of requests, Instagram stops sending the information back, triggering the error

`Failed to get followers of account id ' . $accountId . '. The account is private.`

At this point I have come to two solutions, both with a drawback:

1. increase the timeout between requests from ~3 seconds to ~40 seconds. The issue is that an account following 20k other accounts would take 5 hours to be read.
2. use lots of different accounts to trigger different requests. The issue is that I would need lots of accounts used for reading the infomation

Do any of you have an alternative solution on how to achieve this?

Thanks

**Comment by veuxx** [comment]
Hello, I know it has nothing to do with your post, but could you help me to implement the basic script?
https://github.com/postaddictme/instagram-php-scraper/issues/897

**Comment by veuxx** [comment]
did you can help me on pagination? i have this code:
  "hasNextPage": true,
    "nextPage": "QVFDSlYzMFdLOUthUHRXRGZrZVRKRWo3R3JBZm94ZFJIeWtJdzdqRDBmT256eENvX1JoNUdTRG13c0RNMjdCcnliSm04ZGdjbDg1eUxWRWRVWlBoYzFBUg==",
    "accounts": [

I still don't understand how to work with it. 
I'm looking for better ways to also make this feature ...
