### ISSUE TITLE
getMediasByTag returns empty array

### ISSUE THREAD

**Issue by toms19** [postaddictme/instagram-php-scraper#896]
Hi all,
since yesterday I keep getting empty arrays out of these two methods:

- getMediasByTag()
- getCurrentTopMediasByTagName()

All other methods works just fine (authentication included).
Any comments?

**Comment by toms19** [comment]
It seems that ig response changed structure

- $arr['graphql']['hashtag']['edge_hashtag_to_media']['count']

does not exists anymore

**Comment by veuxx** [comment]
> Hi all,
> since yesterday I keep getting empty arrays out of these two methods:
> 
> * getMediasByTag()
> * getCurrentTopMediasByTagName()
> 
> All other methods works just fine (authentication included).
> Any comments?

Hello, I know it has nothing to do with your post, but could you help me to implement the basic script?

**Comment by arduinotech** [comment]
Please fix it)

**Comment by SwierczKacper** [comment]
Same problem, response structure changed.

**Comment by veuxx** [comment]
you solved this?

**Comment by veuxx** [comment]
> It seems that ig response changed structure
> 
> * $arr['graphql']['hashtag']['edge_hashtag_to_media']['count']
> 
> does not exists anymore

you solved this?

**Comment by veuxx** [comment]
Solved #909
