### ISSUE TITLE
Demo Script

### ISSUE THREAD

**Issue by veuxx** [postaddictme/instagram-php-scraper#897]
Definitely, my knowledge of PHP is basic. For that, could someone provide me with some basic script model in operation? I was unable to implement it just by installing it through Composer. So, I can start from the basics.

I know I may be asking for something very big, but I believe someone can help me with the initial step.

Thanks in advance.

**Comment by carlonicora** [comment]
@veuxx have you checked the examples? Everything depends on what you need to achieve. The examples are pretty good to help you reach what you want!
