### ISSUE TITLE
Something went wrong. Please report issue

### ISSUE THREAD

**Issue by federycko** [postaddictme/instagram-php-scraper#898]
I get this error "Fatal error: Uncaught InstagramScraper\Exception\InstagramAuthException: Something went wrong. Please report issue"
I'm using \InstagramScraper\Instagram::withCredentials  and get error when try to login.
This error occurs randomly. any suggestions?

**Comment by prabaharan-srm** [comment]
Yes, i am getting same issue, but it has problem in live site only, it does not occur in local system. Please help me.

**Comment by cleberalves** [comment]
Yes, same problem here. I believe that something has changed on Instagram to block scraping.

**Comment by yigitkeremoktay** [comment]
Same.

**Comment by masoudomidvar** [comment]
Same problem here

**Comment by madeny** [comment]
Same here

**Comment by 89z** [comment]
Same error

**Comment by ma110y** [comment]
Some error
