### ISSUE TITLE
Where the location of session that saved from psr16adapter?

### ISSUE THREAD

**Issue by ardzz** [postaddictme/instagram-php-scraper#905]

**Comment by veuxx** [comment]
if it's the `cookie` and `csrftoken` you want, you can use the following

```
<?php
$result = $instagram->login();
echo "<pre>";
var_dump($result);
echo "</pre>";
```

**Comment by ardzz** [comment]
Is it not stored on some files?

**Comment by ardzz** [comment]
How I can use output of `$instagram->login();` as credential?

**Comment by veuxx** [comment]
> Como posso usar a saída de `$instagram->login();`como credencial?

`$instagram->login(); ` already use the cached data.
If you want to force the login, you can use `$instagram->login(true); `
