### ISSUE TITLE
Laravel response function return emty result, otherwise dump returns result

### ISSUE THREAD

**Issue by mflash123** [postaddictme/instagram-php-scraper#908]
```
$instagram = new \InstagramScraper\Instagram(new \GuzzleHttp\Client());
$account = $instagram->getAccount("kevin");
```

So, if you make:
```
dump($account);
```
It retuns result.

Problem, if you make this:
```
return response()->json($account); 
```
Result is 
```
{}
```

How to fetch data through return response()?

**Comment by mflash123** [comment]
The problem is, when I try dump - it calls Model;

In return, I need call functions:
```
$account->getUsername()
```

**Comment by Pezhvak** [comment]
To complete the answer, a workaround is:
`return response()->json($account->toArray());`
