### ISSUE TITLE
Square Media Size

### ISSUE THREAD

**Issue by galo4kin** [postaddictme/instagram-php-scraper#91]
How to get medias square size link?

For example: 
https://scontent-arn2-1.cdninstagram.com/t51.2885-15/e35/c257.0.565.565/17438110_278125249293389_4686810287834136576_n.jpg 

and https://scontent.cdninstagram.com/t/17438110_278125249293389_4686810287834136576_n.jpg

**Comment by raiym** [comment]
@galo4kin please see SO answer: 
http://stackoverflow.com/questions/33541162/how-to-get-the-cropped-image-from-instagram-api

**Comment by rhcarlosweb** [comment]
#248
