### ISSUE TITLE
HTTP ERROR 302 on login method

### ISSUE THREAD

**Issue by livevasiliy** [postaddictme/instagram-php-scraper#914]
Hello, @postaddctme I got HTTP error 302 on login. I'm checking on the original site Instagram my credentials are correct, I do not have a banned account.  Below stack trace

Response code is 302. Body:  Something went wrong. Please report issue. {"exception":"[object] (InstagramScraper\\Exception\\InstagramException(code: 302): Response code is 302. Body:  Something went wrong. Please report issue. at /app/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:1788)
[stacktrace]
#0 /app/app/Domains/Instagram/Jobs/LoginInstagramAccountJob.php(46): InstagramScraper\\Instagram->login()

**Comment by mingo1107** [comment]
same issue

**Comment by PhantomArt** [comment]
I am having this same problem. It is observed when trying to log in from a server whose IP address is different from mine.

**Comment by alex2549** [comment]
same here

**Comment by vensires** [comment]
same goes here too

**Comment by VarroReve** [comment]
+1

**Comment by AlexAlexE** [comment]
+1

**Comment by Casmo** [comment]
This problem came out of nowhere. One moment everything works fine, the next I got this error. Could it be Instagram that is blocking this?

**Comment by ahmadharminto** [comment]
I also got this issue recently, but it's weird. Only on different server / IP, but it's working on my local. 
Because I'm using laravel, I tried to changed [this](https://github.com/postaddictme/instagram-php-scraper/blob/f2eeb4ac0525455b088a0a156d53361bb32c5810/src/InstagramScraper/Instagram.php#L1786) to use Http client provided by laravel. It solves my issue. I've no idea why the guzzle request give different response.

**Comment by iyanrinri** [comment]
@ahmadharminto can you show us the replacement code using Http Client by Laravel?

**Comment by ahmadharminto** [comment]
@iyanrinri just replace it using `$response = Http::get(Endpoints::BASE_URL);`
don't forget to use namespace respectively, and there are built on [functions](https://laravel.com/docs/8.x/http-client#making-requests) on response object, such as`->status()`, `->headers()`, `->body()`

**Comment by tanaka55** [comment]
src/InstagramScraper/Instagram.php : 1788
```
            $response = Request::get(Endpoints::BASE_URL);
```
↓
```
            $response = Request::get(Endpoints::BASE_URL);
            if ($response->code === 302) {
                $response = Request::get($response->headers['Location'][0]);
            }
```

**Comment by jangrewe** [comment]
@tanaka55 // @raiym I'm getting the 302 on getAccount(), and after adding the same fix (check for redirect), it seems as if IG wants me to login (again!). I'm already using login() with all the bells and whistles before i call getAccount(), so i'm wondering what's wrong there...
