### ISSUE TITLE
how to use This ?

### ISSUE THREAD

**Issue by Mehran** [postaddictme/instagram-php-scraper#92]
i install it with composer success ,  now when i run `use InstagramScraper\Instagram;`  i got error 

```
~/vendor# use InstagramScraper\Instagram;
bash: use: command not found

```
Where i must type `use InstagramScraper\Instagram;`   i'm not Familiar wit this sorry .

**Comment by denpli** [comment]
You should place it in your PHP code to refer external package class, not run as bash terminal command.
http://php.net/manual/en/language.namespaces.importing.php

**Comment by Mehran** [comment]
**@denpli** Thanks for your mention can give me some example ? i must put these code on my .php file ? then What Compsoer Rule ? i got a little confued Thanks .

**Comment by denpli** [comment]
Well, see you're not familiar with php, so the simplest way to try lib functionality:
1. git clone project
2. run `composer install ` from project dir
3. in project dir in index.php file uncomment last string `//echo json_encode($instagram->getTopMediasByTagName('hello'));` or add examples from docs and call http://path-to-project/index.php
4. profit - scrapped data in you browser
All other questions on application run are out of this topic.

**Comment by Mehran** [comment]
Thank you so much , i Now understand how it work . now i got this error on my browser 


`Fatal error: Uncaught Error: Call to undefined function Unirest\curl_init() in /var/www/html/vendor/mashape/unirest-php/src/Unirest/Request.php:396 Stack trace: #0 /var/www/html/vendor/mashape/unirest-php/src/Unirest/Request.php(236): Unirest\Request::send('GET', 'https://www.ins...', NULL, Array, NULL, NULL) #1 /var/www/html/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php(519): Unirest\Request::get('https://www.ins...') #2 /var/www/html/index.php(46): InstagramScraper\Instagram->login() #3 {main} thrown in /var/www/html/vendor/mashape/unirest-php/src/Unirest/Request.php on line 396`

**Comment by denpli** [comment]
It is impossible - with help of this lib you can only collect (parse) data from Instagram, using there public data in page markup.
To interact with Instagram sending data you should use other libs, which wrap native Instagram API. And also have registered Instagram application
