### ISSUE TITLE
InstagramScraper\Exception\InstagramException: Response code is 302. Body:  Something went wrong. Please report issue.

### ISSUE THREAD

**Issue by Ryan45758** [postaddictme/instagram-php-scraper#930]
using GCP,  error with ˋInstagramScraper\Exception\InstagramException: Response code is 302. Body:  Something went wrong. Please report issue.ˋ,

**Comment by restyler** [comment]
if you are trying to access anonymous endpoints, this means that scraper is redirected to login page. try residential proxies, or cloud proxy fork https://github.com/restyler/instagram-php-scraper which handles proxies for you
