### ISSUE TITLE
Uncaught Error: Class 'GuzzleHttp\Client' not found

### ISSUE THREAD

**Issue by PromptlyDev** [postaddictme/instagram-php-scraper#932]
Fatal error: Uncaught Error: Class 'GuzzleHttp\Client' not found in /www/htdocs/xxxx/xxxx/test.php:9 Stack trace: #0 {main} thrown in /www/htdocs/xxxx/xxxx/test.php on line 9

`<?php
ini_set('display_errors', 1);
echo "1";
require __DIR__ . '/../vendor/autoload.php';

echo "2";

$instagram = \InstagramScraper\Instagram::withCredentials(new \GuzzleHttp\Client(), '###', '###');
$instagram->login();

echo "3";

?>`

Site prints 1 and 2.

Instagram scraper was installed with composer in the directory above.

**Comment by alirezax5** [comment]
Hello, run the command in cmd :
 composer require guzzlehttp/guzzle
