### ISSUE TITLE
Wrong examples on readme page

### ISSUE THREAD

**Issue by OMogilev** [postaddictme/instagram-php-scraper#939]
Hi there! 
Your examples like:
`$instagram = \InstagramScraper\Instagram::withCredentials(new \GuzzleHttp\Client(), 'username', 'password');
$instagram->login();
$account = $instagram->getAccountById(3);
echo $account->getUsername();`

doesn't works, because withCredentials method needs 4 arguments. You have to change in method argument "cache" as null or false by default. 

The error I have catched:
`Too few arguments to function InstagramScraper\Instagram::withCredentials(), 3 passed in /var/www/site/app/Console/Commands/Parser.php on line 83 and exactly 4 expected`

**Comment by am05mhz** [comment]
have made pull request for this too

https://github.com/postaddictme/instagram-php-scraper/pull/942
