### ISSUE TITLE
Response code is 302. Body: Something went wrong. Please report issue.

### ISSUE THREAD

**Issue by OMogilev** [postaddictme/instagram-php-scraper#940]
Trying to login with username, password. 
` if (static::HTTP_OK !== $response->code) {
    throw new InstagramException('Response code is ' . $response->code . '. Body: ' . static::getErrorBody($response->body) . ' Something went wrong. Please report issue.', $response->code);
}`

**Comment by am05mhz** [comment]
have made a pull request to fix this issue

https://github.com/postaddictme/instagram-php-scraper/pull/942
