### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by MSI0072** [postaddictme/instagram-php-scraper#948]
![image](https://user-images.githubusercontent.com/63404067/129494457-11ed0147-2132-406a-b5de-c54aadf8a603.png)

this my script
https://github.com/MSI0072/PHP-INSTAGRAM-STALKER

**Comment by adrianosmateus** [comment]
This could be a hundred of things. Next time please send the proper error and not only the default browser screen.
