### ISSUE TITLE
Catchable fatal error Object of class stdClass 

### ISSUE THREAD

**Issue by filippodicostanzo** [postaddictme/instagram-php-scraper#95]
Catchable fatal error: Object of class stdClass could not be converted to string

\InstagramScraper\Instagram.php on line 529

require('autoload.php');

use InstagramScraper\Instagram;
Unirest\Request::verifyPeer(false);

$instagram = Instagram::withCredentials('username', 'password', '/cached');
$instagram->login();

$account = $instagram->getMediaById(1448575070213480221);

echo json_encode($account);

**Comment by javagose** [comment]
i have the same error here [#76](https://github.com/postaddictme/instagram-php-scraper/issues/76#issuecomment-291623611)

**Comment by raiym** [comment]
Thank you for raising issue I will check it soon

**Comment by matkozikowski** [comment]
Hello,
If this bug was fixed ?

**Comment by matkozikowski** [comment]
Ok I found the reason. The Instagram log out my account. When I log in via Instagram website. Api start working. 
It looks like the PI don't login account.

**Comment by ht22pt** [comment]
I found "Object of class stdClass could not be converted to string" in exception will not throw to cast, it crash process and exit.
Because : $response->body in error of Intastagram now is stdClass not string.
Example: 
```php
throw new InstagramException('Response code is ' . $response->code . '. Body: ' . var_dump($response->body) . ' Something went wrong. Please report issue.');
```
Will not throw to catch InstagramException, it will exit.
