### ISSUE TITLE
It does not work on the serve

### ISSUE THREAD

**Issue by batyayura0** [postaddictme/instagram-php-scraper#953]
It does not work on the server, it works on the LOCALHOST

Already connected the proxy, the UserAgent registered. But doesn't work

`$proxy = [

    'timeout'=>30,
    'curl' => [
        'CURLOPT_PROXY'=>'88.99....',
        'CURLOPT_PROXYPORT'=>'1337',
        'CURLOPT_PROXYUSERPWD'=>'uKX:DCW',
    ]

];

$instagram = new \InstagramScraper\Instagram(new GuzzleHttp\Client($proxy));
$instagram ->setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36');
`

Error:
`Fatal error: Uncaught InstagramScraper\Exception\InstagramException: Response code is 200. Body: <!DOCTYPE html> <html lang="en" class="no-js not-logged-in client-root"> <head> <meta charset="utf-8"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <title> Login • Instagram </title> <meta name="robots" content="noimageindex, noarchive"> <meta name="apple-mobile-web-app-status-bar-style" content="default"> <meta name="mobile-web-app-capable" content="yes"> <meta name="theme-color" content="#ffffff"> <meta id="viewport" name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, ......`

**Comment by pishguy** [comment]
+1
