### ISSUE TITLE
IP Verification Error : We Detected An Unusual Login Attempt

### ISSUE THREAD

**Issue by mojtabaghaseemi** [postaddictme/instagram-php-scraper#960]
Hi

Please see the link below
https://s4.uupload.ir/files/insta_56ky.jpg
If a request is sent repeatedly with an IP, it will be blocked
Until I change the password
 Or we have to click on the button (this was me)
Please automate the verification of this section as well
https://www.instagram.com/challenge/
The link when this error is displayed

**Comment by beshoo** [comment]
Same here. How can we code this?
