### ISSUE TITLE
$twoStepVerificator must be an instance of TwoStepVerificationInterface.

### ISSUE THREAD

**Issue by ateequrrahman97** [postaddictme/instagram-php-scraper#967]
![image](https://user-images.githubusercontent.com/74288984/136515300-22c4519e-54fe-4b1c-8dfa-6b679eea5746.png)
@raiym

**Comment by svonjoi** [comment]
i have the same issue. I created new clean insta acc and is working well, so there are some timeouts or kind of antispam by instagram api -- anybody knows how to check this?

**Comment by bdmtra** [comment]
I have same issue

**Comment by zakrian07** [comment]
how to fix it
