### ISSUE TITLE
getMediaByUrl does not show media!!

### ISSUE THREAD

**Issue by julioleao2018** [postaddictme/instagram-php-scraper#970]
Searching for media by url is not returning any more results. Anyone else facing the same problem?

**Comment by 89z** [comment]
Can you provide example link?

**Comment by julioleao2018** [comment]
This return only appears, There is no media with this code

**Comment by julioleao2018** [comment]
sorry I'm learning to use the library,
![image](https://user-images.githubusercontent.com/44656054/136707945-1ed180e0-4683-44a8-991a-01593104adca.png)

url = https://www.instagram.com/p/CUk7XY1JO2G/
