### ISSUE TITLE
Uncaught InstagramScraper\Exception\InstagramException: Response code is 302

### ISSUE THREAD

**Issue by atulkumarcse** [postaddictme/instagram-php-scraper#976]
Fatal error: Uncaught InstagramScraper\Exception\InstagramException: Response code is 302. Body: Something went wrong. Please report issue. in /var/www/html/insta/src/InstagramScraper/Instagram.php:534 Stack trace: #0 /var/www/html/insta/examples/getAccountByUsername.php(14): InstagramScraper\Instagram->getAccount('kevin') #1 {main} thrown in /var/www/html/insta/src/InstagramScraper/Instagram.php on line 534

**Comment by TimIgoe** [comment]
> try using https://github.com/restyler/instagram-php-scraper fork which leverages cloud proxy to avoid headache of managing residential proxies by yourself.

What happened to this project, it 404's now?

**Comment by skmachine** [comment]
> > try using https://github.com/restyler/instagram-php-scraper fork which leverages cloud proxy to avoid headache of managing residential proxies by yourself.
> 
> What happened to this project, it 404's now?

404 indeed.. try https://github.com/skmachine/instagram-php-scraper instead - not exactly the same but works fine for most of use cases when you need public data
