### ISSUE TITLE
Please Help - Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: 

### ISSUE THREAD

**Issue by tenet912** [postaddictme/instagram-php-scraper#982]
i have seen this error 
please help me fast 

Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://www.instagram.com

**Comment by beshoo** [comment]
This error is not related to the lib, ask your hosting provider to update your CURL SSL Certificate

**Comment by pilarik31** [comment]
Hi,

if you're developing on localhost, simplest solution is to turn off SSL certificate verification.

```php
use Phpfastcache\Helper\Psr16Adapter;
use GuzzleHttp\Client;

$instagram = Instagram::withCredentials(
    new Client(['verify' => false]),
    'username',
    'password',
    new Psr16Adapter('Files')
);
```

You can do that, by passing array with `verify` key that has value `false` into the constructor of `GuzzleHttp\Client`.

[Related documentation.](https://docs.guzzlephp.org/en/stable/request-options.html#verify)

**Comment by tenet912** [comment]
> 
> 
> Hi,
> 
> if you're developing on localhost, simplest solution is to turn off SSL certificate verification.
> 
> ```
> use Phpfastcache\Helper\Psr16Adapter;
> use GuzzleHttp\Client;
> 
> $instagram = Instagram::withCredentials(
>     new Client(['verify' => false]),
>     'username',
>     'password',
>     new Psr16Adapter('Files')
> );
> ```
> 
> You can do that, by passing array with `verify` key that has value `false` into the constructor of `GuzzleHttp\Client`.
> 
> [Related documentation.](https://docs.guzzlephp.org/en/stable/request-options.html#verify)

after i use this code 
`$instagram = \InstagramScraper\Instagram::withCredentials(new \GuzzleHttp\Client(['verify' => false]), 'username', 'password', new Psr16Adapter('Files'));
`

i get this error message
` Fatal error: Uncaught InstagramScraper\Exception\InstagramAuthException: Response code is 403. Body: <!DOCTYPE html> <html lang="en" class="no-js not-logged-in "> <head> <meta charset="utf-8"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <title> Page Not Found &bull; Instagram </title> <meta name="robots" content="noimageindex, noarchive"> <meta name="apple-mobile-web-app-status-bar-style" content="default"> <meta name="mobile-web-app-capable" content="yes"> <meta name="theme-color" content="#ffffff"> <meta id="viewport" name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover"> <link rel="manifest" href="/data/manifest.json"> <script type="text/javascript"> (function() { var docElement = document.documentElement; var classRE = new RegExp('(^|\\s)no-js(\\s|$)'); var className = docElemen in C:\xampp\htdocs\10\src\InstagramScraper\Instagram.php on line 1820`

**Comment by pilarik31** [comment]
Hi,

did you replace `username` and `password` with the actual credentials? That's my first and only guess, based on that `not-logged-in` class in the html.

**Comment by tenet912** [comment]
> 
> 
> Hi,
> 
> did you replace `username` and `password` with the actual credentials? That's my first and only guess, based on that `not-logged-in` class in the html.

yes i replace my username and password

**Comment by pilarik31** [comment]
Can't be of more help without more details, sorry.

**Comment by tenet912** [comment]
> Can't be of more help without more details, sorry.

what details you need ?
