### ISSUE TITLE
Cannot install php scraper, composer dependencies

### ISSUE THREAD

**Issue by carlossaez60** [postaddictme/instagram-php-scraper#989]
`composer require raiym/instagram-php-scraper phpfastcache/phpfastcache`

Using version ^0.12.0 for raiym/instagram-php-scraper
Using version ^9.0 for phpfastcache/phpfastcache
phpfastcache/phpfastcache is currently present in the require-dev key and you ran the command without the --dev flag, which would move it to the require key.
Do you want to move this requirement? [no]? 
Do you want to re-run the command with --dev? [yes]? 
./composer.json has been updated
Running composer update raiym/instagram-php-scraper phpfastcache/phpfastcache
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  **Problem 1
    - Root composer.json requires phpfastcache/phpfastcache ^9.0 -> satisfiable by phpfastcache/phpfastcache[9.0.0].
    - phpfastcache/phpfastcache 9.0.0 requires psr/simple-cache ^2.0||^3.0 -> found psr/simple-cache[2.0.0, 3.0.0] but it conflicts with your root composer.json require (~1.0).
  Problem 2
    - phpunit/phpunit[7.0.0, ..., 7.5.20] require php ^7.1 -> your php version (8.0.11) does not satisfy that requirement.
    - Root composer.json requires phpunit/phpunit ^7.0 -> satisfiable by phpunit/phpunit[7.0.0, ..., 7.5.20].**

Any help, please? Thanks

**Comment by pilarik31** [comment]
Hi,

installing older phpfastcache should do the trick.
`composer require "phpfastcache/phpfastcache:^8.0"`
