### ISSUE TITLE
likes count is -1 but browser data shows likes count when logged in!

### ISSUE THREAD

**Issue by beshoo** [postaddictme/instagram-php-scraper#998]
edge_media_preview_like is a finite value when seen in a browser i.e window._sharedData.entry_data.PostPage[0].graphql.shortcode_media

but in 
**instagram-php-scraper return -1 when am loged in**

To Reproduce while you are logged in 
https://www.instagram.com/p/CUrAS88Pr1G/

**Comment by Bertuga** [comment]
Since May there is an option to hide like count: https://about.instagram.com/blog/announcements/giving-people-more-control

This link you provided doesn't show the like count to me when I open it, even though I'm logged in.

**Comment by 89z** [comment]
I have a tool that works:

~~~
PS C:\> instagram -i CUrAS88Pr1G
{Display_URL:https://scontent-dfw5-1.cdninstagram.com/v/t51.2885-15/e35/p1080x1080/244387208_570283694282391_2114620732502930718_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com&_nc_cat=103&_nc_ohc=Hvo0dbQ6YaAAX8dZTKN&edm=AABBvjUBAAAA&ccb=7-4&oh=3c038ff4053c0260c28ecef2873a9a0f&oe=61A5A4F2&_nc_sid=83d603&ig_cache_key=MjY3ODIzNTcwNTc4NzcyNzE3NA%3D%3D.2-ccb7-4
Edge_Media_Preview_Like:{Count:1496}
Edge_Media_To_Parent_Comment:{Edges:[{Node:{Text:Thanks. Miss
😇💯☝❤🙋‍♂️🤮🚫👀😁}} {Node:{Text:❤️❤️❤️❤️❤️}} {Node:{Text:So cool!!! Will get
this 👍👍}} {Node:{Text:💕💕💕}} {Node:{Text:❤️❤️❤️❤️❤️}} {Node:{Text:There are not
to many things worse than talking to someone who has bad breath. I feel like
I'm contaminated with a terminal disease afterwards.}} {Node:{Text:Hello pretty
girl 💕💕💕💕💋}} {Node:{Text:This sounds amazing!}}]}
Edge_Sidecar_To_Children:<nil> Video_URL:}
~~~

https://github.com/89z/mech

**Comment by beshoo** [comment]
> I have a tool that works:
> 
> ```
> PS C:\> instagram -i CUrAS88Pr1G
> {Display_URL:https://scontent-dfw5-1.cdninstagram.com/v/t51.2885-15/e35/p1080x1080/244387208_570283694282391_2114620732502930718_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com&_nc_cat=103&_nc_ohc=Hvo0dbQ6YaAAX8dZTKN&edm=AABBvjUBAAAA&ccb=7-4&oh=3c038ff4053c0260c28ecef2873a9a0f&oe=61A5A4F2&_nc_sid=83d603&ig_cache_key=MjY3ODIzNTcwNTc4NzcyNzE3NA%3D%3D.2-ccb7-4
> Edge_Media_Preview_Like:{Count:1496}
> Edge_Media_To_Parent_Comment:{Edges:[{Node:{Text:Thanks. Miss
> 😇💯☝❤🙋‍♂️🤮🚫👀😁}} {Node:{Text:❤️❤️❤️❤️❤️}} {Node:{Text:So cool!!! Will get
> this 👍👍}} {Node:{Text:💕💕💕}} {Node:{Text:❤️❤️❤️❤️❤️}} {Node:{Text:There are not
> to many things worse than talking to someone who has bad breath. I feel like
> I'm contaminated with a terminal disease afterwards.}} {Node:{Text:Hello pretty
> girl 💕💕💕💕💋}} {Node:{Text:This sounds amazing!}}]}
> Edge_Sidecar_To_Children:<nil> Video_URL:}
> ```
> 
> https://github.com/89z/mech

If you open the post without log in, you can see likes count. But this is a big problem since you have to use proxies.

**Comment by 89z** [comment]
> If you open the post without log in, you can see likes count. But this is a big problem since you have to use proxies.

Sorry I cant help with that. If you login, likes will be `-1`. The only option is to use anonymous request.
